### ISSUE TITLE
Feature request: **Cut · Copy · Paste** feature needed | Update: Not working - See bug report

### ISSUE THREAD

**Issue by Draxler** [Stremio/stremio-features#10]
I think **Cut · Copy · Paste** feature is realy missed on Stremio. A lot of people have hard time using keyborad shortcuts. Also it's much more ezyer to a lot of users to use mouse for paste text into search box once copyed to clipboard . Especialy this feature would be usefull to copy paste by mouse for magnet links which can't be dragand and droped onto Stremio. I realy hope Stremio would concider this and include this feature (soon).

![2345](https://cloud.githubusercontent.com/assets/7681671/11029887/5d929ac4-86ca-11e5-806e-039cd84422a2.PNG)

**Comment by Ivshti** [comment]
Agree, seems excessive to put a context menu only for paste there. Having copy/cut in the search bar doesn't make any sense, and I'm much willing to add right click -> Paste but it would also be a good idea to add other things to that context menu so that it's not only for "Paste".

How about recent searches?

Like right click->

Paste
------
Search 1
Search 2
Search 3

**Comment by Draxler** [comment]
I think both should be included on meni --> copy and paste <-- . Sometimes you need to copy part or complete search term from search box to paste it later on again or to put it somplace else. If you don't have Copy , then you need to go back to the source to copy again search term and then back to Stremio or you need to type it for yourself , sometimes wery long or wery hard text.. 
I do agree you should included some other things which are need it into ''right click menu'' feature but i also think Copy should be also included along with Paste into ''Right click menu''.

**Comment by Ivshti** [comment]
Ok then.

Cut/copy/paste and recent searches. That makes sense

**Comment by Draxler** [comment]
:+1:   :smile:

**Comment by Draxler** [comment]
PASTE doesn't work. When i copyed Movie title from website and i try to paste into search box , nothing happens. Same goes for Magnet links. When i copy Magnet link and try to Paste into into Search Box, again, nothing happens.

**Comment by Draxler** [comment]
Btw:

I have something like this in mind:

![zajeta slika](https://cloud.githubusercontent.com/assets/7681671/11101253/3909368e-88b6-11e5-975e-b79417f05dfa.PNG)

**Comment by Ivshti** [comment]
Interesting. You tested it on Windows, didn't you?

I tested on mac, it worked, and I assumed it works.

Yep, clear recent searches is a good idea.

**Comment by Draxler** [comment]
@Ivshti 

I tested on Windows and Paste text trough Menu isn't working. 

- I also think that (beside ''Clear recent searches'') having nice design for menu (like one i posted) is good idea as well. (you know,,, to be consistent with the rest of Stremio Design) .. :smile: 

- imo, it would be also good idea to limit max number of recent searches showing on Menu (to maybe 6 search terms). After that, oldest ''search term'' gets automatic deletion to make place for new Search term.

**Comment by Lamp-Post** [comment]
The Paste option works for me, both magnets and movie titles. I am running Windows 10

**Comment by Draxler** [comment]
This was already fixed about 2 versions back. 

But i do think **Cut** should be replaced with **Delete** function, it would be much better choise to have it.

**Comment by Ivshti** [comment]
@Draxler agree about Delete

**Comment by Draxler** [comment]
I agree, it could be called ''Clear'' as well.
