### ISSUE TITLE
[FEATURE REQUEST] Option to manually set server IP

### ISSUE THREAD

**Issue by Vioner** [Stremio/stremio-features#100]
Currently, we can't easily change the server IP in a client app. 
It'd be great to have this on app.strem.io and on all clients.

**Comment by Ivshti** [comment]
You can override it with the ?streamingServer= query parameter for app.strem.io/shell-v4.4 and staging.strem.io

is that sufficient for your goals?

**Comment by inluxc** [comment]
So we need to have a server active in the network.. so we still need a pc to run in the tv. Can we run the server on a raspberry pi without an interface?

**Comment by mehmood-baryalai** [comment]
> You can override it with the ?streamingServer= query parameter for app.strem.io/shell-v4.4 and staging.strem.io

Tried in the local browser with the stremio app running in the background, but I get the following popup message in the (chrome) browser:

**Could not update casting device info: streaming server might be offline**

**Comment by core1024** [comment]
> So we need to have a server active in the network.. so we still need a pc to run in the tv. Can we run the server on a raspberry pi without an interface?

Yes you can. You can see [here](https://github.com/Stremio/stremio-shell/blob/master/release.makefile#L28) how to download the server. You need NodeJS and ffmpeg installed on the system. Then just run `node server.js`. And you have standalone Stremio server.

Bare in mind that the local files add-on is part of the server therefore it will show files on the system where server is running. Also it isn't tested in such scenario and may not work properly.

**Comment by core1024** [comment]
> > You can override it with the ?streamingServer= query parameter for app.strem.io/shell-v4.4 and staging.strem.io
> 
> Tried in the local browser with the stremio app running in the background, but I get the following popup message in the (chrome) browser:
> 
> **Could not update casting device info: streaming server might be offline**
> 
> PS: tried 127.0.0.1 as well as the actual IP but still get this message.

Make sure you load app.strem.io over HTTP and not HTTPS. Like this `http://app.strem.io/shell-v4.4/?streamingServer=http:%2F%2F192.168.1.2:11470` where 192.168.1.2 is the IP address of the PC running Stremio.

**Comment by TRtomasz** [comment]
This has been implemented,
you can find it in the settings under "override the streaming server url"
