### ISSUE TITLE
Add ''Sequel button " to android TV version

### ISSUE THREAD

**Issue by vitouchiha** [Stremio/stremio-features#1000]
**Stremio Version**
Stremio Web Version

**Additional context**

I saw that this icon appears in the web version of Stremio which is extremely useful
In detail you want to see the next content to watch, after the season or film in question.
It is very useful as it suggests any films to watch between one season and another, especially for anime which are divided into many small mini seasons
![photo_5944794526977737058_w](https://github.com/user-attachments/assets/11679428-b212-4c62-a84c-66858bf7da12)
Is it possible to add it to the Android TV APK  versions too?

**Comment by TRtomasz** [comment]
This will not happen, we do not have such data.

**Comment by vitouchiha** [comment]
hi, the information is already included in stremio, the problem is that this button is only visible in the web version of stremio. Can't you also bring it to the Android TV version?
