### ISSUE TITLE
UI/Scale Customization

### ISSUE THREAD

**Issue by bramst0ne** [Stremio/stremio-features#1003]
Stremio 4.4.168 on Windows 11

**Is your feature request related to a problem? Please describe.**
The problem i'm having is I use 45" TV as a second screen, so having a 100% scale on windows make everything small
i'm using 125% for now i would like to use 150% but that on windows messes up the UI, all drop down lists are not properly displayed

![image](https://github.com/user-attachments/assets/b664370e-9584-412b-bfe4-6f86aa3a8094)

**Describe the solution you'd like**
So having the option build in the app would be nice.

**Comment by TRtomasz** [comment]
I cant reproduce your issue at my end 
![image](https://github.com/user-attachments/assets/e2df78ba-0c04-438e-9884-9b8d18d07be6)

**Comment by TRtomasz** [comment]
This is with 150% scaling
