### ISSUE TITLE
AndroidTV - Discovery Tab Enhanced

### ISSUE THREAD

**Issue by TuupacFR** [Stremio/stremio-features#1004]
As of now, on Android tv, all movies within categories are listed horizontally. It would be great that, at least on the Discovery Tab, layout on Android TV of the movies will be displayed as a full page grid, the same way as the Windows or Mobile app. 

Another bonus one would be that it remembers Discover tab filters instead of resetting on each app launch. As I always go discovery to apply the same filters.

![Screenshot_2024-09-12-01-05-41-93_5a1e11fa41055108da81eb54eea93a2a](https://github.com/user-attachments/assets/aad422c5-75a1-40db-89a1-8865236b792a)

**Comment by TRtomasz** [comment]
https://github.com/search?q=repo%3AStremio%2Fstremio-features+grid&type=issues

**Comment by TuupacFR** [comment]
> https://github.com/search?q=repo%3AStremio%2Fstremio-features+grid&type=issues

The more the merrier, the dev needs to understand everyone is asking for this feature. And it only make sense it's available on all other version of Stremio except the one that makes the most sense which is TV.

**Comment by Anoo22** [comment]
The app is fantastic, but please add volume gesture and brightness gesture to the build in player. Please🙏, and perhaps can you add frame generation to make videos run 60 fps. I hope you read my feedback. And thanks 😊.
