### ISSUE TITLE
Auto-play previews on Home tab

### ISSUE THREAD

**Issue by satvik25** [Stremio/stremio-features#1005]
**Stremio Version**
Stremio Version and OS
Stremio 4.4.168, MacOS Sonoma 14.6.1

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Auto-play previews of movies and tv shows on Home tab (see Netflix, etc. for reference).

**Describe alternatives you've considered**
Pre-load from Watch Trailer button to show auto-play previews automatically 

**Additional context**
<img width="1710" alt="Screenshot 2024-09-12 at 1 20 43 PM" src="https://github.com/user-attachments/assets/3d33d435-bfff-470a-a65f-5c399c331500">

**Comment by TRtomasz** [comment]
https://github.com/Stremio/stremio-features/issues/985
