### ISSUE TITLE
UI/UX suggestion: In Library indicator

### ISSUE THREAD

**Issue by introvertedcreature** [Stremio/stremio-features#1006]
**Stremio Version**
4.4, Windows 10

**Is your feature request related to a problem? Please describe.**
Currently, there's no way to quickly see if a title is in the library. The only way is to click on a title and then look for the Add / Remove from Library button.

**Describe the solution you'd like**
Some kind of indicator on the posters themselves would solve this. Just like there's one for watched titles already - the purple checkmark on the top left. There could be another one on the top right, for an example, indicating that a title is in the library. It could even double as a quick Add to Library button, so that there's no need to click on the title at all to do that. An example would be a simple circle with a + or a - in it, depending on if the title's in the library or not. Clicking on + could add a title to the library, while clicking - would remove it from the library, eliminating the need to visit an individual title page to do that.

**Comment by TRtomasz** [comment]
Please update your issue with the template
