### ISSUE TITLE
Stremio Smart Vertical Stretch ?

### ISSUE THREAD

**Issue by Nazim1981** [Stremio/stremio-features#1007]
Most movies don't open in fullscreen mode, so I usually select "Fit Screen." However, 90% of the time, this option zooms in, causing the edges of the screen to get cut off. Ideally, it should use a smart vertical stretch that fills the screen without zooming in or cutting off any corners. This option, also known as "Fill Screen," would stretch the video vertically to fit the screen without losing any content.

Chromecast with Google TV (4K) . ( Connected with Sony TV X950H )

Operating System 12 ( Current )

Stremio Android TV Version . 1.6.11

Issue Movies Zoom in using Fit Screen .

Expected behavior Fill Screen without cutting edges ( Vertical strectch )

some external players that offer this option, such as Kodi, Weyd , MX Player (16:9), and even VLC. However, I prefer using Stremio's default ExoPlayer

**Comment by TRtomasz** [comment]
We cant add such feature, screen modes are controlled by players. We use media3(exo) and vlc

**Comment by Anoo22** [comment]
The app is fantastic, but please add volume gesture and brightness gesture to the build in player. Please🙏, and perhaps can you add frame generation to make videos run 60 fps. I hope you read my feedback. And thanks 😊.
