### ISSUE TITLE
Better Continue Watching

### ISSUE THREAD

**Issue by Pig-E-Wig** [Stremio/stremio-features#1008]
**Stremio Version**
Stremio Version - all, Android TV

**Is your feature request related to a problem? Please describe.**
The continue watching is poor, sometimes new episodes show, sometimes they don’t, difficult to differentiate between a started show and a new to air episode etc

**Describe the solution you'd like**
A new continue watching similar to that of Plex or Emby, where the show only shows up when there are new episodes to be played, or partially through an episode. 

**Describe alternatives you've considered**
Look at the continue watching feature Plex currently has, it’s perfect, if you’re up to date with a show, it automatically hides it, then populates again when the new episode airs

**Additional context**

**Comment by TRtomasz** [comment]
Sorry this feature request does not provide any information about some new feature we already have continue watching and it works exactly as described.

**Comment by Pig-E-Wig** [comment]
If that is the case, it really doesn’t work, I raised it as an issue on Reddit with screenshots and was told to request here. So an example, I can add screenshots next time I get the issue is Smackdown, I finish the recent episode, and it stays on my Home Screen despite the next episode not having aired, I need to click clear progress to remove it, but it then doesn’t come back on when the next episode is aired. If it is meant to act just like the Plex implementation, then there are bugs
