### ISSUE TITLE
Feature in Player 

### ISSUE THREAD

**Issue by MrConqueror** [Stremio/stremio-features#1009]
**Stremio Version**
Stremio Version and OS

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
We should have an option to turn on or turn off tap twice to seek forward or backward. Me i prefer it turn off sometimes i tap the screen to pause to read the subtitle but instead it seek forward or backward pretty annoying. And smaller the 10sces icon it's big

**Comment by Anoo22** [comment]
Hi there.

The app is fantastic, but please add volume gesture and brightness gesture to the build in player. Please🙏, and perhaps can you add frame generation to make videos run 60 fps. I hope you read my feedback. And thanks 😊.
