### ISSUE TITLE
Not able to access "details" or "dismiss" options with remote on android tv

### ISSUE THREAD

**Issue by dhiman33** [Stremio/stremio-features#101]
In the android tv version... if I start watching a movie and then again try to select a different source, I am not able to do that .. on mobile version I can select "details/dismiss" options and select another source for a movie; but on android tv using remote it is not possible.

**Comment by TRtomasz** [comment]
I think you should use mouse app to have access to every element in Android TV

**Comment by dhiman33** [comment]
I understand that..but please treat this as a feature request to be implemented in future versions for android tv
