### ISSUE TITLE
Samsung TV app does not support modern subtitle formats

### ISSUE THREAD

**Issue by FiddleMySticks** [Stremio/stremio-features#1010]
**Stremio Version**
Stremio Theater v1.3.0 on Tizen OS

**Is your feature request related to a problem? Please describe.**
I am not certain if this is an issue with the Samsung TV app or with my TV, but considering my TV is a newer model 50Q60D, I think the app might be at fault.

This issue happens mostly when I watch anime, which uses mostly more modern subtitle formats. As such, the Embedded subtitles do not appear as an option to select at all, which only leaves me with simple subtitles from addons, like OpenSubtitles (where the subs are inferior in quality and older series might not have any subs at all). This is such a shame because all the anime I stream have embedded subs which I can see on both PC and Android phone, but on my Samsung TV the option simply does not show. 

**Describe the solution you'd like**
The app should provide support/ compatibility for more modern subtitle formats, like .ASS .

**Describe alternatives you've considered**
At the moment, when an Anime does not have subs available on OpenSubtitles, I just watch that anime series on Stremio on my android phone, and cast it on the TV with Samsung SmartView. I would love to watch all the anime directly on my TV, provided I can enable the Embedded subs.

**Comment by TRtomasz** [comment]
This is not Stremio issue, this subtitles are simply not supported by the samsung os

**Comment by jiajunhe1997** [comment]
ASS subtitles works on Plex for samsung TV (Samsung S90D). Is it possible for Stermio to support ASS in the future?
