### ISSUE TITLE
Matter Casting

### ISSUE THREAD

**Issue by starman2908** [Stremio/stremio-features#1011]
With the advent of Fire TV's introducing matter casting on devices with OS7/8, just wondering if matter casting could be implemented on the stremio android for mobile app.

As it gains more popularity, it'll hopefully become a universal standard. It would also save having to sideload install/updates to the android TV app.

As always, fantastic work on the whole range of apps for devices and features so far....Kudos!!

**Comment by TRtomasz** [comment]
you can just install android tv app on firetv device so why cast to it?
