### ISSUE TITLE
Feature: Shuffle Button in Player

### ISSUE THREAD

**Issue by matheusroberson** [Stremio/stremio-features#1012]
**Stremio Version**
- Stremio 5.0.0-beta.9 on Web Player
- Stremio 4.4.168 on Windows and Linux

**Is your feature request related to a problem? Please describe.**
The player doesn't have a shuffle button to watch random episodes. 

**Describe the solution you'd like**
A possible solution is creating a temporary list to manage order of the episodes, so when user click in shuffle button sort this list.

**Comment by TRtomasz** [comment]
I dont see this to be used by more than 0.1% of users

**Comment by HypoLuxa** [comment]
> I dont see this to be used by more than 0.1% of users

you'd be wrong.
