### ISSUE TITLE
Child mode

### ISSUE THREAD

**Issue by SteZzy0ne** [Stremio/stremio-features#1015]
**Stremio Version**
1.6.11 and fire os

A child mode to restrict the content that can be seen and watched

Like an age filter or the ability to select the shows or movies that can be viewed

![image](https://github.com/user-attachments/assets/2befdb5e-5f43-440c-bb47-f1899a9e9a59)

**Comment by TRtomasz** [comment]
We do not have information about content rating, especially considering that each country use different content rating system
