### ISSUE TITLE
Library: Keep a Note

### ISSUE THREAD

**Issue by tanotriantaf** [Stremio/stremio-features#1017]
**Stremio Version**
Stremio 4.4.168 MacOS Mojave

**Description of the issue**
I love keeping my watchlist on my stremio library. I watch all films I want to watch on stremio and I keep track of the ones I did watch and the ones I haven't yet. I erase the ones I don't want to watch again and I keep the ones I really like to remember for a re-watch.

**Describe the solution you'd like**
It would be great if there is a feature of note-keeping for each film, as a diary entry for each film on the library. These would be notes from "why I added this to my watchlist" to "why I really like this film" or "what I believe the film means to me" or any short note the user wants to keep in mind when it comes to his favourite or want-to-watch films.

**Additional context**
![Screenshot 2024-09-22 at 15 02 32](https://github.com/user-attachments/assets/d7af5b86-8dfd-4447-9844-ed5a4c0a11d1)
![Screenshot 2024-09-22 at 14 56 11](https://github.com/user-attachments/assets/8b25ed05-6944-41d5-8e9c-a91da8bacc09)

**Comment by TRtomasz** [comment]
This will not happen amount of resoruces needed to store all that data would cost a lot
