### ISSUE TITLE
Unraid / docker container

### ISSUE THREAD

**Issue by Artiom97es** [Stremio/stremio-features#1018]
**Stremio Version**
any

**Describe the solution you'd like**
a container wich works on server like unraid, could be good if its avalible on comunnity store too

**Describe alternatives you've considered**
plex + radarr + sonarr + prowlarr + qbitorrent + Ombi/or others

**Comment by TRtomasz** [comment]
Our container has open source implementation ,feel free to modify it

**Comment by Artiom97es** [comment]
any plans to add it official? to unraid community apps

**Comment by Artiom97es** [comment]
i have no idea how create manually container and that kind of stuff

**Comment by Artiom97es** [comment]
well i tried and its a mess, so hard
