### ISSUE TITLE
Feature: QR code to automagically clone all settings and add-ons to different stremio accounts.

### ISSUE THREAD

**Issue by papajo-r** [Stremio/stremio-features#1019]
So I love the fact that if I set stremio like I want it on my account and want to install it on a new device all I need to do is to log in and it automagically will clone all the settings I made on the previous device so I do not have to do it on my own.

Unfortunately this is only possible for settings you do to your own account and they get transfered to which ever stremio instance you login with that account.

I wished there was a way for transferring settings without the need to log in... eg have in the stremio settings interface an option to export a QR code or a link which if an other stremio user clicks on will have his stremio have the same settings as you.

I think this would be hella useful because here are two instances in which I either wished I had not used my stremio account or do not want to.

instance 1) I installed stremio to my girlfriend which mean I had to share my password with her (a password that I use elsewhere too) and after we broke up it was kinda awkward cause she had my password and also like could check out my watch history and I hers etc...

instance 2) I want to set up stremio for some older family members but I always procrastinate because I am too bored to set all the addons etc and I dont want to just clone them by logging into my account because that way again they will mess up with my recently watched history and also know what I watch etc I dont hide anything but also dont feel that comfortable them knowing everything I watch especially if its kinda adult lol .

**Comment by TRtomasz** [comment]
This is not possible due to legal reasons, each users has to manually accept our rules and terms of use

**Comment by papajo-r** [comment]
> This is not possible due to legal reasons, each users has to manually accept our rules and terms of use

Well if the problem is accepting the terms then why not have a frame where the user can do so before the addons apply using the aforementioned QR code? 

Like if one uses the QR getting getting a screen like "You hereby are to install the following addons, here is the agreement please click agree in order to proceed"
