### ISSUE TITLE
Subtitle positioning

### ISSUE THREAD

**Issue by cangoktas** [Stremio/stremio-features#102]
I'd like to change subtitle's position vertically (up & down). Each movie might have different ratio's so for the best readability, people should be able to change the position of the subtitle a bit.

**Comment by imurreflection** [comment]
Hi Friends, thank you for this great addon. Subtitles positioning is very important feature for non native English speakers like me. Can you please look at this request kindly

**Comment by maxoku** [comment]
Will this be implemented on pc like it was on android? That's a very useful function that would solve many problems.

**Comment by TRtomasz** [comment]
Closing as all major apps are now supporting subtitles positioning

**Comment by traviss64** [comment]
> Closing as all major apps are not supporting subtitles positioning

Didn't get you. What other apps? 

The PSG subtitles on from BDs are way to up. close to the middle of the screen and there is no option to change the position on PC.

**Comment by Practicalbutterfly5** [comment]
Hi @TRtomasz could this be reopened? External subtitles can be supported for vertical offset like it's done on Samsung TV and android. Currently it's not available on PC (Mac in my case).
