### ISSUE TITLE
Feature: Sync movie with different stremio accounts over lan or wan

### ISSUE THREAD

**Issue by papajo-r** [Stremio/stremio-features#1020]
There is an addon for that but i'd rather prefere it to be a streamio feature because the addon besides being clumsy (sometimes it loses sync if you pause for a while or doesnt initiate a sync despite all people getting together usnig the same link etc )

and it also doesnt work with all the trackers that stremio works with (so some movies that you are able to access and watch on your own with stremio and dexter or whatnot you cant watch using the adon or it is available but in a different quality etc)

And it nice to watch movies like that with friends or distant relationships or kin that is not nearby but even over lan would be nice especially with people that e.g are somewhere with their phones and like hotspot and want to watch something togethere but have only their screens to watch.

**Comment by TRtomasz** [comment]
This would require a lot of man power to be implemented and will be used by very small percentage of users

**Comment by papajo-r** [comment]
Maybe it needs a lot of man power (or just syncing the time based on a time server? anyway what do I know lol )  but I dont think that it will be used by a small percentage of users given the amount of people in distand relationships of and all the other people that for some reason or an other are away from a few days/weeks/monts from their loved ones (e.g merchant marine workers )
