### ISSUE TITLE
Better Up Next

### ISSUE THREAD

**Issue by Pig-E-Wig** [Stremio/stremio-features#1021]
The continue watching is poor, sometimes new episodes show, sometimes they don’t, difficult to differentiate between a started show and a new to air episode etc

Describe the solution you'd like
A new continue watching similar to that of Plex or Emby, where the show only shows up when there are new episodes to be played, or partially through an episode.

Describe alternatives you've considered
Look at the continue watching feature Plex currently has, it’s perfect, if you’re up to date with a show, it automatically hides it, then populates again when the new episode airs. 

Don’t close this saying it’s working, it’s not, look at this post on Reddit, people are using workarounds that sometimes work and sometimes don’t. Just have at the top of the page a list of currently started episodes and movies, in the same line, the next episode of a show that’s already running, and then populates when a new aired episode is released, remove said show from this list after watching latest episode until next episode airs again. 

https://www.reddit.com/r/Stremio/s/d0GYKltONz

https://www.reddit.com/r/Stremio/s/L9TPtGEbll

I can send pictures if you need more clarity on what I mean, but for example, I was up to date with impractical jokers, nothing for that show in my continue watching, new episode released a couple of days ago, still nothing appears for that in my continue watching.

**Comment by TRtomasz** [comment]
top right corner - new episode notification, bottom part is moment when you stopped watching
![image](https://github.com/user-attachments/assets/12ede951-cb74-467b-9357-f65c14bf8ed5)
in older stremio version there is just bottom part and new episodes shows in "New episodes" if there are less than 3 episodes from same series or in separate line if there are more new episodes
![image](https://github.com/user-attachments/assets/ba543554-a25e-4c25-aee4-cbe24b1ef04f)
