### ISSUE TITLE
Season and Episode Selection on Double Down Press on all TV OS

### ISSUE THREAD

**Issue by Sophanos** [Stremio/stremio-features#1024]
**Stremio Version**
All TV OS

**Is your feature request related to a problem? Please describe.**
As a user, I want to be able to access the season and episode selection by pressing the down button on my remote control twice while watching a series, so that I can easily navigate to different seasons or episodes without interrupting the playback.

**Describe the solution you'd like**
Solution is as described all TV OS should get a feature where the double click down / upwards creates scrollable list of available seasons and scrollable list of episodes within the selected season. The user should be able to navigate the season and episode list using the arrow keys on the remote control. Selecting a season should update the episode list to display episodes for that season. The selected episode should immediately start playing upon confirmation, if not a new indexer should be picked.

**Describe alternatives you've considered**
Single Press for Season and Episode Menu
A new button (e.g., “Episodes” or “Season”) could be introduced to directly access the season and episode selection. While this provides a clear separation of functions, it may add complexity for users who are already familiar with the current remote control layout. With this button you could add "Info", "Top Act" etc.

Single Press for Season and Episode Menu
Instead of requiring two presses of the down button, the season and episode menu could be accessed with a single press, bypassing the standard playback controls. However, this might clutter the interface or frustrate users who primarily want quick access to playback controls.

**Comment by TRtomasz** [comment]
there already is episode menu, you can open if tom player UI looks like stacked cards iconm right now it has only episodes names but maybe will be enhanced in the futures
