### ISSUE TITLE
Feature: Give the option to the user to decide if he wants stremio (and all other processes e.g the stremio server) to terminate once the user closes the main app

### ISSUE THREAD

**Issue by papajo-r** [Stremio/stremio-features#1025]
This is a quality of life feature there have been dozens of times where I left a show or movie paused for hours only for me when I return and hit play to have a playback issue e.g no audio or to many compression artifacts etc. 

The only solution is to close stremio completely and then boot it again , then it loads the movie/show at the same point but without any issues. 

The problem is that I have to manually kill everything from task manager because if I just click on "X" on the stremio app only the app closes but if I double click stremio exe it pops up back as if I never closed it like in the movie I left it and with the same issues... I guess you have it so for convenience so that it doesnt take much time to reboot stremio but complete hardreboot/reset is necessary I am afraid give that bugs are not infrequent..

**Comment by TRtomasz** [comment]
There is a setting for this in the settings - close app when window is closed
