### ISSUE TITLE
Content Slider in Movie/Series Overview as Carousel View

### ISSUE THREAD

**Issue by Sophanos** [Stremio/stremio-features#1026]
**Stremio Version**
Stremio Version and TV OS

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to leave the view of a film or series to go to the catalogue to get the next content in the catalogue and read the description. 

**Describe the solution you'd like**
Allow users to explore additional content while in the film/show preview without leaving. 
Add a horizontal content carousel view that allows users to swipe left or right to browse movies or shows in the selected catalog, so they don't have to go back and click right again to stay in full-screen mode.

**Describe alternatives you've considered**
None.

**Additional context**
Preview made with Figma by me: https://ibb.co/GWZbZMC

**Comment by TRtomasz** [comment]
why would you want to go back to the catalog and read descriptions while having the video paused? Whats the point of such feature? I dont think almost any one except you would see this feature usable.

**Comment by Sophanos** [comment]
I think there’s a misunderstanding. My feature request isn't about reading descriptions while a video is playing or paused. It's about improving the browsing experience before choosing what to watch.

Here’s a clearer explanation:

Currently, when I’m browsing the catalogue, I click on a film or series to see its full details. Sometimes I realize it's not what I’m looking for, and I want to continue browsing without going back to the main catalogue view. However, I’m stuck in the full-screen mode and can only move left or right through other titles without a good way to return to the catalogue or browse more content.

What I’m Suggesting:
I’m proposing a carousel-style view within the preview screen, allowing users to browse through other titles horizontally (left or right) without needing to exit full-screen mode or go back to the main catalogue. This would save time and make it easier to explore content.

The feature is intended to make browsing smoother, before a user has started watching anything. I hope that clarifies my request!
