### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by Rach0726** [Stremio/stremio-features#1031]
**Stremio Version**
Stremio Version and OS

**Describe the solution you'd like**
I would love if there could be profiles for our accounts. My family loves Stremio but the one negative is having everyone's continue watching all together (2 adults, 2 kids) so I would love to see Profiles for each individual person. 

Thanks.

**Comment by marcoshimselfxd** [comment]
Like this? https://github.com/Stremio/stremio-features/issues/1701
