### ISSUE TITLE
Browsing for shows and categories is too confusing on a TV

### ISSUE THREAD

**Issue by notNSANE** [Stremio/stremio-features#1033]
**Stremio Version**
Stremio, TV version

**Is your feature request related to a problem? Please describe.**
yes, there is a tiny selector that splits browsing into movies or shows, then splits into Genres.

**Describe the solution you'd like**
Both Movies and TV shows should be top level, just like Home or Library. This way that tiny selector starts being a Genre selector.

**Describe alternatives you've considered**
None. People stop using the app, they don't understand it. 

**Additional context**
Most people I know, but specially of old age, barely understand how to use the app. They only select what's available at Home, and when they run out of content, they go back watching live TV.

Stremio needs a minor redesign for TV since it's way too confusing. I'd start by splitting browsing into Movies, and then Shows. That selector needs a redesign too but for now it's serviceable.

This has also been suggested as #891 by @ZainAjam, so there's plenty people requesting this.

**Comment by TRtomasz** [comment]
For the same reason as before, this will not be implemented. This app has over 30 millions of users, two people isnt event close to plenty
