### ISSUE TITLE
Stremio cant passthrough Dolby Truhd and Dolby Truhd Atmos. Show as Dolby Digital Plus

### ISSUE THREAD

**Issue by shanestonk** [Stremio/stremio-features#1036]
**Stremio Version**
Stremio Version and OS
1.6.12 Android Tv 11

**Is your feature request related to a problem? Please describe.**

When playing Kong Skull Island 2017 Bdremux rutor with truhd audio on stremio my soundbar only will output the audio as Dolby Digital Plus. But when i play the same movie on Kodi my soundbar will output it as Dolby Atmos (Truhd).

**Describe the solution you'd like**

Stremio can have passthrough for lossless audio eg Dolby Truhd, Dolby Truhd Atmos, Dts hd ma and Dts-x audio.

**Describe alternatives you've considered**

**Additional context**

**Comment by TRtomasz** [comment]
Enable tunneled playback and hardware accelerated decoding in the settings.
