### ISSUE TITLE
Library categories, playlists, and Watchhub

### ISSUE THREAD

**Issue by Jake6758** [Stremio/stremio-features#1037]
Stremio Version 1.6.12 on Android phone and Android smart TV

Problem
The Library tab doesn't allow you to organise films/series based on genre, director, era/year, language, or playlist. Currently on android phones you can view your Library based on film/series, and you can organise it with three criteria: A-Z, Recent, and Watched. On the TV app your library is stacked in two long banners for Film and Series, and if you've added a lot of media to your library it can take way too long to scroll down the line. Also on the Android TV app you can only organise your Library based on 6 similar criteria: A-Z, Z-A, Watched, Not Watched, Times Watches, and Last Watched.

When the Library organises titles alphabetically it doesn't exclude prefixes like “The, A, An" etc. So films like The Godfather, and The Matrix are all organised under T etc. 

On the TV app the Home, Discover, and Library tabs all display films and series in long banners instead of grids and it's cumbersome and takes a long time to find media (even films/series you've already saved in your library). The banners which the add-ons generate in the Home section all have similar categories which end up showing the same films again and again (Popular, Featured, Premieres, Trending, different award winners, and Popular film/Popular Series/New Film/New Series again and again for Netflix media, Amazon media, Hulu media etc).

Finally the WatchHub official add-on is great, but it misses things that JustWatch/Plex/GoogleTV pick up.

Solution
The library and Discovery sections on Android TVs would look and work much better if it was displayed as a grid the same as Android phones. You should be able to organise your Library based on multiple criteria like the Discover tab. The Library criteria for both Android TV and Android phones should be the same. 

The criteria in the Library should be 1st :film/series/channels/Audiobooks. The 2nd and most important library criteria we need should be :TITLE, GENRE, DIRECTOR, LANGUAGE, YEAR, WATCHED, SERVICE and PLAYLIST. Some of the second criteria should have specific 3rd criteria like the Discover section currently has. Title should bring up :A-Z and Z-A. Language and Year should bring up all the data options available in the discover tab. Watched should bring up :Recent/Not Watched, Last Watched, Times Watched. Service should bring up the different streaming platforms media is associated, with and award winners. Director should order your library alphabetically according to surname with the films in chronological order. But the most important criteria missing from almost the whole app is genre. When you select Genre in Library the grids below should organise into different sections with genre titles delineating at the top, and possibly separate genre appropriate backgrounds. You should also be able to select specific genres from a third criteria and bring all the media in that field to the top of the grid. Selecting Genre should organise your media into all the data available fields even if titles appear multiple times through :Action, Thriller, Drama, Comedy, Romance, Family, Kids, Horror, Sci-fi, Fantasy, Adventure, Crime, Mystery, History, War, Animation, Anime, Musical, Biography, Documentary, and Natural History.

Playlists also need to feature in the Library, and possibly Discovery tabs. It would be good if you could add a Criterion playlist, or a “Best of the Worst” community created playlist all at once to your library. When you select a film and you click the add to library button, the button should expand and allow you to add to playlists you've created in your library and/or community playlists you've added from the Discover tab. There should also be a “mark as watched” button beside the “trailer” and “library” buttons.

Also it would be great if there were “People Also Watched” and “Similar” banners either underneath the Trailer and Library buttons on a film/series or as part of the Discover tab.

The WatchHub official add-on is great, but would work better if we could configure it to look at more apps. The JustWatch app has a similar option where you can add services like Tubi, Pluto, Arrow, and in my case UK specific streams like BBC Player, ITV Hub, All 4, My 5 etc.

THANK YOU SO MUCH to everyone involved in developing Stremio. I've just recently discovered it and it's such a gift. I hope my suggestions are useful.

**Comment by TRtomasz** [comment]
For the future:
1. Please use the search option to check if there already exist similar request
2. Use one issue per one request
