### ISSUE TITLE
[UX] add a portable zip distribution for those who don't want to use an installer

### ISSUE THREAD

**Issue by bradenbest** [Stremio/stremio-features#1042]
**Stremio Version**
N/A

**Is your feature request related to a problem? Please describe.**
There are many reasons why one would prefer an isolated, portable zip distribution containing just the executable and libraries that it needs that they can put wherever they want and keep contained to a single folder and easily delete, over an installer that makes a mess and requires a matching uninstaller that may not undo everything the installer did. Zip distributions are the simplest method of software distribution.

**Describe the solution you'd like**
I want to see a portable zip distribution made available on the website's download page as an alternative to the installer

**Describe alternatives you've considered**
See [issue 978 on stremio-bugs](https://github.com/Stremio/stremio-bugs/issues/978) for a way to improve the installer.

**Additional context**
N/A

**Comment by TRtomasz** [comment]
This is not possible as app requires specific catalog structure, changing it would require a lot of developer time to make it working, time thats not worth if you consider how many times such feature has been requested.
