### ISSUE TITLE
[Feature Request] Set audio language to japanese when watching anime

### ISSUE THREAD

**Issue by NineKain** [Stremio/stremio-features#1044]
**Stremio Version**
1.6.12 - Any platform

**Is your feature request related to a problem? Please describe.**

Every time I watch anime the audio changes to english, but I want it on the original japanese, its a bit tiring to change it each time I finish an episode, it would be great if I could change it on a per-show basis.

**Describe the solution you'd like**

Get the option to set an audio/subtitle language per movie/show

**Describe alternatives you've considered**

Someone suggested Kodi + Otaku but I'd like to use Stremio

**Additional context**

**Comment by kKaskak** [comment]
Hi. You can set a default audio track to Japanese in the global settings of the app. This way each episode language will default to Japanese. While needed you can switch it back to a language of your choice.
