### ISSUE TITLE
[Request] Option to disable Applied Display Mode When enable frame rate matching

### ISSUE THREAD

**Issue by shanestonk** [Stremio/stremio-features#1045]
**Stremio Version**
Stremio ATV 1.6.12

**Is your feature request related to a problem? Please describe.**

When we enable the frame rate or frame rate and resolution setting at Stremio Frame Rate Matching, and we play some video stremio will pop up the Applied Display mode. Most tv nowadays will have their own pop up and will show 1080p,720p,2160p. when stremio want to show it too so it will display twice times the information which is one from the Tv and one from Stremio app.

**Describe the solution you'd like**

Stremio make an option to disable the applied display mode pop up message cos tv or android tv have their own way to pop up the message.

ATV Smarttube have the option to change frame rate and resolution and without the message pop up it change faster then the tv will pop up their own resolution message.

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/user-attachments/assets/6c968d46-db3b-49c7-b2e3-3dc4a351bd07)

**Comment by TRtomasz** [comment]
We want to keep app simple instead adding option to the settings for every piece of the UI
