### ISSUE TITLE
Check Stream Speed and Connected Peers of all the sources automatically

### ISSUE THREAD

**Issue by supermodo** [Stremio/stremio-features#105]
Would be nice if we could automatically check all the addons sources just before choosing, so we can get the good one at the first try.

**Comment by TRtomasz** [comment]
Sounds like great feature but impossible to be done. First of all it would recommend connecting with peers and downloading part of the movie without user knowledge second of all stream speed isn't constant. Some add-ons provide information about number of existing peers so you can pick these with the highest number.

**Comment by Ivshti** [comment]
This is pretty heavy to do, but it can be optimized by querying trackers directly

That said, it's not practical to do in the current Stremio architecture.

It might be an interesting exercise for an add-on though: an add-on that proxies other torrent add-ons, and sorts the results based on some tracker result. Anyone interested can enter our add-on competition: https://www.stremio.com/competition
