### ISSUE TITLE
Disable Libvlc auto change from exoplayer

### ISSUE THREAD

**Issue by shanestonk** [Stremio/stremio-features#1050]
**Stremio Version**
Stremio Version and OS
Android tv Stremio 1.6.12

**Is your feature request related to a problem? Please describe.**

When some movie stream from real debrid stremio will auto change from exoplayer to libvlc. when this happen movie will not play in Dolby Vsion and audio eg dolby truehd, dts hd ma etc. mostly will output audio as stereo pcm. libvlc have micro stuttering issue too when watching a movie with it.

**Describe the solution you'd like**

Option or remove the auto change to libvlc player from exoplayer. let exoplayer show error that it cant play the movie and user can use external video player eg vimu, justplayer, kodi etc that can play dolby vision and dolby truehd audio.

**Describe alternatives you've considered**

remove libvlc as stremio player. use only exoplayer and external player option.

**Additional context**

**Comment by TRtomasz** [comment]
They will change on exoplayer error so disabling this would not help with playback
