### ISSUE TITLE
Auto select quality

### ISSUE THREAD

**Issue by SteZzy0ne** [Stremio/stremio-features#1053]
**Stremio Version**
Stremio 1.6.12 fire os

An option or setting to select a quality like 1080p or 4k so you don't  have to manually the next link. When it's not on the previous. Like an advanced auto play next episode.so it just selects the next Episode in 1080p or 4k

**Additional context**
![image](https://github.com/user-attachments/assets/fd767849-79e4-41e4-8cae-05d6bcb98a47)

**Comment by TRtomasz** [comment]
Stremio does not know quality, it is simply not possible
