### ISSUE TITLE
Search/filter name for file/release

### ISSUE THREAD

**Issue by flavio-araujo** [Stremio/stremio-features#1055]
**Stremio Version**
Version 4 - MacOS Sequoia

**Describe the solution you'd like**
In the episode list, add a search/filter option to allow filtering by part of the name or release, or at least display the full file name. It's a very poor experience to have to hover over the name and wait for the file name to slide to view the release name.

**Comment by TRtomasz** [comment]
Stremio does not know name or release this is coming from addons
