### ISSUE TITLE
Custom Movie/Show Bachgrounds

### ISSUE THREAD

**Issue by lothar-cell** [Stremio/stremio-features#1056]
**Stremio Version**
Stremio 4.4.168 MacOS 15.1

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when a show or movie displays irrelevant or lower quality backgrounds, because it uses the latest one uploaded to TMDB.

**Describe the solution you'd like**
I'd like to choose from TMDB Backdrops, which is used by Stremio already anyway, for example: https://www.themoviedb.org/tv/4087-the-x-files/images/backdrops

**Additional context**
For example, we look at this cringy background with the old-ass actors from the not-so successful reboot season of X-Files, which was only for a couple of months as opposed to the 10 years of the show, instead of the wealth of cool backdrops, available from the source:

![Screenshot 2024-11-16 at 10 32 40](https://github.com/user-attachments/assets/0d726b37-227a-4d80-aa9a-877ef58a369a)
<img width="1678" alt="Screenshot 2024-11-16 at 10 34 07" src="https://github.com/user-attachments/assets/a3c6806b-50ea-4536-95c1-e8f9e512abc0">

**Comment by TRtomasz** [comment]
Stremio is meant to be as simple as possible, we will not introduce such feature as it would go against this rule. Every feature should be usable for major part of our users
