### ISSUE TITLE
Request for thumbnail/frame previews in video player.

### ISSUE THREAD

**Issue by balloonballoon** [Stremio/stremio-features#1058]
Stremio Version and OS
Any/latest version, Google TV

Is your feature request related to a problem? Please describe.
Not directly related to a problem, just a quality of life feature request.

Describe the solution you'd like.
It's like Netflix when you scroll to skip forward or backward, it will show you thumbnail previews in the timeline to see exactly what frame you want to skip to. I think the name for it is like scrubber preview window.

Describe alternatives you've considered.
Don't really know any alternatives.

Additional context
Looks something like this below.

![Screenshot 2024-11-16 113921](https://github.com/user-attachments/assets/5d656b82-60f0-4606-9699-72dd2b678696)

**Comment by TRtomasz** [comment]
thats simply not possible with stremio
