### ISSUE TITLE
Overlapping subtitles now shown correctly on android TV

### ISSUE THREAD

**Issue by YDskull** [Stremio/stremio-features#1061]
**Stremio Version**
Stremio Version - 1.6.12.
OS - Android TV 10.

**Is your feature request related to a problem? Please describe.**
When there are multiple overlapping subtitles at the same time (for example a conversation and a sign from the scene being translated at the same time), only one set of subtitles appear, and it's frustrating to not be able to follow a conversation because chunks of it keep missing due to shop signs being translated and stuff like this.

**Describe the solution you'd like**
I would like for both sets of subtitles to appear at once, they're in different places on the screen anyway so there's not a problem with them colliding - and it works fine when viewing it on the computer.

**Describe alternatives you've considered**
If it's too hard to fix, it would also be fine if at least the main conversation would be shown instead of the less relevant stuff. For some reason it's usually the less relevant stuff appearing, I think it's because the main conversation subtitles appear first for a split second and then disappear when a sign translation is being output.

**Additional context**
This happens a lot in anime.
Happened to me now in DanDaDan for example.

**Comment by TRtomasz** [comment]
thats not a stremio issue, this is exoplayer issue so we cant fix it.
