### ISSUE TITLE
Library Classification

### ISSUE THREAD

**Issue by giorgos-iatridis** [Stremio/stremio-features#1062]
**Stremio Version**
Stremio 4.4.165

**Is your feature request related to a problem? Please describe.**
It's not exactly a problem. It's more like an upgrade. It would be awesome to have more options to sort your library.

**Describe the solution you'd like**
Options to sort your library by: movie's duration, category, release date, imdb rating.

**Describe alternatives you've considered**
Maybe a file that you can extract the data (from the movies that I add in my library) and open it in excel.

**Comment by TRtomasz** [comment]
closing as duplicate
