### ISSUE TITLE
Stremio on 2024 Samsung models not available in smarthub

### ISSUE THREAD

**Issue by srrwdrwng** [Stremio/stremio-features#1063]
I am reaching out regarding an issue I have encountered with my Samsung Q73D TV (released in May 2024). Despite performing multiple resets of the Smart Hub and ensuring that the firmware is updated to the latest version, I am unable to locate the Stremio app in the Smart Hub App Store.

From my research, I found that Samsung has greenlit  support for  Stremio on 2024 models in April. However, it seems that this update is not yet available on my specific model. Can you confirm if there will be a forthcoming update for newer 2024 models like the Q73D?

Additionally, if the app is not yet available, I would like to explore the possibility of uploading the Stremio TPK file to my TV in developer mode. Could you kindly provide the necessary TPK file for installation?

Thank you for your assistance

**Comment by jaruba** [comment]
The app is not available in China for Samsung TV. Samsung is still creating new 2024 models periodically, for which the app will need to pass reviews individually. If you are not from China then you probably have one of the models that have not passed review yet.
We do not provide a TPK file for sideloading.

**Comment by srrwdrwng** [comment]
any idea if this specific model is already submitted for review, do they do it in bulk or model by model? 
Not providing the TPK file  is understandable, thanks anyway

**Comment by jaruba** [comment]
when we notice any new model that appears we send it for review asap, but the samsung reviews can take multiple months

**Comment by srrwdrwng** [comment]
allright, thank you for the fast reply, i keep an eye out
