### ISSUE TITLE
Trickplay image scrubbing for navigation through video

### ISSUE THREAD

**Issue by Techiecatz** [Stremio/stremio-features#1066]
**Stremio Version**
All

**Describe the solution you'd like**
While navigating through video having a trickplay image based scrubbing feature enabling forwarding to the correct section of the video, screenshots are typically generated every 5 seconds.

**Additional context**
Plex and Jellyfin have this feature

**Comment by jaruba** [comment]
i don't believe this is possible, with plex / jellyfin you are maintaining ur own server of media, your server scans the video files to populate the seek images in advance (this is a lengthy process which takes 1.5 days for only 3.5TB of data, according to a jellyfin discussion thread)
then when u stream a video, our own server already has this data and just passes it to the video player
with Stremio you do not maintain your own server of videos, so this data cannot be retrieved in advance, getting this data locally would probably take an hour or so and the process would only start after you choose the video you want to play, so for the first hour of playback this feature would not be available, yet it will make your device use a lot more resources while you play the video
imho, this doesn't make sense as a feature request for Stremio
