### ISSUE TITLE
"Not for me"-button

### ISSUE THREAD

**Issue by virik** [Stremio/stremio-features#1069]
First of all, love the app!

A feature that most (all?) streaming services are missing, is an option to hide movies that you simply don't want to see. Browsing through the lists you keep seeing the same items over and over again, and there are hundreds of movies that you wouldn't even see if you got paid to see them. The time you set aside to watch a great movie is wasted looking for it, and you go frustrated to bed only to start again at the very beginning the next day.

It would be great to have a "Not for me" or a thumbs down button to hide these items for ever. That would help you find some hidden gems or forgotten titles, and make the discover section far more enjoyable.

Taking this further, you could also have to option to hide all items having a certain meta, like an actor you don't like, a genre you're not interested in, a movie older than yourself, etc. There should also be a "Show hidden items" button somewhere in case you change your mind.

Just a thought. Keep up the good work :)

**Comment by TRtomasz** [comment]
It is impossible to hide elements in stremio, they are provided by addons, addons have no idea what you want to hide, it would break loading next pages
