### ISSUE TITLE
User-Profiles and ability to Hide Cinemeta-lists/titles

### ISSUE THREAD

**Issue by da-bosa** [Stremio/stremio-features#1073]
I would like to be able to have profiles, which are linked to separate Trakt-accounts to get recommendations according to preferences.

Since cinemeta is a part of stremio and can't be removed, and maybe to some extent, shouldn't be removed; I'd like the ability to HIDE the rows from Cinemeta since alot of the posters and recommendations are NOT child-friendly. I have a trakt-account for my children which recommends titles according to their previously watched titles, but these titles are farther down the list and I don't want them to see the first 4 (cinemeta)rows.

On their separate tablets, they can have Stremio linked to their trakt-accounts, but that does not remove the non-child-friendly (cinemeta)titles.

On our shared devices, such as TVs, being able to have profiles depending on who is viewing, is very much wanted. Mind you, the ability to link to separate trakt-accounts is crucial. But since Trakt is not directly part of Stremio, the profile feature would need to have separate addons for each user.

**Comment by da-bosa** [comment]
Are the features already implemented?

**Comment by TRtomasz** [comment]
closed as duplicate

**Comment by TRtomasz** [comment]
https://github.com/Stremio/stremio-features/issues/622#issuecomment-4673832722
