### ISSUE TITLE
Hide button or parental controls

### ISSUE THREAD

**Issue by akabane001** [Stremio/stremio-features#1082]
**Stremio Version**
Stremio for AndroidTV1.6.12

**Is your feature request related to a problem? Please describe.**
A lot of inappropriate shows are appearing as a suggested watch and I have a 6-year old who uses it (especially horror which no one in the family watches).

**Describe the solution you'd like**
Can we please get a hide button to hide individual shows, either on the UI or a list function similar to Netflix? Or have specific accounts for Kids that filter anything higher than PG?

**Describe alternatives you've considered**
Heard there was it was possible to remove categories via Trakt, but this did not work for me.

**Additional context**

**Comment by TRtomasz** [comment]
closing as duplicate same request exists in multiple isntances in this repository.
