### ISSUE TITLE
"ignore" or "hide button" for particular titles

### ISSUE THREAD

**Issue by akabane001** [Stremio/stremio-features#1083]
**Stremio Version**
Stremio for AndroidTV1.6.12

**Is your feature request related to a problem? Please describe.**
Similar to a "mark as watched", would like the option to ignore certain titles.  I don't want to use the above as it appears that like this particular content whereas I want to see less of it.  This way I can filter out anything that looks grotesque and not family-friendly.

**Describe the solution you'd like**
Have a similar button next to "mark as watched" that will remove the title from the recommended viewing.
Also the Steam gaming library has a similar function where you can mark games are played or to be ignored on the store library.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by TRtomasz** [comment]
closing as duplicate
