### ISSUE TITLE
External Players support

### ISSUE THREAD

**Issue by jafuuu** [Stremio/stremio-features#109]
VLC is cool and all but DirectShow players, such MPC & PotPlayer, have some unique features that could enhance the viewer experience.

I might not be the most technical person out there but even I understand that some functionality could break, so maybe make it an add-on and warn the user that things like time tracking might not work with an external player, maybe?

Thanks!

**Comment by jafuuu** [comment]
Well, scratch that, I figured there there is support for MPC-BE but I keep getting this error:

![Capture](https://user-images.githubusercontent.com/4993220/60842757-1a4c0e80-a192-11e9-8291-39fcaabfcc79.PNG)

Both Stremio and MPC-BE installed on default locations, S1 Windows 7 64-bits

**Comment by jafuuu** [comment]
Fixed it by adding in server.js and extra space at the end of
```
subArg: '/sub ',
timeArg: 'startpos ',
```
subtitles doesn't seem to load tho, but playback works just fine; closing and opening Stremio revert this change

**Comment by TRtomasz** [comment]
Hi, we know about this issue, at we have fixed it on our side. It should be released soon.

**Comment by maxoku** [comment]
Is there a support for MPC-BE? I don't see it. I see only VLC. How to use it?

**Comment by Enigmatic-Onion** [comment]
> Is there a support for MPC-BE? I don't see it. I see only VLC. How to use it?

the path in the default server.js is wrong. change the pathname from ```'"C:\\Program Files\\MPC-BE x64\\mpc-be64.exe"'```
to ```'"C:\\Program Files\\MPC-BE\\mpc-be64.exe"'```
