### ISSUE TITLE
Stremio won't use the mpv.conf setting vo=gpu-next

### ISSUE THREAD

**Issue by erickyun** [Stremio/stremio-features#1096]
Stremio Version
Stremio Version: 4.4.168
OS: Win11
MPV: [mpv-dev-i686-20241227-git-379c078](https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20241227/mpv-dev-i686-20241227-git-379c078.7z)
Note: [Did edit stremio-executable in a HEX-editor so Stremio can read mpv config file](https://github.com/Stremio/stremio-shell/issues/81#issuecomment-1737716993)

Is your feature request related to a problem? Please describe.

Describe alternatives you've considered
Nothing

Additional context
When using Stremio with MPV as the default video player, the software fails to activate gpu-next for video playback. Stremio won't use the mpv.conf setting vo=gpu-next to enable gpu-next for video playback. As a result, Stremio defaults to CPU-based video rendering. However, activating gpu-next from the console works as expected.

**Comment by TRtomasz** [comment]
go to the settings and enable hardware accelerated decoding

**Comment by erickyun** [comment]
> go to the settings and enable hardware accelerated decoding

The issue still persist even with hardware accelerated decoding enabled, Stremio defaults to vo=direct3d. It seems to ignore the vo=gpu-next setting entirely.

Also, currently, Stremio suppresses the MPV on-screen display (OSD) by default during video playback. This issue is especially noticeable when the 'Launch player in a separate window' option is disabled. How can we override this suppression so that I can access the MPV settings without having to enable 'Launch player in a separate window'?

**Comment by TRtomasz** [comment]
from mpv docs `There is currently no support for the libmpv / render API in vo_gpu_next.`
it is not possible to have it with stremio
also stremio does not support external mpv confings at the moment

**Comment by OverWorldD** [comment]
is it possible to make it support mpv.conf args? that'd be neat
