### ISSUE TITLE
Special characters problem & No DLNA cast

### ISSUE THREAD

**Issue by StVnCataliN** [Stremio/stremio-features#110]
There is a problem with showing the special characters for Romanian subtitles. Characters like: "Ş" , "Ţ" ... . And also I am very frustrated because there is no option for "Cast to TV". I have an LG Smart TV with WebOS and I have no option to watch movies or TV Shows directly on TV.

**Comment by mostlyash** [comment]
@StVnCataliN have you tried installing a DLNA app on your TV and configuring it that way?

**Comment by TRtomasz** [comment]
Closing as DLNA is not supported. Issue with subtitles is known
