### ISSUE TITLE
Your own video category

### ISSUE THREAD

**Issue by master3395** [Stremio/stremio-features#111]
I believe that each user should be able to make their own playlist.
Instead of having to scroll through pre made.
Like if you have friends over and want to have a list of videos/series in 1 list.
It should not take ages to search up the names to find the videos or series.
Imagine if you forget or have to write down the names of the videos/series.
It would be extra work.

**Comment by TRtomasz** [comment]
@master3395  maybe this can be achieved with this https://www.reddit.com/r/StremioAddons/comments/axjx8i/remote_addon_imdb_user_watchlist_for_stremio/

**Comment by master3395** [comment]
> @master3395 maybe this can be achieved with this https://www.reddit.com/r/StremioAddons/comments/axjx8i/remote_addon_imdb_user_watchlist_for_stremio/

I don't really use IMDb.
But it's in the same view as me, just not just external view.
I was thinking more of just an internal "show up in your playlist".

**Comment by TRtomasz** [comment]
There are two solutions 1. Create custom addon that will provide catalogs for movies/series of your choosing 2. Use Library to add there your favorite videos.
