### ISSUE TITLE
Select and Display multiple (2+) subtitles

### ISSUE THREAD

**Issue by RazuErisu** [Stremio/stremio-features#112]
Hi, I would love to have a feature to select 2 different subtitles and display them both at once (maybe position one at the top and one at the bottom? Image Examples are down below).
Me and my partner speak 2 different language yet we love to watch shows together. This is also nice if you're learning a new language.

Image Examples:
https://img.raymond.cc/blog/wp-content/uploads/2009/04/potplayer_multiple_subtitles.jpg
https://img.raymond.cc/blog/wp-content/uploads/2009/04/merge_subtitles.jpg

Maybe display even more than 2 subtitles at once? but 2 would be sufficient for mine and my partner's needs.

Thanks for reading/considering this feature.
Raz.

**Comment by TRtomasz** [comment]
That is out of scope of Stremio currently.

**Comment by wewark** [comment]
I'd like that too.

**Comment by jihadismail8** [comment]
why is out of the scope ? here is an open source package that can help with the requested feature , https://github.com/wistful/srtmerge , you can easily add a button that would merge two or more srt files (or links) and use it in the vedio . here is package in rust " https://github.com/emk/subtitles-rs  " . i hope this would be implemented  . thanks guys for the great work . i love stremio
