### ISSUE TITLE
MPC-BE timeArg should be "/start "

### ISSUE THREAD

**Issue by wilkerfoureaux** [Stremio/stremio-features#116]
Before opening issue #115, I tested the settings of MPC-BE as external player.

The actual command line switch don't work well and I got it fixed only after changing

`timeArg: '/startpos',`

to

`timeArg: '/start ',`

leading with a space, at server.js 132596 line.

    /startpos works with "hh:mm:ss" format, while /start works with milliseconds.

**Comment by TRtomasz** [comment]
Sorry for long waiting,should be fixed in next release.
