### ISSUE TITLE
Custom Subtitle needed  | | |  + one subs related bug

### ISSUE THREAD

**Issue by Draxler** [Stremio/stremio-features#12]
I think Custom subs are first and foremost much need it function Stremio users needs. A lot of time this is the reason why users are forced to switched Stremio with other streaming app with custom subs available. In case when Stremio can't find subs or non of the found subs isn't insynced corectley with the video, user want to add custom subs he or she found on the net.

If Custom subs would be implemented, Stremio would also get ridd of one other subs related bug. 
A lot of time when subs are available for video material that is playing at the momment, SUBs option doesn't turned up (isn't visible) on Stremio player. User need to Cancel video and start again for subs option to actualy turned up. 
I think if Custom subtitles would be implemented into Stremio that also issue above would desapear since Subs option would be always visible by default with Custom subs option available. 
(subs option should be visible always no metter if subs are found or not)

**Comment by Ivshti** [comment]
I agree that this has to be implemented. An alternative however, which may be viable in most cases, is clicking "Wrong subtitles" in the subtitles menu. This will give you an option between differently synced subtitles.

**Comment by Ivshti** [comment]
Should I close this: https://github.com/Stremio/stremio-features/issues/1 ?

**Comment by Draxler** [comment]
Ooo S... , ! i completley forgot i already do this feature reqeust.. :blush: i'll close #1 .

**Comment by Ivshti** [comment]
This is implemented, will be on the next build (tomorrow) as well as a few other things - e.g improved context menus

**Comment by Draxler** [comment]
:+1:

**Comment by Draxler** [comment]
Btw. It's a litlle bug and quick fixed which could be fixed before update so i won't made special bug report.

Take a look at Audio on Stremio Player. When Audio become visible on Stremio player, it's marked same as Subtitles as SUB. So user see 2 SUB options on player when subs option is also visible. It's only text bug. Text on audio option need to be replaced, from SUB into Audio.

**Comment by Ivshti** [comment]
I think there's a report on that: 
https://github.com/Stremio/stremio-bugs/issues/1

Wow, good job reporting issues! You're so good you're now finding them again! :)

**Comment by Ivshti** [comment]
The 3.3.3 release now has the ability to drag / drop .srt files into the Player

Read about it here: https://www.reddit.com/r/Stremio/comments/3sfjap/stremio_333_custom_subs/

**Comment by Draxler** [comment]
About this Audio-SUB thing, i did know i already reported, before i reported again here. it was just, 
i thoght you somehow overlooked my first report about this bug because there was no replay on that Bug report so .. the rest is history. :wink:
