### ISSUE TITLE
Discord Rich Presence

### ISSUE THREAD

**Issue by Suburbanno** [Stremio/stremio-features#120]
Please add, something like this.
![image](https://user-images.githubusercontent.com/13632826/71373325-8fbb6800-2595-11ea-94db-d4154e01f787.png)
![image](https://user-images.githubusercontent.com/13632826/71373331-9944d000-2595-11ea-80ed-8d82cf44de9e.png)

**Comment by jaruba** [comment]
Hi, there is already such an addon available as a local addon for [PimpMyStremio](https://github.com/sungshon/PimpMyStremio).

Here is the addon in question: [Discord Rich Presence](https://github.com/Sleeyax/stremio-discord)

**Comment by rollingmoai** [comment]
Updates on this? The extension is no longer maintained.

**Comment by kKaskak** [comment]
implemented
