### ISSUE TITLE
Trakt Sync 

### ISSUE THREAD

**Issue by ravtakhar** [Stremio/stremio-features#123]
I have the Trakt addon installed and it pulled in all of my shows. However, it's not going back and updating information on my trakt profile and when I add a show to my list (trakt) it won't come back and populate back on Stremio.

**Comment by TRtomasz** [comment]
There is a cache so it might take some time in order for changes to be visible in stremio

**Comment by ravtakhar** [comment]
@TRtomasz I've been using Stremio for months at this point and nothing has gone back into Trakt. My watched list is still stuck.

**Comment by TRtomasz** [comment]
Watched list? So you meant that videos watched in Stremio are not synchronized with trakt?

**Comment by ravtakhar** [comment]
Yes

**Comment by TRtomasz** [comment]
In order for that to be synced you have to watch a video till the very last second that's how it work at the moment

**Comment by krishne35** [comment]
> In order for that list to be synced you have to watch video till the very last second that how it works at the moment

Any update on this ?

**Comment by TRtomasz** [comment]
@krishne35  Movies are marked as watched by trakt once you watch at least 80% of them as far i remember.

**Comment by krishne35** [comment]
> @krishne35  Movies are marked as watched by trakt once you watch at least 80% of them as far i remember.

But the reverse is not true meaning movies from trakt history isn't marked as watched on stremio
