### ISSUE TITLE
Request: add "hide" for shows and movies

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Stremio/stremio-features#124]
In case I don't want to be offered with specific ones.

This allows me to hide those that I watched not just via the app, but also from other places.
Or, just because I don't want to see some.

**Comment by TRtomasz** [comment]
thats not possible due to how stremio works as this comes from addons.

**Comment by AndroidDeveloperLB** [comment]
@TRtomasz  There is no way to overcome it? Can't you generate IDs to the items from the source of them?
