### ISSUE TITLE
Request: offer rating 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Stremio/stremio-features#125]
So that each could be marked according to the quality.

For example, if you tried to watch from some sourced, but they have bad quality so you've stopped watching, you could mark them as bad-quality, and try the next ones.
This can help managing the sources and watching only the good ones.

The rating could be either completely local or available for all, but the local rating should have a priority.

**Comment by TRtomasz** [comment]
Closing, as this will not be implemented. We cannot store such data especially in regards to streams from unknown sources.

**Comment by AndroidDeveloperLB** [comment]
@TRtomasz Why not? Not even locally?
You already save the streams themselves. Each one has some ID, so just save how much we rate each one...
I wrote that it can be completely local too, on the PC/device.

**Comment by TRtomasz** [comment]
@AndroidDeveloperLB  we cannot spent multiple on a feature that would be used by very few users.

**Comment by AndroidDeveloperLB** [comment]
@TRtomasz How do you know how many would use it?
What do you mean by "spent multiple" ? Multiple what? Spend what?
How do you suggest users to handle torrents/streams that don't work , when many are offered and there are plenty of addons available?
There isn't even an indication of which addon each stream came from.
