### ISSUE TITLE
Request: offer magnet links

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Stremio/stremio-features#126]
So that if you really want to handle the downloading on a different torrent client, you could.
Please add it for both Android and PC

**Comment by TRtomasz** [comment]
This is now available in Stremio version 4.4.116 - simply click in player with right mouse button, there is new option in the context menu "Copy Magnet Link"

**Comment by AndroidDeveloperLB** [comment]
@TRtomasz Nice, but not available for Android yet?
