### ISSUE TITLE
PPA for Linux

### ISSUE THREAD

**Issue by Tbizla** [Stremio/stremio-features#13]
Would you be willing to create a ppa for linux users if it is possible?

**Comment by Ivshti** [comment]
Yeah, of course we want to do that, unfortunately we have a few large things on our plate atm.

Actually, deb packages and etc. can be built from the current .tar.gz without an issue.

**Comment by TRtomasz** [comment]
@Ivshti  is it still valid or can be closed?

**Comment by Ivshti** [comment]
There is no PPA, but there is a .deb on the website, so we can close this

**Comment by assafmo** [comment]
https://assafmo.github.io/2019/05/02/ppa-repo-hosted-on-github.html
