### ISSUE TITLE
Request: allow to set how many seconds to move using the arrow keys

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Stremio/stremio-features#130]
Currently it moves quite a lot (I think it's about 5 seconds).
If I miss something that was just said, I would prefer to just move a second or so.
This way if I want more, I just press more...

Please allow to customize this number.

**Comment by TRtomasz** [comment]
That will be part of the next release, thanks for your patience.

**Comment by AndroidDeveloperLB** [comment]
Thank you very much for this.

**Comment by AndroidDeveloperLB** [comment]
@TRtomasz Today I got a new update, and I still see that it skips a lot exactly as before. It has a customization of just down to 5 seconds, which was the same as before.
If I miss a single word, I have to go back a whole 5 seconds...

You said I will be able to customize the number of seconds. There is only a list of how many, and 5 seconds is the minimal...

:(

**Comment by AndroidDeveloperLB** [comment]
@TRtomasz Please re-open the request.
