### ISSUE TITLE
Content from Magnet Link to My Library

### ISSUE THREAD

**Issue by thiagowww** [Stremio/stremio-features#132]
Hey!

Possible to have an option for content added through Magnet Link to display on Stremio interface such as My Library, Continue Watching, Other, etc?

Some contents cannot be found through add-ons - specially dubbed movies - so would be awesome to have them displaying on the platform to keep watching or watch again.

Thanks,
Thiago

**Comment by TRtomasz** [comment]
Hi,
You can convert magnet link to torrent file and save this file locally http://www.magnet2torrent.com/
Stremio local addon should discover the local torrent file and you will be able to use it in the way you mentioned.
