### ISSUE TITLE
Problem with Persian subtitles 

### ISSUE THREAD

**Issue by mfat** [Stremio/stremio-features#134]
**This is not a duplicate. Please read additional description of the problem at the bottom of the post.**

Hi I set my default subtitle language to Persian but no there is no entry for Persian when I try to load subtitles for a movie.

Example: [The Adjustment Bureau movie](https://www.opensubtitles.com/en/subtitles/7278692-the-adjustment-bureau-2011-720p-bluray-x264-yify)

Also I wish there was a way to load external subtitle files on Android tv boxes.

A previous issue I posted was closed before I had a chance to explain. There ARE Persian subtiltles on opensubtitles.org for the movies I tested. But Persian is completely absent from the list of available subtitles for the movie on Stremio.

**Comment by TRtomasz** [comment]
Please install this addon. http://subtitlesv2.strem.io/ it will provide persian subtitles. Although you will have to manually select them from the subtitles menu. They should be listed under `per`

**Comment by mfat** [comment]
That's great. Many thanks!
