### ISSUE TITLE
Lower cache settings

### ISSUE THREAD

**Issue by sshaji** [Stremio/stremio-features#141]
Please include lower cache settings like 250MB, 500MB, 1GB etc. Currently 2GB is the lowest we can choose. Will be good for low memory streaming players.

**Comment by TRtomasz** [comment]
Caching doesn't work in that way, stremio will use as much space as file does. Cache space usage will be checked when you start streaming another video and then in case cache limit has been reached, stremio will remove other files.

**Comment by sshaji** [comment]
Question,
If I choose 2GB caching and the cache size reach 2GB, what will happen?
