### ISSUE TITLE
Better TV-like experience

### ISSUE THREAD

**Issue by ales-tsurko** [Stremio/stremio-features#143]
Hi,

I really liked Stremio. It's a lot faster and more stable then Kodi. I'd like to switch to Stremio. It looks good. But it does so far until you want to watch it on the sofa and use a remote control, instead "right in front of the display" usage. Can you add an option to make everything like 2x-3x times bigger or some alternative theme for this, or something like this?.. Just try to watch it from 2-3 meters far from the display and you'll understand what I mean. Sorry, but this is what makes Kodi better then Stremio — Kodi is really suitable for TV-like experience and even as a TV OS, but with Stremio you should continuously move your ass to your PC/laptop and back to the sofa because you just can't see anything. And it ruins everything.

Also, can you make it more adopted for remote controls? Currently, it's possible to switch between some items in the menu on a page but to switch between pages you need to use cursor, which is really inconvenient with a remote control. To make it adopted for remote controls you just need to make it possible to navigate using only arrow keys, enter/return and backspace/escape.

Everything else looks great and very promising. Thanks for your work and for this great software!

**Comment by Sunnysky** [comment]
A wireless "Wii" key/touchpad solves this or similar wireless key + 
mouse for remote PC control.

Overall:
  The Torrent addons help but many selections don't work.
RD paid service helps.

Stremio has a common interface that works unlike chameleon Kodi with 
many unknowns  for failure yet awesome when it did work.

But lately Powershell.exe is stuck in a constant loop and sometimes more 
than one.
This is a nuisance CPU hog on equiv of 1/N CPU's e.g. up to 12.5% of 8 
CPU which I can kill with no ill effects.


Tony Stewart

**Comment by ales-tsurko** [comment]
@Sunnysky you don't need those wireless stuff when you have a remote control. I didn't say that you can't use a remote control with Stremio, I said it's inconvenient because you need to use cursor a lot (this "wii"-like thing). For example, you can't switch to the navigation bar without using cursor.

For the theme, I didn't mean to introduce full theming support and I like Stremio's theme, I just thought about some zoom feature. That would solve the problem. I mean adoptable zoom — not the one when you get everything bigger and should scroll, but the one where every element becomes bigger and layout changes.

BTW I already found a workaround — to use the web version and zoom there. The one, which you get when you use **Cmd + =** and **Cmd + -** (on macOS). Of course, to use the web version running the desktop one in parallel isn't a very good solution. Also, Backspace and Escape just switch off the fullscreen mode instead of moves you to the previous page, as in the desktop version. And the worst thing is that at least some if not all IPTV addons just don't work there. It would be great to have the same zoom feature in the desktop version.

**Comment by TRtomasz** [comment]
closing that one as it was achived with new android tv app.
