### ISSUE TITLE
[Request] In App Torrent Search Using Jackett API 

### ISSUE THREAD

**Issue by zero77** [Stremio/stremio-features#146]
**Is your feature request related to a problem? Please describe.**
There are limited sources for torrents, which makes
stremio less all inclusive as you have to find and add torrents like a standard torrent client.

**Describe the solution you'd like**
I would like to see Jackett API support added so that you can search for torrents all with in stremio.
Jackett works as a proxy server to search for torrents, it uses the Torznab or TorrentPotato protocols to communicate with Jacket itself. Esenchly you send a search request to Jackett and it sends results back.

**Additional context**
Torznab example:
>   GET http://servername.com/api?t=tvsearch&apikey=xxxq=The%20Beverly%20Hillbillies&season=S01

![screenshot_2018-11-12 sonarr sonarr](https://user-images.githubusercontent.com/16563034/48353080-718ef300-e686-11e8-8694-6b224fde7ed7.png)

Also the following may be helpful:

- ResultsController.cs is where the query endpoints are located (Potato and Torznab actions)
- Torznab action returns XML and accepts TorznabRequest as an argument
- Potato action returns JSON and accepts TorrentPotatoRequest as an argument
- To view configured trackers one can issue the following request: http://127.0.0.1:9117/api/v2.0/indexers/all/results/torznab/api?apikey=[APIKEY]&t=indexers&configured=true
- To query all configured trackers one can issue the following request:
http://localhost:9117/api/v2.0/indexers/all/results/torznab/api?apikey=[APIKEY]&q=hackers%201995

Example, search plygin used by qbittorrent:
https://raw.githubusercontent.com/hannsen/qbittorrent_search_plugins/master/jackett.py

https://github.com/Jackett/Jackett

**Comment by TRtomasz** [comment]
that is outside of stremio scope. Content is provided by addons.
There is community project called PMS that provides jackett api 
https://github.com/sungshon/PimpMyStremio
