### ISSUE TITLE
Popular in your AREA ?

### ISSUE THREAD

**Issue by Draxler** [Stremio/stremio-features#15]
What that means **Popular in your AREA ?** 
... are movies available besed on Poppularity on user AREA =IP  ? 

Since last update a lot of movies which have streams on STREMIO and have tons of sources available at kat.cr, sudenley there's no streams available in Stremio.
Since update i also see this sign; ''Popular in your area'' which make me wonder;
Let me get this right; If some movie is available at Kat.cr and if this same movie is not popular in my area, is that mean that app won't get this movie for me becuase i got ''wrong'' IP? but some other user will get this same movie because it's popular in his/her area?  I think if movie is available at kat.cr app should get it, no metter if movie is Popular in someones area or not.

- Gardians of the Galaxy -- No Stream available
- The Maze Runners -- No Stream available
- Fast & Furious 7 -- No Stream available
- Edge of Tomorrow -- No Stream available

![1](https://cloud.githubusercontent.com/assets/7681671/11385162/5f7fceb2-9316-11e5-9022-752fb40e2753.PNG)

![2](https://cloud.githubusercontent.com/assets/7681671/11385283/7bc929be-9317-11e5-9983-fd9362001179.PNG)

![4](https://cloud.githubusercontent.com/assets/7681671/11385174/79b2ce9c-9316-11e5-89ba-874c6d90b58e.PNG)

![6](https://cloud.githubusercontent.com/assets/7681671/11385182/85469d88-9316-11e5-88a3-50e4ec9cb46b.PNG)

- there are more titles which could be add it. 

Streams for these movies were available before on STREMIO. These movie titles are realy strong on trackers in general and have a lot of available sources to choose from at kat.cr and are super seeded. But for some reason i get 
''No stream available'' .

I like to know if app indeed work this way. Or am i wrong about all this and issue lies some place else.

Or maybe this new API need some more twiking ?

**Comment by Ivshti** [comment]
It's not a new API. It's always been there, just the GUI is enabled now.

Also, "Popular in your area" refers to **popular add-ons** in your area. For example Juan Carlos Torrents. 

The issue lies elsewhere though, I guess Juan Carlos Torrents is losing more and more torrents for some reason, could be because of takedown orders to trackers, caches or etc. :)

**Comment by Draxler** [comment]
If Juan Carlos Torrents API get's torrents from kat.cr then these movies should have a lot of streams available for them. Issue should be somewher else then.. anyway, thanks for explaining all Popular in your Area thing .. :smile:

**Comment by Ivshti** [comment]
It does pull from kat but it doesn't do it very well, it appears.

**Comment by Draxler** [comment]
Today all these movies have streams available...  i gues API had a bad day yesterday. :smile: 
i'm closing this.
