### ISSUE TITLE
"Watch Party" with friends

### ISSUE THREAD

**Issue by AleksanderEvensen** [Stremio/stremio-features#151]
**Describe the solution you'd like**
During the pandemic, it has been hard watching movies together with your friends. I would like a party watch feature that lets you share ex. a party code and then you and your friends can watch the exact same movie at the same time.

**Comment by Ivshti** [comment]
this is out of scope for stremio itself but there's a great service that does just that: try https://peario.xyz/

**Comment by AleksanderEvensen** [comment]
Thanks. I will be trying out https://peario.xyz/
