### ISSUE TITLE
Playback speed controls

### ISSUE THREAD

**Issue by greyml** [Stremio/stremio-features#154]
**Is your feature request related to a problem? Please describe.**
Not being able to watch videos at different  speeds with out reselecting vlc every time there is a new episode 

**Describe the solution you'd like**
Playback speed controls

**Describe alternatives you've considered**
Being able to use vlc by default and continue playing from vlc to next episode when done without having to reselect.

**Comment by leanlow** [comment]
I second this! I typically watch a lot of my shows at 1.25 - 2x speed bc it makes the pacing better. Also it's great for binging. Right now I'm doing the vlc method too, but sometimes captions don't transfer over. It would be cool to have native controls within stremio for playback speed!

**Comment by HumayanKabir-re** [comment]
I second this well. Some of us badly need this

**Comment by umagon** [comment]
Yes please! A lot of people nowadays are trying and adopting this feature where present. I myself recommend it and it´s well received very often.

**Comment by wisdomrider** [comment]
Can someone contribute to this issue?

**Comment by TRtomasz** [comment]
Implemented in desktop and android app
