### ISSUE TITLE
Cimemeta update to TMDB. 

### ISSUE THREAD

**Issue by mrcanelas** [Stremio/stremio-features#158]
Hello guys, have you considered changing the Cinemeta? it takes a long time to be updated, and it doesn't have some of the titles that I want to watch (they are anime), I don't know if the problem is IMDB or something else, have you considered using TMDB as a source? because they have an API, I believe it is easier than using IMDB, another cool thing is that they have several languages which would make it possible to choose the language from the catalog in the settings of the Cinemeta, is this possible?

**Comment by Ivshti** [comment]
We use TMDB already, but we don't get new items from TMDB

The problems usually are in how we discover items and queue them for updating, as none of the APIs (afaik) have reliable sources for new items.

**Comment by mrcanelas** [comment]
Thanks for responding @Ivshti , and how much to use TMDB for metainfo in other languages? it would be possible?
