### ISSUE TITLE
Choose what Film Language you are the most interested

### ISSUE THREAD

**Issue by kripskroll** [Stremio/stremio-features#16]
Hi all,

Because I'm french, I'm more interested by movies in French if possible (or I would like to be able to choose)
I have installed through github the Juan Carlos Torrent 2 addon (JCB9090/juan-carlos-torrents-2) and I modified the multipass.cfg.js at line 48 : 
https://kat.cr/movies/?rss=1
to
https://kat.cr/usearch/FRENCH/?rss=1
and line 50 
https://kat.cr/highres-movies/?rss=1
to
https://kat.cr/usearch/french%20category:highres-movies/?rss=1

I also deleted before to restart the multipass-torrent addon database to be sure to start with a clean DB. 
It works partially because I can see that multipass-torrent is retrieving a few torrent (far more less than the default search) but I still see in the Stremio Desktop application many Movies that are not French or not seen by multipass-torrent.

Thanks

**Comment by Ivshti** [comment]
First, does stremio load with a different catalogue in Discover than the default one? If not, then you haven't loaded the add-on

Also, the way add-ons override the DIscover order is:
1. they put their movies/series first
2. after that, stremio may choose to display movies/series from it's own Cinemeta add-on

So if you see french movies on top then everything is alright, if not, then the add-on isn't loaded

Ensure you start stremio with --servicesPrio=http://localhost:PORT_OF_ADDON

**Comment by kripskroll** [comment]
Thanks.
I started stremio with --servicesPrio=http://localhost:PORT_OF_ADDON
I suppose French movies are loading because I achieve to find one when I play it and sounds were in French; 
BUT 2 things :
Most of the movies that are discovered raise a "No Stream" when I try to play them
Or I have a warning "Movie Still In Theatre" that seems to block it to play.

How does it work ? Is it possible to disbale the check on this ?

**Comment by Ivshti** [comment]
This is normal, since your local add-on does not have a lot of movies indexed.

What's important is, as I said, that the order in Discover changes from the default order, that will indicate the add-on has loaded. You'll see in your SEttings panel if the add-on is loaded, and you'll also have the option to toogle it.

When you manage to play something, press "D" or hover on the stream info icon in the bottom right to see a information dialog, which will say on it's bottom which add-on you're playing from.

**Comment by kripskroll** [comment]
That's fine the add-on is loading (I chanegd the ID name and description to be sure because the add-on keeps the name Juan Carlos Torrents 2.)

How can I improve movies indexed ?
How to disable the check on the movies that raised the "Movie Still In Theatre"

Thanks for your time

**Comment by Ivshti** [comment]
I don't know about juan carlos torrents, but I know that multipass would only index the info hashes found on the url you pass to it. It won't automatically know to index page 2, page 3, page 4 and so on of any given website.

So you'll have to figure out a way to pass to it either page 2/3/4/... of the rss feed, which I think is impossible, or find another way to scrape info hashes.

```
3727:1127/105843:INFO:CONSOLE(5)] "Discover pulled 16 items from http://localhost:7025",
```
This means it's working properly :) But after the first 16 movies stremio is going to show a default catalogue

**Comment by kripskroll** [comment]
Juan Carlos is in fact just only a configuration file for multipass.
I need to look at multipass doc (not really well documented or I do not understand it) to see how I can do it.

How can I disable the default Stremio catalogue ?

**Comment by Ivshti** [comment]
We can call out @jaruba to help with the multipass documentation. You should look at http://github.com/Stremio/stremio-addons too, explains, albeit poorly, the basic mechanisms behind the add-ons in Stremio. 

I'll have to supplement that with documentation on how stremio actually calls meta.find/meta.get/stream.find, but I've been delaying that since we'll release actual open-source client soon.

As for over-riding the default stremio catalogue - the concept is that you'll just serve enough items so that the default stremio catalogue never comes into play. Also, what I mean by "default stremio catalogue" is actually cached items, not something pulled every time.

That said, I could think about how to distinct between streamable / non-streamable in discover when you just glance at it.

**Comment by jaruba** [comment]
![666ec8587d11b175c1b44dbcfec1df4bcd4a0a455737ca75eb3939a766fc0d31](https://cloud.githubusercontent.com/assets/1777923/11439685/c8d2f178-9505-11e5-8f38-d5c2d3eb876a.jpg)

**Comment by kripskroll** [comment]
Hi Jaruba,

I tried using Juan Carlos Torrents configuration file to use multipass-torrent as an add-on for Streamio but to look at French movies.
It works pretty well, except that I have a lot of "No Stream" when I try to play them. Ivshti just tell me probably due to lack of indexed files...
I also have a lot of "Movie Still In Theatre" : Is it something done by multipass .

Thanks in advance

**Comment by Ivshti** [comment]
@kripskroll as I mentioned, multipass now gives you 16 items. Of course all others will be not available, since it only has 16 items.

To solve this, you have to index more content.

That's why I called out @jaruba to brainstorm how to index more french content from kat

**Comment by kripskroll** [comment]
OK, I've got it running.
No issue in Stremio.
It is only Juan-Carlos-Torrent issue = multipass configuration file 
I did not use one source that look for Seeded streams.
Now I have 250 torrents indexed and I have no more "No Stream" issue.
I still have an issue with "Movie Still In Theatre" an I need to investigate in multipass code to understand.
@jaruba I'm fulling open for any advice
Thanks

**Comment by jaruba** [comment]
I.. I don't know.. maybe if @vankasteelj and @kripskroll knew some good public french only torrent sites, those could be used with multipass to build a good french catalogue..

The way multipass works now, it could even be made into a script to just run from time to time on specific searches on those sites to keep the catalogue up to date, if stremio can't be "hacked" into doing it automagically.

**Comment by jaruba** [comment]
> I still have an issue with "Movie Still In Theatre" an I need to investigate in multipass code to understand.

unfortunately i have little knowledge on how multipass communicates with the stremio catalogue, but i seriously doubt that the solution your looking for is in multipass and not stremio. :/

**Comment by Ivshti** [comment]
@jaruba it is in multipass

as I said, it's simply about having more content indexed. If there is no content indexed, of course you're going to get a lot of "movie still in theatre" mesasges.

it's not about looking at the code, although that will be helpful to understand how multipass interacts with the stremio catalogue, but simply about indexing more content

**Comment by kripskroll** [comment]
@jaruba 
>The way multipass works now, it could even be made into a script to just run from time to time on specific searches on those sites to keep the catalogue up to date (if stremio can't be "hacked" into doing it automagically)

Isn't it multipass that is doing it. Juan-Carlos-Torrent is doing that by just providing a configuration file for multipass.
 
> @kripskroll knew some good public french only torrent sites, those could be used with multipass to build a good french catalogue..

http://www.cpasbien-torrents.fr/film-streaming/2015/

Thanks for your time

**Comment by Technoblink** [comment]
This list includes the best official [**Stremio addons**](https://www.techgiga.net/stremio-addons/) and also the best unofficial/network stremio addons that enables you to watch tons of free content.
