### ISSUE TITLE
Use ram when no chache is selected

### ISSUE THREAD

**Issue by raycekar** [Stremio/stremio-features#160]
Many devices for tvs and such have limited flash storage.  With any type of writes to flash will deplete it's lifespan

So from what I could gather, when you set stremio cache to no cache, there is a temp file on the hard drive/ssd still temporarily storing that video file.  

This is a feature request to do any caching to the ram when set to no cache setting is selected instead of a writing to flash.

This request is mainly for Android devices and android tv but can also benifits desktop devices as well.

**Comment by Ivshti** [comment]
You misunderstood - the no cache option does precisely that - it caches in a 100mb ring buffer placed in the ram

**Comment by raycekar** [comment]
Now I know, sorry and thank you!

**Comment by Skorpinakos** [comment]
@Ivshti 

> You misunderstood - the no cache option does precisely that - it caches in a 100mb ring buffer placed in the ram
> 
> Your arguments are precisely why we implemented it

Is it possible to increase the 100mb in-ram buffer size or even add an option in the settings? 
Many desktop users can spare considerable amounts of RAM in order to protect their storage devices from wearing out through write & read ops. 

Thanks in advance for your time !

**Comment by jaruba** [comment]
@Skorpinakos this would offer no benefit, the ring buffer feeds the video player buffer, increasing the ring buffer size will only cause duplication in memory, as both ring buffer and video player buffer would hold the same data (twice)

the correct approach would be to allow the video player buffer to be increased in the settings, but given that we use many different video players (depending on platform, and on android tv we have 2 video player options) it is not trivial to add such a setting
