### ISSUE TITLE
Video Source Availability Indicator

### ISSUE THREAD

**Issue by yahyaanwar** [Stremio/stremio-features#161]
**Is your feature request related to a problem? Please describe.**
I always get frustrated when I open a film card but in the end I don't have the source for the movie.

**Describe the solution you'd like**
It would be nice when I was able to know in advance how many video sources were available before I opened them.

**Describe alternatives you've considered**
Or at least I know that the film has no video source at all. The options for hiding it are great too.

**Additional context**
I only use Torrentio and ThePirateBay+ as video sources so not all movies are available to watch.

**Comment by Ivshti** [comment]
Unfortunately this feature is nearly impossible 

Requesting all addons is really resource heavy both towards your internet connection and towards the addon themselves

and aggregating/keeping an index is not possible for privacy/legal reasons
