### ISSUE TITLE
Filter Content Based on language or Country

### ISSUE THREAD

**Issue by TheRealTechWiz** [Stremio/stremio-features#163]
**Is your feature request related to a problem? Please describe.**
Can't discover my local content. Top content is always english content.

**Describe the solution you'd like**
Give an option to view content(movies and series) of only a particular language or based on region. This will be a really nice thing to have where english is not the first language or multilingual countries.

**Describe alternatives you've considered**
Filter by language or filter by region.

**Comment by jaruba** [comment]
... I already explained this quite clearly on the community chat..

**Comment by TheRealTechWiz** [comment]
I understand that sir. It's just that I really really wanted this feature. Even a decent filter i.e. not very accurate would have worked. something is better than nothing. And it's not like it is impossible to implement this many apps already have this feature.
 In any case I understand the difficulty associated with this. Thankyou for your time. Have a good day.

**Comment by jaruba** [comment]
you can always study the addon sdk:
https://github.com/Stremio/stremio-addon-sdk

and create an addon for it if u really really want something..
