### ISSUE TITLE
Local Library - No login required

### ISSUE THREAD

**Issue by igorcmelo** [Stremio/stremio-features#166]
**Is your feature request related to a problem? Please describe.**
"My Library" is currently only on Cloud

**Describe the solution you'd like**
For gest users, have a local library for saving favorite TV shows

**Comment by TRtomasz** [comment]
It isn't required. Once you turn on local addon in settings 
![image](https://user-images.githubusercontent.com/40594253/114175156-95c38c80-9931-11eb-8fef-8eb660a06c18.png)
and restart stremio you will be able to see your local content in Discover -> Other -> Local Files catalog
