### ISSUE TITLE
Easier marking as watched

### ISSUE THREAD

**Issue by maxoku** [Stremio/stremio-features#175]
**Is your feature request related to a problem? Please describe.**
It's annoying when I have to click on every episode with right mouse button and then click with left button on second option to mark it as watched.

**Describe the solution you'd like**
It would be nice to mark all episodes that are below at once. Cuz if I watched 50th episode so most likely I watched all before it.
Additionally mark whole seasons that would result in marking each episode in it.

**Comment by TRtomasz** [comment]
Marking the whole seasons as watched will be added in next release :)

**Comment by maxoku** [comment]
Thank you for adding marking whole seasons as watched. I really appreciate it, but it's not a full solution for the problem. First it doesn't work on special category only numeric seasons. Second I can't use it when there are no seasons like YouTube channels.
So it would be nice if the issue was reopened and my main suggestion would be reconsidered.
I'm talking about an additional option in episode context menu. Next to "Mark as watched" another option to mark all below as marked. That all episodes that are below it would be marked as read with single click. E.g. if use it on 50th episode then episodes from 1 to 50 would be marked as watched.
It would really be helpful for YouTube channels or seasons with a lot of episodes where I'd like to mark only half of the content.

**Comment by victorgveloso** [comment]
> Next to "Mark as watched" another option to mark all below as marked. That all episodes that are below it would be marked as read with single click.

"Mark all episodes below as watched" would be a nice addition for stremio's UX. 

Is the "Mark as watched" pop-up implemented on stremio-shell with Qt? Or is it from the closed-source UI?
