### ISSUE TITLE
Remember subtitles only for specific shows

### ISSUE THREAD

**Issue by maxoku** [Stremio/stremio-features#176]
**Is your feature request related to a problem? Please describe.**
It's annoying to have to enable and disable subtitles on series/movie switch. Subtitles are needed only on series and movies that are not in known language. E.g. I need then on anime, cuz I don't know Japanese, but I don't need them on American TV shows, cuz I know English.

**Describe the solution you'd like**
It would be nice if Stremio would remember that I set subs for anime and would automatically enable every time when I watch it. But at the same time wouldn't automatically enable it on other ones.

**Describe alternatives you've considered**
Alternatively it would detect language and enable subs when audio is not in known language. It would require adding an option with language list to select multiple languages. It would also require detecting the audio language which I presume isn't easy.

Easier would be to just to have subs disabled by default and setting them separately to each series/movie/channel. Not to remember it globally and have it disable again on the next show that already is in English and doesn't require subs.

**Comment by maxoku** [comment]
That function would be very appreciated while I have a serious problem with one of the tv shows. It turns off subtitles every time I go back from playing or go to next episode, but when I open other show the subtitles are on. Very annoying to not have subtitles in the series that I need the most but just pop out when not needed at all.

**Comment by TRtomasz** [comment]
This will not be implemented, as it is highly subjective. While one user might have it remembered for whole series another might want to have it enabled only once. Cluttering UI with setting for everything isnt a solution. In almost all our apps you can select default subtitles language to none/disabled. In currentl desktop app this is not possible but can you can use a workaround and set some exotic language to defualt one and this way you will have subtitles most for the most of the time.
