### ISSUE TITLE
Platform Option (ie. Netflix, Prime Video, Disney+, Hulu etc) and UI like JustWatch.com

### ISSUE THREAD

**Issue by aamiralihere** [Stremio/stremio-features#177]
**Is your feature request related to a problem? Please describe.**
We are unable to know about the movie/series platform

**Describe the solution you'd like**
An addon that categorizes movies/streams according to their platform (ie. Netflix, Prime Video, Disney+, Hulu etc) like JustWatch.com. Also if you can add filters and UI like JustWatch.com it would be great.

**Describe alternatives you've considered**
JustWatch.com

**Additional context**
![Screenshot 2021-03-05 01 56 34](https://user-images.githubusercontent.com/8972937/110029574-734cbb00-7d56-11eb-935b-e79863c5e843.png)

**Comment by TRtomasz** [comment]
There is new community addons called Streaming Catalogs. You can use it for this.
