### ISSUE TITLE
Mark Series as Watched, Watched per season and Non-Watched

### ISSUE THREAD

**Issue by Lamp-Post** [Stremio/stremio-features#18]
Right now when you right-mouseclick on a tv-series and click 'Mark as watched' it does not mark all the episodes as watched. Maybe add this? It may also be handy to be able to mark a whole season of a series as watched. And could you also add an option to mark it as non-watched, this is able with movies but not yet with series

**Comment by Ivshti** [comment]
Yep, I agree, but first thing that has to be implemented is a visual 'watched ' indicator for an episode

**Comment by natostanco** [comment]
also playing episodes from torrents/magnet links should mark them as watched automatically, I am not sure if this is related to the fact that such episodes are not yet included in the episodes list or not.

**Comment by seahindeniz** [comment]
Hi @TRtomasz

I couldn't find any option to mark seasons or a single season watched. May I know why this issue got closed or could you explain how to use the functionality?

**Comment by TRtomasz** [comment]
@seahindeniz it has been added but it has not been deployed this. Sorry this is github automation which closed it.

**Comment by seahindeniz** [comment]
Hey @TRtomasz, Thanks for the reply! 
It's been ~2 years since this issue got closed. Do you know when this feature will be deployed?

**Comment by TRtomasz** [comment]
Sorry, didnt notice. It was closed due to lack of activity. Although the feature with marking seasons as watched will be added in next release. I can't give you exact date but it will be available soon.
