### ISSUE TITLE
UI/UX: Possibility to automatically select stream / filter streams list

### ISSUE THREAD

**Issue by igorcmelo** [Stremio/stremio-features#180]
**Is your feature request related to a problem? Please describe.**
It is not a bug. Just a UX enhance idea.

When a user face something like this below, with a huge list of options, it is probably very confusing.
Also, for each episode of a series, the user has to select the stream again, what is kinda annoying.
![image](https://user-images.githubusercontent.com/59902451/111069335-5711f200-84ab-11eb-8466-def32c0c508c.png)
<br><br>

**Describe the solution you'd like**
Something that Stremio could (optionally) do, is to **remember the preferred resolution**, things like **dubbing / original** and automatically select the stream that best matches and has more peers.
<br><br>

**Describe alternatives you've considered**
Another option I thought would be to the user to manually specify preferred resolution and other necessary options to select the best stream. 
Also, instead of selecting the best stream, Stremio could filter the streams list to just a few that matches some criteria specified.
<br><br>

**Additional context**
In my case, I always watch things on original language, 720p, and I always choose the stream that has the greater number of that little avatar, which I believe is the number of peers.
So I always have to scroll from 4k, 2k, 1080p to 720p, for every episode of any series I watch.

**Comment by edwyn-amador** [comment]
This would be very useful! Please add this🙏
