### ISSUE TITLE
[Request]Sync with google calendar, please

### ISSUE THREAD

**Issue by TheLorry** [Stremio/stremio-features#181]
A clear and concise description of what the problem is that: I follow several series simultaneously and having the calendar only in the desktop version is a problem when used with the mobile version.

**Describe the solution you'd like**
A clear and concise solution is sync the stremio's internal calendar with de google calendar, same way like gnome does for example. 
with such a synchronization, not only does the mobile user have access to the Stremio calendar feature, but it also extends that access to multiple devices " easily "

**Comment by Ivshti** [comment]
this feature already exists

1. go to stremio.com
2. login
3. go to your account management
4. scroll down to Calendar and you can add iCal
