### ISSUE TITLE
Set default or/and remember dubbing language

### ISSUE THREAD

**Issue by maxoku** [Stremio/stremio-features#184]
**Is your feature request related to a problem? Please describe.**
Every time I open a video with multiple audio tracks it's starting playing in a language I don't know and have to manually change it to English. It's beyond annoying.

**Describe the solution you'd like**
It would be nice to have a setting where I can set a default audio language that will be automatically chosen.

**Describe alternatives you've considered**
Or at least it would remember that I chose once English and choose it every time.

**Comment by DaedalusBLN** [comment]
+1, we need this feature... Also make sure to add all language abbreviations like english;en;eng

**Comment by TRtomasz** [comment]
Done in 4.4.144
