### ISSUE TITLE
Show addon loading progress on Android

### ISSUE THREAD

**Issue by ssnjrthegr8** [Stremio/stremio-features#185]
![image](https://user-images.githubusercontent.com/38104354/115235508-e740f800-a137-11eb-9dc3-576fc906c831.png)

Stremio on desktop shows how many addons are left to load streams and it is really useful. I find it quite frustrating when I wait for streams on android with no way of knowing if a certain addon is still loading or not.

**Comment by jaruba** [comment]
@ssnjrthegr8 This is a valid request, I have added a task for it for the Stremio Android app.
