### ISSUE TITLE
Multiple subtitle tracks at the same time

### ISSUE THREAD

**Issue by zardoy** [Stremio/stremio-features#186]
Motivation / alternatives have greatly described here: https://www.raymond.cc/blog/playing-two-subtitles-at-the-same-time-in-dvd-player-and-computer/

### Motivation
> In some areas of the world, you might see more than one set of subtitles on a cinema screen at once. This is because the country might have more than one major language so just showing one subtitle language isn’t enough

I need this feature to learn foreign languages.

Please let me select multiple subtitle tracks (by holding CTRL key for example). Thank you!

**Comment by jaruba** [comment]
This has been requested a few times in the past too, but I don't think that we will add it anytime soon, most of our users do not have any need for it.

**Comment by pabloalgo** [comment]
Would be a nice feature, VLC or ororo.tv had it

**Comment by hewei07** [comment]
As a Chinese, i also want to have this feature so that i can read Chinese and English together.

**Comment by zardoy** [comment]
> I don't think that we will add it anytime soon

I understand it took several years to add a button to copy magnet link. I think these guys are just extremely busy on implementing ...

Meanwhile, you can *copy stream link* and then watch anything you want in *performance player with secondary subtitles support* such as [IINA](https://iina.io/) (idk an easy way to enable them on mpv).

<img width="393" alt="Screenshot 2022-01-29 at 16 24 40" src="https://user-images.githubusercontent.com/46503702/151662906-eb17336c-8ff7-492e-83d1-63ff2c0bee3e.png">

**Comment by jihadismail8** [comment]
here is an open source package that can help with the requested feature , https://github.com/wistful/srtmerge , you can easily add a button that would merge two or more srt files (or links) and use it in the vedio . here is  a Rust package https://github.com/emk/subtitles-rs

**Comment by abacnus** [comment]
where to get this now? https://github.com/wistful/srtmerge

I am getting "Page not found" now.

**Comment by zardoy** [comment]
> where to get this now? https://github.com/wistful/srtmerge
> 
> I am getting "Page not found" now.

Why would you ever need? Just use mpv which has native support for secondary subtitle track. Here is what you do:
1. Paste the stream link into the player
2. Press ` to open the console
3. Type `set secondary-sid 2` where 2 is the id of loaded subtitle track (starting from 0)
