### ISSUE TITLE
Option to change volume increase/decrease steps

### ISSUE THREAD

**Issue by Araxeus** [Stremio/stremio-features#187]
### The problem
I'm always annoyed by the insensitivity of the volume control shortcuts, its always either too loud or too quiet
I would  personally prefer much smaller steps
(steps = the change in volume percentage on volume up/down via shortcuts, **which is currently 10% fixed**)
(shortcuts = mousewheel && arrow up/down)

### Possible Solution
Maybe just add a setting to change the volume "steps":

Could be like those cool options:

![21-04-2021 17 55 35](https://user-images.githubusercontent.com/78568641/115575048-dd9bc980-a2ca-11eb-8850-25e72457dea9.png)

I think allowing complete custom steps value from 1 to 20+ would be best
but if not, just some pre-made values could be great too.
for example: [1% , 2%, 5%, 10%, 15%, 20%]
(Personally I would want to set it on my pc to 1% per step, a tenth of the current default value)

### Additional Note
I'm not sure how exactly the volume control is implemented here, 
but this feature should probably change both mousewheel and arrowkeys volume control

**Comment by Araxeus** [comment]
Not worth implementing? Based on what lol

Other people need it but I don't = not worth?

You could atleast say "Closed as this is not planned in the near future"

**Comment by TRtomasz** [comment]
@Araxeus not worth = would be used by very small fraction of users, based on user reports who asked about something like this i would say propably only by you. Therfore considering how small team we have right now we prefer spend our time on features that will have greater impact
