### ISSUE TITLE
Shortcut button to show controls

### ISSUE THREAD

**Issue by maxoku** [Stremio/stremio-features#189]
**Is your feature request related to a problem? Please describe.**
It sucks when every time I want to see controls (title, time of playing etc.) I need either move mouse or pause the video.

**Describe the solution you'd like**
It would be nice to have have a shortcut button that would make controls appear like when I pause or move mouse without doing those things.

**Describe alternatives you've considered**
Button could either show controls for a moment or toggle it.

**Comment by jaruba** [comment]
Thank you for your suggestion, I added a task for it for the Desktop app.

**Comment by maxoku** [comment]
Yeah, it works, thanks.
