### ISSUE TITLE
Allow to download with a download manager

### ISSUE THREAD

**Issue by maxoku** [Stremio/stremio-features#190]
**Is your feature request related to a problem? Please describe.**
If I want to download something I need to open the browser, in Stremio click to download the video, cancel downloading with the browser, copy link from adres bar, close the browser, open download manager and paste link in download manager. It's frustrating to do so many steps.

**Describe the solution you'd like**
I would like to download the video with my download manager instead of the browser.

**Describe alternatives you've considered**
Or maybe just allow to copy the link instead of sending it to the browser. Then I can paste it in my download manager, so half of work is saved.

**Comment by jaruba** [comment]
Thank you for your suggestion, I added it as a task for Stremio Desktop.

**Comment by maxoku** [comment]
It's not really resolved. The "Copy stream link" doesn't have the same link that is used in "Download this video". The latter is better, cuz contains the file name, while the first is only a digit like 0 or 1.
