### ISSUE TITLE
Request: allow to set less than 5 seconds to move using the arrow keys

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Stremio/stremio-features#192]
It's actually this request:
https://github.com/Stremio/stremio-features/issues/130

But I was probably mis-understood.

The app doesn't let me move just a little in the playback. It is at least 5 seconds. Even before the new update. It's way too long.
That's in fact the number one reason for me to sometimes prefer downloading instead of watching directly on the app, as the UI is very annoying in terms of being a player.

**Comment by igorcmelo** [comment]
For now, try using VLC.

**Comment by TRtomasz** [comment]
Done in 4.4.144
