### ISSUE TITLE
Caching Debrid Streams

### ISSUE THREAD

**Issue by gozervandechat** [Stremio/stremio-features#195]
I think allowing for caching when streaming from a debrid server/https connection will make for smoother playbook especially on weaker internet connections and 4k streams.

**Comment by gozervandechat** [comment]
Alternatively an option to extend the 100MB RAM allocation would also work

**Comment by jaruba** [comment]
@gozervandechat Is this feature request for Desktop or Android?

**Comment by gozervandechat** [comment]
@jaruba I think this would make sense for both Desktop and Android.

**Comment by Dyras** [comment]
@jaruba This would indeed be absolutely golden. I wish we had it on both Android (Great for Media Players, etc) and Windows (For those of us watching at the PC)

**Comment by paurakhsharma** [comment]
Also Android TV please.

**Comment by TRtomasz** [comment]
It is not possible on Android TV due to lack of space, on desktop you can just use option to download video.
