### ISSUE TITLE
Boost volume

### ISSUE THREAD

**Issue by maxoku** [Stremio/stremio-features#196]
**Is your feature request related to a problem? Please describe.**
Yeah, some videos are very quiet, they are just make that way. It produces problems that even if every volume control is set to maximum it just still might be too quiet to comfortably watch while other sounds might be too loud. In those cases I have to have surroundings very quiet and extremely focus to listen what gives me headaches. Or I can manually send video to my video player by e.g. downloading it.

**Describe the solution you'd like**
It would be nice if Stremio would boost volume like some video players do. In settings could be an option how to boost e.g. 100% the boosting is off, 200% is two times louder etc. Thanks to that I can still watch comfortably in Stremio.

**Describe alternatives you've considered**
Or Stremio could detect itself the the volume in certain video is very quiet and boost it automatically.

**Comment by jaruba** [comment]
This is an edge case that I haven't seen anyone else complain about tbh. Although we will not add it as a feature of it's own, there is already a task to allow users access to the internal MPV player config file, changing that file would allow configuring volume boost.

**Comment by maxoku** [comment]
Was it added that the volume can be changed by modifying the file?
