### ISSUE TITLE
Request: when choosing to download a video, set the correct name of it

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Stremio/stremio-features#198]
**Is your feature request related to a problem? Please describe.**
More of a problem.
When I choose to download the video, I get "0.mkv" instead of the original title that I would get by downloading via magnet link

**Describe the solution you'd like**
Use the same name as you'd get via magnet link.

**Describe alternatives you've considered**
Magnet link?

**Additional context**
v4.4.137

**Comment by jaruba** [comment]
This has been requested before, `0` in this case is the file index within the torrent file list.

Could you state why the file naming is a problem for you?

**Comment by AndroidDeveloperLB** [comment]
@jaruba Because if I download, I expect it to have a proper name. Imagine if I download multiple...
Why not using the real name?

:(

If it was requested, can I close this and star the other request?

**Comment by TRtomasz** [comment]
This has been added in the last release.

**Comment by AndroidDeveloperLB** [comment]
@TRtomasz Can we also choose to download and/or open/copy magnet link even before starting to play?
