### ISSUE TITLE
Tiny request: allow to copy app version 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Stremio/stremio-features#199]
**Is your feature request related to a problem? Please describe.**
Request

**Describe the solution you'd like**
Be able to copy the version name. 

**Describe alternatives you've considered**
Maybe just be able to select this part as text.

**Additional context**
Useful to write here which version we are talking about.

**Comment by jaruba** [comment]
I'm sorry but I do not see the realistic value in this, you can just as easily screenshot the bottom right side of the settings page and post the screenshot..

**Comment by AndroidDeveloperLB** [comment]
Screenshot doesn't later allow you to search it textually.

**Comment by jaruba** [comment]
Even if we'd allow copying the version tags, most will still screenshot them, so text search still couldn't be used. Besides, we have no need for text searching version tags.

**Comment by AndroidDeveloperLB** [comment]
@jaruba Your choice. 
On Android Studio, for example, using CTRL+C (or pressing a copy-button on the dialog) will copy the entire information about the IDE. Example:

```
Android Studio 4.2.1
Build #AI-202.7660.26.42.7351085, built on May 10, 2021
Runtime version: 11.0.8+10-b944.6842174 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4000M
Cores: 12
Registry: external.system.auto.import.disabled=true, ide.settings.move.mouse.on.default.button=true, debugger.watches.in.variables=false
Non-Bundled Plugins: String Manipulation, org.jetbrains.kotlin, com.google.mad-scorecard, org.intellij.plugins.markdown, GenerateSerialVersionUID
```
