### ISSUE TITLE
Streming quality selection for tv shows

### ISSUE THREAD

**Issue by rauldipeas** [Stremio/stremio-features#2]
Please, give to us this feature.
480
720
1080

**Comment by bloodshinoda** [comment]
+1

**Comment by Ivshti** [comment]
As already mentioned, please do not post any issues related to non-official Add-ons. Currently no official add-ons provide TV shows.

Perhaps we should explain a bit better how Stremio works.

Stremio picks streams for TV Shows / Movies / Channels from the Add-ons which you can see in the Settings panel, which are by default the official ones + popular in your area.

**Comment by Ivshti** [comment]
I'm closing this, because the functionality is implemented in stremio, but which shows have HD is beyond our control as we do not produce any add-ons with TV shows.

**Comment by rauldipeas** [comment]
Thank You for nothing, Your app really sucks.
