### ISSUE TITLE
Ubuntu integrated playback controls

### ISSUE THREAD

**Issue by astra1** [Stremio/stremio-features#20]
Stremio should support the [MPRIS2](http://specifications.freedesktop.org/mpris-spec/latest/) specification
thanks

**Comment by Ivshti** [comment]
We've implemented media keys integration using [Electron](http://github.com/atom/electron)'s APIs, and it works on Mac and Windows. Apparently doesn't work for MPRIS2, I'll open an issue report if there isn't one already

**Comment by 360fun** [comment]
on Mac OS 10.14.6 Media Keys don't seem to work either... :(
