### ISSUE TITLE
Request: Add UI buttons for 5/10 seconds playback

### ISSUE THREAD

**Issue by SandeMC** [Stremio/stremio-features#202]
Sometimes I don't want to use arrows on my keyboard but instead UI, but UI doesn't seem to have such buttons. Is it possible to add?

**Comment by jaruba** [comment]
Most video players don't have such buttons though, we're trying to keep the video player UI as minimalistic as possible, as otherwise it could become crowded easily.

**Comment by SandeMC** [comment]
Ah, okay, makes sense. Great to see you guys want to keep it simple.

пт, 2 июл. 2021 г., 15:09 Alexandru Branza ***@***.***>:
