### ISSUE TITLE
Request: Save torrents/magnet links from nyaa Groups.

### ISSUE THREAD

**Issue by InFerNoBeasTz** [Stremio/stremio-features#203]
Could you allow stremio to save magnet links and torrents from nyaa since i get specific anime torrents from groups/fansub on nyaa. In the image provided I have to paste this nyaa link everytime I login to stremio which is long. 
![Capture](https://user-images.githubusercontent.com/52253277/124358043-5d70d900-dc16-11eb-919d-c2e7e98ae20b.JPG)

Thank you

**Comment by TRtomasz** [comment]
Hi,
I think feature you are looking for is playing local content. You can go to the settings -> Streaming and enable local addon option (Stremio restart required)

**Comment by rzfzr** [comment]
@TRtomasz  I'm not sure if that's what OP had in mind, I am too looking for a "Save to Library" button on opened magnets
