### ISSUE TITLE
Make locked plugins uninstallable

### ISSUE THREAD

**Issue by QNET17** [Stremio/stremio-features#206]
I would like to be able to uninstall locked plugins so that I can customize the whole thing to my needs. Restrictions, locks... In this day and age, these things have a negative connotation.

**Comment by TRtomasz** [comment]
At the moment only two locked addons are cinemeta and local addon and they are like this for a reason, as they provide basic functionalities to stremio, allowing users to remove them might end with a lot of users making app not usable for them.
