### ISSUE TITLE
[Request] Always play with external player

### ISSUE THREAD

**Issue by Qu4tro** [Stremio/stremio-features#207]
I like mpv. I _really_ like mpv. I think the set of features I use are unlikely to be ported to stremio player (i.e. keybinding to jump to next subtitle), so I'm not going to ask for them.

Instead, what I would appreciate, would be to check a settings box, that makes it so that all videos are played in mpv by default. Hopefully allowing it to be combined with the auto next-video toggle.

Thank you! Stremio is great!

**Comment by TRtomasz** [comment]
This feature was added to stremio 5, stremio 4 will not implement it. It is also already present int Android and Android TV app.
