### ISSUE TITLE
General UI: Ratings on posters

### ISSUE THREAD

**Issue by Bananaman** [Stremio/stremio-features#210]
The RPDB project made me realize how great it is to see ratings on posters to make it easy to find good movies when glancing at a wall of unknown posters you have never heard about.

I am not sure how feasible this is. But if the API from cinemeta/tmdb returns the ratings from various sites, perhaps it would be doable to display that info directly in the general catalog listing rather than just on the details page.

Here is what the ratings poster project looks like, for inspiration, to see why this is a great feature:

https://ratingposterdb.com

**Comment by TRtomasz** [comment]
Hello,
sadly cinemeta addon has only IMDB rating at the moment, so there is no possibility to add such feature.

**Comment by Bananaman** [comment]
@TRtomasz Ah okay, understandable. Thanks for the answer.
