### ISSUE TITLE
Subtitles: Prefer embedded subtitles for target language

### ISSUE THREAD

**Issue by Bananaman** [Stremio/stremio-features#211]
I have noticed that Stremio insists on searching plugins for subtitles, and always picks something external from the web. Even when videos have incredible, perfect subtitles in the target language already embedded.

This is when Stremio has been configured to apply default subtitles.

So let's say there is a movie with perfectly synced Swedish subtitles embedded. Stremio will still try the internet instead and will find often-desynced subtitles instead.

I know that you use ffprobe and ffmpeg. Is it feasible to probe the embedded subtitles and select those before searching the internet?

**Comment by TRtomasz** [comment]
Hi,
Stremio shell application will prefer embedded subtitles over external in the next release on which we are working now.

**Comment by Bananaman** [comment]
@TRtomasz That's beautiful news, thank you so much! :)

**Comment by Bananaman** [comment]
@TRtomasz Thanks a lot again for implementing it. I can confirm that the feature is working. Thanks a lot! :)

One [user on Reddit was saying that the feature is broken](https://www.reddit.com/r/Stremio/comments/r0cv16/stremio_desktop_tech_update_13/hm1wl17/) and isn't selecting embedded subtitles on some videos, but I think I've figured it out the reason for that. So I'll post my theory here in case other users wonder the same thing:

> In video files, whenever you embed subtitles, you have two data fields that can be set for the subtitle streams:
> 
> 1. Language Code: A value such as "en" for English or "sv" for Swedish.
> 2. Title: Just text, can be anything, like "English Director's Commentary" or just "English".
> 
> 
> Nobody forces anyone to set a language code or title. I think most of the professional rip-groups do it properly though. But it's totally possible to leave a blank language code or title, or both.
> 
> Most likely, the broken video examples you are using, are just "text titles", without any language code data.
> 
> So Stremio cannot know what language it is, even if the TEXT TITLE is something that seems clean like "English" or "English \[SDH\]", there's no way to assume that the title is correctly spelled and is the correct track and correct language etc. The only way to know for sure is via a Language Code like "en". So if language code is missing, then I suspect that Stremio skips the embedded subtitles.
> 
> Basically, it's not Stermio's fault that some videos may not be tagged properly.

**Comment by Bananaman** [comment]
@TRtomasz That being said, perhaps it's worth adding a title scanner too. Just a really basic one which only supports properly spelled English names for the languages. Since that's the most common scenario.

It could analyze each embedded subtitle stream like this:

1. If `language code` exists, use that value and stop here.
2. Otherwise, look at `title`.
3. Trim the title to remove leading/trailing whitespace.
4. Scan the title for a case-insensitive, English name for a language. Meaning "SWEDISH", "Swedish", "swedish" would all be interpreted as Swedish. If that is found, use that value and stop here.

This would probably cover at least 70% of all videos that lack tagged languages, since they usually have clean, English TITLES describing each language.

As for "special" streams, just ignore them. Meaning, if you see something like "English [SDH]", just ignore it, since it's not a clean language description. Many videos have both "English" and "English [SDH]" embedded at the same time, so it would not be good to interpret both as pure English. SDH for example is annoying extra text which is only meant to help deaf people, such as "\[Sound of someone opening the door\]". And likewise, other examples such as "English [Director's Commentary]" or "English Director's Commentary" etc are not clean language names either and need to be ignored.

So yeah... that's my proposal for a simple way to scan non-tagged languages without any risk of messing up. I can make a new ticket to track the idea if this sounds like something you'd want to consider.

I guess there are quite a few content sources that are lazily ripped with only titles, no language codes, so it could be a very good improvement for Stremio...
