### ISSUE TITLE
Subtitles: Primary and Secondary language choices for default subtitles

### ISSUE THREAD

**Issue by Bananaman** [Stremio/stremio-features#212]
Most people speak two languages (their native language and English).

Therefore platforms like Kodi let people select multiple languages as their preference, in a prioritized order.

It would be fantastic if Stremio could apply the same logic.

For example: Primary Language = Swedish, Secondary Language = English.

When starting a movie, it would try this order and stop as soon as it finds a match:

- Primary Language Embedded in Video (see https://github.com/Stremio/stremio-features/issues/211) 
- Primary Language from Internet
- Secondary Language Embedded in Video
- Secondary Language from Internet
- no subtitles (this change is also important because currently it just picks a random useless subtitle from some unknown language if it can't find what you want 😂)

Hopefully this idea makes sense for an improvement to Stremio. 😊

**Comment by TRtomasz** [comment]
Hi, thanks for your ideas
We are trying to make stremio as simple as possible to use. Adding 3 additional settings for subtitles it just cluttering app with uncessary options.
@jaruba  if you don't agree please reopen.

**Comment by jaruba** [comment]
We won't implement this, it's been discussed in the past too. The majority of the users would never need or want such a feature.

**Comment by Bananaman** [comment]
@TRtomasz @jaruba Thanks for explaining the reasoning. It's unfortunate since it would make life easier if it would auto-pick my native language or fall back to English otherwise. It would only be one extra box in the settings:

- Preferred Subtitle Language: Swedish
- Fallback Subtitle Language: English

Is that really too complicated? Especially considering how much it simplifies the life of all users.

Currently, the workflow is this: Play the media. Pray that it has your subtitles, because if it doesn't, then it randomly picks some useless subtitle in a random language like Chinese or whatever it finds, which has no relation whatsoever to what the user wanted as preferred language. Then, the user has to stop the video, open the subtitles panel, and explore the list to try to find something better.

This is what every user has to do almost all the time, since most of the world is not native English speakers, and prefers their own language, but their own language is quite often not available. So they end up with a randomly picked language and have to edit the subtitle every time they play some media. It's a terrible experience at the moment.

Adding a secondary/fallback language option would totally solve it.

I have a suggestion for a fix which doesn't involve adding extra settings though:

1. We make the assumption that almost every person on Earth would pick English as their Fallback/Secondary Subtitle Language, so we don't add any extra settings to the GUI at all. We just assume English as the fallback.
2. Search internal subtitles for preferred language.
3. Search internet for preferred language.
4. If both of those failed, search internal subtitles for English.
5. If that failed too, search the internet for English.
6. If that failed too, don't display any subtitles at all (currently Stremio randomly enables some useless subtitle such as Chinese or whatever it found, if it couldn't find what you really wanted).

So, there's an algorithm that makes some easy assumptions which are correct for 99% of all people on Earth (using English as fallback) who are rich enough to have media players, thereby doesn't need to add any extra settings. And instead simply improves the subtitle selection algorithm to do "The Right Thing" automatically for most people.

:-)
