### ISSUE TITLE
[Feature] GUI Scale setting to fix small and unreadable GUI

### ISSUE THREAD

**Issue by Bananaman** [Stremio/stremio-features#216]
Would it be possible to add a GUI Scale slider to Stremio?

There are a few problems with it on Desktop.

On Windows, the GUI seems to follow the Windows desktop scale. It's pretty okay but looks a bit big (not perfect).

On Linux, both KDE and GNOME, it ignores the desktop scale (which I have at about 2x on a 4K TV), and Stremio therefore renders super tiny. Cannot read the text unless I stand with my face a few centimeters from the TV. 🤣

I researched and [apparently Electron is supposed to properly use Linux desktop scale](https://github.com/electron/electron/issues/2625), but Stremio is not working.

Anyway, since it's really just a website viewport renderer, it would be great to get control of the actual scale. Then users could get the perfect size for their desktop. Even on the Windows desktop, Stremio would benefit from extra control of the GUI size.

Hopefully it would be possible to implement one of these two things:

- Either a user control for the GUI scaling.
- Or fixing the support for Linux desktop scale factor so that the GUI isn't unreadably tiny anymore. This solution seems harder because it looks like Electron has a very limited understanding of desktop scale, and doesn't understand DPI and other things that also affect scale.

Or perhaps someone has any other ideas? 😊 Maybe a pair of binoculars 🔭 on the sofa to look at the Stremio GUI with? 🧐🤔😉

**Comment by garoto** [comment]
@Bananaman sorry to tag you on this issue of yours, but do you care to clarify to me if are you are indeed the next incarnation of @SteveJobsWosniak? (I'll delete this comment once you reply on in ~24h). Someone on IRC a long time ago (circa 2019), said you're dead, so just checking.

**Comment by Bananaman** [comment]
The simplest solution would be to pass through the regular Electron / Chromium scaling keys: `Ctrl +`, `Ctrl -` and `Ctrl 0` to zoom in/out and reset to 100%.

**Comment by Bananaman** [comment]
I have some news to add:

- X11: The bug exists.
- Wayland: The GUI automatically scales itself to match the desktop scale. Rendering looks great. I can see that  Stremio is rendering at 200% on my 200% scaled desktop in Wayland mode.

Either way, having a GUI scale control would:

- Fixes the X11 bug.
- Would let people set the exact GUI scale they want.

**Comment by TRtomasz** [comment]
You have to set env variable to achive this, check this out https://github.com/Stremio/stremio-shell/issues/151
also stremio does not use electron anymore it uses QT now. If you use old electron app, then for sure it will not be added.
