### ISSUE TITLE
Feature Request: Download Subtitles

### ISSUE THREAD

**Issue by edwyn-amador** [Stremio/stremio-features#222]
Along with the "Download this video" feature, please add the "Download subtitles" option as well, I would love to be able to download the selected subtitles as well, also it would be really helpful instead of having to go to the browser and manually look for those.

**Comment by TRtomasz** [comment]
You can download subtitles, after enabling them, this option is available under the gear icon
![image](https://user-images.githubusercontent.com/40594253/144204008-6ed9c08c-7695-4134-a197-0aa205619a32.png)

**Comment by edwyn-amador** [comment]
Right, didn't saw that option, probably because I was watching with the embedded subtitles.

I think it would be much better to instead of hiding this option when there's no external subtitle selected, disable (gray out) the option instead, so users can notice better that there's an option for that, just needs to have an external subtitle selected in order to enable it.
