### ISSUE TITLE
Android: Add more stream caching options

### ISSUE THREAD

**Issue by nima-sharaf** [Stremio/stremio-features#223]
Similar to the desktop builds of Stremio, add higher cache size and infinity(∞). This will help with 4K movies which are usually very large and require extensive buffering/caching.

**Comment by TRtomasz** [comment]
Actually it does not matter how big is video you are trying to watch. Even if you set cache to 2GB it will download whole video to your disk no matter how big it is. Cache size only matter for how many video files will be saved for later on your disk.
