### ISSUE TITLE
Android: Configurable Stream Caching Location

### ISSUE THREAD

**Issue by nima-sharaf** [Stremio/stremio-features#224]
Make the cache location/path to be configurable, so we can get benefit of larger storages(i.e. external).

**Comment by TRtomasz** [comment]
You can simply move app to your SD card and this way cache will be also on this sd card.

**Comment by norriswohoo** [comment]
I have moved the app to sd card and the cache still loads on internal storage 
Any other solution or 
Even a way to request this feature?
