### ISSUE TITLE
Download data from my Library

### ISSUE THREAD

**Issue by 2LaMa** [Stremio/stremio-features#227]
I use Stremio as my main library to store all the movies I've watched, and I want to watch.
It would be **great** to be able to download all the data in a CSV file, in order to complete it / sort it / share it with friends !
Ideas of columns :

-  Type : ['movie', 'series']
-  Name
-  Genre
-  Résumé
-  Length
-  Year
-  Director
-  Casting
-  **Watched or not**
-  IMDb note

**Comment by xplosionmind** [comment]
Other fields it would be very important to have:
- date added to library
- watched date and time
- IMDb unique code
- if serie, season and episode
