### ISSUE TITLE
Option to turn off Trakt scrobbling

### ISSUE THREAD

**Issue by infekSK** [Stremio/stremio-features#235]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I like having Trakt linked and being able to view my watch list, history, etc. However, I do not like it auto-scrobbling as I've ran into issues of it scrobbling the same episode multiple times

**Comment by TRtomasz** [comment]
We have fixed multiple issues with trakt scrobbling, should not be a case anymore
