### ISSUE TITLE
Trakt integration

### ISSUE THREAD

**Issue by Light7654** [Stremio/stremio-features#239]
Please add trakt watchlist, history, collection to library tab

Or 

Add a feature to update my trakt watchlist through stremio

**Comment by kwest12** [comment]
I'd like this too - solid Trakt integration is the primary reason I haven't switched to Stremio yet.

**Comment by tfouto** [comment]
+1.

Trakt integration that allows custom trakt lists makes all the diference.

**Comment by digitalbarrito** [comment]
+1 to everything mentioned already.

Just got Trakt setup with Stremio and was a little disappointed to find how lack luster the current implementation is.

**Comment by KINGLIFER** [comment]
Is there a reason why this is being ignored?

**Comment by VictorCharlie9701** [comment]
+1, this needs to happen

**Comment by TRtomasz** [comment]
https://blog.stremio.com/stremio-tech-update-28-trakt-scrobbling-2-way-sync-more/

**Comment by aleqx** [comment]
> https://blog.stremio.com/stremio-tech-update-28-trakt-scrobbling-2-way-sync-more/

The above page says:
 > Added an “Import” button for Trakt in the [User Dashboard](https://www.stremio.com/login) on the website, this imports your entire Trakt history to Stremio’s library for 2 way Trakt sync, this button can only be used once every 24h

I have a trakt account with a lot of titles in both history and collections. I have a new Stremio account, enabled Trakt scrobbling in the setting, and then I tried the Stremio Library saying "Import your media library from Trakt" (which takes me to Trakt, I allow Stremio, Stremio website then says complete, and I can return to Sremio). The Stremio window now shows the Discover tab, and in there it's selected Discover > Movies > Trakt History (showing only 10 titles) while the Stremio > Library tab is still empty.

How do I actually import my titles from Trakt?

**Comment by TRtomasz** [comment]
Click `User Dashboard` link and log in there and there you will see the button article mentions

**Comment by Chinerama** [comment]
I've Imported Trakt in my Stremio dashboard.

But I still can't see my Track movies and series collection on Stremio. I've also uninstalled and reinstalled the Trakt app in Stremio to see if that helps but it didn't work.

Is there any step or setting I may have missed? I'm on Google TV Stremio app if that helps
