### ISSUE TITLE
Sync Stremio history with Trakt

### ISSUE THREAD

**Issue by kvaidas** [Stremio/stremio-features#245]
The Trakt plugin only sends information to Trakt about what you watched after installing the plugin.

Anything that you have in Stremio as watched before the installation of the Trakt plugin isn't being synchronized.

It would be nice if it was.

**Comment by cojoMan** [comment]
+1

**Comment by kwest12** [comment]
In other similar apps to Stremio there are options to merge local info with Trakt info. I believe the result of choosing that option is that any things that have been 'watched' (or marked watched

**Comment by 1yusufjee** [comment]
I am not able to authenticate trakt scrobbling from stremio. Keep getting the following error.

"Something went wrong. Authentication may have failed"

Does anyone know the reason?

**Comment by kvaidas** [comment]
A feature like this could also help with situations where for some reason some episodes aren't getting marked in Trakt as watched.
For example, I recently finished a show and in Trakt only ~50% of episodes were marked as watched.

**Comment by ForSite** [comment]
+1

**Comment by wildgoose1uk** [comment]
+1

**Comment by Boreo** [comment]
This is the only thing stopping me switching from kodi.

**Comment by stozzo** [comment]
+1

**Comment by xologram** [comment]
+1

**Comment by TRtomasz** [comment]
can be done from stremio.com user profile settings

**Comment by ValYouW** [comment]
@TRtomasz can you please direct me on how to do that? In the settings all I see is "import" button which import trakt history into stremio, this issue talks about exporting stremio history into trakt

**Comment by Cursealot** [comment]
+1 ^

**Comment by jimhuds** [comment]
+1
