### ISSUE TITLE
External subtitles support

### ISSUE THREAD

**Issue by medanisjbara** [Stremio/stremio-features#247]
**Problem description**
Sometimes the subtitles you need aren't available in the subtitle menu under the video (maybe you search for a specific language translation that you can't find), therefore one might want to search online to get subtitles which is great. But I can't seem to find a way to add external subtitles in that menu. And dragging and dropping the subtitles results in a notification on the upper right displaying `ERR_OPENING_MEDIA invalid file`. A workaround is to open the video in an external media player (mpv in my case) and add the subtitles there.

**Suggested solution**
Having an *Add external subtitles* button where you can choose an external subtitle file you downloaded or Changing the behavior when dragging and dropping so that the subtitles will be added to the video.

Thanks a lot

**Comment by TRtomasz** [comment]
It is possible to open external subtitles but the file must be in srt or vtt format. Other formats are not supported.

**Comment by igoracmelo** [comment]
@TRtomasz 
I'm watching a show but I can't find that option to load subtitles from file.

**Comment by TRtomasz** [comment]
@igoracmelo you have to drag and drop them directly to the stremio video player. This is only available for the PC app
