### ISSUE TITLE
Copy magnet link from torrents list

### ISSUE THREAD

**Issue by rebelcode-xr** [Stremio/stremio-features#249]
Would be great to be able to copy a magnet link just right clicking on a torrent, without start the stream.

<img width="353" alt="image" src="https://user-images.githubusercontent.com/63522951/159482267-73c1b182-2461-454c-975e-f9387b5c075a.png">

The reason behind this need is that some torrents don't have enough seeds for streaming, so you need a classic "download first and watch later" approach with an external app to download torrents.

**Comment by igoracmelo** [comment]
I agree.
That is a problem that I face regularly.
Sometimes I just want a quick way to copy the magnetic link but I have to wait the content to load.

**Comment by TRtomasz** [comment]
closing as duplicate https://github.com/Stremio/stremio-features/issues/310
