### ISSUE TITLE
Stremio add/remove menu item scripts. (Linux)

### ISSUE THREAD

**Issue by ghost** [Stremio/stremio-features#25]
The gist down below should work on all linux desktops that follow the free desktop standard.
Gist for the scripts: https://gist.github.com/NityaSatta/966648a9ee144cc7672e

Notes: 
- Scripts and images should be in the same folder as the executable and start up script.
- To get the scripts to work one needs to add 4 icons with the name and size as mentioned in the add script. (I used the logo from the main website and resized it for testing.)

**Comment by Ivshti** [comment]
This is amazing!
I'm wondering how to integrate those - first question is do they require root access? @NityaSatta

**Comment by NityaSatta** [comment]
In short:
* No root access required for single user setup.
* Add the scripts and 4 expected icons to the folder with the executable and/or start up scripts.

---

Scripts like these are common in binary downloads on Linux without a installer where the goal is to give a single user an easy setup option. (Like your download right now) As a long time Linux user I would expect those scripts to be inside the archive so I can just run add when I downloaded the app and remove when updating or removing the app.

The other option is to have a flag inside your app or statup script asking the user if they want to add menu items the first time they start the app and a options to remove/update the menu items somewhere in the setup dialog of your app. In this case your app would run the full scripts or execute the bottom part of the script from within the app. (Aka "xdg-*" commands)

The scripts only require root access if your goal is to make the app available for all users. But if that is the goal the app files and the "stremio-client.desktop" file created by the script would have to be moved in to a location where all users can access them, this differs from one distro to other so the default package managers becomes a more interesting option. (or a custom installer that also adds the desktop entry using the "xdg-*" commands.)

**Comment by Ivshti** [comment]
Great!

We'll include those scripts, unless we make .deb/.rpm packages instead, which is on the agenda :) 

Probably the scripts would be easier, thank you!
