### ISSUE TITLE
Add Torrent Seeding Support

### ISSUE THREAD

**Issue by TheBluuDot** [Stremio/stremio-features#250]
**Is your feature request related to a problem? Please describe.**
Currently, Stremio leeches from the BT swarm and does not upload anything in return which is part of basic torrenting etiquette.

**Describe the solution you'd like**
Add seeding support to the app. It can upload the downloaded/cached parts back while downloading the next parts. It can be toggleable from the settings for users with low internet speeds.

**Comment by TRtomasz** [comment]
Stremio also seeds while you are streaming a video.
