### ISSUE TITLE
Cache issue on Android

### ISSUE THREAD

**Issue by dawoodk212** [Stremio/stremio-features#253]
The latest update for Android has fixed a cache issue which was that cache would automatically turn off at times. 

**New Issue:**
Now there is a new issue which is that when clearing cache from system settings > apps, the cache is used under "data" instead of "cache" so to clear cache the user has to clear data. This causes the user to have to then set up the app again. 

Could a "Manage cache or Clear cache" button be added in the app or could the cache go back to cache instead of data. 

**Increased Cache Option Needed**
Also could a cache saved be added with an increase to 100gb as most of the 4k and HDR content is above 10gb even some are between 20GB - 60GB. 

**Cache location option possible feature**
If it is possible could the user choose the location to save cache as I would rather be able to choose to save it to my external SSD if it is increased to 100GB but keep the app installed on internal storage since most android tv devices are closer to 16GB.

**Comment by TRtomasz** [comment]
Regarding cache size. It does not matter what size of cache you set. If video file you are trying to watch is bigger than whatever value you have set it still use as much space as is needed by this  file. Example File Size: 100 GB Cache Size: 1GB it will still use 100GB. Only difference is when you start to play another video then it will check if Cache Size has been reached and if so then app will delete files from cache.

**Comment by lonelypositron** [comment]
This is bad design at best.

1/First you rely completely on the app to manage that. So you don't have any way to force to delete the cache besides delete the app completely as the OP explained it to you.
2/ i can easily demonstrate to you as i demonstrated to your support member karen that in one day i can make the app go over the limit whether it's 2 or 10
3/ no caching does not delete personal storage and i suspect that besides the cache of the torrent you put also other information in personal storage 

So at the very least you should have put a button to delete the cache inside the app.
