### ISSUE TITLE
Be able to configure CORS

### ISSUE THREAD

**Issue by igoracmelo** [Stremio/stremio-features#254]
**Is your feature request related to a problem? Please describe.**
I am trying to use peario.xyz with Stremio Desktop as my server.
Problem is: Stremio only allows CORS for some specific domains, for security reasons.

![image](https://user-images.githubusercontent.com/85039990/162493696-72711f8b-53f8-4787-b2c4-fb98232a103b.png)

What I did to solve that, with the help of a friend, was, instead of running Stremio Desktop, I ran [this file](http://dl.strem.io/four/master/server.js) with the code modified for allowing CORS from anywhere (just for testing purposes).

![image](https://user-images.githubusercontent.com/85039990/162494205-71bfc7ee-ae51-4937-98a5-06ee8c23a990.png)

**Describe the solution you'd like**
For a regular user, having to run server.js and modify the code for changing CORS settings is not doable.
I would like to have an option in settings, like "Allowed origins:" and user could set some URLs to allow.

**Describe alternatives you've considered**
I don't know.
Let me know if you think of another solution :)

**Comment by TRtomasz** [comment]
I checked and peario works fine, could you please explain what is your issue exactly, perhaps you were using old version.
