### ISSUE TITLE
[Feature request] Subtitle languages

### ISSUE THREAD

**Issue by nenjeb** [Stremio/stremio-features#258]
It will be nice if we can set languages for subtitle download.

So when I play movie it show only subtitles for languages that I know.

Thanks for great work!

**Comment by TRtomasz** [comment]
You can configure default subtitles language in the settings.

**Comment by PascalDk** [comment]
> You can configure default subtitles language in the settings.

They are not always available, or multiple versions of the subs may exist for one language - and only one works fine.
In that cases, being able to download the selected sub as easily we can download the file or get the torrent would help a lot.
