### ISSUE TITLE
Auto sync playback with another user

### ISSUE THREAD

**Issue by sunnypatel** [Stremio/stremio-features#26]
I've been looking for a tool that will allow me to watch movies with my gf remotely.  The feature would only have to sync playback between 2 or more clients.  Ideally my client will generate a uuid, I can share that uuid with another client and it would attempt to sync playback.  Yes the 'weakest link' would be the person with the lowest bandwidth causing the entire party to wait but still would be a badass feature.

**Comment by Ivshti** [comment]
I agree, it would be a great feature

I've been looking at Hulu With Me and Netflix party for inspiration for this.

we're thinking on how to implement it :)

**Comment by nathanredblur** [comment]
This is cool :)

**Comment by eduararley** [comment]
It would be great!

**Comment by LucasLeandro1204** [comment]
Any solutions by now?

**Comment by TRtomasz** [comment]
Could be done using this sollution

**Comment by igoracmelo** [comment]
> Could be done using this sollution

Wait. Which one?

**Comment by TRtomasz** [comment]
Lol, @igoracmelo  looks like link didnt go through, not sure which one i mentioned back then and which one is working now https://www.reddit.com/r/StremioAddons/comments/g6klce/remote_addon_watch_together_with_friends_with_the/
https://www.reddit.com/r/Stremio/comments/cvmuok/guide_stremio_how_to_watch_together/
you could check these two posts
