### ISSUE TITLE
Android Media Session Controls

### ISSUE THREAD

**Issue by andia89** [Stremio/stremio-features#261]
**Is your feature request related to a problem? Please describe.**
When using the internal player of stremio on Chromecast (Google TV / Android TV the same), I can't open my phone and pause the video using the google home app. That also means that I cannot use google assistant to pause / unpause the video or use the TV remote (via HDMI CEC) to control  the playback. When using VLC it works (but I really prefer the internal player). As far as I understand this is because [Media Sessions](https://codelabs.developers.google.com/codelabs/supporting-mediasession#0) are not implemented?

**Describe the solution you'd like**
Implement Media Sessions on Android version, such that Android understands a video is currently played and allows to stop / start videos using Voice control and the google home app

**Describe alternatives you've considered**
Mainly using alternative players like VLC, but it is not ideal

**Comment by TRtomasz** [comment]
Thanks, we will check this out although this will mean we will have a lot of notifications from stremio, it might be pretty weird. We already have notification from a server, one from VLC interna player and this would be the 3rd one from media session.

**Comment by andia89** [comment]
That's true. But to be honest the notification from internal VLC Player would not be necessary anymore since all the information (and play pause action) would be handled by the media session. The notification from the server is arguably untlrelated. 

It's mainly annoying not to be able to use HDMI CEC and voice commands to control playback which seems like an obvious feature that would be nice to have

**Comment by andia89** [comment]
Fixed. You guys are great 👍
