### ISSUE TITLE
Import data from custom CSV/JSON

### ISSUE THREAD

**Issue by xplosionmind** [Stremio/stremio-features#262]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
As of right now, the only way to migrate from another service (note: *not* synchronizing, but moving altogether) can happen only if the user goes through their list of movies and series to watch/watched and manually add them to the Stremio library, one by one. It should be possible to import such data from other services, from a simple CSV or JSON file.

**Describe alternatives you've considered**
Going through the list of movies and series to watch/watched and manually add them to the Stremio library, one by one.

**Additional context**
- It should be possible to do something like what [Bookwyrm](https://bookwyrm.social) or [Inventaire](https://inventaire.io) offer in order to import new sera of books
- data fields should be the ones listed in #227

**Comment by TRtomasz** [comment]
I'm sorry but i guess we will not introduce such functionality. It would require a lot of effort for a feature that would be used by less then permyriad of our users.
