### ISSUE TITLE
Continue browsing while video loads

### ISSUE THREAD

**Issue by xplosionmind** [Stremio/stremio-features#264]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Instead of having to wait without doing anything while a film loads, it should be possible co continue browsing the library

**Describe alternatives you've considered**
Wait while doing nothing else.

**Comment by TRtomasz** [comment]
I can't imagine this being useful, i have checked netflix, disney+, hbo go or amazon prive non of them has such feature.
