### ISSUE TITLE
Import and export from CSV

### ISSUE THREAD

**Issue by xplosionmind** [Stremio/stremio-features#272]
I have a customized IMDb export CSV file where I log all of the movies I watched and that I like to watch. Is there a way to provide functionality to import them in Stremio, as well as exporting them, to ensure maximum portability?

**Comment by TRtomasz** [comment]
Sorry, it is not possible to import custom csv data to stremio.

**Comment by xplosionmind** [comment]
Hello! This will not even be ever planned? It is a bummer…
