### ISSUE TITLE
Option to turn off IMDB ratings on the media page, option to display Metacritic / Rotten Tomatoes / TMDB / Letterboxd / Trakt.tv ratings

### ISSUE THREAD

**Issue by lothar-cell** [Stremio/stremio-features#274]
**Is your feature request related to a problem? Please describe.**
IMDB ratings spoil the experience for me, as it gives a presupposition about the movie/show, especially because I found IMDB ratings don't reflect my taste in general.
Rotten Tomatoes rating system is particularly interesting, as it shows controversial receptions too, doesn't just reflect the opinion of a community or popular opinions in general.
Letterboxed is also interesting, because it has statistics too, not just ratings.

So basically this is about freedom of choosing your sources of opinions.

**Describe the solution you'd like**
An option to turn ratings on/off and option to change ratings sources to Metacritic / Rotten Tomatoes / TMDB / Letterboxd.

**Describe alternatives you've considered**
There's no alternative currently, when using Stremio.

**Additional context**

![Screenshot 2022-06-13 at 11 25 43](https://user-images.githubusercontent.com/2356354/173323206-132e8aa5-de6c-4f6d-9a4c-3ccdd7a8651a.png)
![Screenshot 2022-06-13 at 11 24 57](https://user-images.githubusercontent.com/2356354/173323244-3bc5452a-b64a-44aa-acd7-f9be5af34800.png)
![Screenshot 2022-06-13 at 11 23 35](https://user-images.githubusercontent.com/2356354/173323250-44881ae3-a4b4-4b8b-8466-8498ada3a4b5.png)
![Screenshot 2022-06-13 at 11 31 41](https://user-images.githubusercontent.com/2356354/173324411-130be0d5-ccf6-4c4e-9171-567b44310703.png)
![Screenshot 2022-06-13 at 11 22 51](https://user-images.githubusercontent.com/2356354/173323259-fc464740-9136-457a-a285-6f2a44fd8bcc.png)

**Comment by SanKalp4** [comment]
Interesting and helpful feature request. but do they pay heed to feature request , I see request pending unattended and unassigned for months.

**Comment by Lexatarg** [comment]
This option would be a fantastic idea. I second this

**Comment by TRtomasz** [comment]
This is not possible for stremio to implement these, we cant integreate every possible rating service into the app, maintenance of all integrations would be impossible.

**Comment by llagerlof** [comment]
@TRtomasz 

> This is not possible for stremio to implement these, we cant integreate every possible rating service into the app, maintenance of all integrations would be impossible.

Thanks, but I think I don't get it. Is it IMPOSSIBLE to hide the ratings?

**Comment by TRtomasz** [comment]
@llagerlof anything is possible, but idea for app is to be simple not to make ever one part of the app configurable

**Comment by lothar-cell** [comment]
Does your job consist of anything else than saying “not possible” to every single feature request on GitHub?
First, I didn’t ask for “every single rating service”, and when the commenter above pointed out to this, you just come up with a nonsense excuse. 
Next time just say I don’t give a s**t, because your attitude definitely implies it.
