### ISSUE TITLE
[Feature Request] Please add the option to pre-download a movie or a series in advance

### ISSUE THREAD

**Issue by tigerjoy** [Stremio/stremio-features#277]
**Is your feature request related to a problem? Please describe.**
Stremio works exceptionally well for new movies or series with many seeders but does very poorly for old torrents. I've seen that for some of the series torrents which are a bit old when streaming individual episodes the download speeds are under 1 MB/ps, but when I download the entire series by copying the magnet link using uTorrent, the download speeds exceed 4 or 5 MB/ps. 

**Describe the solution you'd like**
Because of slow download speeds/streaming speeds of individual episodes in contrast to downloading of the entire series, I was requesting a feature, where the users can select a movie, an episode or an entire series and cache it or download the entire series in advance in the system (preferably in the background), and then it can be played back from the storage medium without needing to buffer it again.  Such downloads would be cached in a manner similar to recently played movies or episodes, or the user's can be provided with the choice of manually deleting any pre-cached series through the UI.

**Describe alternatives you've considered**
The only alternative that I can find is to download the entire series using uTorrent and then using VLC or other tools to play it back. But I want to be able to do that using Stremio as it has one of the nicest UI's and also because it marks the episodes that have been completed, stores the last playback time for resumption afterwards and then I'll not need to switch between apps.

**Additional context**
Torrentio extension is one, that can pick up torrents that contain all the episodes of a series and it can easily auto-play the next episode in sequence if there are any. I believe, with the help of this extension, after identifying the torrents which contain all the episodes, the entire torrent can be cached and played back on demand without needing to buffer.

**Similar to**
#138 
#188
#240

**Related to**
#242

**Comment by isc30** [comment]
yes please, this would be great

**Comment by TRtomasz** [comment]
If you want to download video such option has been added to the desktop app, you can use it from the player. Such option will not be added on the other platforms with limited storage space(like smart tvs)

**Comment by eifr** [comment]
> If you want to download video such option has been added to the desktop app, you can use it from the player. Such option will not be added on the other platforms with limited storage space(like smart tvs)

What about android? An offline option would be very helpful before going to flights or so

**Comment by wisdomtooth** [comment]
Or also to prefetch streams with few seeders. A smart download feature like YouTube's, prefetching next episodes on a series, or movies on a list, would also be a great addition.

**Comment by rodrigoGA** [comment]
@TRtomasz  It might be worth reopening this issue. I believe this is a more than justified feature for mobile clients.

Streaming apps like Netflix already offer this functionality. It's incredibly useful in situations where you're traveling, the network will be intermittent, and you want to enjoy the content. It also makes a lot of sense to download it beforehand when the network is slow, so you can watch without interruptions.
