### ISSUE TITLE
Crop video

### ISSUE THREAD

**Issue by abavoil** [Stremio/stremio-features#279]
VLC has a crop feature which is usefull when a video contains black borders to not have borders on all 4 sides. We can use VLC but it would be a great addition for croping at different ratios to be available in Stremio, to keep subtitles, advancement etc.

**Comment by TRtomasz** [comment]
Please use template when creating new issue here. Don't forget to add most important details like Platform/OS so it is easier for us to reply. On android you already have tha feature that can change video scaling, right in the video player.

**Comment by ignamiranda** [comment]
I'd love to have this issue reopened and completed for Windows
