### ISSUE TITLE
Access .torrent files or magnet links BEFORE loading

### ISSUE THREAD

**Issue by skal-dB** [Stremio/stremio-features#280]
Is it possible to have an option to grab the torrent file or the magnet link BEFORE the video loads ?
When you have 2 or zero people sharing a file, it will never start and you will never be able to access that torrent file or magnet link.

There(s tons of old movies from the Black/White days that are just not accessible at all... just because of that.

Please bring Torrent files / Magnet link button BEFORE buffering the video.

(pretty sure that topic already exists somewhere but the search bar doesn't find them)

**Comment by igoracmelo** [comment]
@gmjimenezc personally the main problem is that I copy magnet links a lot, and having to wait for the video to start playing is kinda annoying...

**Comment by PascalDk** [comment]
> Not sure how having the magnet links beforehand would help a case with 0 seeds, still I want to work on this.

Seems obvious... 

Sometimes 0 becomes a few and in that case, with patience, you may unlock a shit load of movies that won't play in streaming but that you may eventually download.

**Comment by gmjimenezc** [comment]
@PascalDk ok, got it, do you maybe know how the contribution here works?

**Comment by PascalDk** [comment]
@gmjimenezc yes I do but I don't code.

**Comment by gmjimenezc** [comment]
@PascalDk no i mean if you can point me to contribution rules or where can i claim this issue so I can work on it? hehe

**Comment by TRtomasz** [comment]
This requires changes in part of our software that is not open source, sorry you can't contribute to add it this time.

**Comment by PascalDk** [comment]
@TRtomasz Do you know if there is any chance to see this feature soon ?
It seems to be a common request...

**Comment by falulon** [comment]
great idea, I would be grateful as well for this feature

**Comment by tester248** [comment]
Similarly, it would be useful to also have the "copy stream link" option outside the player as well. Since I prefer using an external media player.

**Comment by PascalDk** [comment]
Yep, it comes together. That's what I meant by "access torrent file" : being able to get it from magnet link or .torrent file

**Comment by Shabinder** [comment]
+1 for support of this.

**Comment by nnhieu97** [comment]
they still don't do it...

**Comment by TRtomasz** [comment]
closing issue as duplicate  
https://github.com/Stremio/stremio-features/issues/310 https://github.com/Stremio/stremio-features/issues/249
