### ISSUE TITLE
Feature Request: Android TV App Clearlogo in Player dialogue

### ISSUE THREAD

**Issue by starman2908** [Stremio/stremio-features#283]
Excellent work on the Android TV App, it's working great and looks sleek.

Would be great to see the Movie/TV Clearlogo in the app player instead of the text title(and year) that currently displays. Think it would fit really nicely with the look and feel of the app.

Thanks,

Ryan

**Comment by TRtomasz** [comment]
Logo is now displayed while loading a video.
