### ISSUE TITLE
[Android App] Feature request -Enable embedded subs size and position change 

### ISSUE THREAD

**Issue by SanKalp4** [Stremio/stremio-features#286]
[Android app] 

Hi , sometimes the subtitle addons dont work so we have to resort to embedded ones but they look big and ugly in small screen, can the size change option be enabled someway or is its restricted in embedded ones ? 

In mxplayer embedded subtitles have a perfect size, it will be helpful for most it the team can update it like that

**Comment by TRtomasz** [comment]
that is not possible
