### ISSUE TITLE
Change aspect ratio on Android TV player

### ISSUE THREAD

**Issue by DorayakiWarrior** [Stremio/stremio-features#289]
**Is your feature request related to a problem? Please describe.**
When the new app was released, change aspect ratio button available in other versions is no longer there. 

**Describe the solution you'd like**
Add the change aspect ratio back to the AndroidTV player

**Describe alternatives you've considered**
Using an external player is a workaround. However, I prefer using the internal player for a more seamless experience. 

**Additional context**

**Comment by TRtomasz** [comment]
It has been added in latest update for android TV
