### ISSUE TITLE
Adding ARM support to flatpak

### ISSUE THREAD

**Issue by the-cave-dweller** [Stremio/stremio-features#293]
Stremio works great on this architecture, Im currently using it on aarch64, but currently its only possible to build it easily inside Archlinux, I was wondering if it would be possible for you to support this architecture in your Flatpak builds, as the program works correctly on it and it would be easily accessible to any linux running small computer or mobile platform

**Comment by TRtomasz** [comment]
99% sure it is not possible for the same reason there is no native build for Mac ARM processors. QT version we use does not support ARM builds

**Comment by the-cave-dweller** [comment]
I use it on my aarch64 pinephone. I can submit a screenshot later if it helps, even a package or something.

**Comment by the-cave-dweller** [comment]
[Uploading stremio-4.4.142-2-aarch64.pkg.tar.xz…]()

> 99% sure it is not possible for the same reason there is no native build for Mac ARM processors. QT version we use does not support ARM builds.

**Comment by the-cave-dweller** [comment]
[Stremio Arch binary](https://cloud.operationtulip.com/s/amiDc5Saw8Zy7sF) 

> 99% sure it is not possible for the same reason there is no native build for Mac ARM processors. QT version we use does not support ARM builds

**Comment by VictorVow** [comment]
Current Qt supports ARM.

**Comment by antrmn** [comment]
Any hope for this?
