### ISSUE TITLE
For Android TV (V1.5.3 ARM APK) Trakt not scrobbling

### ISSUE THREAD

**Issue by starman2908** [Stremio/stremio-features#294]
**Describe the bug**
The Android TV App doesn't appear to be scrobbling items being watched and do not show in trakt history after watching

**Expected behavior**
Watched items appear in watched history, and appear on trakt as watched.
.

**Comment by jaruba** [comment]
moved to `stremio-features`, as the Android TV app is a new app, it is not the evolved version of the Mobile app, so this feature is in the works and not implemented yet.

**Comment by TRtomasz** [comment]
Trakt scrobbling has been added in the latest android tv app version.
