### ISSUE TITLE
Casting improvements

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-features#3]
Opening this issue since this is the next thing on our roadmap.

Can someone suggest an open-source module I can contribute to and use for stremio?

I'm thinking about nodecast https://github.com/gyzerok/nodecast-js

**Comment by jaruba** [comment]
![post-36434-tyrion-lannister-cheers-gif-dr-ik5y](https://cloud.githubusercontent.com/assets/1777923/11440129/b3080902-9508-11e5-9e6a-c014e42ffbbc.gif)

**Comment by Ivshti** [comment]
@jaruba I was just about to post to the casting threads that we can learn a hell of a lot from http://connectsdk.com/

**Comment by jaruba** [comment]
someone posted that thing on powder's issues, i looked at it, from what i understand the only way we can use that is by casting a page and the tv remote won't work with it. :/

**Comment by Ivshti** [comment]
@jaruba nothing of the sorts. It casts a video/picture/youtube to any tv/chromecast/airplay. It's basically the exact thing we need. As I said, it's only for iOS and Android - and uses their respective libraries heavily, so it won't be easy to port without introducing bugs. However, it has plenty of DLNA/DIAL/Castv2/Airplay implementation inside that we can look at.

**Comment by jaruba** [comment]
http://connectsdk.com/docs/1-6-0/tv-web-app/

^ a page (of sorts)

**Comment by Ivshti** [comment]
Apparently it supports that TOO. But the core functionality we need is there. Great resource & starting point, and along with all the inconsistent and chaotic node.js modules we have, we might be on to something :boar:

**Comment by jaruba** [comment]
i'm not that sure what we could learn though, we could wireshark it to understand what it does better, but without having all the casting scenarios at our disposal we won't ever be able to fully grasp how it does everything. :walking:

**Comment by Ivshti** [comment]
Why wireshark? It's open source and it's got all the protocol implementations in plain sight.

**Comment by jaruba** [comment]
do they? i got lost in their 30 repos, didn't seem like it was in _plain sight_ when researching it :))

**Comment by Ivshti** [comment]
https://github.com/ConnectSDK/Connect-SDK-iOS-Core
https://github.com/ConnectSDK/Connect-SDK-Android-Core
