### ISSUE TITLE
request 

### ISSUE THREAD

**Issue by kxe5** [Stremio/stremio-features#301]
okay so i love the new ui but i guess there's something missing in the last update i can go to the actors and the crew the dictator etc.. so in the new ui i miss this thing maybe you can add it in a new ui too so it gets the pictures and the name in a circle i don't know just an request thx for your work I appreciate I love you Stremio Crew

**Comment by TRtomasz** [comment]
Closing it as, it didnt use the template. Also perhaps it is duplicate
