### ISSUE TITLE
Embedded subtitles for Chromecast!

### ISSUE THREAD

**Issue by djgenesis** [Stremio/stremio-features#303]
When streaming a movie/series, many of the options presented to use have embedded subtitles and Stremio uses them by default which is awesome! When casting a movie from my (android) phone to Chromecast, the embedded subtitles are not an option so I am left with the opensubtitles options which (as you might already know) are almost never the right ones for the option I am currently playing (out of sync) and people can't be bothered to sync the manually.

Solution:
When casting a movie from my (android) phone to Chromecast, Stremio should make use of the embedded subtitles the same way it does when streaming a movie/series to a phone or pc.

Alternative:
A bit more complex but...here we go... Choose an opensubtitles option by matching the movie/series file name with the opensubtitles filename

**Comment by hectorgm** [comment]
I'd love to see this implemented!

**Comment by Tzvika-m** [comment]
That would be super helpful

**Comment by TRtomasz** [comment]
this is not possible due to chomecast simply not supporting emdedded subtitles.
