### ISSUE TITLE
Android TV : Auto frame rate matching

### ISSUE THREAD

**Issue by farhanito** [Stremio/stremio-features#304]
Currently, i have to use external player ([Just Player](https://github.com/moneytoo/Player) ) that has auto frame rate matching feature. I'd love to have this feature implemented in the internal player so i don't have to use external player. It already has audio passthrough, whis is great. Auto frame rate matching will make it perfect.

Thank you

**Comment by eSkRo32** [comment]
Yes I agree, very important!

**Comment by Sparh4wk** [comment]
+1

**Comment by base08** [comment]
ExoPlayer should support this when android 12 is more common...

**Comment by farhanito** [comment]
> ExoPlayer should support this when android 12 is more common...

My CCwGTV is on android 12, and it's not. 
**Just (video) Player**, also based on exoplayer, does match framerate. I guess the app need to add support as well.

**Comment by speiiky** [comment]
I really wonder why a Media-App like Stremio hasnt that auto frame rate matching enabled by default. Do only people who dont see the difference use the app? That micro stutter is bad, and manually changing refresh rate in Android settings is bad. I really hope that feature is introduced soon. Any update yet?
