### ISSUE TITLE
Learning languages with movies.

### ISSUE THREAD

**Issue by nathanredblur** [Stremio/stremio-features#31]
The Idea is simple and powerful. 
and come in different flavors. 
1. load two different subtitles on watch your movies.
   op1: only show one but on stop or mouse over then show the second one. 
   op2: show both at the same time.
2. you can click the word and check the dictionary definition or translation
3. you can jump between dialogs. (like forward or backward to the next or previous actor line)
4. you can save words or lines to review later or share in social media.

Cool right?

I can help with this. I really really want this. 

Greate app, see you soon.

**Comment by Ivshti** [comment]
Already looked at your ideas in poly-player :) 

The problems with this in stremio are:

1. add-ons do not allow any other functionality than providing content
2. this is a powerful idea that should be marketed on it's own, and won't shine as a function to stremio
3. plus, we have too many side-functionalities and things to market ourselves already

So my proposal is:
We can expose some kind of a Stremio REST API that would allow

* To get a list of available streams 
* To activate content add-ons 
* to get a Bittorrent/IPFS gateway for playing bittorrent/ipfs streams
* to transcode any non-mp4 streams into HLS for playing in the browser

This would allow you to extend your application on top of Stremio, and we can figure out some kind of cross-promotion scheme.

What do you think?

**Comment by nathanredblur** [comment]
Sounds good :) how we start it?

**Comment by Ivshti** [comment]
can you ping me at ivo@strem.io with more details about your project, how do you see it and etc.

I'll start working on the REST API

**Comment by Ivshti** [comment]
@nathanredblur

**Comment by adrifernandev** [comment]
Hello, is this completed? Any way to use it? Thanks!

**Comment by Eva02Daruma** [comment]
i have the same question!  , i really want to use it to improve my Japanese.
