### ISSUE TITLE
[Video player] Allow processing of a stream before displaying

### ISSUE THREAD

**Issue by GreenMan36** [Stremio/stremio-features#311]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I watch a video that's of decent quality but its poorly upscaled to my monitor's resolution or a show is recorded in a lower framerate.

**Describe the solution you'd like**
I'd like a way to hook into between video streams and the video player, allowing you to post-process the image.
This enables things like frame interpolation, non AI based algorithmic upscaling, AI upscaling and more enhancements like audio or image outpainting (for example having an AI fill in the black bars around movies with what _could_ be there) or giving black and white movies color again.
There are quite a lot of open-source methods that can achieve some of these features and since the field is rapidly evolving I expect more and more ways an end user can enhance old content.
I do not expect implementation of any of these algorithms however I would like to see the application allow addons that can step in-between getting the stream and displaying of the stream.

**Describe alternatives you've considered**
I have been using a third party program to upscale the whole app during video playback however I need to size the window to be exactly 16:9 pixel-perfectly with the video's input resolution and it will also upscale the application UI which is not ideal. I mainly use FSR 1.0 for this, and I've also manually had to download shows to interpolate the frames with a third party program.
There is currently no way (that I know) of changing the video before its displayed, not via addons or within the application.

**Additional context**
In the following example I'm upscaling big buck bunny from 720p (1280 × 720) to the (uncommon in video content) 1440p (2560 × 1440) which contains 4 times the pixels as the original. Although the algorithm doesn't generate new details, it does a great job of reducing the blur caused by regular upscaling
Original 
![image](https://user-images.githubusercontent.com/5887406/189525120-ed2a9e92-6d95-4908-92f1-851ce261ae75.png)
FSR 1.0 ![FSR 1.0 example](https://user-images.githubusercontent.com/5887406/189524787-2489c31e-e167-4fa4-a03e-aef13f625242.png)
Default desktop upscaling filter ![Default desktop upscaling Example](https://user-images.githubusercontent.com/5887406/189524792-fce9382d-6cd5-4dc4-ad03-212d70f079d6.png)

You see some big differences in the leaves in the background, sharpness of the eyes and the fur.
![image](https://user-images.githubusercontent.com/5887406/189525502-6abdf9de-42fd-46b5-83d9-2bff5ddb5af6.png)

To some these may look like minor improvements to some however a this would allow a lot more features and algorithms to be implemented as mentioned before. This is just scratching the surface, the field is rapidly improving so it would be great to have a strong foundation now rather than having to do it later.

**Comment by TRtomasz** [comment]
@GreenMan36 i'm looking at them and all i can think is 
![FKe9fK5WQAk3JOs](https://user-images.githubusercontent.com/40594253/189609716-28904839-f8f2-44db-82c5-3f5d58977ea7.png)

**Comment by GreenMan36** [comment]
I would like to point you at my final message, and add that FSR 1.0 was used just because it was the only tool I had available to show some potential, if you'd like more details you can look at [ESPCN](https://github.com/leftthomas/ESPCN), [ECCV2022-RIFE](https://github.com/megvii-research/ECCV2022-RIFE), [interactive-deep-colorization](https://github.com/junyanz/interactive-deep-colorization) (old research focussed on images), [Deep-Exemplar-based-Video-Colorization](https://github.com/zhangmozhe/Deep-Exemplar-based-Video-Colorization) (more up-to-date for video), [NVIDIA DEV BLOG](https://developer.nvidia.com/blog/transforming-noisy-low-resolution-into-high-quality-videos-for-captivating-end-user-experiences/)

I haven't found many devices that do use AI or post processing in their pipeline to enhance the displayed output but the Nvidia Shield is a great example, it can upscale 480p content to 4k in real time. And this is using an older model. In the coming years we'll be seeing better and better systems for sure.

These are all just examples of the potential that could be unlocked. It would make Stremio not only the best media center but also the best media player as it would allow for real time enhancements to existing content.

Again I am not asking for these to be implemented, I'm asking for a system that allows addons to process the video before it is displayed.
This would probably fit best as a settings button within the player where you have a sub menu for each of the addons.

**Comment by TRtomasz** [comment]
Although idea sounds interesting. Something like this will not be added to the addons system, too much effort for such enhancenebt

**Comment by GreenMan36** [comment]
I understand, just adding some possibly relavant info.
[VLC currently has a test version](https://download.videolan.org/testing/vlc-rtx-upscaler/) that includes RTX VSR.

I feel like AI features and algorithms for upscaling, frame generation and possibly even auto translation of on-screen text will get more prevalent in the coming years. No guess on the timeframe and hardware availability (low power devices for example) though.

**Comment by GreenMan36** [comment]
I may be stupid for not knowing about this but; SVP/ SmoothVideo Project
iOS & Android, NVIDIA support, 4k & HDR, RIFE interpelation, DLSS3 and I've been shown that FSR works on the MPV media player.

I would really like to have these features at least be possible in Stremio. Instead of not having any support for it at all.

@TRtomasz  At the bare minimum I would at least like to keep this issue open, tagged as an "enhancement" in case anyone else is willing to make these enhancements possible.

**Comment by TRtomasz** [comment]
This will not be implemented on Stremio level. Sorry i do not understand what you mean in this sentence.
``` but; SVP/ SmoothVideo Project
iOS & Android, NVIDIA support, 4k & HDR, RIFE interpelation, DLSS3 and I've been shown that FSR works on the MPV media player.```
If MPV decides to implement this, it will be working in Stremio once we update it. For example Nvidia Shield Pro device offers AI upscaling and if you use stremio on Nvidia Shield Pro it will upscale video when possible.
