### ISSUE TITLE
Playback Speed Buuton Stremio Android TV

### ISSUE THREAD

**Issue by jagnve** [Stremio/stremio-features#318]
Stremio on my Google Chromecast  Android TV is working perfectly. Absolutely no problems.

The Playback Speed button on the main screen, like the Subtitle button or as it is on the PC and Android versions, would be more useful as I think most people use it more often than the other options under Configuration.
It is really the only thing that lets you get through the slow boring parts of some films and episodes.
As I am on this topic, would it be possible to make the Configuration menu box maybe semi transparent as it would really help when trying to synchronize subtitles?

Thanks for considering it.

**Comment by TRtomasz** [comment]
Playback speed option is available from player settings now.
