### ISSUE TITLE
Option to hide episode Images

### ISSUE THREAD

**Issue by Ablado19** [Stremio/stremio-features#319]
While it looks great, the images of individual episodes of TV shows can occasionally contain spoilers in the Android TV app.

You can see several episodes ahead (including into the next season) which can ruin some storylines. 
For example, you're wanting to watch the last episode of a season so you go into the episode selection menu. You can see a main character in the image for first episode of the next season directly to the right of the episode you're going to watch. In the last episode of the season that main character gets shot and has to get surgery but you already know they're not going to die as you've seen the image/s from the start of the next season.

An option to hide all episode images in settings or in individual TV shows would be great (perhaps next to "remove from library/mark as watched").

I know you can use autoplay to sort of get around this but I still end up in the episode selection menu at times and see some spoilers

Thanks.

**Comment by TRtomasz** [comment]
Closing as this wont be implemented
