### ISSUE TITLE
Import shows to library from pogdesign.co.uk/cat/ .iCal

### ISSUE THREAD

**Issue by Turante** [Stremio/stremio-features#32]
http://www.pogdesign.co.uk/cat/ has a great show calendar with .iCal feed for users. I currently use it with Google Calendar, but moving that data to Stremio would be ideal. Is this technically feasible?

**Comment by Ivshti** [comment]
I can't understand how to use this and what's exactly the info that has to be moved. :)

are you asking about the release dates themselves, because we're working with a partner at the moment to improve episode airdate information

Or are you asking about some sort of watchlist/library that you have at this service that you want to move to Stremio?

**Comment by Turante** [comment]
It's a bit of both - a watchlist that keeps track of what you've watched
and want to watch, and an episode guide and TV schedule. When you sign up,
you pick all the TV shows you like and the service keeps track of it all
and creates an .iCal for upcoming episodes. I'm mostly wondering if the
.iCal can be imported in some way. I mean, the other data would be nice
too, but since there's no API that I know of that's seems like a bit much
to ask.

**Comment by Ivshti** [comment]
iCal imports are generally a good idea so I'm thinking about it.

Personally I'd like to see iCals for sports to notify me in the Board..but that's a bit of a different thing I guess

I'll put it on our agenda, but you should also know that we're working with a new provider for TV schedules data, so we'll have even more than before. And Calendar does the same for you providing you have the shows in your lib

**Comment by Milamber79** [comment]
When adding pogdesigns ical to my google calendar it merges with my personal calendar and doesn't show up as a separate calendar.

If I want ro remove pogdesigns ical, how is that possible?
