### ISSUE TITLE
(Android TV) Cache to external Memory

### ISSUE THREAD

**Issue by lanzapidras** [Stremio/stremio-features#321]
**Cache settings**
As al ot SmartTVs memory space it is not so big, when enablig cache to 2Gb it almost fill the memory causing crash of the reproduciton.
**Option to move cache or app to external storage**

**More options of cache setting**
Ma be 1Gb of cache option could make the difference

**Comment by joaofcribeiro** [comment]
I would love this feature too as it would allow to watch 4k movies with little caching time.

**Comment by Dogindeluszion** [comment]
This would be a great feature, and very useful.

I would even be happy to just have regular caching return to the Android TV app version.
