### ISSUE TITLE
"Up Next to Watch" integration - Trakt

### ISSUE THREAD

**Issue by Jesuninfinity** [Stremio/stremio-features#322]
The "New For you" list doesn't work on the android TV version of Stremio and the feature could be better with it being interested with the Trakt "Next up to watch" List.

I know the Android TV version is in it's early stage but I see this version of the app becoming one of the most popular. This feature will make it easy for users to find their beloved content quickly. Stremio already has Trakt Integration so would be nice to have that feature Integrated. 

 As an alternative it would be nice if the "Continue Watching" and  "New for you" feature be combined to function similar to how the Trakt "Next-up to watch" list works.

**Comment by TRtomasz** [comment]
Please use template when creating an issue.

**Comment by Jesuninfinity** [comment]
> 

Template? Kindly explain or provide an example.

**Comment by Jesuninfinity** [comment]
Issue revised and reposted as Issue 324

https://github.com/Stremio/stremio-features/issues/324
