### ISSUE TITLE
Next episode pop up on Android TV

### ISSUE THREAD

**Issue by RichyRicho** [Stremio/stremio-features#327]
Problem: On Android TV version there is no next episode pop up notification with a customisable timer to be able to skip the credits of a show and start the next episode.

Solution: Add an option to the setting to enable a pop up with customisable time.

Alternative or additional feature: None

Additional context: please see the next comment

**Comment by RichyRicho** [comment]
![kodi-nextup-featured](https://user-images.githubusercontent.com/3308677/197332212-c5b10578-bd0d-46b9-b46a-d58f99c34613.png)

**Comment by TRtomasz** [comment]
it has been aded now in latest update
