### ISSUE TITLE
(Android) Add SeriesGuide extension for direct Stremio access

### ISSUE THREAD

**Issue by linguax-gc** [Stremio/stremio-features#333]
**Is your feature request related to a problem? Please describe.**
There's is no easy way of going from SeriesGuide (which is a very popular content tracking app that I use to keep a record of what I've watched and want to watch, and where I get announcements of new episodes, etc.) directly into the Stremio corresponding movie/episode.

**Describe the solution you'd like**
This could be easily fixed by adding an extension to the Stremio Android app, which would add a link inside SeriesGuide that would automatically open Stremio to that specific movie/episode.
The instructions to adding the extension using the [SeriesGuide API](https://seriesgui.de/api/) can be found [here](https://github.com/UweTrottmann/SeriesGuide-Extension-Example#how-to-build-an-extension-for-seriesguide).

**Describe alternatives you've considered**
If there is this kind of feature already available on some other tracking app I would consider changing tracking apps.

**Additional context**
Examples of the "Web search" and "YouTube search" extensions on an episode of a TV show. Adding Stremio would add a "Stremio search" button here that would give super easy access to the content you're looking for.
![Screenshot_20221119-150616_SeriesGuide](https://user-images.githubusercontent.com/25809253/202854717-cdd28258-b14c-40b1-b54f-edd1bdff5983.png)
![Screenshot_20221119-150633_SeriesGuide~2](https://user-images.githubusercontent.com/25809253/202854718-4279e8ed-9f8d-48eb-a8b5-556f6df85600.png)

**Comment by TRtomasz** [comment]
If you have an addon request you should ask this on addons forum https://www.reddit.com/r/StremioAddons/

**Comment by linguax-gc** [comment]
@TRtomasz hey, I don't think this would work as an addon, I think it is a feature that you get adding some code to the main app (or as an additional app, I guess). I would do it myself and add a pull request but I don't really know much about coding and I can't understand how to make the example extension work with Stremio. Are you sure this doesn't belong here? Thanks!
