### ISSUE TITLE
No autoplay for already watched series on Android TV 

### ISSUE THREAD

**Issue by Cmc303** [Stremio/stremio-features#335]
The ability to unmark episodes as watched on Android TV should be added, it will not autoplay next episode on a series unless the episodes are unwatched.

**Comment by TRtomasz** [comment]
@TheBeastLT  is this possible?

**Comment by TheBeastLT** [comment]
@TRtomasz no, not possible. Autoplay does not depend on the watched status in any way. It only depends on the binge settings and whether there's a next episode.

**Comment by TRtomasz** [comment]
ok closing this for now as there are not enough details to reproduce.
