### ISSUE TITLE
Anime category on the library for less clutter or a filter search.

### ISSUE THREAD

**Issue by john-ssh** [Stremio/stremio-features#336]
This tab is too cluttered with series and anime, for so many anime can be watched on Stremio but the more I personally add to the list the more big the series tab becomes too long.

![image](https://user-images.githubusercontent.com/38481142/205430780-42b6a99f-5e53-421b-9c07-be4a4a613e53.png)

**Comment by TRtomasz** [comment]
This depend on the addon, kitsu addon will provide Anime under separate Anime catalog so if you add elements from kitsu addon it will be in the library under 'Anime'
