### ISSUE TITLE
Strem.io Browser edition 

### ISSUE THREAD

**Issue by YUSDOTCOM** [Stremio/stremio-features#34]
i would prefer to open up strem.io on my browser and stream movies so i don't have to download apps or download updates so i can just open my browser and stream.

**Comment by pateldhruv1993** [comment]
I'm assuming hosting is such a big issue without being able to make money off of it (atleast for now). Not to mention you'll need to download and update some sort of plugin to stream the torrents anyways.

**Comment by Ivshti** [comment]
@YUSDOTCOM @pateldhruv1993 

1. hosting is not really an issue, as we don't host any video content and serving html is pretty cheap 
2. technically, we are working in that direction - de-coupling stremio from it's node.js parts to put it in the browser
3. yes, BitTorrent streaming won't be supported in the browser, which breaks many use cases
4. we still believe that we should make a browser version, supporting all the non-BitTorrent add-ons, such as YouTube based and HLS based (TVs)
5. for BitTorrent, support can be added, with a browser plug-in that does it (Chrome extension) or with an integration with a re-streamer service like put.io/seedr (which also protects your privacy, so it's a win-win)

Hope that gives you enough info about where we're headed :)

**Comment by YUSDOTCOM** [comment]
Well if you do make a browser version how would it look and would i need to install plugins or just use a online video player like youtube and how much does it cost for hosting.

**Comment by YUSDOTCOM** [comment]
i have a question are you going to make a browser edition of strem.io and if you do when will it be available to the community just wondering :)

**Comment by Ivshti** [comment]
@YUSDOTCOM yes, there's going to be a browser version of Stremio

You won't need to install any browser plugins / software to use the official stremio sources.

To use un-official torrent-based sources, you'd have to install a browser plugin, or use a stremio add-on to a service like put.io

**Comment by TRtomasz** [comment]
You can try web version here http://app.strem.io/shell-v4.4/#/
