### ISSUE TITLE
Using data from trakt tv and or stremio server add an option to hide previously watched movies and shows

### ISSUE THREAD

**Issue by mo-5** [Stremio/stremio-features#342]
**Is your feature request related to a problem? Please describe.**
Everytime you go through a catalog you have to keep going through movies and shows you have already watched to find something to watch. 

**Describe the solution you'd like**
Add an interceptor to catalog with the option to toggle it on or off the settings to filter out movies and shows already watched based on trakt.tv 

**Describe alternatives you've considered**
This can be implemented into addons but it would be easier to have a "master" filter based on IMDb Id that can triggered on and off from within the app while you are already authenticed to trakt. 

**Additional context**

**Comment by TRtomasz** [comment]
Due to current stremio architecture, it is not possible to hide movies from UI manually or using data from trakt. 
Perhaps best way would be an addon that would filter these data before serving it to the Stremio app.
