### ISSUE TITLE
Integrate stremio watchlist library with trakt watchlist as well as watch history (2 way integration)

### ISSUE THREAD

**Issue by mo-5** [Stremio/stremio-features#344]
**Is your feature request related to a problem? Please describe.**

Currently stremio library is only stored on stremio servers it would nice to integrate it with trakt that way there is a 2 way sync anything that's on a watchlist on stremio is saved to trakt and vica versa. 

**Describe the solution you'd like**
When a movie or a show is added to stremio library send a request to trakt to save it on watchlist as well. 

**Describe alternatives you've considered**

**Additional context**

**Comment by kwest12** [comment]
Seconded.  If Stremio would integrate fully, I'd switch to it from other competing apps.  Without two way Trakt sync, I can't justify switching.

**Comment by Beno951** [comment]
Yes please!!! I'd love to have Stremio library synced with trakt watchlist. Or just having any way to add titles to trakt watchlist using Stremio.

**Comment by jhedfors** [comment]
I want Stremio Library - Trakt sync as well, but it should be Trakt Collection instead.

Trakt Watchlist items are removed once watched - I am sure that is not what is desired here. I would suggest updating the title and description.

**Comment by Vigmos** [comment]
> I want Stremio Library - Trakt sync as well, but wouldn't Trakt Collection be more appropriate than Trakt Watchlist?

Not really, collection is simply a static list which is not used for tracking anything, you could even make a custom list and name it collection and that would essentially be the same thing and you can already add trakt lists to stremio. Watchlist is dynamic, and once you start watching content in your watchlist it is automatically removed and then moved to watching (up next).

**Comment by candroid-man** [comment]
I actually got a Trakt account hoping this is how it worked, unfortunately I was wrong. Hoping this gets added in soon! Could be a big deal to a lot of people myself included.

**Comment by TRtomasz** [comment]
this has been added and can be triggered from user panel on stremio.com

**Comment by Gaspartame** [comment]
Is there a plan to make the integration 2 way ? Or maybe it is already the case and it doesn't work as it should for me ?
