### ISSUE TITLE
Android TV: Move OSD to the top so it doesn't block subtitles when paused

### ISSUE THREAD

**Issue by LITUATUI** [Stremio/stremio-features#347]
In Kodi when paused, the OSD goes to the top so we can see the subtitles. 

Hopefully, Stremio for Android TV will evolve to do the same. The temporary solution is to open the video with VLC, which hides OSD when paused, instead of blocking it like Stremio for Android TV does.

Example of subtitles in Kodi when paused:

![Kodi-OSD](https://user-images.githubusercontent.com/49299328/209319775-07ede6f8-bc02-4741-a79d-fe2559b0e4e4.jpg)

**Comment by TRtomasz** [comment]
That would be  too big change for a very small benefit, you can pause video, press back button tom make osd disappear and then read subtitles.

**Comment by LITUATUI** [comment]
Thanks for the suggestion. 

The problem with having to use the back button to hide the OSD is because sometimes the device might not respond promptly and you press the button again and end up closing the player.

This is not much a problem for me, but it's for my parents that have to constantly stop to read the subtitles.

The alternative is to use VLC as a player, but then we no longer have the auto-download subs featured of the internal player.

Anyway, this is just a first world problem. Kodi also had this problem before they introduced a new skin to solve it.
