### ISSUE TITLE
Configurable cache directory

### ISSUE THREAD

**Issue by npit** [Stremio/stremio-features#350]
**Is your feature request related to a problem? Please describe.**
No way to utilize free space on external / additional disks, or prevent the application from taking up space on the main system disk.

**Describe the solution you'd like**
Ability to configure the cache path from the settings.

**Comment by TRtomasz** [comment]
Please use the template. When reporting an issue or feature request. Otherwise it is not possible to tell about to what platfor it applies to.

**Comment by npit** [comment]
I used the template bullets that I deemed relevant and omitted the rest. If that's unhelpful, I edited the OP accordingly.
