### ISSUE TITLE
Developer Documentation

### ISSUE THREAD

**Issue by nunojsa** [Stremio/stremio-features#362]
**Is your feature request related to a problem? Please describe.**
I'm a very newcomer to stremio but from what I could dig in, it's very hard understand the "full picture" of the APP and how everything glues together. To me, this is a clear barrier for potentially new contributors for the project. There's also a big question mark on the Android APP as stremio is supposed to be open source but I cannot find a way to check the Android (and and Android TV) source code...

**Describe the solution you'd like**
Better Documentation describing APIs and how the different pieces glue together.

**Comment by nunojsa** [comment]
> Android app is not opensourced, in this case code is the documentation 

Well, if it's not open sourced, not even code can server as doc :smile:

**Comment by TRtomasz** [comment]
That apply to everything else that is opensourced.
