### ISSUE TITLE
Disable tray icon

### ISSUE THREAD

**Issue by rebelcode-xr** [Stremio/stremio-features#363]
Hi, I would like to disable the tray icon on Stremio Mac because I don't need it and it takes space.

![image](https://user-images.githubusercontent.com/63522951/217520178-006612b9-a100-426d-93ff-0d254896eaff.png)

I expected to be able to do it with CMD and drag'n'drop the Stremio icon out of the menu bar but it doesn't work.
I also looked inside Stremio settings, where normally is this kind of option, but I realised that there's no way to do it.

Hope you can add this feature! 🙏

**Comment by TRtomasz** [comment]
Sorry, such thing will not be added as this simply does not go along with our vision of making app not complicated

**Comment by cisc0disco** [comment]
Atleast give us option in config file or something, it's annoying and making my tray feel cluttered

**Comment by rebelcode-xr** [comment]
yeah, honestly the tray icon (on Mac OS) makes the app more complex than it should be...probably it makes sense for Windows or Linux users, but not on Mac.

**Comment by fxzzi** [comment]
yeah, i personally think having no tray icon makes it less complicated

**Comment by adam-tj** [comment]
Having a tray icon is more complex. I expect the software to close when I press the close button and not to hide in the system tray.

**Comment by dusrdev** [comment]
It is clear that users want this icon gone, why is the issue closed? re-open it please.

Closing this issue doesn't make any sense, in fact, having the icon doesn't make sense in the first place, as it doesn't add any options - there is only "Show window, Always on top, and quit", Out of those, "Show window" and "quit" can be done even more easily without the tray icon, and "Always on top" which I am sure is barely used anyway, can be moved into the settings within the app.
