### ISSUE TITLE
I am unable to watch stremio on my NanoCell TV 43NANO73SQA, Is there a stremio app in development for LG WebOS?

### ISSUE THREAD

**Issue by Utkarsh005** [Stremio/stremio-features#364]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RahulMalhotra5** [comment]
Can we have a Web Os based app LG Tv's

**Comment by jaruba** [comment]
Stremio is now available on 2020+ LG TVs: https://blog.stremio.com/stremio-is-now-available-on-lg-tvs-for-models-2020/
