### ISSUE TITLE
Add speech recognition button to search bar

### ISSUE THREAD

**Issue by cauebs** [Stremio/stremio-features#365]
In some setups a keyboard isn't available, so a voice typing feature would make the browsing experience much more convenient. I believe the only places where you type in the app are search fields, so a little mic button in each would probably suffice.

Taking into account potential privacy concerns, this feature could be disabled by default, with a warning in the settings toggle that explains it makes use of third-party services.

**Comment by TRtomasz** [comment]
Please use the template to create features requests otherwise we are not able decide on the requests if it is valid.

**Comment by TRtomasz** [comment]
This is something provided by keyboards.  We do not plan to implement speach recognition in app it is too much effort for something that is provided by 3rd party software that everyon has (keyboard) also for some android boxes it is implemented as part of device with a button on a remote.
