### ISSUE TITLE
Please add "SEE ALL" to the Android phone/tablet version app main screen

### ISSUE THREAD

**Issue by hsp1020** [Stremio/stremio-features#370]
![Screenshot_20230411-203848](https://user-images.githubusercontent.com/125277818/231152482-f61ec9fc-bdf1-40d9-b142-14f6f39cd4e0.png)
In the Web, PC version, there is "SEE ALL" by catalog on the main screen, so it is easy to check all the items in the catalog.

![Screenshot_20230411-204145](https://user-images.githubusercontent.com/125277818/231152525-0a846b39-92ec-4913-9e24-77e0e7e87861.png)
However, in the Android mobile version, there is no "SEE ALL" by catalog on the main screen, so it is very difficult to check all the items in the catalog.

**Comment by the-badmannn** [comment]
Agreed, that would be very useful also to be able to see every catalog expanded with rows and columns even on Android tv

**Comment by nathsl** [comment]
Yes please

**Comment by TRtomasz** [comment]
This will not be added to the existing Android app, closing this issue for now.
