### ISSUE TITLE
Multiple languages support for subtitles

### ISSUE THREAD

**Issue by boriseto** [Stremio/stremio-features#372]
Coming from an area in which we understand multiple languages, can it be made that we can add custom number of languages in case the priority one doesnt exist?
Right now on the tv app we have primary and secondary subtitle. If possible to be made so we can add custom number of subtitle languages and order them by priority?

**Comment by TRtomasz** [comment]
It possible to add such thing but i don't think it will happen anytime soon, sorry

**Comment by jihadismail8** [comment]
why it can not happen at any time soon ? here is an open source package that can help with the requested feature , https://github.com/wistful/srtmerge ,   you can easily add a button that would merge two or more srt files (or links) and use it in the vedio .

**Comment by boriseto** [comment]
The idea is not to have multiple subtitles shown at once, it's having a bigger list of languages to show the first available.
Right now it's set to two. I think it would be easy to set it to unlimited amount so it would check by priority again. The use case is that it would be a one time setup so my family that isn't tech savvy wouldn't have to change anything.

For showing multiple subtitles at once, if there isn't an issue, you should create a different one.

**Comment by jihadismail8** [comment]
well i understood "multi subtitles" as  multisubtitles at once

**Comment by TRtomasz** [comment]
Closing as this feature is not aligned with stremio purpose
