### ISSUE TITLE
A button to switch accounts

### ISSUE THREAD

**Issue by SSwaggerSoulss** [Stremio/stremio-features#373]
Since the implementation of profiles is hard. 

How about adding a button next to the delete account to switch account and be able to choose from a list of saved accounts?

Basically this way we can use different accounts as profiles.

Is this in any way easier to do or same amount of difficulty?

![IMG_20230429_160513](https://user-images.githubusercontent.com/117945147/235318278-20d5750d-a167-434d-83b2-1936e8531a42.jpg)

**Comment by TRtomasz** [comment]
Sorry currently this is not possible and not planned.
