### ISSUE TITLE
Suggestion: put seasonXepisode first

### ISSUE THREAD

**Issue by lucasew** [Stremio/stremio-features#376]
**Describe the bug**
Phones have narrower screens compared to PCs, laptops and tablets so I have to put It in horizontal mode to be able to see which season and episode I am in the episode screen.

**To Reproduce**
1. Open any tv show that doesn't have a small name such as Rick and Morty or Breaking Bad
2. Open any episode of this series
3. Realise that the season and episode number is hidden because it overflows the width and cuts into  ...

**Expected behavior**
I being able to see that the episode is season X episode Y

A format like `($num_seasonX$num_episode) $series - $episode`

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TRtomasz** [comment]
Looks like you are trying to use web app on your phone, web app is not mentioned for standalone use, and most sure was not designed for mobile devices as we have dedicated apps for Android and Android Tvs systems.

**Comment by lucasew** [comment]
> Looks like you are trying to use web app on your phone, web app is not mentioned for standalone use, and most sure was not designed for mobile devices as we have dedicated apps for Android and Android Tvs systems.

Not really. BTW didn't know about the webapp.

![image](https://user-images.githubusercontent.com/15693688/236681748-f9bd18e2-f7df-4263-a569-6f593550173f.png)

**Comment by TRtomasz** [comment]
In order to get to this screen you first have select season and episode, so you already have the knowledge `which season and episode I am in the episode screen.`
