### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by Roedosla** [Stremio/stremio-features#378]
Hello. Do you think it's possible to add a function that allows to view offline the content? Specially in smartphone version. In this way, you could download the content with a WiFi network and then watch it when the network connection is unstable, even in airplane mode, for example when traveling on a bus or train or airplane. This function would be great.

**Comment by TRtomasz** [comment]
Please do not clear the form whem creating an issue.
Closing as duplicate of https://github.com/Stremio/stremio-features/issues/281
