### ISSUE TITLE
Smart Vertical Stretch 16:9 ?

### ISSUE THREAD

**Issue by Nazim1981** [Stremio/stremio-features#379]
Some time When I Screen Resize in Stremio TV app , it doesn't smart stretch  16;9 vertically but rather Zoom it 1x or 2x , Kindly resolve this issue on next update and also can we add manual smart stretch screen like reducing PIXEL RATIO First and then increase Zoom to reach video full screen without cutting edges just like  Kodi which has this option ? with this option every movie can be seen in full screen which will boost the viewing experience . someone like it or not that varies but option should be there at least .

**Comment by TRtomasz** [comment]
Please reopen feature request using the form instead just removing it, also do not forget to provide details about hot to reproduce the issue you have mentioned.
