### ISSUE TITLE
Hide watched content

### ISSUE THREAD

**Issue by fcampo** [Stremio/stremio-features#38]
As a user, I want to be able to hide from my library the content that I already watched, either films or series (specially if finished or discontinued).
Ideally a checkbox that's easy to toggle on/off, or just a new category aside from 'Recent' / 'A-Z' / 'Watched'

**Comment by Harith163** [comment]
I agree!

**Comment by serradino** [comment]
Yes, please !! :D

**Comment by TRtomasz** [comment]
To keep repository clean, we will move discussion to issue #96

**Comment by Hawkling** [comment]
10 years later, please add this!

**Comment by DronovasP** [comment]
Upvoting this, as previous duplicate discussion was closed with no action. An ability to filter out already watched both movies and series will make it a hundred times easier to find new content to watch, and given we already reflect what is watched with a check mark in the corner, I don't see how we cannot filter user side already watched items. A user might have a setting in his client to enable/disable this option.
