### ISSUE TITLE
Android - Copy title to clipboard

### ISSUE THREAD

**Issue by YourHeroAngel** [Stremio/stremio-features#381]
**Is your feature request related to a problem? Please describe.**
Sometimes I search online the name of a show I am watching, but I get annoyed typing out the title of the show (especially when it's another language).

**Describe the solution you'd like**
When on the page of a show, holding the title for a second should copy the title of the show directly to clipboard.

**Describe alternatives you've considered**
When on the page of a show, holding the title for a second should let you highlight the title's text which the user can then manually copy the text to clipboard.

**Additional context**
Holding "Breaking Bad" at the top should copy the title to my clipboard.

![Screenshot_20230513-234815.png](https://github.com/Stremio/stremio-features/assets/69997739/b6ed5638-9524-467b-89ab-cd18a12ebfea)

**Comment by TRtomasz** [comment]
This kind of feature would is not worth in terms to rewards/complexity ratio.
