### ISSUE TITLE
Apple SharePlay (FaceTime) implementation

### ISSUE THREAD

**Issue by lothar-cell** [Stremio/stremio-features#383]
**Is your feature request related to a problem? Please describe.**
I know Peario exists, but it doesn't work in Safari and it would be great to have SharePlay as a native solution. Api is straightforward, shouldn't be too hard to implement, considering Stremio is in the App Store already.

**Describe the solution you'd like**
Stremio would use SharePlay api: https://developer.apple.com/shareplay/

**Describe alternatives you've considered**
Peario (not working in Safari)

**Comment by AlvinHV** [comment]
They cannot implement full stremio app with apple's app store guidelines. SharePlay api is available on app store app meaning you cant use it even with side-loaded app. It may be only possible with trollstore and if it is possible i will implement it

**Comment by TRtomasz** [comment]
Closing as not possible to implement according to the comment
