### ISSUE TITLE
Support RTX Video Super Resolution on the native media player

### ISSUE THREAD

**Issue by NJinsei** [Stremio/stremio-features#388]
**Is your feature request related to a problem? Please describe.**
Stremio users who watch older shows or stream from low-resolution sources may experience poor video quality on their high-resolution displays. The native media player of stremio does not have any upscaling technology to enhance the image quality. This would allow stremio users who have RTX GPUs and high-resolution displays to enjoy better video quality without sacrificing bandwidth or performance.

**Describe the solution you'd like**
I would like to request the support of RTX Video Super Resolution (VSR) on the native media player of stremio. RTX VSR is a technology that uses AI and Tensor cores on NVIDIA RTX GPUs to upscale lower-resolution video content up to 4K, enhancing the sharpness and clarity of the image.

**Describe alternatives you've considered**
I have tried some alternatives, but none of them worked well for me. For example, I tried running stremio on the web server feature and using a browser that supports RTX VSR, but the compression and degradation of quality made it worse than watching it natively. I also tried downloading the content and then upscaling it using another GUI, but it took too much time and storage.

**Additional context**
Other applications use the NVIDIA Broadcast SDK to get VSR onto their application, such as the "Waifu-2x Extension GUI". I hope stremio can implement this feature soon and make use of the power of RTX GPUs. Thank you for your consideration.

**Comment by GreenMan36** [comment]
This request is similar to #311 although mine is more about allowing it in the form of "extentions" so people can implement their own upscalers, ones that work on high-end devices and also low-end devices like FSR and VSR or frame interpolators.

Someone let me know MPV can use [FSR. You can also use CAS and NIS.](https://www.reddit.com/r/mpv/comments/sregrr/amd_fidelityfx_fsrcas_and_nvidia_image_scaling/) It might fit your usecase, although its not as great of an user experience as a native integration would be.

**Comment by TRtomasz** [comment]
Stremio uses MPV, we do not modify player. IF they decide to add support for this it then will be supported.

**Comment by Loukious** [comment]
> Stremio uses MPV, we do not modify player. IF they decide to add support for this it then will be supported.

It's officially supported. https://github.com/mpv-player/mpv/pull/14698 can we get the new version in Stremio?

**Comment by GreenMan36** [comment]
There's an issue requesting MPV to be updated; https://github.com/Stremio/stremio-features/issues/984
