### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by shnbwmn** [Stremio/stremio-features#39]
Hi there

Is it possible to create a portable version of Stremio? I would like to put it on my USB/ext HDD and take it with me when I travel. What's needed is the settings to be stored in the application folder, but it would also be great if it doesn't leave anything behind on the computer.

**Comment by Ivshti** [comment]
You can just put the folder which is usually in %LOCALAPPDATA%\Programs\LNV\Stremio on a flash drive.

Then, when you log-in with your account on any computer, it will auto-sync your Library and personal settings.

**Comment by shnbwmn** [comment]
Ah that's great. Thanks.

**Comment by Protoplast26** [comment]
I did this method, but every time that I need to restart the computer the "portable" instance of the application can't maintain account, settings, addons, it's like a new install every time
