### ISSUE TITLE
Can stream description be added to player in Android TV version

### ISSUE THREAD

**Issue by RayzaEFC** [Stremio/stremio-features#390]
In the mobile version player there's a stream description to what's playing. Can this be added as an option in the Android TV version, thanks

**Comment by TRtomasz** [comment]
Please update with the feature idea template to reopen this issue 
![image](https://github.com/Stremio/stremio-features/assets/40594253/8f1541c4-8f8d-4d9f-a206-48830d9ad558)

**Comment by RayzaEFC** [comment]
Sorry I don't understand. I'm not to good at all this, sorry. Thanks for
reply
