### ISSUE TITLE
A way to watch torrent/magnet links on web stremio without needing to install stremio service or the app it self

### ISSUE THREAD

**Issue by smartinoaj** [Stremio/stremio-features#391]
Currently you cant watch torrent/magnet links on web stremio without needing to install on your device either the new stremio service app or the main stremio app, and it would be nice to make that work somehow, cuz some of us cant install things cuz we are at work for example or on a pc without the admin pass and we cant install things, so it would be nice to make that work so we dont need to install anything and actually use the web stremio fully relying on the web.

**Comment by TRtomasz** [comment]
Please use the template when opening new issue. Please update your current issue with the new feature template so we can reopen it.
