### ISSUE TITLE
Split "Discover" to two top level Navigations, "Movies" and "Series"

### ISSUE THREAD

**Issue by notNSANE** [Stremio/stremio-features#392]
**Is your feature request related to a problem? Please describe.**
Discover is annoying.

**Describe the solution you'd like**
A separate top level category for each, that works like Discover.

**Describe alternatives you've considered**
None.

**Comment by TRtomasz** [comment]
Closing this for now as this issue does not contain enough information to even consider it, starting from what platform it is about as each our app is slightly different
