### ISSUE TITLE
Synopses translations

### ISSUE THREAD

**Issue by hassansaadfr** [Stremio/stremio-features#394]
**Is your feature request related to a problem? Please describe.**
Synopses are not translated or fetched in the correct language despite the configuration

**Describe the solution you'd like**
Fetch synopses in UI language

**Comment by TRtomasz** [comment]
closing as duplicate of https://github.com/Stremio/stremio-features/issues/236

**Comment by gonsodany** [comment]
except its not "completed", its been almost a year and synopses are still fetched in english only
