### ISSUE TITLE
In App update checker 

### ISSUE THREAD

**Issue by mo-5** [Stremio/stremio-features#396]
**Is your feature request related to a problem? Please describe.**
Using fire stick I have to manually check for updates and then download them through a 3rd party app and install them to update the app. 

**Describe the solution you'd like**
An in-app update checker, similar to how it's done in smart tube next. They use a library to check the version and if the version is newer it would prompt you to install the newest version. This would be very helpful:

https://github.com/yuliskov/SharedModules/tree/9d3c57d6cbd23b1a2c276e84ce71c7982854df31/appupdatechecker2

**Describe alternatives you've considered**

**Additional context**

**Comment by TRtomasz** [comment]
Sorry, we do not plan to add such feature just for firesticks.
