### ISSUE TITLE
Actor/Director info Android TV

### ISSUE THREAD

**Issue by Maddhatter182** [Stremio/stremio-features#398]
i've been waiting for years for this feature. i want the director/actor feature where i can look up the actor director or writer and see the movies they made or at least when im hovering over a movie i can see the director, and not having to go to google every single time.

**Comment by TRtomasz** [comment]
closing as duplicate of https://github.com/Stremio/stremio-features/issues/302
btw "for years"? We released Android TV app like a year ago lol.
