### ISSUE TITLE
On the stream selection page, show each stream's available audio tracks

### ISSUE THREAD

**Issue by kaydenpmd** [Stremio/stremio-features#399]
**Is your feature request related to a problem? Please describe.**
If I watch anime on Stremio, all of the files will have the Japanese audio. While some will say multi audio, half the time when I open the video and go to select an audio track, there's weirdly no English track, but there's Spanish or German or something like that. I have to load and check a few files before I get to one with an English audio track.

**Describe the solution you'd like**
My solution is to show the audio track information in the description on the button/card for each file.
![Screenshot_20230627-203141_Stremio.png](https://github.com/Stremio/stremio-features/assets/73806300/6f93bfcd-dc23-45bc-b97f-fa8ba9c7f7c7)

**Comment by kaydenpmd** [comment]
Also, this screen on mobile feels claustrophobic. I think the card setup should be changed to be Twitter-style with all the borders removed and simple dividers between each stream.

**Comment by TRtomasz** [comment]
This is not controlled by stremio, info comes from addons, Stremio app have no idea before selecting video what audio tracks are available.
