### ISSUE TITLE
Android / Android TV app

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-features#4]
We're planning on releasing an open-source android TV app.

**Comment by TwanoO67** [comment]
I would be glad to help on that :)

**Comment by ceuaugusto** [comment]
Any news on this? Thanks in advance!

**Comment by Ivshti** [comment]
right.

Initially, the plan was to make an open-source app based on html5.

After that, we found out we cannot reach good performance using HTML5, and furthermore we made an agreement with a set-top box provider to build an Android app with them.

Therefore, the app is not open-source and currently in alpha: http://www.strem.io/android-launch

**Comment by ceuaugusto** [comment]
Does this version have BitTorrent based add-ons? I will give it a try! Thanks, man!

**Comment by Ivshti** [comment]
It supports them, so if you have them on the desktop, you will have them on android too.

Please report the results of your test, as it's a early alpha with a lot of issues still to iron out.

**Comment by bmandrade** [comment]
Any news on Android TV support?

**Comment by darkfrog26** [comment]
I'm interested in Android TV support as well.  I'd like to be able to use it on my Shield TV box.

**Comment by Dramaretchi** [comment]
News? manage the UI on android with the mouse is not user-friendly.

**Comment by ravtakhar** [comment]
Wondering if there is any update on this?

I understand the Android APK works, but it's not user-friendly and missing some features (calendar).

**Comment by Ivshti** [comment]
Unfortunately Android TV is not our priority for now.

There is a base library implementing the core of Stremio (addons, user accounts and library sync) here https://github.com/stremio/stremio-core which can be used to develop new apps on. If someone qualified wants to do it, we may be able to provide support and funding, feel free to contact me directly.

**Comment by AndroidDeveloperLB** [comment]
@Ivshti Where is the repository for Android version of Stremio though?

**Comment by Snusifer** [comment]
@AndroidDeveloperLB 
> Where is the repository for Android version of Stremio though?

Looks like it isnt public yet. @Ivshti Any plans to publicise that repo in the near future? Modifying that code to suit an android TV experience shouldnt be too hard.

**Comment by AndroidDeveloperLB** [comment]
@Snusifer Depends how nicely you want to adjust it for Android TV. 
I've already noticed various bugs on it (whether you use on Android TV or smartphone) so I thought maybe I could check it out.
