### ISSUE TITLE
Hardware decoding modes in Android TV app

### ISSUE THREAD

**Issue by Zebim** [Stremio/stremio-features#401]
_**Is your feature request related to a problem? Please describe.**_

I'm using the Dune Homatics Box r 4k with Stremio (Android TV version) and it has problems with playing DTS audio formats. The only solution I found is to toggle off hardware accelerated decoding. However, I prefer to use hardware acceleration when possible. As a result I have to toggle it on/off everytime I'm want to play DTS formats.

_**Describe the solution you'd like**_

A helpful solution to this problem would be to implement the hardware decoding modes used in the normal Android (phone) app. Here, you are not just presented with the options "on" or "off" like the Android TV version, but you can choose multiple modes: Automatic, Disabled, Decoding acceleration, Full acceleration and Legacy. I believe that especially the "Automatic" mode would be helpful in the Android TV version and thus solve my problem.

**Comment by TRtomasz** [comment]
Both apps use diifferent players so it is not possible to do this. Try using tunneled playback when you have problem with sound.
