### ISSUE TITLE
Add Network Interface Option

### ISSUE THREAD

**Issue by de-sawal** [Stremio/stremio-features#407]
**Is your feature request related to a problem? Please describe.**
An option that makes stremio connect through only the selected network interface.

**Describe the solution you'd like**
Users can choose whether stremio works with any interface or selected interface (eg. Ethernet, LAN* 1, Wi-Fi, or vpn interfaces like NordLynx).
A similar implementation to that of "qBittorent -> Options -> Advanced -> Network Interface".

**Describe alternatives you've considered**
.

Would be massively helpful to users that only want to use the application through VPNs, and also applicable in other cases.

**Comment by TRtomasz** [comment]
Please update your issue with the new feature form

**Comment by de-sawal** [comment]
> Please update your issue with the new feature form

done

**Comment by TRtomasz** [comment]
IF you turn on VPN on your system it works in a way that all apps are using it unless you configure it for some ips or applications not to use it.

**Comment by jan-kleks** [comment]
@de-sawal I have also described in more detail what interface binding is all about, here: https://github.com/Stremio/stremio-features/issues/371#issuecomment-1852796195

Maybe you have anything to add there?
