### ISSUE TITLE
Volume Booster on Android TV App

### ISSUE THREAD

**Issue by JJarvo** [Stremio/stremio-features#408]
**Is your feature request related to a problem? Please describe.**
Headphones and soundbars seem to be very low volume when watching on TV. YouTube or other streaming apps have a boost or sound loud enough.

**Describe the solution you'd like**
Volume Booster on Exo player Android TV app.

**Describe alternatives you've considered**
I have tried external players like VLC or MX, but don't seem to play 4k DV files well like Exo does.

**Comment by TRtomasz** [comment]
Just volume up your device, or change a stream if it has modified sound in a way it is too quiet.
