### ISSUE TITLE
Use more privacy-friendly alternatives for analytics

### ISSUE THREAD

**Issue by ADHDefy** [Stremio/stremio-features#409]
**Is your feature request related to a problem? Please describe.**
According to an Exodus scan, usage data can be collected by Google, Facebook, and Microsoft. This is a huge privacy issue, especially if this app is the core of someone's media consumption. 

https://reports.exodus-privacy.eu.org/en/reports/358156/

VPNs will not protect users from this data collection. The only solution would be to outright block connections to these services at the DNS level, which also means that you would not get crash/analytics feedback.

**Describe the solution you'd like**
Please remove these embedded trackers and implement more privacy-friendly, less invasive solutions. Also, analytics would ideally be opt-in. 

**Describe alternatives you've considered**
If analytics are necessary, please consider something like the open source [Matomo](https://matomo.org) or another privacy-respecting service.

**Additional context**
N/A

**Comment by TRtomasz** [comment]
@ADHDefy  Matomo isn't an alternative for what we are using. It looks like the scan detects libraries included in the mobile app but it does not necessarily  mean that we are utilizing them.Facebook libraries are included by default when you add facebook login feature and use their SDK, but we don't use facebook analytics. We use Google firebase for sending push notifications but we do not use any analytics feature here, it looks like they libraries are included by default when using other firebase functionalities. Microsoft libraries are used for purposes of crashlytics.

**Comment by celenityy** [comment]
@TRtomasz Stremio does in fact appear to use Google Analytics on the website and in apps. 

Has there been any consideration to at least allow disabling Google Analytics and Microsoft crash reporting? Ideally, I'd like to see them both removed, but being able to opt out would at least be something for those of us who are privacy conscious. We all know Stremio's main use case, which makes including these trackers even more concerning.

Stremio looks like a great app, I tried it out and like it a lot, but including this tracking is the one thing blocking me from using it, so I hope this can be reconsidered.
