### ISSUE TITLE
Subtitles position on Chromecast

### ISSUE THREAD

**Issue by ansantos** [Stremio/stremio-features#41]
Hi,

When streaming to Chromecast with subtitles, I noticed that the subtitles position is too much to the lower edge of the screen and they are not fully shown. Is there any chance to change the subtitles position when streaming to Chromecast?

Thanks

**Comment by Ivshti** [comment]
Hi, 

We will check this out.

In the meantime though, can you check aspect ratio of your TV? Usually that shouldn't happen with the chromecast

**Comment by ansantos** [comment]
Hi,
The TV is set to exact mode, but I tested with several different aspect ratios and it always happen. However, my TV is a bit old and is only HD ready. Nevertheless, having an option to set the subtitles position (even when streaming to chromecast) would be nice.

Thanks

**Comment by celorodovalho** [comment]
+1 to this issue!
