### ISSUE TITLE
Upgrade Cache of Caledner and add Support For Android Phones and TV's

### ISSUE THREAD

**Issue by CrypticCus** [Stremio/stremio-features#410]
**Is your feature request related to a problem? Please describe.**
Yes and No, when you follow too much tv shows calender sometimes doesn't show all of them. Needs a update.

**Describe the solution you'd like**
I Want "Calender Support For Android Phones and TV's"

**Describe alternatives you've considered**
Trackt and other platforms

**Additional context**
Don't need to

**Comment by TRtomasz** [comment]
This will not be changed calendar is limited to 120 shows and this is due to techical limitations.

**Comment by EgeGurkan** [comment]
its not completed we need it on andorid apps
