### ISSUE TITLE
White Box to show selected show by remote

### ISSUE THREAD

**Issue by Matrix40au** [Stremio/stremio-features#414]
On Android TV version ( but set for all versions). it needs a small white box around selection to show which show you have selected. At the moment, the tile allivates to show which one is selected.
On the main screen as you log in.

When you select a series or movie, and then episodes it fine from then on...

That's about it, make it easier to see on a dark screen.

**Comment by TRtomasz** [comment]
Please update yout issue with new feature template.
If i understand you correctly you want white border around selected item? There are already plenty indicators showing what is selected. Selected item is higlighted, selected item poster is lifted up and additionally on the top it says what item is selected with its description. So for know i think we can close this issue
