### ISSUE TITLE
Side-load Stremio "channel" on Roku TV's developer mode?

### ISSUE THREAD

**Issue by lucarampi** [Stremio/stremio-features#417]
"Yes... I bought a Roku TV thinking it was an Android TV (because it always is). So, doing my research, I found a way to sideload third-party apps on the Roku TV by enabling Dev Mode, as you can see here: https://developer.roku.com/pt-br/docs/developer-program/getting-started/developer-setup.md

Reading the docs, I found that it runs on the Linux kernel, as you can see here: https://developer.roku.com/pt-br/docs/developer-program/getting-started/architecture/dev-environment.md

With that said, is there, by any chance, a way to install the Stremio "channel" (also called app) or perhaps fork/adapt the existing Stremio Linux program to run on those devices?"

**Comment by MisterTelevision** [comment]
Better to buy Onn 4k. I did this with my roku tvs. Boxes are only 20

**Comment by DCFUKSURMOM** [comment]
Roku is running a stripped down and locked down Linux environment. It is not Android based and will not run Android apps. There isn't a version of Stremio for the Roku OS, and there probably never will be because Roku doesn't allow fun things on their devices.

**Comment by TRtomasz** [comment]
There is no stremio roku app.
