### ISSUE TITLE
Make a "playlist"

### ISSUE THREAD

**Issue by roy979** [Stremio/stremio-features#418]
I'm looking for an addon for stremio that lets me choose my favorite tv shows, makes a "playlist" of all of their episode and shuffles them. The goal is to get stremio to play a random episode of a random show from the shows in my list.

Thanks!

**Comment by TRtomasz** [comment]
for addons issues or ideas please use addons forum https://www.reddit.com/r/StremioAddons/

**Comment by jaruba** [comment]
@TRtomasz it's already possible, actually, if u serve a series or channel type from an addon, and the user has autoplay enabled, then that is a playlist by definition

but the users cannot create playlists themselves, that is ourside the scope of the project
