### ISSUE TITLE
Chromecast subtitles styling

### ISSUE THREAD

**Issue by PedroMCostaAndrade** [Stremio/stremio-features#42]
please consider ading this...
https://github.com/thibauts/node-castv2-client/issues/8

**Comment by Ivshti** [comment]
Thanks for the link, it will be added to the roadmap; I cannot give an ETA about this yet though. 

Simplest thing to do would a a JSON file in the Stremio data dir that allows you to write in a custom chromecast styling - without a GUI. That would take 10-20m to add, so I can give you an ETA.

**Comment by PedroMCostaAndrade** [comment]
That would be amazing ;)
Em 11/05/2016 10:27 da manhã, "Ivo Georgiev" <notifications@github.com>
escreveu:

**Comment by Ivshti** [comment]
@PedroMCostaAndrade done, from 3.5.14 (or 3.6) - scheduled next week by that time, you'll be able to use chromecast-textstyle.json in data path (in Linux, ~/.stremio) to modify chromecast styles.

It should be filled with properties that go into textTrackStyle, like backgroundColor/foregroundColor, etc.

**Comment by Ivshti** [comment]
Also I need to mention that we updated the default Chromecast subtitles style, they now no longer have a black background, but look while the usual stremio style.

**Comment by PedroMCostaAndrade** [comment]
Thanks :)
Em 11/05/2016 6:47 da tarde, "Ivo Georgiev" <notifications@github.com>
escreveu:

**Comment by PedroMCostaAndrade** [comment]
Nice, if so i dont even need to change nothing ;)
Em 11/05/2016 6:50 da tarde, "Pedro Andrade" <pedrom.costaandrade@gmail.com>
escreveu:
