### ISSUE TITLE
Android: choose cache location (sdcard vs internal)

### ISSUE THREAD

**Issue by dany123** [Stremio/stremio-features#423]
**Is your feature request related to a problem? Please describe.**
I'm using Stremio on my android tablet (Samsung Galaxy Tab A8) with 32GB of internal memory and a 250GB memory card and even though I had Stremio moved to SD Card it still used my internal memory. 
Please see the attached screenshots for proof of this.

**Describe the solution you'd like**
Option in settings to be able to choose the application cache location.

**Describe alternatives you've considered**
An alternative it would be to make the current move to sdcard in android work fully, (as to include the cached files) I don't know how/why this isn't working right now, .

**Additional context**
Just to be 100% sure that moving to sd card was properly done I did this again fully from scratch: cleared all data, moved the app to sdcard from android settings, rebooted device, logged in my account then clicked on a ~4GB movie and waited ~20mins to cache as much as possible. Here are the before and after screenshots in app list and storage usage:

![01  stremio before move](https://github.com/Stremio/stremio-features/assets/3215812/eec8dae8-eb38-4adf-87bb-d6daf24f29e2)
![02  stremio after move and dw](https://github.com/Stremio/stremio-features/assets/3215812/761afd6b-9e57-4ab9-8dcd-160fd10ec308)

**Comment by technout** [comment]
And this cache location option is also not available in Stremio version 1.6.1

**Comment by TRtomasz** [comment]
This is how android works, sorry we cannot change it any further.

**Comment by dany123** [comment]
I mean it's not "how android works" because other apps do this properly.
I guess this means my request was denied, thanks anyway.
