### ISSUE TITLE
Android TV: (AFR) Auto frame rate matching using tvQuickActions Pro

### ISSUE THREAD

**Issue by jorges4lu2** [Stremio/stremio-features#425]
Currently, Stremio supports AFR but only with devices that support this feature natively.

With tvQuickActions Pro a lot of Amlogic devices with Android 9-11 can get AFR even if they don't support it natively.

I'd love to have this feature implemented.

Thank you

**Comment by marian353** [comment]
l

**Comment by TRtomasz** [comment]
Don't see how it is related to stremio, since this is a 3rd party app and from it's description it does not even seems to be doing what you wrote.
