### ISSUE TITLE
request features

### ISSUE THREAD

**Issue by marian353** [Stremio/stremio-features#426]
put a report function so that we can report the lack of subtitles or out of sync or the problem with a movie where that report should go to the one who owns the addon so that he knows it's a problem and to solve it problem

**Comment by TRtomasz** [comment]
stremio does not controll subtitles they are provided by addons so it does not make a sense to add such functionality.

**Comment by marian353** [comment]
I sent an email to stremio and the contact people sent me to request features here
Karan (Stremio)

Aug 9, 2023, 10:22 GMT+3

Hi,
 
You can request features here: https://github.com/stremio/stremio-features/issues

**Comment by marian353** [comment]
I sent an email to stremio and the contact people sent me to request features here
Karan (Stremio)

Aug 9, 2023, 10:22 GMT+3

Hi,
 
You can request features here: https://github.com/stremio/stremio-features/issues
