### ISSUE TITLE
Adjustable Subtitle Brightness / Color on AndroidTV app

### ISSUE THREAD

**Issue by apfelchips** [Stremio/stremio-features#427]
**Is your feature request related to a problem? Please describe.**
I'm using stremio to watch HDR content with my _Chromecast 4K with Android TV_ on an LG OLED, the switching to HDR mode works beautifully.
The Problem is, 100% white subtitles in HDR mode are so bright they hurt my eyes.

**Describe the solution you'd like**
Please consider implementing subtitle brightness / color adjustment options, or auto dim them when switched to HDR mode.

**Describe alternatives you've considered**
I'd simply use SDR mode, but without proper tone mapping dark scenes of HDR content in SDR are so dim you can't see anything.

**Additional context**

Thank you for developing stremio.

**Comment by LorenzoCabras** [comment]
Totally agree with you, they're too bright and they ruin the experience

**Comment by klaare** [comment]
Is this implemented yet? I can only adjust subtitle delay on TCL android tv
