### ISSUE TITLE
Please add more subtitle addons in the Android tv version

### ISSUE THREAD

**Issue by kkolio** [Stremio/stremio-features#429]
I have the Android tv version but when I install subtitle addons they don't appear. Only opensubtitles. Can you please fix this? Thank you

**Comment by TRtomasz** [comment]
Stremio does not controll available addons, they are created by the community.

**Comment by kkolio** [comment]
Yes but that's an issue of Stremio I guess. Maybe it's a bug. Only on the Android tv version of the app this problem exist
