### ISSUE TITLE
Translation for Cinemeta

### ISSUE THREAD

**Issue by Vinsn1** [Stremio/stremio-features#433]
Hi guys. My father doesn't speak English and he would love to have italian translation in cinemeta addon.
Even a beta Google translate Version would be very appreciated. 
Cinemeta competitor Tmdb has italian language in the catalog but it can be used by default catalog addon. 

Thanks you even if you are only considering to add this feature. 

Cheers

**Comment by YuriAniceto** [comment]
Please, this would be really important for me, and shouldn't be hard on IMDB api to change language, or let TMDB handle metadata for all sections.

I know on metadata section it's on desired language, but other addons that I use should also be in portuguese.

Thanks!

**Comment by Cacha21** [comment]
+1 for this feature. It would be great and make stremio better for many people.

**Comment by TRtomasz** [comment]
duplicate https://github.com/Stremio/stremio-features/issues/236

**Comment by marcoshimselfxd** [comment]
Stremio could be number 1 by now... Specially considering that the famous" My Family Cinema" here in Brazil has been turned off, more than 6 million users are migrating to different platforms.
It requires too much work for someone to Install the add-ons and set-up everything to have the descriptions and titles in portuguese, and it's not even that great.
A native option should be have been available years ago.
