### ISSUE TITLE
App for Tizen (Samsung Smart TV)

### ISSUE THREAD

**Issue by POLFLAPS** [Stremio/stremio-features#434]
I have a Samsung TV which runs on Tizen. I currently can only use Stremio through the browser, which is a very clunky on a Tizen TV.

This request was already made [a while back in 2018](https://github.com/Stremio/stremio-features/issues/86), I'm hoping it could now become more of a priority as the share of Smart TVs has increased. A native Tizen Stremio app available in the Samsung app store would be perfect.

My monitor has a limited amount of ports which are all in use, so an Android TV stick is not a user-friendly alternative (and defeats the purpose of a Smart TV). Sideloading is not feasible.

**Comment by MrMonkeyz** [comment]
Definitely needs a tizen version.. we have the likes of plex and emby so no reason why streamio couldn't be done

Even if the app had to be usb sideloaded I'd be happy with that.. just like I do now with the newer versions of emby

**Comment by aliveli49505152** [comment]
+1 to this. We definitely need a tizen version

**Comment by ADHDefy** [comment]
Yes please!

**Comment by Ricrdsson1** [comment]
I installed it as an app on a Samsung TV with Tizen. Unfortunately it doesn't work well so far. The controller navigation is poor, you can't even get to some options.

**Comment by MrMonkeyz** [comment]
where can we even get the tizen app to try or test out, as who is developer of it?

**Comment by Ricrdsson1** [comment]
I used the web version and compiled it for a TV application.

**Comment by MrMonkeyz** [comment]
ahh thats pretty cool, love to try it out

**Comment by jacubsmith** [comment]
@Ricrdsson1 does anyone have any idea the work required to get a controller working with a web interface? If the web app has good tab accessibility it could just be remapping the controller input events.

I'd be happy to help work on this if anyone else fancies it?

**Comment by Ricrdsson1** [comment]
Yeah it just seems that the navigation is not finished, you can try it on PC where you scroll with the keys.

**Comment by MrMonkeyz** [comment]
hopefully someone out there is able to make a working version of it for tizen as would defo be amazing, the web one works on my 95b oled but just need better navigation for it

**Comment by MrMonkeyz** [comment]
Currently using the chromecast for this reason.. but really needs to be a app made for tizen... we got the likes of plex and emby app etc so can't see why streamio can't be ported over

**Comment by jaruba** [comment]
Stremio is now available in the Samsung TV App Store - https://blog.stremio.com/stremio-is-now-available-in-the-samsung-tv-app-store/

**Comment by hlapatsas** [comment]
Seems like today's update on Tizen OS has broken the app. No video is loading. "Unknown error" appears every time..

**Comment by jaruba** [comment]
@hlapatsas torrent playback is broken, yes. we will rollback the latest version, but this will take a few days, after that, we can submit a new version with the fix (but that will take 2-3 weeks due to Samsung reviews)

**Comment by b1scoito** [comment]
> Seems like today's update on Tizen OS has broken the app. No video is loading. "Unknown error" appears every time..

Same is happening to me on Q80 55" Samsung TV, relates to https://github.com/Stremio/stremio-bugs/issues/627.

Tizen version 6.5
Theater version 1.2.0

**Comment by hlapatsas** [comment]
Hello everyone!
Is there going to be a new Stremio version any time soon?
There are 2 issues I have noticed:
1. Constant freeze of the application without any pattern on the behaviour.
2. Random buffering on the TV version while the PC version works fine.

**Comment by hlapatsas** [comment]
Additionally, every time  I try to select subtitles different from the default ones, a purple error message appears on the top right corner of the screen and the subtitles are not loading at all.

**Comment by MrMonkeyz** [comment]
I am also wondering when we will see an update to the tizen version... as been a while since had any news

Having to keep turning off subtitles is annoying due to them showing as "unknown" even though I have it set to show none in the settings
