### ISSUE TITLE
Ability to search by IMDb URL (searching by IMDb ID already supported)

### ISSUE THREAD

**Issue by mattalxndr** [Stremio/stremio-features#435]
Currently, it is possible to search by IMDb ID, which is a helpful little hidden feature. But I am unable to search by IMDB URL. 

When I have a keyboard handy, it's about the same thing. But on a phone, it's a bit of a pain to just grab the ID from the browser. My browser's address bar only allows me to select the whole URL, which means I'm manually deleting the beginning and the end of the URL, then copying. 

It would be much easier to grab the full URL and toss it into Stremio.

**Comment by TRtomasz** [comment]
You click on the pen icon in the chrome or perhaps similar icon in every other web browser and then you are able to select just the imdb ID
