### ISSUE TITLE
A random button for shows and movies

### ISSUE THREAD

**Issue by bmerrill42** [Stremio/stremio-features#44]
you could configure it to only pick SD or HD streams or only streams like HBO Go and xfinity, and maybe even have some sliders to pick between a certain range of ratings.

**Comment by Ivshti** [comment]
That's a fantastic idea! Especially considering that:

1) Discover can be improved by adding such sliders/options - for ratings, only from certain streams, etc.
2) Random button that picks from this entire selection

We will see what are the technical implications of this, as are being held across add-ons in different place from where the metadata is - several caching layers will have to be introduced

**Comment by Harith163** [comment]
I loike this.

**Comment by TRtomasz** [comment]
Done with stremio dice
