### ISSUE TITLE
Adjusting movie sound not working with android TV volume setting

### ISSUE THREAD

**Issue by technout** [Stremio/stremio-features#443]
I like the new version and UI! But i noticed with this version that the audio volume setting is different on my android TV.

I use Stremio on my android (version 9) TV.
I cannot change the movie sound volume with my android volume setting (like i can do for all my other android apps).
I have to adjust the volume with my TV remote, this is a bit annoying. I like to use the android volume setting for this (like in version 1.5.9)

Am i the only one with this problem?

**Comment by TRtomasz** [comment]
For new issues please use this repository https://github.com/Stremio/stremio-bugs/issues please open new issue there with more detailed issue description, right now we can only guess what is 'android volume setting'
