### ISSUE TITLE
Translate with AI

### ISSUE THREAD

**Issue by 360fun** [Stremio/stremio-features#444]
**Is your feature request related to a problem? Please describe.**
Sometimes a subtitle is not available in the language I need

**Describe the solution you'd like**
What about integrating DeepL, ChatGPT or a similar (free) service?

**Describe alternatives you've considered**
Create a collaborative translation service...but that's a lot more complicated and expensive. AI is good enough to watch most of the movies.

**Additional context**
What I normally do is:
- download the subtitle (at least before the latest re-design, now this option is missing 😭)
- rename .srt in .txt
- convert the .txt in .docx (sadly Deepl don't support simple .txt ...absurd)
- translate with DeepL
- convert back the .docx in .txt
- rename .txt in .srt
- drop it in Stremio

Not 100% accurate but it works pretty well with some languages (ex. Spanish to Italian).

**Comment by TRtomasz** [comment]
Subtitles are provided by addons, stremio does not provide it, so if someone is willing to c reate an addon that will translate existing subtitles using AI he can do it.
