### ISSUE TITLE
Re: auto-play feature 

### ISSUE THREAD

**Issue by KingWing98** [Stremio/stremio-features#446]
**Describe the solution you'd like**
To further describe this. I thought that there could be a setting within the settings where you can enable or disable auto play for episodes or movies so you don't have to scroll through all the links that come up.

**Describe alternatives you've considered**
You could choose your default resolution that you'd like and set it at say 720p and it would only play links that are in that said resolution.

**Additional context**
Like I said, I think it would save time and be a lot more user friendly as most people like myself don't know what size mb to use when looking to play a link so I think the app should introduce this as it would be easy, fast, and now reliable for people

**Comment by TRtomasz** [comment]
There already is auto play feature and you can disable/enable it in the settings.
