### ISSUE TITLE
DLNA Server and Navigation

### ISSUE THREAD

**Issue by dyorgio** [Stremio/stremio-features#45]
Stremio can stream media to DLNA devices.
But we can't navigate our library directly on TV.
My request is include on stremio a DLNA browser/navigation support.

**Comment by Ivshti** [comment]
Good idea

Example projects that also do this would be great to get us inspired

**Comment by dyorgio** [comment]
Hi @lvshti,

Kodi, ps3mediaserver, serviio and Plex are some examples.

**Comment by boriseto** [comment]
Is it possible to consider the other approach too as well? Like having an explorer inside stremio that would stream files to a chosen device?

**Comment by inluxc** [comment]
Is it possible to do this with an addon???
