### ISSUE TITLE
Auto select original source audio / remember subtitle language based on source language

### ISSUE THREAD

**Issue by araggohnxd** [Stremio/stremio-features#450]
**Is your feature request related to a problem? Please describe.**
It is very annoying to have to manually select subtitle and audio source depending on what I'm watching. I'm aware of the preferred audio and subtitle language settings, but I like to watch things in its original audio source. For example, if I'm watching anime, I'd like the audio to default to japanese, but that would not be the case if I decided to watch an american movie, where as I'd prefer the original english source. Apply that to every language, and then the preferred audio/subtitle setting causes more hindrance than help, considering you'll change it, anyway.

**Describe the solution you'd like**
A way to select the default audio source to be the media's original language, and set the subtitle language based on that. Netflix kinda does that, I don't know how they do it, but they appear to have a way to remember which subtitle language you like based on what is the original audio. For example, I like to watch english content with english subtitles, because I'm not a native speaker and it helps me practicing. But I know nothing about japanese, so when watching anime, it defaults to japanese audio and portuguese (my native language) subtitles. And when watching brazilian movies, it defaults to source (portuguese) audio with no subtitles.

**Comment by Flyologist** [comment]
This new update stopped working on my MacBook and tv.

**Comment by TRtomasz** [comment]
Stremi does not have info what is media's original language.

**Comment by jan-kleks** [comment]
@TRtomasz Maybe you could pull this info from IMDB? They do list languages.

**Comment by jan-kleks** [comment]
Wikipedia also lists movies' languages.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Stremio/stremio-features/issues/450#issuecomment-1712520224

@jan-kleks, Wikipedia's formatting is too inconsistent to parse - it's not really machine-readable, and nobody wants to use RegEx - but IMDB should work.

**Comment by Flyologist** [comment]
Error code io network connection failed

Sent with Spark
