### ISSUE TITLE
Set the first day of the calendar week

### ISSUE THREAD

**Issue by enryson** [Stremio/stremio-features#451]
**Is your feature request related to a problem? Please describe.**
Possibility to set the first day of the calendar week; in my country and 66 more countries, the week starts on Sunday. Is way more convenient to have this option on Stremio.

**Describe the solution you'd like**
Ability to set the first day of the week, and store this option in the settings of the profile of a user.

**Describe alternatives you've considered**
Maybe get this setting from a calendar API or library, but it would be nice to give the user the chose option...

**Additional context**
Globally, we have 67 countries where the week starts on Sunday...

Outlook, Windows, Thunderbird, and more apps have this feature...
It will be nice and convenient to have this...

On some countries, including Israel... Pakistan... UAE... The week starting on Monday is unacceptable for religious reason.
The rest of the countries this option could be a lot more convenient..

Screenshot to show the differences between the two calendars..
![Screenshot 2023-08-28 234636](https://github.com/Stremio/stremio-features/assets/12296670/a260fa03-deeb-4d38-8c07-3d2f6aad17c6)

**Comment by TRtomasz** [comment]
this is known bug after redesign i will close this issue as we track it in stremio-bugs repo
