### ISSUE TITLE
Allow quality selection for trailers playback

### ISSUE THREAD

**Issue by leonpros** [Stremio/stremio-features#453]
It seems that during playback of trailers on youtube, tha application selects highest quality. On some older devices the selected resolution is not supported, thus playback gets stuck. 

I think this could be configured in 2 ways:
1. Allow to configure globaly maximum video resolution.
2. Allow to configure resolution during the playback using youtube controls

Allowing youtube controls during playback can also add features like playback speed and auto captions

**Comment by TRtomasz** [comment]
Please update your issue with new feature form so we can reopen it then.
