### ISSUE TITLE
Feature Request - Simple view mode that automatically start playbackbased on some settings

### ISSUE THREAD

**Issue by CDrosos** [Stremio/stremio-features#456]
Hello fam,
I have a lot of friends that are of an old age and its not easy for them to use stremio. i would like to suggest a feature about that:
It would be cool if an advanced user could configure an advanced mode with settings like:

- Providers priority,
- Quality above or below(for example quality to be 720p or above)
- Seeders minimum number
- Max tries of the above settings if the first match does not start playback, continue to the next best setting match

With a mode like that an advanced user could configure it and then it would only require a click on the play to start playing and i believe most of the times it will work great.

**Comment by TRtomasz** [comment]
Stremi does not have information like quality, seeders number it is all coming from addons and is not standarized in anywaym, this feature is not possible to be implemented.
