### ISSUE TITLE
Option to change aspect ratio 

### ISSUE THREAD

**Issue by steevan464** [Stremio/stremio-features#461]
Please give us an option to change aspect ratio. So we dong need to switch to other players

**Comment by TRtomasz** [comment]
Please update your issue with new feature template that is vailable when you open new issue
then we will reopen this issue.
https://github.com/Stremio/stremio-features/issues/new/choose
![image](https://github.com/Stremio/stremio-features/assets/40594253/5616ef77-6fd9-4c56-b1ed-90419d463a0f)
