### ISSUE TITLE
Stremio on LG WebOS

### ISSUE THREAD

**Issue by db90mt** [Stremio/stremio-features#462]
Is your feature request related to a problem?
Yes, the current unavailability of Stremio on LG WebOS is a problem for users who want to use the app on their LG Smart TV.

Describe the solution you’d like:
I would like Stremio to be made available on LG WebOS 22 onwards so that users can easily access and use the app on their LG Smart TV.

Describe alternatives you’ve considered:
Some alternatives that can be used to watch Stremio on LG Smart TV include casting it from a phone to the TV using an external player such as “Web Video Caster” or using an Android TV box or Firestick.

**Comment by bvidovic1** [comment]
Plus one for this

WebOS is probably the best TV OS out there.

**Comment by hideki2k02** [comment]
Bumping this, a webOS app would be nice.

**Comment by EnzoAlbornoz** [comment]
I got it running on my C3 on the web browser through [Stemio Web](https://web.stremio.com). Porting it to a proper app should be easy now.

**Comment by kubo6472** [comment]
how to do this? old webos won't launch web.stremio.com outside their integrated web browser

**Comment by EnzoAlbornoz** [comment]
> how to do this? old webos won't launch web.stremio.com outside their integrated web browser

What's your webOS version?

**Comment by db90mt** [comment]
My TV model is OLED55C2
webOS version 7.3.1-44

I tried web.stremio.com but when I click on the torrent, I get this message![image](https://github.com/Stremio/stremio-features/assets/143727557/a20eff63-6e0c-47f7-a480-0a8c4bcef0b7)

**Comment by db90mt** [comment]
When I click on "open an external player" I get a white blank screen with a message as shown below

![image](https://github.com/Stremio/stremio-features/assets/143727557/56c1274b-2c8e-4556-9682-3606382b12f7)

**Comment by EnzoAlbornoz** [comment]
> My TV model is OLED55C2 webOS version 7.3.1-44
> 
> I tried web.stremio.com but when I click on the torrent, I get this message![image](https://private-user-images.githubusercontent.com/143727557/292668180-a20eff63-6e0c-47f7-a480-0a8c4bcef0b7.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NDE1MzIsIm5iZiI6MTcwMzY0MTIzMiwicGF0aCI6Ii8xNDM3Mjc1NTcvMjkyNjY4MTgwLWEyMGVmZjYzLTZlMGMtNDdmNy1hNDgwLTBhOGM0YmNlZjBiNy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjdUMDE0MDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGNhOWNkNzE2NzAwMmJiZmUzMDdiOWRjZDRlNThlYTE5MWJmZmVhMjdjNTk4YTQ1MTQyMTdiNDFmOGFmZTM5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qQq9TR8K3loP3mSDe4oq9expGJ1nqa_kinxEblKowTU)

What add-ons are you using to watch this stream? Torrentio?

**Comment by kubo6472** [comment]
> > My TV model is OLED55C2 webOS version 7.3.1-44
> > I tried web.stremio.com but when I click on the torrent, I get this message![image](https://private-user-images.githubusercontent.com/143727557/292668180-a20eff63-6e0c-47f7-a480-0a8c4bcef0b7.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NDE1MzIsIm5iZiI6MTcwMzY0MTIzMiwicGF0aCI6Ii8xNDM3Mjc1NTcvMjkyNjY4MTgwLWEyMGVmZjYzLTZlMGMtNDdmNy1hNDgwLTBhOGM0YmNlZjBiNy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjdUMDE0MDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGNhOWNkNzE2NzAwMmJiZmUzMDdiOWRjZDRlNThlYTE5MWJmZmVhMjdjNTk4YTQ1MTQyMTdiNDFmOGFmZTM5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qQq9TR8K3loP3mSDe4oq9expGJ1nqa_kinxEblKowTU)
> 
> Which add-ons are you using to watch this stream? Torrentio?

For me torrentio. The built-in browser works, but I think the app I built using ares has problem with the web assembly. No idea why the browser runs it okay. If I package app.strem.io it loads, but navigation with arrow keys on the remote is broken, because the code I'm trying is focusing on specific elements or smth.

**Comment by kubo6472** [comment]
This is what I used as a reference:
https://webostv.developer.lge.com/develop/getting-started/web-app-types#hosted-web-app
https://github.com/webOS-TV-app-samples/HostedWebApp

**Comment by kubo6472** [comment]
Why did the OP close this?

**Comment by robertosolano** [comment]
@EnzoAlbornoz how do i configure it on my TV?

**Comment by EnzoAlbornoz** [comment]
> @EnzoAlbornoz how do i configure it on my TV?

I'm currently using the embedded chrome browser. 

Then I created a shortcut in the main menu. ![20240327_182805.jpg](https://github.com/Stremio/stremio-features/assets/39244167/80ba7e77-2bdb-4813-b10f-6ff1e48cf58e)

**Comment by jaruba** [comment]
Stremio is now available on 2020+ LG TVs: https://blog.stremio.com/stremio-is-now-available-on-lg-tvs-for-models-2020/
