### ISSUE TITLE
More options for the mobile player

### ISSUE THREAD

**Issue by notmohe** [Stremio/stremio-features#465]
- It would be cool if the team managed to add the same options as the pc ones for example the skipping option if it could be changeable it's set by default at 15s which is so long
- more details for the subtitles fonts like adding edge types to the font like : outline, shadow..
- if you could guys make the icons of the player a little bit smaller cus it covers the whole image once u touch the screen 
- an option to select a source when choosing the server you're trying to watch like torrentio or tpb..

**Comment by TRtomasz** [comment]
Closing, as it issue does not use new feature template, please create one issue for one feature request.
