### ISSUE TITLE
full season doenload option

### ISSUE THREAD

**Issue by 22tooty2** [Stremio/stremio-features#472]
So far when we wanted to download entire seasons, we would need to go episode by episode and download.

It would be very helpful if we could auto download entire season from the first source that appears or by resolution.

**Describe alternatives you've considered**
Going one by one and downloading, or using a third party software.
It can become really frustrating on long seasons or for new users.

**Additional context**
The button can be on a right click menu or on the show's page, it will be very helpful to many people.

**Comment by TRtomasz** [comment]
Stremio is not aware of streams resolution so this is not possible

**Comment by 22tooty2** [comment]
> Stremio is not aware of streams resolution so this is not possible

Weird, it is aware of stream resolution when suggesting the next episode to watch.

Is it not possible to just chain the next episode and download until we get to the end of the season?
