### ISSUE TITLE
Compact view of episodes

### ISSUE THREAD

**Issue by Dieterdemuynck** [Stremio/stremio-features#473]
**Is your feature request related to a problem? Please describe.**
While the new UI looks better, I feel that user experience has become worse because of it. I cannot open the details of a series from the "recently viewed" tab to select a new episode, without pressing an extra button. If I click the thumbnail as usual, I usually get left on the end card of the previous episode. Switching between seasons also requires an extra button press.
Most importantly, there is no compact view of the episodes anymore, meaning that if I want to select the next episode in a series, I must first scroll down before finding the episode I'm looking for. This last part also means I no longer get the same information I used to get in the blink of an eye: I used to have a visual representation of how many episodes of a season I watched by simply looking at where the checkmarks end (episodes watched), compared to how far down the last episode was.

**Describe the solution you'd like**
I think a "compact view" option for the episode selector would already go a long way, similar to how reddit has a compact view for posts. In this compact view, there would be no thumbnail, as well as no date, simply the title would be left. This means it would be something similar to the old UI's episode selector. I believe this alone would already solve (most of) my negative feelings towards the new UI.

Note that I do not want a more compact view of the series/movies in eg. my library, as they are already compact.

**Describe alternatives you've considered**
An expandable list (kind of like a fullscreen for just the episodes selector) or a grid view similar to how series/movies are represented. The first doesn't really solve my issue, while the second isn't very intuitive and most likely also harder to implement. Switching to an older version of the app doesn't seem like a reliable solution either.

**Additional context**
I'm using the desktop Stremio app.
In the image below, I marked the episodes selector I talk about in this request. Note that I scrolled down to the last episode I watched.
![image](https://github.com/Stremio/stremio-features/assets/42997575/4345d9a4-547d-4181-998b-66635314f86b)

**Comment by TRtomasz** [comment]
you can open details  of a series from recently viewed, crom context menu(right click) or using thre dots menu that is under the poster.

**Comment by TRtomasz** [comment]
this has beend fixed, and depends on the place you click if inside the play button it will start playing outside play button it will open the details
