### ISSUE TITLE
Xbox app

### ISSUE THREAD

**Issue by primecomrade** [Stremio/stremio-features#474]
Hello I was wondering if you could make Stremio app for Xbox because my Android tv can't handle the app as it's too heavy for it on the other side Xbox is more powerful machine... android tv crashing and when it freezes I must unplug it and then plug it again

**Comment by jaruba** [comment]
Hi, I'm afraid that Stremio has a very important internal rule of not teasing / announcing future features or plans. Our team is small and we don't have deadlines, teasing anything gets users very excited and that makes our job much harder.

So unfortunately, we cannot answer this question.
