### ISSUE TITLE
Possible way to allow streaming on apple tv?

### ISSUE THREAD

**Issue by gdm-1718-indymeer** [Stremio/stremio-features#476]
I recently discovered that Moviebox uses TVM player, this way it allows to navigate through their library and plays them through the app.

I don't exactly know what type of connection they use, but perhaps you could achieve this with the web version of strem.io?

https://apps.apple.com/us/app/tvmplayer/id1583149482

**Comment by jaruba** [comment]
This is not possible for Stremio, TVM Player is literally just a player with Samba share / playlist support, there is no way to integrate Stremio with that.
