### ISSUE TITLE
Full screen launch off app

### ISSUE THREAD

**Issue by Freezer777** [Stremio/stremio-features#478]
**i am using Stremio on Linux mint. I would like to autostoel the app in full screen so we have a true media center experience.]

**Describe the solution you'd like**
Code a setting in de system settings or add a command switch with the app like —fullscreen 

**Describe alternatives you've considered**
Or maybe a shortcut in the app like F10

**Additional context**

mor maybe the app can remember the last setting used.

**Comment by tymmesyde** [comment]
There is already a shortcut to toggle fullscreen mode in the app, it's `F`

**Comment by Freezer777** [comment]
Hi Tim,

Can I use the F as a command paramater like --f

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows

Van: ***@***.***>
Verzonden: 06 September 2023 07:20
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [Stremio/stremio-features] Full screen launch off app (Issue #478)


There is already a shortcut to toggle fullscreen mode in the app, it's F

**Comment by TRtomasz** [comment]
no, this is not possible @Freezer777 sorry
