### ISSUE TITLE
Auto play next episode when streaming to smart TV

### ISSUE THREAD

**Issue by FrazJ** [Stremio/stremio-features#48]
Would love for the next episode in a series to auto play when steaming from Stremio to a smart TV. It's annoying to have to get up after each episode to play the next.

**Comment by Sunnysky** [comment]
That feature works on the Windows Stremio app when displayed to a dumb TV which is how I use it. either VGA or HDMI on 1080p to 55" screen.  It also works on Prime thru a browser. What might be or might not be cool is to have a Prime add-on with sharing.

**Comment by TRtomasz** [comment]
Closing as now we have smart tv apps
