### ISSUE TITLE
5 Feature Requests 

### ISSUE THREAD

**Issue by TuupacFR** [Stremio/stremio-features#483]
After trying many similar streaming apps, Stremio stands out as the best so far in my experience. However, there are some interface tweaks and features that could make it even better:

- Allow reordering home screen add-ons and categories to customize priority. 

- Remember Discover tab filters instead of resetting on each app launch + Improve Discovery Tab layout on Android TV to display the same way as mobile (Full Wall Display instead of horizontal line)

- Improve Trakt integration for tracking watched status and add a working Up Next feature. 

- Split out Movies and TV Shows into 2 separate sections in the left nav menu

- Add Rotten Tomatoes ratings natively  

 The developers are clearly listening to the community so I'm optimistic about the future of this open-source platform.

**Comment by ADHDefy** [comment]
+1 for reordering home screen, remembering discover tab filters, and making movies and TV two seperate sections

**Comment by icpryde** [comment]
Yes, 100% being able to reorder home screen would be awesome and also a way to turn on/off certain catalogs that we don't want to clean up the home section

**Comment by TuupacFR** [comment]
Would be really nice to have an update on the requested feature the community is sharing if it's planned or not 🙏🏼

**Comment by ccigas** [comment]
+1 for reordering without the need to reinstall add ons.

**Comment by lothar-cell** [comment]
There's an unofficial workaround for this, worked for me perfectly so far: https://github.com/Stremio/stremio-features/issues/562#issuecomment-1969170326

**Comment by TRtomasz** [comment]
I will close the issue, when requesting new feature, please use the new feature template and request one feature per issue.

**Comment by TuupacFR** [comment]
But then don't mark it as complete? Because none of them are complete

**Comment by lothar-cell** [comment]
Exactly.
