### ISSUE TITLE
list of a franchise.

### ISSUE THREAD

**Issue by user01302** [Stremio/stremio-features#484]
Hello. stremio could make an option like a set of movies from the same franchise. for example, franchises that have many movies like Fast and Furious, Harry Potter, Stars Wars and etc.. and since there are many movies it would be a good idea to show in the set of movies of the franchise when you enter a movie of some big franchise. I wish there was an option like that.

**Comment by TRtomasz** [comment]
This is not stremio task, this could be done by an addon.
