### ISSUE TITLE
Stremio + Corsaro Nero - it's possible?

### ISSUE THREAD

**Issue by vitouchiha** [Stremio/stremio-features#488]
hello everyone, I'm new and enthusiastic about the stremio world, I apologize in advance if I ask a question that has already been covered.. I'm Italian and I find enough ita and sub-ita results on Torrentio.. Very happy, but I was wondering if it is not possible to add for search other sites like "il corsaro nero" (purely for ita - sub-ita - eng torrent search). Thanks in advance

**Comment by jaruba** [comment]
I'm afraid that this is outside the scope of the Stremio apps. A community addon should be developed for it, but as the name says (community addon), addons are not built by the Stremio team, they are built by community developers..
