### ISSUE TITLE
Keep chosen embedded audio and subtitles when playing next episode in a series

### ISSUE THREAD

**Issue by crazyrabbit0** [Stremio/stremio-features#490]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
When I finish an episode of a series and I click on the "Next" button,
I have to re-select my preferred (in my case embedded) audio and subtitles streams.
It would be nice if the chosen audio and subtitles where tranfered from current to next episode.

**Describe alternatives you've considered**
Nothing really.

**Additional context**
None.

**Comment by NoSpamMaam** [comment]
Second this!

**Comment by TRtomasz** [comment]
you can select default audio/subtitles track and they will be automatically selected in the video yoy play.

**Comment by crazyrabbit0** [comment]
> you can select default audio/subtitles track and they will be automatically selected in the video yoy play.

Yes, this is true, but it's not what I am asking for, case in point:

1. I mostly watch English Movies/Series (for which I don't want/need subtitles)
2. but I also watch Anime (where I need English subtitles)
3. and I also watch Series in other Languages with different Subtitles (since English is not my main Language)

In case of point 2 or 3, I would prefer the selected subtitles to be passed on to the next episode,
so that I don't have to select the preferred subtitles in each and every episode.
