### ISSUE TITLE
Ambient Light with Stremio

### ISSUE THREAD

**Issue by Krwawyy** [Stremio/stremio-features#496]
Hi, is there any way to make Ambient light application by Vsevolod Aleksandrov to work with stremio? It works fine with interface but when trying to watch film it's not, tried different players, vlc etc. Nothing works, somehow it works fine while watching videos on SmartTube (there is fix in options). Is there any way to make something similar in stremio? On Reddit they said stremio is not recognized as video player which doesn't make sense 'couse it works in menu.
You are making awesome job!

**Comment by TRtomasz** [comment]
We dont know, sorry.
