### ISSUE TITLE
Feature Request: visible item titles

### ISSUE THREAD

**Issue by kabe-inc** [Stremio/stremio-features#498]
I've been an enthusiastic Stremio for some time and with the recent UI change I was hoping that users would be getting visible item titles everywhere (especially on the Discover page) and not just in the Continue Watching list, or at least the option to toggle on/off.

The reason this is needed is because the thumbnails on some movies/series don't clearly display the title, meaning the user has to manually select them in order to verify what they are.

![screenshot](https://camo.githubusercontent.com/c6cdcb2c584f3e550c01207ec80e932719e0147ddf5bb532f238b17be60dfa92/68747470733a2f2f692e706f7374696d672e63632f643378336e6768342f7469746c65732d32303233303832373130343435362e77656270)

**Comment by TRtomasz** [comment]
closing as a duplicate
