### ISSUE TITLE
Stremio Linux Uninstall

### ISSUE THREAD

**Issue by loudermp** [Stremio/stremio-features#50]
Obviously from the title I am using linux, I may not use the instructions, I recently switched from linux from windows and it has the Add/Remove but how is it uninstalled in linux?

**Comment by Ivshti** [comment]
if you install the .deb file, you can use your package manager. But we haven't made the .deb public yet (but sent it to some users), so you probably installed the .tar.gz, in which case you simply remove the "Stremio" directory and you're OK

**Comment by elmaxx** [comment]
Just want to add, in ubuntu 16.04, stremio-runtime creates folder ~/.config/stremio, if you wish to fully uninstall remove that folder as well

**Comment by meetdilip** [comment]
How to uninstall from 16.04 Ubuntu ?

**Comment by Faisal-nfl** [comment]
I remove stremio directory & even ~/.config/stremio
But when I search stremio in application, it exist there & run too
