### ISSUE TITLE
Playback speed update

### ISSUE THREAD

**Issue by Landed9771** [Stremio/stremio-features#501]
Is your feature request related to a problem? Please describe.
I encounter frustration with the current playback speed options, as they are limited to a maximum of 2.0x, and lack intermediate choices. This issue has led me to resort to the web app and utilize a browser extension for custom playback speeds. However, this workaround sacrifices the functionality of working HDR. Shortcuts for playback speed would be nice as well as a default speed feature.

Describe the solution you'd like
I would like to see an expanded range of playback speed options beyond 2.0x, allowing for more flexibility in adjusting playback speed to my preferences. Additionally, the inclusion of shortcuts for playback speed adjustments and a default speed feature would greatly enhance the user experience.

Describe alternatives you've considered
I've explored using VLC as an alternative, but unfortunately, its pitch-shifting algorithm produces a somewhat robotic sound, which is not ideal for my needs.

Additional context
None at the moment.

**Comment by TRtomasz** [comment]
Existing playback speeds are enough for existing users. This will not be implemented as it is not a simple change of just adding more options to the list. Priority is to make stremio as simple as possible not as extendable as possible.
