### ISSUE TITLE
more info in movie info

### ISSUE THREAD

**Issue by Goncaf** [Stremio/stremio-features#510]
While I'm watching the film I can't see details such as the name of the film I'm watching, total min of the film, year of release, and rating. I find it useful if I can also see this information while I'm watching, and especially the name of the film.

The problem is on the mobile, because on the PC there is a good example of what I was thinking, I think I just needed to add the IMDB rating.

https://github.com/Stremio/stremio-features/assets/145500141/09b22cac-583d-4ffe-b6f6-faa7df667d7c

![Captura de ecrã 2023-09-19 205855](https://github.com/Stremio/stremio-features/assets/145500141/e04b1bd3-62d5-4816-890b-9b59a7efdd1d)
![Screenshot_20230912_204250_Stremio](https://github.com/Stremio/stremio-features/assets/145500141/b16a3492-7079-4f9c-850c-43c1c662fb64)
![Screenshot_20230912_204351_Stremio](https://github.com/Stremio/stremio-features/assets/145500141/3760f376-51ac-473c-8a45-0c4345cc21c1)

**Comment by Androiix** [comment]
Total runtime would be great, especially for TV series as right now we can't see the runtime of each episode

**Comment by TRtomasz** [comment]
Title of the video is on the top of the player and it is visible with player ui.
