### ISSUE TITLE
Series Calendar for Android Tv

### ISSUE THREAD

**Issue by digitvadmin** [Stremio/stremio-features#511]
Could you please update the TV series calendar feature so that I can follow the TV series added to the library for the Android TV version?

**Comment by TuupacFR** [comment]
+1️⃣

**Comment by TRtomasz** [comment]
closing as duplicate https://github.com/Stremio/stremio-features/issues/430

**Comment by tundrablasen** [comment]
> closing as duplicate #430

You closed now this issue and the referred issue. But there eis no calendar integration in the android tv version. 

I’m a little bit confused
