### ISSUE TITLE
Addon developer contact info

### ISSUE THREAD

**Issue by GKid94** [Stremio/stremio-features#512]
Add developer contact info for each addon
![Screenshot_2023-09-21-08-53-12-900_com stremio one](https://github.com/Stremio/stremio-features/assets/18757054/5ad8eef4-9912-4a24-acba-498f5eedcbc8)

**Comment by TRtomasz** [comment]
we do not have contact info if they do not provide it, if they do then you will be able to get it from the manifest 
https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/api/responses/manifest.md#other-metadata
`contactEmail`

**Comment by GKid94** [comment]
> we do not have contact info if they do not provide it, if they do then you will be able to get it from the manifest https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/api/responses/manifest.md#other-metadata `contactEmail`

It's easier in the app
