### ISSUE TITLE
About and contact

### ISSUE THREAD

**Issue by GKid94** [Stremio/stremio-features#513]
Add about and contact info in the app

**Comment by TRtomasz** [comment]
There already is contact info under "help & feedback"

**Comment by GKid94** [comment]
> There already is contact info under "help & feedback"

Where?
![Screenshot_2023-09-23-18-05-02-946_com stremio one](https://github.com/Stremio/stremio-features/assets/18757054/3ed87d75-3a80-451c-b91a-9586dfa73886)
![Screenshot_2023-09-23-18-05-06-128_com stremio one](https://github.com/Stremio/stremio-features/assets/18757054/77a6e048-1402-4b6b-9abc-d11339a3c036)

**Comment by jaruba** [comment]
@GKid94 

if u find a bug, u open a ticket here: https://github.com/Stremio/stremio-bugs/issues

if u want to ask for a feature, you create a ticket in this repository, as you already did

you cannot contact the Stremio Team for any other reason, so you won't find our email in the apps if that's what you're hoping for

**Comment by GKid94** [comment]
> @GKid94
> 
> if u find a bug, u open a ticket here: https://github.com/Stremio/stremio-bugs/issues
> 
> if u want to ask for a feature, you create a ticket in this repository, as you already did
> 
> you cannot contact the Stremio Team for any other reason, so you won't find our email in the apps if that's what you're hoping for

Then add the GitHub links in the app
