### ISSUE TITLE
Watched movies greyed out in Discovery 

### ISSUE THREAD

**Issue by Sarblade** [Stremio/stremio-features#514]
**Is your feature request related to a problem? Please describe.**
When I open Discovery, Movies, filtered by Latest or Popular, I would like to see at a first glance which movies I have already watched.
This is in Discovery, NOT Library.

**Describe the solution you'd like**
Similar to what Popcorn Time did, automatically - or manually - grey out the covers of the movies I have watched. If not a grey scale, any other solution that easily makes me understand what I haven't watched.

**Comment by TRtomasz** [comment]
duplicate https://github.com/Stremio/stremio-features/issues/96

**Comment by Sarblade** [comment]
I don't want to hide it though, just a CHECK that tells me I watched it.
