### ISSUE TITLE
Stremio android only issues I've found

### ISSUE THREAD

**Issue by hotfuzz10** [Stremio/stremio-features#515]
1. Biggest issue is Default players exo/lib (slow fast forward, not smooth, laggy playback, lack fan sub support and sometimes errors) would use external player but takes you out of app. Also no forced sub options on official addon opensubtitles which is available on their site and would be a brilliant feature.

2. Horizontal ui is nice in home page but in discover and library would prefer multi grid next page layout similar to desktop, also a custom folder or genre option in library so it isn't a mess. (quick note some tv/movie thumbnail covers incorrect when in library).

3. limited amount of movies in official catalogs/categories.

Apart from that this app and addons are great and thank you to the creators and community who have contributed.

**Comment by TRtomasz** [comment]
I will close this issue as any on these three issues will not be changed or considered at this moment.
1. exoplayer and libvlc are biggest and almost only established players you can use in your app there is no alternative.
2. There are no plans to change this ui, this currently designed according to google guidelines for tv apps
3. Our official catalogs are basically based on imdb/tmdb if someone needs more content, which usually be some kind of niche kind of content like anime there are community alternatives
