### ISSUE TITLE
ARM version for MacOS

### ISSUE THREAD

**Issue by filintodelgado** [Stremio/stremio-features#519]
I have been using a mac with the new M chip and has there is not a ARM version for MacOS I had to use the x86 version.
Through this time I felt lags, frame drop and crash after using the app for hours.

So I'm requesting a ARM version as I don't see does things happen often in native x86 platform.

**Comment by TRtomasz** [comment]
It is currently not possible as our app uses framework that does not support native arm builds.

**Comment by filintodelgado** [comment]
Thanks for the clarification.
I hope those can be x86 APis can be ported to ARM as well.
