### ISSUE TITLE
[Feature Request] Autoplay Feature

### ISSUE THREAD

**Issue by tundrablasen** [Stremio/stremio-features#528]
**Is your feature request related to a problem? Please describe.**
currently you need to choose a source from your content provider. I would be great if we could get an autoplay feature. instead of manually choosing a source, just play the first available source.

**Describe the solution you'd like**
instead of manually choosing a source, just play the first source.

**Describe alternatives you've considered**
the alternative to autoplay is source select. thats the current stremio standard.

**Additional context**
no additional context

**Comment by TRtomasz** [comment]
As wrote before, there already is autplay feature called 'auto play next episode' if Stremio can find next available streams based on internall logic then it will play it. We will not make it play 'first' source cause first of all there is no way to define 'first source' second of all it might not be what everyone is expecting.
