### ISSUE TITLE
Cannot move past certain months in calendar in windows destop app

### ISSUE THREAD

**Issue by londonreturns** [Stremio/stremio-features#530]
**Is your feature request related to a problem? Please describe.**
In the desktop app, going to the calendar, we can see that this is September month which is highlighted in bold in the center just above the monthly canlender previous month can be seen in the left and next month can be seen in the right. The issue is when i try to click the previous and next month's names I cannot go before August and I cannot go after December (so just 1 month before and 3 months after the current month). Even though I can see July and January the calendar is limited to just that. 

**Describe the solution you'd like**
Potentially increase the timeline to make it longer. 

**Describe alternatives you've considered**
Or remove the months which cannot be accessed.

**Additional context**
<img width="356" alt="image" src="https://github.com/Stremio/stremio-features/assets/76239421/44ff0be1-94a2-4831-8cf9-b25edceca80c">
<img width="374" alt="image" src="https://github.com/Stremio/stremio-features/assets/76239421/09e39ca3-0765-48b1-859e-89b7a0aa0228">

**Comment by TRtomasz** [comment]
This limit will not be changed, sorry.
