### ISSUE TITLE
Auto play first result

### ISSUE THREAD

**Issue by isaacbh2** [Stremio/stremio-features#532]
**Is your feature request related to a problem? Please describe.**
Right now when clicking a movie or an episode, a list of files from installed addons appear and we need to choose one for playing.

**Describe the solution you'd like**
To aid the less tech-savvy and make playing more intuitive, add an option so when clicking a title, autoselect and play the first result without showing the result list. This is available in some Kodi addons. Assuming Torrentio + a Debrid service is set up, this should work as during Torrentio configuration we already filter non-relevant resolutions etc. Alternativley have some filtering as part of the option. This should be optional and non-default, but I think if you find you always choose the first result to play, this should make things faster.

**Describe alternatives you've considered**
Not currentley available afaik. Available in Kodi.

**Comment by jhedfors** [comment]
Yes. Having this as option would be perfect. 

Short-press title: Auto-plays first result
Long-press title: Shows the result list

**Comment by TRtomasz** [comment]
This is simply not possible to be done good.
