### ISSUE TITLE
Separate option for selecting External Player for Trailers Only (Stremio Android TV)

### ISSUE THREAD

**Issue by nightknight111** [Stremio/stremio-features#535]
Experience with Trailers was never smooth for me (mainly being screen flickering). However this is not a complain but rather a feature request I would love to see be implemented regardless of the bug.

I used the default option for playback to use external player which would also normally open the installed youtube app when you play trailers (this was better). However the problem is that when you back out of the trailer you are still in the youtube app. How I solved this problem was using SmartTubeNext (A Modded Youtube App) in which, when you back out of the trailer it goes directly back to where you left of on stremio. This makes the trailers experience for me atleast go as smooth as it could be.

What I would like to see is a separate option to select external player but for trailers only as I would still like to use stremio's own exoplayer.

**Comment by TRtomasz** [comment]
Such feature will not be implemented cause it would bloat the app and we want to keep it simple.
