### ISSUE TITLE
Just Player as a native player option like libvlc on (Android TV App)

### ISSUE THREAD

**Issue by nightknight111** [Stremio/stremio-features#536]
I was surprised how well Just Player works in my case compared to exoplayer as it based on exoplayer I believe. But the files that would buffer alot or not work at all much of the time, work perfectly with Just Player. For the longest time i thought it might be my connection or my android tv that was the problem but with JustPlayer I can play remuxes without any issues at all.

The only thing that is a bummer is that the binge watching experience hurts a bit as using an external player stops me from using amazing features that stremio has implemented over time such as next episode pop up, Episode/Movie Title instead of the filename such as blabla.mkv once inside the player. As well as selecting episodes directly from the player.

I'm not an expert at all so idk how it would work but It would be amazing if just player could be implemented natively like libvlc has been as it has been a way better experience with Just Player. It's not the focal point of the subject i want to put out but with libvlc i had issues such as progress not saving at all which i have seen other people report as well as app crashes. 

Also I do use realdebrid if you were wondering since I mentioned playback concerns.

**Comment by jan-kleks** [comment]
Just Player sounds really interesting! Maybe it could even be a default choice... I also do wonder how mpv would fare as an optional player. On my weaker computers it can play smoothly the movies that VLC cannot.

**Comment by jan-kleks** [comment]
It looks like there are more users who are enjoying using Just Player: https://github.com/Stremio/stremio-core/issues/547

**Comment by TRtomasz** [comment]
Justplayer isnt a library.

**Comment by nightknight111** [comment]
so isnt vlc

**Comment by Masamune3210** [comment]
.....but libvlc is
