### ISSUE TITLE
Are you still watching? - Streaming auto pause

### ISSUE THREAD

**Issue by aleksandarbst** [Stremio/stremio-features#537]
**Is your feature request related to a problem? Please describe.**
Stremio (app) will keep my macbook from going to sleep. 

**Describe the solution you'd like**
The same "Are you still watching?" automatic pause, after 2 or 3 episodes, that will pause streaming to save on data, energy, and your position in a series if you doze off

**Describe alternatives you've considered**
I think on a thread somewhere for this feature, someone left a comment to "just use something else to turn off the device on a timer". The latest MacOS update redesigned the settings menu, and there is no longer a setting to schedule the device to switch off at a certain time. The MacOS app Quitter, which you can use to set apps to quit on a timer, doesn't allow for Stremio to be added as an app for some reason. I can't think of another way to do this besides using the terminal which isn't very intuitive. A native feature in Stremio would be very welcome!

**Additional context**
Netflix description of the "Are you still watching?" feature is [here ](https://help.netflix.com/en/node/114059#:~:text=Netflix%20asks%2C%20%22Are%20you%20still,90%20minutes%20of%20uninterrupted%20watching) - key takeaways are to auto pause after 3 uninterrupted episodes of a TV show, or 90 minutes uninterrupted watching

**Comment by TRtomasz** [comment]
Turn off autoplay next episode feature in the settings and you will have the same effect
