### ISSUE TITLE
Include more information for subtitles on Android TV

### ISSUE THREAD

**Issue by nt294** [Stremio/stremio-features#539]
I feel more information about subtitle tracks need to be provided. At the moment, it can be a nightmare trying to find the right track, for instance when watching extended edition movies, or series with a "previously on..." segment, etc. 

For reference, the photo below shows a bunch of available subtitle tracks with nothing to differentiate them, potentially leading to a lot of trial and error in finding one that fits, or tediously adjusting the delay to compensate. 

![IMG_20231006_204509](https://github.com/Stremio/stremio-features/assets/79095109/1e8ad596-9b30-43b3-828c-336f396749a0)

**Comment by TRtomasz** [comment]
no need to open the same issue again - https://github.com/Stremio/stremio-features/issues/374
