### ISSUE TITLE
Display a message instead of {} when using magnet link

### ISSUE THREAD

**Issue by treebeard** [Stremio/stremio-features#54]
When the stremio app isn't able to find the episode/movie name in a magnet link, it displays {} in the popup box with the play options, I think it would be a little nicer to display a message like "No Title Found", and it doesn't seem like too difficult of a change.

**Comment by Ivshti** [comment]
Yep, i agree
We'll fix it for our next release, but all of our focus is on the 4.0 release at the moment, which is scheduled for 2-3 months from now

We'll probably push an intermediate update fixing this issue, but i'm not sure
