### ISSUE TITLE
Subtitles background android 13

### ISSUE THREAD

**Issue by dionysaKYS** [Stremio/stremio-features#542]
Recently I realised that with the new update of Stremio on my android 13 phone (Samsung galaxy s22)you can't change you background colour,no matter what(like you used to in the older versions of it)

Please find a solution or maybe anything that could bring back the entire player setting on android version 1.6.7 of Stremio 

![Screenshot_20231009_161248_Stremio](https://github.com/Stremio/stremio-features/assets/147419917/38ad00a8-8920-44e8-900b-24d24f15b9e6)

**Comment by TRtomasz** [comment]
Please update your issue with the template otherwise we will have to close it

**Comment by TRtomasz** [comment]
there never was such option, in the android app to change background color, and there is still option to enable black background in the subtitles menu in the player.

**Comment by dionysaKYS** [comment]
> there never was such option, in the android app to change background color, and there is still option to enable black background in the subtitles menu in the player.

In the oldest versions it was available(I literally used it before the big rediign update on the same device)I know that you can actually change it from the player settings,but guess what...there is no player settings on my new updated version of stremio, that's the main reason I write about this issue
