### ISSUE TITLE
Video Player Navigation Highlight 

### ISSUE THREAD

**Issue by quincyp** [Stremio/stremio-features#543]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to navigate the video player from a keyboard/remote. There is a veryyyy faint highlight indicating where you are. This often leads to misclicks or potentially exiting the video.

**Describe the solution you'd like**
A clearer highlight of where you are in the video player, most likely on brand with Stremio colors.

**Describe alternatives you've considered**
Increasing contrast as there is a faint highlight you can see sometimes (depending on the current playing content background)

**Additional context**
This is likely an issue you do not notice if you are on a touch screen interface only keyboard/remote/gamepad. Also I have a device with an older version and this is an issue on the newest version

**Comment by Vikssa** [comment]
to not open a new topic, I was hoping for a keybind for speed of playback on the pc version
