### ISSUE TITLE
Movie begins before display can show image with frame rate matching on

### ISSUE THREAD

**Issue by jan-kleks** [Stremio/stremio-features#547]
**Is your feature request related to a problem? Please describe.**
Before my display can switch from 60 hz to 24 hz (to match the frame rate), the movie starts playing and I miss a few seconds seeing just a black screen.

**Describe the solution you'd like**
Either some way of fully synchronizing the display's refresh rate switching with the playback (automatic or manual, e.g. specifying the delay in seconds) or a setting to start the movie "paused".

**Describe alternatives you've considered**
A workaround that I am currently using is to press the pause button on the remote as soon as the screen goes black. But one has to remember about it all the time...

**Additional context**
Android TV 11, Nvidia SHIELD TV connected to a projector

**Comment by TRtomasz** [comment]
Cant reproduce the issue, on my tv switch happens before video starts playing. Perhaps an issue with a projector to not switch it fast enough
