### ISSUE TITLE
[Feature Request] AniList, Kitsu and MAL Support 

### ISSUE THREAD

**Issue by icpryde** [Stremio/stremio-features#550]
We have Trakt support which is great but Trakt is kinda terrible for Anime as it gets the episode lists wrong and also just sometimes doesn't even have certain anime which is why it would be amazing if we could have support for AniList, Kitsu and MAL for us anime fans to keep our watchlists and episode tracking marked.

Your add-on is amazing thank you for all your hard work.

**Comment by TRtomasz** [comment]
Stremio will not integreate every tracking project, trakt was integrated as it is the biggest video tracking platform.
