### ISSUE TITLE
[Feature Request] Organize Main Page and Change Order of Catalogs 

### ISSUE THREAD

**Issue by icpryde** [Stremio/stremio-features#551]
I really would love the ability to turn on/off certain catalogs and also reorganize the order they appear as well, example is with Trakt. I just want it to show watchlist and collection but it also shows history, recommendations and a few others and I would like to keep it minimal.

Thank you for all your hard work.

**Comment by tundrablasen** [comment]
Reorganising of Home Screen and the widget lists is really needed

**Comment by bennodxb** [comment]
This seems like its an essential feature. I spent ages trying to work out why I couldnt find the option.

**Comment by mophawka** [comment]
100% +1

**Comment by TuupacFR** [comment]
+1, let us re order the homepage !

**Comment by Zizou3000** [comment]
We really need this...

**Comment by lothar-cell** [comment]
+1

**Comment by rawIce** [comment]
+1 

Really needed, including the option to hide or at least move the default Cinemata catalogs
There are also several threads and comments on Reddit regarding this functionality.

**Comment by lothar-cell** [comment]
Here's an unofficial workaround, until they come to their senses finally: https://addon-manager.dontwanttos.top

**Comment by bennodxb** [comment]
Why did you delete the previous reply? You should incorporate this functionality into your app, not try to censor it. It makes stremio so much better.

**Comment by lothar-cell** [comment]
https://github.com/Stremio/stremio-features/issues/562#issuecomment-1969170326

**Comment by TRtomasz** [comment]
closing as a duplicate

**Comment by lothar-cell** [comment]
More will come:D

**Comment by mophawka** [comment]
> closing as a duplicate

odd. since the other is a duplicate of this. not the other way around.
