### ISSUE TITLE
Stremio App - Movies with Parts

### ISSUE THREAD

**Issue by permedd** [Stremio/stremio-features#553]
**Movies with Parts:**
When we search a movies name that has more than 1 part, it should be similar to how the series page is, or maybe can make it different and it only shows with the cover part 1 / 2 / 3 and so on, with the dates its been created.
For example, clicking Harry Potter/Saw/Lord of the rings/Avengers etc has more than 1 part, when we search for any of them there should be one with the cover and inside that there should be the part 1/2/3 etc.

**Why?**
Because its so much faster and easier to find the movies part instead of going back and forward to check the correct part of the movie and wouldn't have to go on google to check the order of the movie parts.

**Screenshots:**
As you can see when i search harry potter its not in order, those are the years of when they were released

![image](https://github.com/Stremio/stremio-features/assets/37475765/4b38926a-370f-4f5e-8f93-925fa549d646)

**Comment by TRtomasz** [comment]
this is not possible, we do not have such metadata.
