### ISSUE TITLE
Ai-powered auto-subtitles 

### ISSUE THREAD

**Issue by ronrozenberg** [Stremio/stremio-features#555]
**Is your feature request related to a problem? Please describe.**
A lot of shows and movies have bad subtitles, whether they are out of sync or generally messed up. An easy auto transcribing and translating option would be extremely convinient with non native speakers.

**Describe the solution you'd like**
A little option in the subtitles menu that lets you make subtitles for the playing content, with option of translation into another language , and potentially ai dubbing.

**Describe alternatives you've considered**
I tried 3rd party solutions but they are often expensive or inaccurate. A built in solution would be very convenient.

**Additional context**
None

**Comment by TRtomasz** [comment]
There are no free solutions for this that would allow usage required by stremio so it is not possible to be implemented.

**Comment by ronrozenberg** [comment]
I recently found a solution for linux called "Live Captions" and it works pretty well. It works on a local model and is completely free. It would be really neat if it can incorporated into stremio.
