### ISSUE TITLE
Vimu media player compatibility

### ISSUE THREAD

**Issue by Blueybarnes** [Stremio/stremio-features#556]
I have experimented with various media players on Fire stick 4K and came to the conclusion that my preferred player is Vimu media player. It works great but does not remember film/show progress if viewing is interrupted. When I contacted the developer they said it can only do this if the streaming app requests Vimu to do this over Intents API. They then sent me a link https://www.vimu.tv/player-api
I contacted Stremio and they directed me here. Is this possible?
Thanks, Mike.

**Comment by TRtomasz** [comment]
this player is too small and uknown for us to be benefitial to put that much effort into implementing this
