### ISSUE TITLE
Anime: Dubbed | English Subtitle - Dropdown Menu

### ISSUE THREAD

**Issue by permedd** [Stremio/stremio-features#557]
**Anime: Dubbed | English Subtitle - Dropdown Menu**
Where it says the type of addons you can watch the anime one, maybe next to it you can have another dropped down menu and have **Dubbed** (English) version & English **Subtitle**, so we can choose which version we want to watch it.

**Screenshot**:
Screenshot shows where to put the drop down menu and what the drop down menu should have.
![image](https://github.com/Stremio/stremio-features/assets/37475765/ffd7708c-aac0-43b9-9ff5-7a134ad0d871)

**Comment by TRtomasz** [comment]
this is not possible, we have no such information.
