### ISSUE TITLE
chromecast for your android version

### ISSUE THREAD

**Issue by dumarjo** [Stremio/stremio-features#56]
Hi,

Good tool you alpha version of android app. I wonder if you plan adding the cast option in it ?

regards

**Comment by Ivshti** [comment]
we are planning to add chromecast to the android app in january

**Comment by MarcosPiresDev** [comment]
I am Android developer, I wonder if it is possible to contribute with the android project of the stremio..

**Comment by TRtomasz** [comment]
Already added.
