### ISSUE TITLE
Update Stremio from within app on Firestick

### ISSUE THREAD

**Issue by RayzaEFC** [Stremio/stremio-features#563]
Can a feature be added in a future update so Stremio can be updated from within the app on Firestick. There are some apps that are on Google Play that can be updated from within the app on Firestick but they aren't available in Amazon app store. So 2 of these apps I know of are Tivimate and Smarttube (< not on Google Play). They download an update via the app and delete the installation file in the cache (< I think). Anyway would be great if this feature could be added so it is easier updating Stremio on Firestick.

**Comment by TRtomasz** [comment]
You have to update app on firestick manually we do not plan to add such feature for the tv app.
