### ISSUE TITLE
Improve visual cue in new UI

### ISSUE THREAD

**Issue by fanttazio** [Stremio/stremio-features#565]
Hi team,
This is not a bug but a UI enhancement request. I know the app is not officially supported for Amazon devices, but I've sideloaded the app on Amazon TV stick and after the UI refresh and new look, app navigation is not great because the background colour of selected menu item so transparent that it's very difficult to know what you've selected and where you are on the app, especially when there's a daylight. Would it be possible to make an adjustment and make the background a bit more visible?
![photo_2023-10-21 13 08 00](https://github.com/Stremio/stremio-features/assets/4039265/34e28f78-877e-47ab-9f86-19fe579232b9)
![photo_2023-10-21 13 08 09](https://github.com/Stremio/stremio-features/assets/4039265/e190faf0-b466-45f8-86c7-587ef2464c43)

**Comment by jaruba** [comment]
this is not an issue with the app, u need to increase the contrast in ur TV settings..

**Comment by fanttazio** [comment]
I understand there's no issue with the app. my feeling is that the UI could improve. either by making the background darker so the selected item pops out or make the selected item's background brighter. my screen contrast is at 70 right now.

**Comment by jaruba** [comment]
the background is almost black already, there is no issue with the colors, there are issues with ur tv settings or the quality of ur screen
