### ISSUE TITLE
Seek thumbnail preview

### ISSUE THREAD

**Issue by jan-kleks** [Stremio/stremio-features#569]
**Describe the solution you'd like**
Show a changing thumbnail when seeking through a video to make searching for a particular movie fragment easier.

**Additional context**
You can see an example of such a feature here: https://github.com/rubensousa/PreviewSeekBar

**Comment by TRtomasz** [comment]
this is not possible as most of the time we do not have full video downloaded.

**Comment by Gadetron** [comment]
what about for real debrid or similar use cases?

**Comment by IsaiahBideshi** [comment]
What about if the video is downloaded then show the preview and if it's not, then leave it black?

**Comment by VictorVow** [comment]
It should at least be possible to show for the parts of the video that have already been downloaded, to allow easier rewinding as well as skipping a short time ahead.

**Comment by IsaiahBideshi** [comment]
Are the admins even getting these comments since its closed? Is there a way to bring this back to their attention?

**Comment by TehBrian** [comment]
@TRtomasz, this issue should be closed as "Not Planned" rather than as "Completed".
