### ISSUE TITLE
Persisting settings by User.

### ISSUE THREAD

**Issue by tfouto** [Stremio/stremio-features#572]
To ensure a more seamless user experience, it would be beneficial to have settings persist according to individual logins, or at least by device. For example, if two people share a device but use different logins, the settings should be retained after one user logs out and the other logs in. This includes preferences such as subtitle language. With such a feature, settings would not reset every time a user logs out, preventing the need for constant readjustment. This is particularly important for non-English speakers.

This feature would be especially useful for Android TV

**Comment by TRtomasz** [comment]
We do not plan to add this, as it would requires much more storage on our side which would generate more costs.
