### ISSUE TITLE
[FEATURE REQUEST] Streaming server url permanent

### ISSUE THREAD

**Issue by alanmilinovic** [Stremio/stremio-features#573]
I know there is an option to overwrite Streaming server url in Settings, and it will be stored in browser cookies. Is it possible to have an option to specify default Streaming server url? For example in server-settings.json file. That would be amazing.

?streamingServer= query parameter would also be nice as an alternative solution but it is only working for app.strem.io/shell-v4.4 and staging.strem.io but in my case I am hosting stremio-web on my server and query parameter is not working.

**Comment by TRtomasz** [comment]
we are working on adding query parameter for stremio-web
https://github.com/Stremio/stremio-web/issues/295

**Comment by alanmilinovic** [comment]
Sounds good. Thanks for your reply.

**Comment by TRtomasz** [comment]
this is implemented now
