### ISSUE TITLE
Have "Details" context menu option actually show details instead of duplicate click, at least on Android TV version

### ISSUE THREAD

**Issue by who-is-matt** [Stremio/stremio-features#578]
**Is your feature request related to a problem? Please describe.**
In the Android TV version of Stremio, the "Details" option in the context menu duplicates clicking on the item.  So for a movie or an episode, this takes you to the source list, and for a series it takes you to the episode list.

**Describe the solution you'd like**
On the Android TV version of Stremio, the title and/or description of items may be too long to fit in the allocated space.  Having the Details context menu option open a "Details" page that provides more room for this information, at least on the Android TV version, would be useful.  

A Details page  that is accessed by the Details context menu option could be useful (on all versions of Stremio) for providing additional metadata on the item that is not normally shown, such as age rating, director, country of origin, etc. that are available through the IMDb, TheTVDB, and TheMovieDB APIs but that aren't otherwise available in Stremio.

**Describe alternatives you've considered**
If the item title and description would autoscroll if they can't fit the allocated space, that would help some, though not everyone likes the marquee effect.  

**Additional context**
Notice in the screenshot below that neither the full title or description are displayed.  Selecting "Details" from the context menu as shown could open a details screen providing more room to display this information, as well as other information about the item that is available through the APIs accessed by Cinemeta.
![Stremio_20231110_025031](https://github.com/Stremio/stremio-features/assets/4270243/a6d6552a-57d7-4e4b-b6c1-2c594b318948)

**Comment by TRtomasz** [comment]
cant reproduce anymore, click on details goes to the episodes list.
