### ISSUE TITLE
iOS App Login with Facebook

### ISSUE THREAD

**Issue by serradino** [Stremio/stremio-features#58]
As a User I'd like to log-in on the iOS App using Facebook log-in.

Right now I got a message: "Account created through FB login" and even if I manually changed my password by resetting I can't log in on iOS app.

Thanks and keep it great as it is!

**Comment by Ivshti** [comment]
thanks for the feedback, we are planning to release a brand new app in Feb for iOS which contains that feature

**Comment by serradino** [comment]
Awesome ! Thanks :)
