### ISSUE TITLE
Language fix

### ISSUE THREAD

**Issue by GKid94** [Stremio/stremio-features#580]
Add the original language movie name on the page like on IMDb and Wikipedia
![Screenshot 2023-11-13 035133](https://github.com/Stremio/stremio-features/assets/18757054/40277622-e8ba-43f1-b48f-aa9784a7707d)
![Screenshot 2023-11-13 035316](https://github.com/Stremio/stremio-features/assets/18757054/16024cd7-89f8-4d5f-b71d-dbbf0b2a2ab0)

**Comment by TRtomasz** [comment]
We do not store data about original name of movies this is not possible.
