### ISSUE TITLE
Addon auto update option

### ISSUE THREAD

**Issue by GKid94** [Stremio/stremio-features#581]
Add a auto update addons option
![Screenshot 2023-11-13 035316](https://github.com/Stremio/stremio-features/assets/18757054/b9076acf-b86c-46e9-802e-c4c0e69e5a07)
![Screenshot 2023-11-13 040400](https://github.com/Stremio/stremio-features/assets/18757054/b53073e9-49c2-472b-9e7d-c758d15554d9)

**Comment by TRtomasz** [comment]
This is not possible for addons that are configured due to security reasons, addons that does not have configuration are getting updated automatically.
