### ISSUE TITLE
Stremio app desktop fullscreen UI TV

### ISSUE THREAD

**Issue by Sanctur2** [Stremio/stremio-features#582]
**Is your feature request related to an issue? Please describe.
The feature is related to a UI and console controls

**Describe the solution you want
Add an option to the desktop app so that the fullscreen has the appearance of the TV stream, as many people use their PC on their TV and the desktop app doesn't look good on a TV, they could also further improve the console control in the app

**Describe the alternatives you considered
I considered something similar to Steam Big Picture, being added by clicking a button and going full screen with the UI of the Stremio TV app

**Additional context
I'm using it on Steam and I would like to use it on the TV while using the PC, as I have a smoothvideo application

**Comment by TRtomasz** [comment]
Desktop app is for desktop, it will not have TV UI. We have android TV app for desktop or stremio web.
