### ISSUE TITLE
[FEATURE REQUEST] Folder Playlist

### ISSUE THREAD

**Issue by Avaritia06** [Stremio/stremio-features#583]
**Is your feature request related to a problem? Please describe.**
It is more of a feature request that you could create your own folder of movies/series

**Describe the solution you'd like**
to be able to create a folder playlist

**Describe alternatives you've considered**
a way to organize your library maybe adding a hide button for watched movies/series or to be able to categorized your library to your own liking

**Comment by TRtomasz** [comment]
closing this one as a duplicate of many previous requests for folders in the library
