### ISSUE TITLE
Using you own configured player when enabling the "launch player in a separate window"

### ISSUE THREAD

**Issue by Avaritia06** [Stremio/stremio-features#584]
**Is your feature request related to a problem? Please describe.**
Using your configured MPV rather than the STREMIO native MPV when enabling the "launch player in a separate window", a little bit annoying to always click the three dots and click watch to mpv that will use your own configure player every time you will another episode.

**Describe the solution you'd like**
Be able to select your own player or  adding a sub-option when enable the "launch player in a separate window" same feature to Auto Play option which will open another option to choose when enabling it.

**Comment by TRtomasz** [comment]
This option is only for MPV as it uses libmpv internal mechanism to open player in the separate window, you can cast to other players like vlc from other menus.
