### ISSUE TITLE
Choose tab on startup

### ISSUE THREAD

**Issue by isaacbh2** [Stremio/stremio-features#585]
**Is your feature request related to a problem? Please describe.**
Currently Stremio always opens on the Home tab.

**Describe the solution you'd like**
A setting to choose which tab will open on startup: Home/Discover/Library/Calendar.

**Describe alternatives you've considered**
No other way except manually clicking on a tab.

**Comment by TRtomasz** [comment]
This will not be implemented. We do not see this as needed.
