### ISSUE TITLE
Add volume control/booster to the android TV version of Stremio

### ISSUE THREAD

**Issue by stoneb26** [Stremio/stremio-features#586]
**Is your feature request related to a problem? Please describe.**
I have a problem using the android TV version of stremio and the issue is related to volume. On every movie i watch, the volume is very low and soft, almost muffled so i have to turn up the volume on my TV to compensate for this. The odd thing is that i never have to turn up volume on TV when i use other mediaplayer apps so it seems the volume output is set unusually low in the stremio app for android TV and after contacting support, i was told that the output volume of stremio is tied to the mediabox or TV so there´s currently no way to boost the volume from the app itself like we can with the PC or Mac version of stremio.
**Describe the solution you'd like**
Add a volume control/booster just like the PC/Mac apps have which will let the user control the output of audio and adjust it to ones needs. A simple slider in the audio settings of the app that can be controlled either via remote control using arrow keys up/down or possibly also via mouse.

**Comment by stoneb26** [comment]
Have to say i´m a bit surprised this feature hasn´t been added to the android TV version yet given how many reports there are from other users with exact same problem. A quick google search gave me these reports from reddit: [https://www.google.com/search?q=stremio+low+volume+site:www.reddit.com&client=firefox-b-d&sca_esv=582945116&sxsrf=AM9HkKmgHL9kJt5Ii1Ux4nm4JtxePZO6qg:1700144742577&sa=X&ved=2ahUKEwipqMrb3MiCAxU5IBAIHZ_1CE4QrQIoBHoECBsQBQ&biw=1747&bih=1195&dpr=1.5#ip=1](url)

**Comment by TRtomasz** [comment]
if there is a low volume you either are trying to play a video with audio codecs that your device can't handle, or you switched tunneled playback setting and now your device pass the sound in the way it can't be decoded properly. On TVs you can boost volume using your TV speakers or external speakers.

**Comment by stoneb26** [comment]
Sorry to see you closed this request and i can only repeat what i described earlier. On every movie i played using stremio for android TV, the volume is very low and i tried at least 50 movies with different type of audio codecs and all give the same result. I have a high end home cinema system that can decode everything so that´s not the issue here. Not only that, every other app i run on my android media player like Plex, IPTV etc. outouts volume normally and i never have to compensate by boosting using those apps. So this is def a stremio issue with the android TV version specifically and yes, of course i can boost my TV volume by 100% or even 200% but we should not have to do this which is my point and why i created the request.

Did you even bother reading the multiple reports by other users of the exact same issue i mentioned?

I did find an alternative solution which is using an external player like VLC and then boost the volume by 200% in the equalizer settings of VLC which gives me about the same volume output as with all my other media player apps on the android system. But unfortunately, VLC lacks the ability to position subtitles up/down like i can with Exoplayer.

**Comment by TRtomasz** [comment]
Try enabling tunneled playback in the settings.

**Comment by stoneb26** [comment]
Yeah i already tried enabling tunneled playback but made no difference..
