### ISSUE TITLE
Add "See All" button to movie lists on Android version  (The Windows version has it)

### ISSUE THREAD

**Issue by soliverc** [Stremio/stremio-features#589]
**Is your feature request related to a problem? Please describe.**

I would like to view movie lists in a grid rather than having to scroll sideways forever.

On Windows, in the Home section with the movie lists, we have a "See All" button that allows us to do this.

![image](https://github.com/Stremio/stremio-features/assets/47222261/e329d170-f5c0-4a26-acdf-ae474773f6e6)

It opens up the list of movies in a nice and easy to view grid.

However on Android, both mobile and android TV, this button is missing.

This means we have have to scroll sideways forever to see the list of movies. This is not user friendly (in my opinion) if you don't know what to watch and are looking for something to catch your eye.

**Describe the solution you'd like**

Add the "See All" button from Windows to the Android versions, so we can view movies in a grid and scroll up and down.

**Comment by stoneb26** [comment]
I second this request

**Comment by garreth64** [comment]
Thirsted. This would be a big improvement.

**Comment by XAlienAssassin** [comment]
Fourth this request. It would be really easy to see multiple movies at once

**Comment by bennodxb** [comment]
Please add the button

**Comment by 0o120** [comment]
Please add

**Comment by miyazonoyuzuki** [comment]
Please

**Comment by miguelferreiraweb** [comment]
+1

**Comment by riotinprogress** [comment]
+1

Scrolling left to right forever seems counter-intuitive, especially on large-screen TVs where a grid option makes more sense, allowing you a wider view of the catalogs you're viewing.
