### ISSUE TITLE
Firestick - Calendar

### ISSUE THREAD

**Issue by permedd** [Stremio/stremio-features#596]
**Calendar on Firestick** 

**Suggestion**
Can we have a calendar to see when the Series/Shows/Animes are released on firestick.

**Idea from**
This image is from Stremio on windows, but on firestick there is no calendar button, only has library button, on firestick we cannot track the series/shows/anime and don't know when they are released.
![image](https://github.com/Stremio/stremio-features/assets/37475765/835da4da-304c-41f6-84af-d7fdea06810f)

**Comment by arrow00009** [comment]
Also new released shows on top like in android app

**Comment by permedd** [comment]
Same goes for IOS, there is no Calendar on IOS either

**Comment by TRtomasz** [comment]
Closing as duplicate of other issues requesting calendar in the android tv app
