### ISSUE TITLE
Change Layout Library - Firestick

### ISSUE THREAD

**Issue by permedd** [Stremio/stremio-features#597]
**Change layout for Library on Firestick**

**Suggestion**
Can we have the same layout or design as the Windows on firestick, right now we have a dropdown on Firestick which is:
- By Last Watched
- By Name
- By Times Watched

On windows we have a Dropdown menu of Movie/Series, Recent, a-z, z-a, and __Watched__ Can we have the same thing what we have on windows on firestick, can we also have 'All' on the dropdown of movie/series.
![image](https://github.com/Stremio/stremio-features/assets/37475765/9d790abc-a347-494c-a365-5f28c3cbee33)

**Comment by TRtomasz** [comment]
this vis not possible, two different platforms, with totally  different controll devices.
