### ISSUE TITLE
VERTICAL OFFSET

### ISSUE THREAD

**Issue by garethk79** [Stremio/stremio-features#601]
Hi guys. Firstly I want to thank you for simplifying my home theatre experience almost to the stage that it should be.....

However,

The subtitle position MUST be adjustable from either top of the screen or bottom of the screen. It's a very basic requirement. I've tried playing around with the vertical offset settings but as far as I can tell they don't actually do anything.

Please chuck in the option, and complete the perfect package!!

Thanks.

**Comment by TRtomasz** [comment]
Please use feature request template to include all  details about the feature request most important one is the platform.

**Comment by garethk79** [comment]
Actually in this instance the platform is the least important one because if provisions were made to adjust the height of the subtitles and move them to the top of the screen, then one would expect it should be rolled out on all platforms.

Sent from Yahoo Mail on Android 
 
  On Wed, 29 Nov 2023 at 6:55 pm, ***@***.***> wrote:   


Please use feature request template to include all details about the feature request most important one is the platform.
