### ISSUE TITLE
[Feature Request] Multiple Feature Requests, To make the app experience much more smoother

### ISSUE THREAD

**Issue by ankitgurua** [Stremio/stremio-features#602]
•If i put something in my library. Then I'd wish to have it autodownloaded.

•Also if i start watching a series. It's next few episodes should also be autodownloaded so it's ready to stream when an episode ends. Makes the series binging experience much much smoother

•Sonarr and radarr have options to know our preferred torrents, like if i wanna have 1080p or 4k torrent, minimum seeders it should have, preferred language, preferred size. After knowing all my preferences it doesn't ask the same question everytime. I click on a series and it gets downloaded in my preferred settings, i wish something similar is available on stremio. So you can use these settings to autodownload the movies and series i talked earlier. And can help nuking the torrent selection screen.

•Add an auto subtitle generator plugin. That instead of generating subtitles from scratch, match the already existing subtitles to the accurate timing because rarely my subtitles are on point. I always have to mess around with timing. There's no point of having 25 + subtitle files available when none of them works. This will reduce the clutter and provide one solid working subtitle experience. There are alot of AI apps that can do this. Maybe use their api.

• Provide Indicators that a media supports Dolby audio, Dolby vision, HDR. Like it's shown in Amazon Prime app

Love this app, probably the best app on my computer. Trying to help make it even better. So that clutter is reduced. i.e. the torrent selection screen can be nuked, so is the hundreds of subtitles in the same language. And a download button.

**Comment by permedd** [comment]
**suggestion: **
Also if i start watching a series. It's next few episodes should also be autodownloaded so it's ready to stream when an episode ends. Makes the series binging experience much much smoother

**answer**
I like this, really helpful for series/animes to not freeze while watching them, would like this to be on stremio.


**Suggestion**
If i put something in my library. Then I'd wish to have it autodownloaded.

**answer**
I like this aswell auto download, but I think it means you’ll have to have a big memory on your pc/firestick or something, 

**answer for both**
I think if these two does gets added I’m guessing it might even be possible to do it offline, but I’m sure it won’t, but will be great if it did.
