### ISSUE TITLE
Library - Movie, Series/TvShow, Anime

### ISSUE THREAD

**Issue by permedd** [Stremio/stremio-features#603]
**Library - Movie, Series/TvShow, __Anime__**

**Seperate Series/TvShow with Anime**
I don’t know how it is on other platform but on firestick Anime and Series are on the same category, can it be possible to seperate them so they are on different category, as how it is seperate to the movies.

- Movies
- Series/Tv Show
- Anime

**Comment by TRtomasz** [comment]
anime are series so it will not be changed
