### ISSUE TITLE
Samsung TV subtitle issue

### ISSUE THREAD

**Issue by Poster123456** [Stremio/stremio-features#606]
When prompt appears that subtitles failed to load.  The play bar and all other buttons don't dissapear.

**Comment by bvidovic1** [comment]
Same

Subtitles never load regardless if they are embedded or from opensubtitles.

**Comment by dr0vur** [comment]
+1 on this

**Comment by seddik88** [comment]
+1

**Comment by TRtomasz** [comment]
closing as fixed for now, if it happens again please let us know
