### ISSUE TITLE
VLC In Stremio

### ISSUE THREAD

**Issue by Cmai7385** [Stremio/stremio-features#609]
VLC Player and TV Series "Continue Watching" Segment.

For Devs.    Is there any way to resolve the issue in the title when using VLC player, as opposed to the built in player.

If I use VLC, the series is not maintained or is visoble, any longer in the " Continue watching" Segment when I return to the series and wish to continue watching  any time after closing down the app.

One of the reasons I use VLC is because of the low sound quality using the built in player.    This is evident on every stream available on series or movies.

Thank you

**Comment by Cmai7385** [comment]
App versions Android mobile 1.6.8and Andoid TV. 1.6.4

**Comment by Cmai7385** [comment]
Why have you closed this, before receiving the info you asked me for

**Comment by TRtomasz** [comment]
To keep order in this repository. 
VLC has a bug when it does not return properly exit timestamp if you use stremio option of "Always play in the external player" this is outside of our controll to fix it. If you manually pick VLC as an external player each time you try to play something then we will be able to keep track of this.

**Comment by Cmai7385** [comment]
Hi

I always pick external player manually as opposed to have it preselected in settings as " always use external player".

But I do not use it all the time.   Would you like me to start using it, say for a week.   And if I do, how will you monitor it?   Would you need my details?

**Comment by TRtomasz** [comment]
@Cmai7385 if you will use it with "Always use external player" for sure it will not work, VLC has a scheme to return results to other apps, and we follow it in both mobile and tv app. But sometimes VLC returns empty object and we cant do anything about it.

**Comment by Cmai7385** [comment]
Maybe I misunderstood your previous message.  I thought you said if I manually select external player, you could monitor it.   I always select manually.   That is why I asked you if you wanted to monitor my use of it for the next week.

Please clarify.  Thank you for trying to help

**Comment by TRtomasz** [comment]
Yes, if each time you click in stremio option to play in external player and then manually select VLC it should be working fine. But stil, if VLC returns empty response there is nothing we can do about this.

**Comment by TRtomasz** [comment]
My only idea regarding low volume could be caused by the fact you are trying to play a stream that has multiple audio channels (like 5.1 7.1 atmos etc) but your system does not support it. You could try to switch in the mobile app: Audio passthrough option
in the tv app: Tunneled playback option

**Comment by Cmai7385** [comment]
@TRtomasz 

Ok.   That is very helpful information.

I have a Samsung Q60T soundbar.  Which plays 5.1 as far as I know. 
But I will check our your tips when I stream tomorrow.

Thank you again for all your help.

**Comment by Cmai7385** [comment]
@TRtomasz 
Hello.

I thought I would give you some feedback on sounds and volume.

I enabled passthrough and 5.1 and 7.1 channels play fine.  So, thank you for the advice.
Just some information for you as feedback.   
Playing a DV stream does not show on my AFR when using built in player, nor VLC.
But works fine if I manually select just player.   No  need for reply.  Just some information for you.

Regards
