### ISSUE TITLE
Stremio doesn't recognize MX Player Pro as MX Player

### ISSUE THREAD

**Issue by victorgveloso** [Stremio/stremio-features#610]
**Is your feature request related to a problem? Please describe.**
When using stremio web on Android, I can choose to play content in external players. MX player is on the list but only the free version.

Currently, if I choose "MX Player" the play store opens even though I have MX Player Pro installed.

**Describe the solution you'd like**
MX Player Pro should be an option or the "MX Player" option should check for the pro version installed

**Describe alternatives you've considered**
Meanwhile I'm using the "allow choosing" option and selecting MX Player Pro from the OS context menu. However, subtitle passthrough doesn't work this way.

**Additional context**

**Comment by TRtomasz** [comment]
This is not related to stremio, proposed players comes from the system. Perhaps you have to remove free version.
