### ISSUE TITLE
Please Create an "cache Size" or "Buffer Size" option in Android TV app

### ISSUE THREAD

**Issue by luizthiagor** [Stremio/stremio-features#612]
Stremio is very, very good app!

But in Android tv version, needs to have an "Cache size" configuration likes "100Mb, 250Mb, 500Mb, 750Mb or 1Gb" because some movies or series content dont have enough seeds to run smootly.... And if this option exists we can pause the content and wait some minutes to have an more cached size like PCs, it helps to have much better experiences in app when watching content .... Please devs, considerate my idea.... Is very necessary and dont do impact on some major TV models!

For default , this option can be disabled, but when users like to have more smootly watching in poor seeds content, can enable this sizes according to the device we have ...example : 100Mb is not an "giant" size, 250Mb,  , maybe 500Mb ? but can be "cache until 50% of an Serie episode of 1Gb for example and, if have poor seeds, the user can be activate this option, open the content, then , pause it , do an little "happy Hour" and return to watch without freezes .... 

The app could be too an option to "Clear Cache" ...users can use it to clean all cached content when have one issue ....

I understand the Stremio team have removed the old "cache" option in stremio because the majority of Android TVs dont have enough space to use it without issues , but the old Cache option starts in 2Gb , is enough space for some TVs YES ! but my ideia is an little cache sizes and the maximum allowed can be 1Gb ....THIS WILL HELPS A LOT !

**Comment by luizthiagor** [comment]
Until today and all users of Android TV , dont have cache option again to activate and solve The cache issues ...

Os impossible tô give cache option again for Android tv option ? I have a 32Gb Tvbox, using stremio without cache because dont have The option anymore 😥... Why ??

**Comment by TRtomasz** [comment]
It will not happen, it could happen once devices have enough storage so users will not be able to hurt themselves which mean perhaps around 100GB-200GB otherwise running almost any video with cache enabled will end up with a crash due to disk space running out.

**Comment by luizthiagor** [comment]
I understand ... But , in PC and mobile version for example i can set cache to 2Gb, 5Gb, 10Gb ....

Today has more devices with more internal space like Tvbox with 32Gb of rom for example ... Not only Android smart TV with poor space ... Is impossible to give cache option again , with option for user can set it on or off and set size ? And clean this cache with a button ? ... I Believe this is an important feature for stremio and only Android tv version dont have it 😥....

Please, reconsiderate this option for US 😉

> It will not happen, it could happen once devices have enough storage so users will not be able to hurt themselves which mean perhaps around 100GB-200GB otherwise running almost any video with cache enabled will end up with a crash due to disk space running out.

**Comment by luizthiagor** [comment]
> It will not happen, it could happen once devices have enough storage so users will not be able to hurt themselves which mean perhaps around 100GB-200GB otherwise running almost any video with cache enabled will end up with a crash due to disk space running out.

Maybe you can work mainly for a New option named "Buffer size" and not cache anymore for Android tv .... And so, user can set an value to Buffer like "500Mb" for example and so, if pause an vídeo , it stills dowloading only The size set By user .... And not 100Gb - 200Gb ...  No? ... Its an ideia ....

Buffer size ...managed By user in stremio app and not a cache for all content of vídeo (Buffer size can work only with actual playable vídeo ... If user close The vídeo player ,all Buffer size can be deleted.... Today stremio for Android tv has an active Buffer ... But it's very tinny and if can be adsjustable By user this can be great for US set it according space of device ...

Can be work about Buffer size ? ...

**Comment by TRtomasz** [comment]
This is not how chache works, if you play a video which size is 100gb it will need 100GB, cache gets cleard only once you try to play another video.

**Comment by luizthiagor** [comment]
> This is not how chache works, if you play a video which size is 100gb it will need 100GB, cache gets cleard only once you try to play another video.

Okay, thank you very much for your reply, and I understand how the cache works now. That is, you need to have ALL the video's available disk space to cache the video...

In light of this, I have some few questions:

1) Currently, when you open a video in Stremio AndroidTV, in a torrent, and pause it, you can see in the connection menu that it keeps downloading a bit of the video (buffer) within the default player (exoplayer). However, this buffer is small, around less than 100MB. Isn't it possible to increase this buffer to just 500MB? (in a new config by user) So that, while I'm watching, at least 500MB is ahead of what I'm watching and helps with the download?

2) Since the "cache" function requires all the space of a video, as you mentioned, isn't there a future option for the user to set "save cache to USB device" and thus not save this cache locally but rather to a memory card or flash drive? (Remember that every actual smart TV has a USB port, and TV boxes also have a card reader/USB flash drive)?

These two options I mentioned could perhaps be a solution to the problem, as increasing the ExoPlayer's internal buffer to, maybe, 500MB for example could help with downloads. An option to select a device to cache videos would also be interesting. Keep in mind that not all videos are 100GB (only 4K), and most of the 1080P content we watch daily on Stremio doesn't exceed 4GB. We can easily find good, inexpensive flash drives with at least 16GB or 32GB, and today, TV boxes with 16GB or 32GB of internal memory are readily available on the market, making it perfectly possible to cache 1080P content, right?

I believe it would be interesting to have the option to access these resources of cache like as in the past, even if they are turned off by default, but that we users can turn on / off / configure if possible as we have on other platforms: On Mobile or Computer, we can define whether we want the cache to be made or not .... on Android TV the function was removed because it caused problems, but users had the option to keep the cache option turned off ... the suggestions I gave above are just ideas to get around the problems caused by the cache on devices with little memory and for new devices or BoxTV with large space of memory. (today, for example, Stremio can be installed on a USB drive in Android TVs and Box TVs, and this drive can have good storage space to make this cache features too ...

I apologize for the doubts, but they are just doubts and healthy discussions about this topic especially now that we are in the Beta phase of Stremio for AndroidTV and it would be a good time to test new functions and reports from users like us!

**Comment by preetstyle** [comment]
this is something i was after, so now i am using Vimu player because it has buffer size
