### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by issakthomas** [Stremio/stremio-features#618]
Please make the macOS stremio app to run native on apple silicon rather than using rosetta to increase app performance and efficiency.

**Comment by TRtomasz** [comment]
This is not possible as QT 5 does not support this in thir free opensource version.

**Comment by issakthomas** [comment]
What about migrating to qt6? (just asking)

**Comment by TRtomasz** [comment]
@issakthomas  this is not planned for now as it would required to much effort considering that our current shell is rather stable and does not have any major issues. Migration to QT6 could cause a lot of issues

**Comment by heri16** [comment]
@TRtomasz Can this be done for the headless stremio-service for stremio webapp?

<img width="1204" alt="image" src="https://github.com/Stremio/stremio-features/assets/527101/41ef848e-37de-4b7b-816f-2fedf5a05b36">

**Comment by JustCorrect** [comment]
@TRtomasz according to the internet QT5 supports building for Apple Silicon since 5.15.9 https://doc.qt.io/qt-5/macos.html#architectures. So why is this not possible?

**Comment by kokroo** [comment]
@TRtomasz Will you accept a PR for Apple Silicon support?

**Comment by TRtomasz** [comment]
Sure @kokroo

**Comment by DamienBlackwood** [comment]
what is happening? any progress...?

**Comment by jaruba** [comment]
doesn't seem like it, but the new iOS app that is currently in testflight (seats are full though) will work on macos silicon too
