### ISSUE TITLE
IOS add-ons

### ISSUE THREAD

**Issue by Vitormdias** [Stremio/stremio-features#62]
Install add-ons like juan carlos 2, netflix, and others on the IOS app

**Comment by Ivshti** [comment]
We will show all add-ons with the next update, but we should warn you that torrent add-ons are not and won't be supproted on iOS due to Apple App Store restrictions

**Comment by ianrod30** [comment]
You could compile .ipa to sideload with torrent add-ons and then not submit it to the app store and let us sideload it ourselves.

**Comment by ernesto** [comment]
> You could compile .ipa to sideload with torrent add-ons and then not submit it to the app store and let us sideload it ourselves.

Yeah, have plan to that? I can help make a template or pod framework

**Comment by akar995** [comment]
Any update
