### ISSUE TITLE
MOBILE PLATFORMS: Scrobbling in external player that supports picture in picture.

### ISSUE THREAD

**Issue by horris87** [Stremio/stremio-features#620]
**Is your feature request related to a problem? Please describe.**
In the context of the mobile platform (I'm using android). Because there is no goal to enable picture in picture mode in streamio, it would be great to be able to scrobble in external players that can do picture in picture. E. VLC for mobile.

**Describe the solution you'd like**
The most elegant solution is to enable picture in picture for the streamio app.
Alternatively, is there a way to track the progress of videos (scrobble) being streamed to an external player within streamio?

**Describe alternatives you've considered**
Streamio does have a trakt tv plugin. I haven't tested, but I assume that scrobbling is synced with trakt tv servers.
If so, then all you need is an external player that supports both picture in picture and trakt tv... Which I have been struggling to find.

**Additional context**
KODI is all around a terrible mobile user experience.
Streamio is waaaaaay better. However this is literally the only feature that I am missing.

I got the streamio extension working on cloudstream, which does have picture in picture support, however the native streamio scrobbling wasn't working. And sadly, cloudstream doesn't support trakt tv.

Thank you!

**Comment by TRtomasz** [comment]
this is simply not possible.
