### ISSUE TITLE
Possibility of select Dolby vision or HDR10+ in videos with both options 

### ISSUE THREAD

**Issue by d13g0m0nt3s** [Stremio/stremio-features#625]
Hi, I request an option to be added to the Stremio internal player. The possibility of disable Dolby vision or HDR10+ in videos that have both options.

Is your feature request related to a problem?.
Yes, In the specific case of the Fire stick 4k Max, the videos with both options show a black screen. It is a known bug of that Fire stick but it seems that Amazon does nothing about it.

Describe the solution you'd like.
The only possible solution at the moment is what Kodi developers have done in the beta version of Kodi 21, adding an option that allows you to deactivate one or both options.

The change adds a setting under the Videos/Processing section, where users can choose which HDR type should be allowed.
By default, the video bitstream is kept intact, so all metadata is kept.

If you don't want HDR10+, uncheck HDR10+.
If you don't want Dolby Vision, uncheck it.

Describe alternatives you've considered
There are other players that have this option and it would be nice if Stremio's internal player included it. At the moment I use either an external player or Kodi.

Regards

**Comment by TRtomasz** [comment]
we are limited to what exoplayer can offer and it does not have such feature.
