### ISSUE TITLE
Allow Offline Access and all possibilites of offline playablity

### ISSUE THREAD

**Issue by ankitgurua** [Stremio/stremio-features#630]
**Is your feature request related to a problem? Please describe.**

- I'd Love if offline access of movies and tv shows was available in the app itself.  Just like Streaming apps, You just press a button and the movie is available to stream at all times specially in android phone and PC. 
- You can add an option in settings to auto download movies that i add to my library.
- The next episodes of a tv series are auto downloaded in background if I'm streaming its previous episodes so i dont have to wait for an episode to start downloading when on a binging spree. 

**Describe the solution you'd like**

- I know that when using torrents auto download is kinda difficult cuz you dont know our preferences, so have some preferences option for downloads in settings where you ask our preferred video settings like preferred resolution, Language, Maximum size of the file, x264/x265 etc, so when we click on download video gets downloaded in our preffered settings, the 'arr' apps like radarr and sonarr use this feature of knowing preffered torrents so they can auto download them in future without asking its user to select particular torrent settings again and again.
- After a Movie/series is downloaded i'd love if the app marks that movie as already downloaded in library, and the movie is playable from inside the app itself.

**Describe alternatives you've considered**

- I know there's an option to 'download this video', but the problem here is that it downloads a particular torrent after i open and load that torrent from inside the app player , there's no way to download it while I'm on discover tab searching for potential movies to watch, this also adds the movie outside of stremio so i have to leave the app to open that movie in vlc. this ruins the experience
- That Download this Video option just isnt viable for series as one'd have to download seperate episodes for each series, not entire seasons or entire series at once. Allowing users to download entire series at once in desired settings would be a great help.

**Comment by TRtomasz** [comment]
We feel like simple download option is enough we will not add automatic downloads.
