### ISSUE TITLE
Infuse as an external player (MacOS/web)

### ISSUE THREAD

**Issue by zeronullempty** [Stremio/stremio-features#635]
Can Infuse player be added as an external player for the MacOS and Web clients, similar to how iina and mpv are supported? Infuse's HDR implementation is better than other players and it supports audio formats that are unsupported by other players.

If anyone knows if I can make some local modifications to some files to add it manually on my end, that would also be helpful. You could do it on previous versions of Stremio before the big UI update.

Recently, infuse has added an API you might be able to use for this purpose...

https://support.firecore.com/hc/en-us/articles/215090997

**Comment by TRtomasz** [comment]
Infuse was not working correctly when triggering it so it was removed

**Comment by zeronullempty** [comment]
It works fine when pasting in the stremio link normally...
