### ISSUE TITLE
Please allow us the option to rearrange our addons

### ISSUE THREAD

**Issue by Alex1397** [Stremio/stremio-features#639]
Please allow us to rearrange our addons. It is such a hassle for me to type out my add-ons every time I want to change the order due to me changing my filters on an add-on  It's especially hard when doing it on a Chromecast remote. A simple feature of rearranging would solve this.

**Comment by subexx** [comment]
This would be awesome.

**Comment by lothar-cell** [comment]
I've been waiting for this for ever!

**Comment by lothar-cell** [comment]
There's now an unofficial workaround for this, worked for me perfectly so far: https://github.com/Stremio/stremio-features/issues/562#issuecomment-1969170326

**Comment by TRtomasz** [comment]
closing as a duplicate
