### ISSUE TITLE
Season Names Suggestion

### ISSUE THREAD

**Issue by Donut56** [Stremio/stremio-features#644]
I think a good feature to have similar to other streaming platforms is adding season names if they have them instead of numbered seasons.  For example, the seasons for American Horror Story are just numbered on all platforms of Stremio instead of listing the season names (Coven, Hotel, 1984, etc.).  Just a small feature, but would be a nice add-on.  The attached picture is an example of the numbered seasons in AHS instead of the season names.
<img width="285" alt="Screen Shot 2023-12-21 at 6 56 08 PM" src="https://github.com/Stremio/stremio-features/assets/154564297/71547f96-5708-48c6-b687-f9907c2f06df">

**Comment by TRtomasz** [comment]
we do not have such data, we do not have season names so it cant be added
