### ISSUE TITLE
"New to you" section

### ISSUE THREAD

**Issue by dr0vur** [Stremio/stremio-features#647]
It would be great if the "New for you" section from android app can be added in the samsung tv app. It's the section showing the new episodes for the shows you have in your library.

**Comment by jhedfors** [comment]
Yes. It is present in Android app, but not Android TV.

**Comment by the-badmannn** [comment]
+1

**Comment by charliesheen14** [comment]
+1 for android tv

**Comment by shadyabdou** [comment]
+1

**Comment by TRtomasz** [comment]
There is no such section in Android Tv, Samsung Tv and stremio 5 web app. New episodes notifications are shown on the continue watching section

**Comment by fairtale5** [comment]
I'd contribute with $5 to whoever builds this. Hope enough others also chime in so we can get this sooner. Anyone?
