### ISSUE TITLE
Filter by audio 

### ISSUE THREAD

**Issue by dr0vur** [Stremio/stremio-features#648]
It would a nice feature if there was the possibility to filter the available audio from files.

This would be extremely helpful to filter out results for parents or children in specific languages.

**Comment by TRtomasz** [comment]
not possible, stremi is not aware of files names or their audio capabilities

**Comment by dr0vur** [comment]
> not possible, stremio is not aware of files names or their audio capabilities

Ohhh ok then, thanks!
