### ISSUE TITLE
Subtitles Settings (Color, Font, Position)

### ISSUE THREAD

**Issue by vaurelios** [Stremio/stremio-features#65]
Would be great to have these settings in Stremio, some movies have too much clarity making hard to learn white subtitles.

Font size can help in small-size monitors/tv, and would be good for accessibility too.

Position is more personal-like.

**Comment by tiagocardosoweb** [comment]
Agree!

**Comment by wptd** [comment]
Agree!

**Comment by quintanilhaedu** [comment]
Agree!

**Comment by JayKickButts** [comment]
I would like to see this option on Stremio as well.

**Comment by Sunnysky** [comment]
It is a nuisance the way it is now for, yet essential for my wife.

**Comment by Morteza-Rastgoo** [comment]
So, is this implemented or just ignored?

**Comment by mouradvip7** [comment]
Please implement this.

**Comment by sabala** [comment]
ignored!

**Comment by aleqx** [comment]
> If you feel like some feature is missing feel free to open new issue with detailed description of missing feature. Do not forget on what platform you think feature is missing.

Why open a new issue when one already exists? Clearly it's been ignored, it's been 3 years. Would a new issue have a different fate? Not trying to be sarcastic. As a dev myself, I don't want new issues for the same thing (unless I explicitly close old ones without a fix as "wontfix" or for other reasons).
