### ISSUE TITLE
Filter a movie option by it's subtitle

### ISSUE THREAD

**Issue by guimatheus92** [Stremio/stremio-features#650]
Have you guys tried to select a movie option and then select a different subtitle? It's so stressful to TRY to find the right subtitle for a given movie and then you see that subtitle it's not meant for that movie option.

I know that substitles has the right time for a given movie, so having the option to filter the movie FROM it's subtitle would be amazing.

OR 

Check if that movie option has the necessary subtitle for a given language.

For example: Click to watch **Avengers Infinity War** and try to select a subtitle, it has SO MANY but none of them I was able to find the right one for **Portuguese Brazil**, not only that but neither one of those portuguese options worked, and I also tried at least 10 options from that movie from different addons. It's really annoying.

Also another great idea from @ankitgurua from his #602 that matches my problem: Add an auto subtitle generator plugin. That instead of generating subtitles from scratch, match the already existing subtitles to the accurate timing because rarely my subtitles are on point. I always have to mess around with timing. There's no point of having 25 + subtitle files available when none of them works. This will reduce the clutter and provide one solid working subtitle experience. There are alot of AI apps that can do this. Maybe use their api.

**Comment by TRtomasz** [comment]
This is not possible as we do not controll subtitles, would increase addon load a lot.
