### ISSUE TITLE
statistics panel

### ISSUE THREAD

**Issue by PeroG28** [Stremio/stremio-features#651]
**Is your feature request related to a problem? Please describe.**
I want to see the statistics of an account, like how much the account watched, what genres the account favorites, and more like that 

**Describe the solution you'd like**
I think the solution is some sort of a bi-tab (like the calendar or the library) so you can get to the tab in the left menu.
statistics:
shows/movies/all filter
period of time filter
time watched (minutes/hours) KPI
time watched (minutes/hours) per genre bar chart
number of items KPI
number of items per genre bar chart
a pie chart of addons usage (to see what addon is most used)
number of "abandoned items" (not watched all of them), maybe it can in a click go to the item list
and maybe more

**Describe alternatives you've considered**
the tab can maybe be accessed with a button in the library or from the user menu in the top right 

**Additional context**
I am happy to help and contribute, I tried to get into the code and do it for a pull request but I couldn't get into the code and understand where I got the information from

**Comment by TRtomasz** [comment]
You can use trakt for this
