### ISSUE TITLE
Blank all other screens

### ISSUE THREAD

**Issue by vigna** [Stremio/stremio-features#655]
It would be very nice if Stremio, when going into full screen mode, would turn off all other screens (i.e., except the one it is displaying on), exactly like VLC does.

I have MacOs but this is a general feature.

**Comment by TRtomasz** [comment]
Not enough details: OS.

**Comment by TRtomasz** [comment]
Will not be added, this would be too disturbing for user experience, i'm not even sure if this is possible

**Comment by vigna** [comment]
What is disturbing is having your additional screen illuminating the room.

Of course it is possible—did you even read my message? That's what VLC does. https://www.videolan.org/

**Comment by TRtomasz** [comment]
IT doesn't on windows
