### ISSUE TITLE
[feature request] Multichannel audio to stereo 2.0

### ISSUE THREAD

**Issue by shanestonk** [Stremio/stremio-features#656]
**Is your feature request related to a problem? Please describe.**

my android tv only have 2.0 speaker and whenever i watch using real debrid torrentio movie which in 5.1 or 7.1 audio the audio will become low volume especially the actor speech.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. stremeo downmix the multichannel audio to stereo for android tv

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. kodi video player can downmix to stereo. nova video player can downmix to stereo and boosted the audio.

**Comment by TRtomasz** [comment]
Go to the settings and switch "tunneled playback" setting it should help with your issue.

**Comment by tukez** [comment]
Tunneled playback did not work for me, multichannel audio won't be downmixed even I have forced stereo output set on my TV.

**Comment by TRtomasz** [comment]
@tukez  you should try check multiple audio settings on your TV. I was able to configure my TV(Samsung tizen) To have good audio when playing videos with multichannels. 
Other option is to switch player from exo to libvlc in the settings

**Comment by lakyljuk** [comment]
Those solutions are android Stremio specific. I have the same issue on Windows PC, where I have only stereo speakers and streams which are 5.1 are not mixed into stereo. There is no option for Tunelled playback, nor there is any option to switch player from exo to libvlc. Any advice?

**Comment by tiagovla** [comment]
> @tukez  you should try check multiple audio settings on your TV. I was able to configure my TV(Samsung tizen) To have good audio when playing videos with multichannels. 
> Other option is to switch player from exo to libvlc in the settings

I have a projector with android stremio. Exo and libvlc with and without tunneling have the same issue.
