### ISSUE TITLE
Samsung TV apps (Tizen): Option to sync subtitle (Increase/decrease).

### ISSUE THREAD

**Issue by SubEdict** [Stremio/stremio-features#657]
**One big issue:**
Subtitle is missing the sync options.

Any way to add the Increase/Decrease 'H'/'G' keys function to the remote/GUI option?

**Second small issue:** 
After all known sites uploaded new subtitle, it takes more than a day before they will shown in the player available language results. Please fix it so it will be able to refresh the results instantly.

**Comment by SavvasMohito** [comment]
+1 on this, we definitely need it

**Comment by dquak** [comment]
+1!

**Comment by TRtomasz** [comment]
This will be added in the next release, so i will close this issue. It should be available soon!
