### ISSUE TITLE
Mono Audio - Earphone/Headset (Wireless)

### ISSUE THREAD

**Issue by permedd** [Stremio/stremio-features#662]
**“Mono Audio” Enable or Disable**

**Suggestion**
We should have an option to enable or disable “Mono Audio”

**Right now:**
Right now when I watch series or movies, the Mono Audio is disabled, where I can hear two noises different on each earphone/headphones. 

**Idea:**
It will be great to be able to control what you want to hear, we should be able to enable/disable “Mono Audio”.

**Me**:
Me personally I would like to enable it, so I can hear same noise on both of my earphones/headphones and not different noises on one ear than the other.

I don’t like to hear wind noises on my right ear and people talking on my left ear.
Or hearing people talk on both ear and hearing background noises on my right ear only.

**Comment by TRtomasz** [comment]
Sounds like a system setting not stremio confiugration i use my headphones and dont have such problem

**Comment by permedd** [comment]
Oh okay, well Spotify has it, aint it possible to also have it on the app maybe?
Maybe some people wants to Enable or Disable  “Mono Audio”?
