### ISSUE TITLE
Customize HomePage Section(s)

### ISSUE THREAD

**Issue by permedd** [Stremio/stremio-features#663]
**Show or Hide or Freely (Order) Move “HomePage Section(s)”**

**Section Example:**
• Popular - Movie
• Popular - Series
• Featured - Movie
• Featured - Series
• Youtube - Channel
… Etc etc etc

**Suggestion:**
Would it be possible to “Show or Hide” all these sections, or maybe being able to “move” them in our “own custom order”, I would like other stuff being on top rather them being all the way at the bottom, especially when you have loads of addons. 
Making it customized will help a lot and look more cleaner.

**It will be great to have all 3 option which are:**
- Show 
- Hide
-  Freely (Order) Move

**Comment by lothar-cell** [comment]
Yes!

**Comment by SubEdict** [comment]
So true that it hurts. 😲 
Also, on the first row, I would like to see my Trakt - TV Show - **Progress** (Up Next).

**Comment by boseann** [comment]
most people just use TMDB so it would be great to have the option to uninstall Cinemeta addon or at least remove it's sections (popular movies and popular series etc )

**Comment by lothar-cell** [comment]
So does closing mean it is implemented in the upcoming release?

**Comment by lothar-cell** [comment]
?

**Comment by lothar-cell** [comment]
@TRtomasz Why did you close this - because it has been implemented or because Stremio doesn't care to do this?

**Comment by TRtomasz** [comment]
This is duplicate of many others such requests so there is no need to keep that one open
