### ISSUE TITLE
Arrow Keys remap to J-L for smaller keyboards

### ISSUE THREAD

**Issue by iMAboud** [Stremio/stremio-features#667]
I don't have Right - Left Arrows on my keyboard. 
I use J - L keys to seek forward or backward on streaming services like Youtube. 

Requesting a remap option or an alternative Seek keys for those who don't have Arrow Keys. 

### Suggesting (J - L) for seeking Backward and Forward.

**Comment by TRtomasz** [comment]
Sorry, we intend to keep stremio simple, do not add features that would be usable by 0.001% of users.
