### ISSUE TITLE
Continuous random play

### ISSUE THREAD

**Issue by StephenFisher52** [Stremio/stremio-features#668]
Hello, loving Stremio so far but would like to submit a feature request.

I'd love it if you could select a TV show and have it continuously play random episodes.

My wife loves having Friends on in the background when she is chilling out, if she could press a button and Stremio would play random episodes for a couple of hours it would be brilliant.

Appreciate this isn't a feature most people would use, but would be great if it was available.

Thank you

**Comment by TRtomasz** [comment]
Sorry, this will not be added to stremio, we want to keep the app simple as possible.
