### ISSUE TITLE
Crop the playback video to avoid black bars

### ISSUE THREAD

**Issue by ab1nash** [Stremio/stremio-features#669]
**Stremio Version**
Stremio 4.4.165 on Windows
Stremio inbuilt player

**Is your feature request related to a problem? Please describe.**
I am unable to crop the playback video in the native player to remove black bars. For example, on a 16:9 screen any 16:10 video will have black bars on the top and the bottom.

**Describe the solution you'd like**
There should be an option to custom crop the playback video that zooms the video to fill the screen vertically.

**Describe alternatives you've considered**
Playing the video on VLC.

**Additional context**
-

**Comment by TRtomasz** [comment]
closing as duplicate https://github.com/search?q=repo%3AStremio%2Fstremio-features+crop&type=issues
