### ISSUE TITLE
Issue with linking account to tv

### ISSUE THREAD

**Issue by Benmyk** [Stremio/stremio-features#677]
Hi, anyone experiencing this, I was able
To set up my account and added the PM configured torrentio to it, I linked to my tv via the QR code scanning and was great, however I turned on my tv today and I was logged out , I tried linking the same account to the tv and it’s not successful, I get “ remote device successfully logged in “ on my phone yet nothing happens to the tv . Anyone aware of this and is there any fix to this please ?
Thanks

**Comment by TRtomasz** [comment]
If problems persist please reopen it in the stremio-bugs repository.
