### ISSUE TITLE
Subtitles position Android

### ISSUE THREAD

**Issue by mistergii** [Stremio/stremio-features#68]
Hello.

I am using android device to play movies on tv. I really like the app, almost everything is working fine 👍 
The one problem that is really bothering me is that subtitles are way to high on screen(see attached photo). Can you please add function to settings so we can customize subtitles position? I am using Stremio 4 beta 40.1 apk from your site. Also, soon I will make translation to Slovenian language, and try to make my own add-on. Keep up the good work! 🥇 
![20170911_215751 1](https://user-images.githubusercontent.com/31878821/30311678-c289b3f2-9796-11e7-99d0-c17145a73ffe.jpg)

**Comment by Ivshti** [comment]
Thanks for the feedback, we appreciate it!

We will consider this feature!

**Comment by Ivshti** [comment]
Thanks for the feedback, we appreciate it!

We will consider this feature!

We'll be really happy to see a translation and even an add-on!

**Comment by mistergii** [comment]
This feature is really missing, I really hope that you will add it soon, maybe in next version? I don't think that it will take much time to you to add this setting bellow subtittle size setting :)

**Comment by TRtomasz** [comment]
Implemented in 1.3.5 :)
