### ISSUE TITLE
User can Add multiple profiles in Stremio such as Netflix or any other platforms

### ISSUE THREAD

**Issue by lord3mmar** [Stremio/stremio-features#680]
I only have a recommendation. First I'd like to thank the people who made this platform. I'm using stremio since 2021 and I'm enjoying it so much so far. But I really had this idea from back then, that why the developers doesn't add an option to: Add a Profile. I even think it is more important for others than me. It is a must for a Movie & TV platforms such like this. So I really love to see stremio being better than before, and I hope -finger🤞🏼crossed- that you consider this message at least.
Thank you,
Loyal User.

**Comment by boseann** [comment]
i agree that would be very useful

**Comment by TRtomasz** [comment]
duplicate issue.
