### ISSUE TITLE
[Feature Request] Add Buffering on Samsung TV App Player

### ISSUE THREAD

**Issue by cortezothiago** [Stremio/stremio-features#681]
The app for Samsung TV will soon be polished and as good as the Android and PC apps. But I would also like to make a suggestion: **add buffering to the player.**
In 4k content, I still need to watch it via external HD, because in the Samsung TV app they play (when they play) at a very low frame rate while it loads...

**Comment by guimatheus92** [comment]
I agree! I also created an issue about this feature: https://github.com/Stremio/stremio-features/issues/643

**Comment by TRtomasz** [comment]
Tv's dont have enough memory to be able to cache big files.
