### ISSUE TITLE
[Feature request] the ability to reposition embedded subtitles

### ISSUE THREAD

**Issue by boseann** [Stremio/stremio-features#682]
Stremio Version 1.6.9 android 

I encounter an issue with embedded subtitles on the built-in player – when going full screen, the subtitles get cut off, making them unreadable. this happens on all smartphone.

I'd appreciate the option to reposition subtitles, similar to how it's possible with add-on subtitles, when they work which is rare.

![Screenshot_20240111-192415](https://github.com/Stremio/stremio-features/assets/156013889/1bd43e7d-eb36-4168-b083-3006f94a43c5)

**Comment by TRtomasz** [comment]
switch video proportions to ones that have subtitles on the screen, vlc does not allow changing embedded subtitles postion so it cant be added.
