### ISSUE TITLE
[Feature request] Library Movie/Series drop-down revert

### ISSUE THREAD

**Issue by kekkers23** [Stremio/stremio-features#686]
**Stremio Version**
Latest desktop/Android TV

**Is your feature request related to a problem? Please describe.**
The change made with the UI overhaul made it so the Library > Movie/Series is now a drop down. This is incredibly annoying as this now requires an additional couple click every time to swap between views.

**Describe the solution you'd like**
Revert this back to static Movie/Series options instead of a drop-down.

**Describe alternatives you've considered**
No alternative

**Additional context**
If you still want a drop down for future use, leave that blank or only show it if you enabled in through an addon or something

**Comment by kekkers23** [comment]
Hey @TRtomasz is this change being implemented? :)

**Comment by TRtomasz** [comment]
It will not be implemented we do not plan to revert new UI to the old UI

**Comment by kekkers23** [comment]
> It will not be implemented we do not plan to revert new UI to the old UI

It wouldnt require the entire UI overhaul to be undone, however the flow of changing between Movie/Series within the desktop app Library now requires additional clicks as opposed to the old UI as well as when compared to the mobile/tv versions.

Essentially, when under library there should be two static options at the top for Movie / Series in order to quickly navigate between these. If there are future plans to have additional categories then leave the drop-down menu which can be populated when needed.
