### ISSUE TITLE
Hide Community Addons List

### ISSUE THREAD

**Issue by a1kalin3** [Stremio/stremio-features#688]
**Is your feature request related to a problem? Please describe.**

It’s frustrating that there is no way to hide adult or nsfw community Addons from the community Addons list, especially if using Stremio in a family setting. These Addons appear in the list even if you don’t install them.

**Describe the solution you'd like**

The easiest, least impact way to address this issue is to add an option in the settings page to hide the community Addons list.

**Describe alternatives you've considered**

An option to hide the Addons tab completely would also work well, and would have the added benefit of making it harder for other users to accidentally change Addon settings.

**Comment by megadrive** [comment]
+1

**Comment by heyalok** [comment]
+1

**Comment by saifshaikh1805** [comment]
+1
