### ISSUE TITLE
Integrate with other databases

### ISSUE THREAD

**Issue by xdk78** [Stremio/stremio-features#69]
It possibe to add api or something to integrate with custom databases?
I want to use anidb.net for geting info about anime, because imdb don't have all titles in their database. My addon will add torrents sources from anime torrent sites

**Comment by Ivshti** [comment]
It is possible to develop your add-on in a way that it also provides metadata, by handling the `meta.find` and `meta.get` hooks

**Comment by xdk78** [comment]
ok
