### ISSUE TITLE
Can't load external subtitles Samsung TV

### ISSUE THREAD

**Issue by seddik88** [Stremio/stremio-features#691]
"Error retrieving subtitles" Samsung TV doesn't load external subtitles ( at all) and sometimes doesn't even load embedded ones.

On first install it worked, then stopped working. I deleted the app both on PC and tv and tried again. 

Same error. I uninstalled all subtitles add-ons and installed to hem back one by one still no fix.

Please help

**Comment by bartolo112** [comment]
how to fix it?
