### ISSUE TITLE
Youtube Channel Profiles.

### ISSUE THREAD

**Issue by Iamforilla** [Stremio/stremio-features#692]
I think it would be awesome if we could get a playlist feature that would hook up to specific youtube channels.   We all have our favorite creators on youtube.   It would be so COOL if we could get there latest videos to pop up in a category that we could set up to the channel that would appear whenever there is a video upload.     I know stremio has a youtube addon.   But it does not pop up the videos from channels into the category  so instead of finding the profile it would be cool to have our favorite channell releases to pop up in one category!   Just an idea.!

**Comment by TRtomasz** [comment]
Sorry, stremio wasnt designed as youtube alternative and we do not play to increase it functionalities in this area as it would require to get paid access to the youtube api.
