### ISSUE TITLE
[Feature request] Adding availability to switch GUI resolution on 4K monitor to FHD for windows Desktop version, remembering maximal window view

### ISSUE THREAD

**Issue by Tienssy** [Stremio/stremio-features#693]
**Stremio Version**
Stremio version: 4.4.165
OS: Windows 10 latest

**Is your feature request related to a problem? Please describe.**
I'm running Stremio desktop app on Windows 10 with 4k screen monitor and resolution. When I'm playing a video with the 4K GUI resolution, Stremio takes a lot of power resources (CPU, GPU) from laptop. But when I first switch to FHD resolution (very bad for 4k monitor) and then I launch app and play something it works as it should - less/normal CPU and GPU power consumption BUT the app is then very blurred on FHD resolution on 4K monitor. It really does not look good. Why? It was happening to me also with Kodi, but in Kodi it is possible to switch inside the app to FHD GUI resolution easily, and then it works correctly, and it then also look nice on FHD resolution. Also, I am not able to set maximal window (as Kodi is starting) on launching the app (It does not remember it). Stremio has issues with lagging and consuming much more CPU and GPU resources on 4K resolution against FHD resolution. It is a huge issue for me. Would it be possible to have an ability to choose the resolution inside the app?

**Describe the solution you'd like**
Possibility to choose FHD resolution on different screen monitor resolution (4k) of Stremio GUI without needed to switch from 4K to FHD manually in Windows before launching Stremio. And regards to maximal window - remember from the last session.

**Describe alternatives you've considered**
Change the resolution via "QRes" utility - not good. When I change the resolution on 4K monitor to FHD, Stremio GUI is very blurry and not looking good.

**Additional context**

**Comment by TRtomasz** [comment]
Sorry this kind of feature will not be added, as it is too complex with to little benefit. Please enable hardware accelerated decoding in the app settings to achive better performance results.

**Comment by Tienssy** [comment]
> Sorry this kind of feature will not be added, as it is too complex with to little benefit. Please enable hardware accelerated decoding in the app settings to achieve better performance results.

I've already enabled hardware accelerated decoding, but it didn't help at all. Streamio is not able to work with 4K resolution properly. It consumes much more GPU/CPU resources in the same way as Kodi when it is not set to FHD GUI resolution. For me, it would be a huge benefit. Otherwise, I'm not sure how can I solve it to view Streamio GUI properly on 4k resolution. Any suggestions to solve the issue, please?

**Comment by TRtomasz** [comment]
It is normal when decoding 4k video to use cpu/gpu resources. Playing 4k content while having full hd resolution will not make any difference so you could just play full hd content. And i'v just checked some 4k content on my laptop, integrated gpu is utilized at 35% maximum so this is not much

**Comment by Tienssy** [comment]
The issue is not playing the 4k video. The GUI that is running at 4K resolution while playing any video, causes the CPU and GPU to use much more power than Streamio running at FHD resolution with the same video. It is the same issue as Kodi, but in Kodi you have a choice to switch to 1080p GUI, and after that, the GUI still remains clear. This is not the case with Streamio. Its GUI is blurry on a 4K monitor switched to FHD resolution.

**Comment by Tienssy** [comment]
@TRtomasz Just try:
1. On Windows, switch to 4K resolution.
2. Run Stremio and play a video.
3. Check CPU and GPU workload.

vs

1. Switch to 1920x1080 resolution on Windows.
2. Run Stremio and play the same video.
3. Check the workload.

Stremio on 4K resolution burdens a computer CPU/GPU by more than 6-10x against Stremio running on Windows switched to 1920x1080 resolution. It doesn't make sense.

**Comment by Tienssy** [comment]
> @TRtomasz Just try:
> 
>     1. On Windows, switch to 4K resolution.
> 
>     2. Run Stremio and play a video.
> 
>     3. Check CPU and GPU workload.
> 
> 
> vs
> 
>     1. Switch to 1920x1080 resolution on Windows.
> 
>     2. Run Stremio and play the same video.
> 
>     3. Check the workload.
> 
> 
> Stremio on 4K resolution burdens a computer CPU/GPU by more than 6-10x against Stremio running on Windows switched to 1920x1080 resolution. It doesn't make sense.

@TRtomasz

**Comment by TRtomasz** [comment]
It works just fine with 4k resolution playing 4k video as i wrote earlier it was using gpu at max 35% and this is just my integrated GPU

**Comment by Tienssy** [comment]
@TRtomasz Yes, you are right. 4K video with 4K resolution is playing with 20% CPU and 45% GPU for me. When I play the same 4K video with FHD Stremio resolution, the CPU is on 10%, GPU 20%. And the difference is only with Stremio running on 4K vs FHD resolution. I also have to admit that Stremio on 4K resolution is much more sluggy and way less responsive (search, search results, choosing a media, ...) on 4K against FHD resolution, where everything is smooth.

**Comment by Tienssy** [comment]
> @TRtomasz Yes, you are right. 4K video with 4K resolution is playing with 20% CPU and 45% GPU for me. When I play the same 4K video with FHD Stremio resolution, the CPU is on 10%, GPU 20%. And the difference is only with Stremio running on 4K vs FHD resolution. I also have to admit that Stremio on 4K resolution is much more sluggy and way less responsive (search, search results, choosing a media, ...) on 4K against FHD resolution, where everything is smooth.

@TRtomasz
