### ISSUE TITLE
Issue with Just Video Player and Vimu Player

### ISSUE THREAD

**Issue by Blueybarnes** [Stremio/stremio-features#694]
Just Video Player continues to play audio after exiting stream for around 5-10 seconds. It also plays audio with a black screen on the majority of 4k links. This does not happen with Vimu. 

Vimu media player starts stream around 1min 15secs into content on all streams.
This is on Firestick 4k.

**Comment by TRtomasz** [comment]
Please use stremio-bugs repository for issues reports.
