### ISSUE TITLE
Windows Desktop App x32 Release

### ISSUE THREAD

**Issue by alpergkcan** [Stremio/stremio-features#698]
**Issue**
Stremio isn’t available on old 32 bit cpus. Which, i believe, can easily be targeted. 

**Describe the solution you'd like**
Windows Desktop application Release for 32 bit architectures

**Comment by TRtomasz** [comment]
We do not plan to release such version.
Shell is opensource so you can try building it yourself https://github.com/Stremio/stremio-shell
