### ISSUE TITLE
Add local files into detail page

### ISSUE THREAD

**Issue by Draxler** [Stremio/stremio-features#7]
Some movies have realy poor quality or have good quality with bad health (bad seed support). And there are some movies which have no stream available at all.
Could you implemented feature wich would aloud user to add custom source (stream) and cache it, torrent or magnet link on to user PC? Once such file is saved and when user would enter next time onto this movie detail page, it would show normal play button with litlle circle with L in it (as local file) same as you have 2 circles for HD and SD sources. The only defference be that source would be from users PC not from outside source. I have in mind that each detail page would have an option to store one extra local source (torrent or magnet). So if Movie detail page already have SD nad HD option you could add a third circle (option) with L (as Local) in it. All this have nothing to do with tempeiring with third party addons. it's standalone feature which could be integrated.

I hope you understand what i have in mind. my english is not that well .. :)

![44r5z](https://cloud.githubusercontent.com/assets/7681671/11003525/4a0b8d94-84b3-11e5-970c-2445211678c2.PNG)

![add torrent source](https://cloud.githubusercontent.com/assets/7681671/11004864/f7b68bcc-84ba-11e5-92c8-dc34354e134a.PNG)

**Comment by Ivshti** [comment]
Why did you delete this issue? I received it on email, it's a good point.

**Comment by Draxler** [comment]
I thought you don't won't  to bother with this one for some reason. :) Sorry 

If you still have this full text you could posted here and i could copy paste onto original post. Or you maybe you do have an option reinstate my delete post?

**Comment by Ivshti** [comment]
```
Some movies have realy poor quality or have good quality with bad health (bad seed support). And there are some movies which have no stream available at all.
Could you implemented feature wich would aloud user to add custom source (stream) and cache it, torrent or magnet link on to user PC? Once such file is saved and when user would enter next time onto this movie detail page, it would show normal play button with litlle circle with L in it (as local file) same as you have 2 circles for HD and SD sources. The only defference be that source would be from users PC not from outside source. I have in mind that each detail page would have an option to store one extra local source (torrent or magnet). So if Movie detail page already have SD nad HD option you could add a third circle (option) with L (as Local) in it. All this have nothing to do with tempeiring with third party addons. it's standalone feature which could be integrated.

I hope you understand what i have in mind. my english is not that well .. :)

23er45
```

**Comment by Draxler** [comment]
@Ivshti 

Thanks. Next time i leave my posts alone :smile

**Comment by Ivshti** [comment]
@Draxler this is covered now by the Available Streams dialog. When there's a local file, it will appear after clicking Play

**Comment by Draxler** [comment]
I didn't have this mind.
What you did is something completley defferent. I don't have a clue where this ''local'' files even come from, i'm lost here.

What i proposed is completley defferent feature, much more user friendley feature, where user have complete control over what file in what quality to add (magnet link or torrent) and to which movie or tv series to add. And not for app to automaticley add whatever quality file as long as it's there for every movie if available.

It's like if you add another source which act in same way as API which automaticley add what ever movie in whatever quality, as long as it's there to add. No user control what so ever.

i don't even know from where this ''local'' files come from.

**Comment by Ivshti** [comment]
@Draxler actually, if you drag any torrent file, video file or magnet link to the stremio UI, stremio will attempt to index it and therefore remember it on the Available Streams for the given movie/episode. 

Try it to see if it is so.

As for the indexing, it's an implementation bug - full indexing is not working on all OS-es, instead fallbacks to scanning Downloads/Desktop

**Comment by Draxler** [comment]
I agree, this would be actualy much better (if worked) to indexed only magnets and torrents user draged into Stremio. It would be nice if this gets fixed and start working as you imagined - Drag and Drop magnets/torrents only and stop scanning files from Download/Desktop , because now user doesn't have absolutley no control over it what torrent would Stremio get for a certain movie.
I hope this is something you'll fixed . :smile:

**Comment by Draxler** [comment]
Win OS
----------
It doesn't work.. When only Juan Torrents Stream is available for a movie and when Drag and Drop torrent into Stremio to add local file, it ask you if you want to REMOVE from a library (not to add). In the end only default stream is available.
Also, i removed ALL torrent files from Downloads folder and Desktop but all local files were still there , available in movie detail page. Also i couldn't replaced local files (from Downloads) with New local files (Drag and Drop). Magnet links also doesn't works - it doesn't open menu whene ask user if want to add this movie into library, nothing happens when magnet is droped into Stremio.

Stremio should only recognised torrents and magnets which were Drag and Droped into Stremio, as you have in mind. I also think **Remove local File** function should be implemented, so user could remove certain local file if choose to have only Juan Torrent stream for some reson or to replace with better local file.. 
Where i could find cache or DB file with local files, so i could remove local files and try again from a start?
- Maybe this could be reopend?

**Comment by TRtomasz** [comment]
Currently solved with local addon
