### ISSUE TITLE
wait fixed time in addition to variable time buffering in settings, before starting to play.

### ISSUE THREAD

**Issue by mybuntu-git2** [Stremio/stremio-features#701]
**Stremio Version**
All versions

**Is your feature request related to a problem? Please describe.**
no problem

**Describe the solution you'd like**
I start a stream and then it blocks, because it is missing some parts. this happens almost always.
it does not happen if I pause immediately the video after starting and wait some minutes.
I would like to have a "wait time" set before the movie autoplays. in other words, after I click play movie, the screen with the movie starts up, and it should play like, half a second and then pause automatically for N seconds, with N a parameter to be defined in settings.

this prevents us from starting to watch a movie, hear a minute or two, and then stop.

**Describe alternatives you've considered**
there is no workaround

**Additional context**
this is happening on MacOS and Samsung TV.

**Comment by TRtomasz** [comment]
While this is possible it will not have the effect you expect.
