### ISSUE TITLE
Suggestion: Detect and disable broken addons

### ISSUE THREAD

**Issue by master3395** [Stremio/stremio-features#703]
Perhaps a good idea to auto-detect and disable addons, that can't detect the files/links?
That way, the user will have fewer errors showing up, and if disabled, perhaps add a small text around the addon on the addon page, for example: "Disabled because of issues".
In case it starts working 1 minute later, perhaps let users have a checkbox "Restart after 1 minute", so it would loop the restart of the disabled apps?
Reference to this: https://github.com/Stremio/stremio-core/issues/631
![420071877_7822827654401212_3371072101385108755_n](https://github.com/Stremio/stremio-core/assets/4199669/86da9566-6f41-4cb6-aaa2-1b09800e72c4)

**Comment by TRtomasz** [comment]
as  i wrote before, this is simply not possible to be done correctly so this kind of feature will not be implemented
