### ISSUE TITLE
Loading Images

### ISSUE THREAD

**Issue by Twizt3r** [Stremio/stremio-features#704]
So I'm sure that not the only one who has had this happen, but the images that show in the background when an episode is loading sometimes give huge spoilers.
For example, the loading screen for "Person of Interest" is, I'm assuming, from season 2 or beyond, and it has the actress that plays Root. I didn't know she played that character, but it's not a hard connection to make.
Can we have season relevant loading images when episodes are being loaded ? Is that something that's possible ?
Thank you !

**Comment by TRtomasz** [comment]
Please explain how:
1. Picture of the actress is a spoiler, same way cast list is a spoiler
2. Knowhing what chracter that person plays is a spoiler?

**Comment by Twizt3r** [comment]
Cast list for that episode (S01E23) lists the actress as Caroline Turing, which, you discover later, is an alias. Only in S02E01 is she listed as Root.
It's a spoiler because it's a dramatic reveal of a major antagonist.
It's fine, doesn't bother me that much, I only made this post as a suggestion, not as a thing to fix.
