### ISSUE TITLE
Manual Refresh 

### ISSUE THREAD

**Issue by jhedfors** [Stremio/stremio-features#706]
Android TV OS 12
Stremio Version 1.6.7

It would be great if the (Android TV) app provided a way to manually refresh the data. 

Thy only way I can do this is to force-stop the app and clear cache - doing one or the other is not enough to refresh.

**Comment by Vance-ng-vn** [comment]
+1 for refresh stream and subtitles list

**Comment by TRtomasz** [comment]
This will not be added as in 99.9% cases it is not needed.

**Comment by Vance-ng-vn** [comment]
> This will not be added as in 99.9% cases it is not needed.

"On Android, Stremio does not cache status codes like 504, 502... On desktop, all errors are cached, even if the error comes from the Cloudflare server, perhaps this should be reported as a bug."

**Comment by roosht3** [comment]
> This will not be added as in 99.9% cases it is not needed.
I disagree with this statement. 100% of the time, when I change something in stremio, or make any changes to addons, it doesn't reflect on the TV. 

Today, I faced that subscription expiration message, even after purchasing and it didn't refresh, so I had no idea to watch. I had to force-stop the app and clear the cache. @TRtomasz

**Comment by KyoukanGG** [comment]
> Today, I faced that subscription expiration message, even after purchasing and it didn't refresh, so I had no idea to watch. I had to force-stop the app and clear the cache. @TRtomasz

This is the main reason a force refresh should be available. Whether it's no results because of a debrid issue, a subscription expiration warning, or even just a "download in progress" result.

**Comment by TRtomasz** [comment]
> > Today, I faced that subscription expiration message, even after purchasing and it didn't refresh, so I had no idea to watch. I had to force-stop the app and clear the cache. @TRtomasz
> 
> This is the main reason a force refresh should be available. Whether it's no results because of a debrid issue, a subscription expiration warning, or even just a "download in progress" result.

and this is better instead giving users a weapon that will increase load on addons and our servers.

**Comment by michaelhazan** [comment]
> > > Today, I faced that subscription expiration message, even after purchasing and it didn't refresh, so I had no idea to watch. I had to force-stop the app and clear the cache. @TRtomasz
> > 
> > This is the main reason a force refresh should be available. Whether it's no results because of a debrid issue, a subscription expiration warning, or even just a "download in progress" result.
> 
> and this is better instead giving users a weapon that will increase load on addons and our servers.

I'm confused by this, is adding a refresh button with a a slow mode really worse then making users go in and out of the page? having a refresh with a slow mode at least makes the refresh interaction much more intuitive rather than exiting and re-entering constantly
