### ISSUE TITLE
Auto Update feature within stremio app

### ISSUE THREAD

**Issue by mysticmac3** [Stremio/stremio-features#707]
**Stremio Version**
All versions

**Is your feature request related to a problem? Please describe.**
App not available in my region in app store

**Describe the solution you'd like**
An ability to check and update the app within stremio without having to side load or redownload new version manually from the website as the app is not available in my app store due to region restrictions

**Describe alternatives you've considered**
As of now i am going to official stremio website and downloading the latest version and reinstalling manually whenever there is a new update 

**Additional context**
Automatically check for updates whenever stremio app is opened and prompt to download and install directly without having to update via app store or download manually from website

**Comment by TRtomasz** [comment]
This will not be added to the android and android tv app, sorry.
