### ISSUE TITLE
Consoles 

### ISSUE THREAD

**Issue by primecomrade** [Stremio/stremio-features#709]
Please make Xbox and playstation stremio app I know it's a lot of work but just a suggestion... You are the best app Stremio 🙂

**Comment by DethMetalz69** [comment]
Would love a ps4 homebrew .pkg

**Comment by Julmik647** [comment]
There's a way to make Xbox possibile: while Stremio doesn't have a UWP version, you can make an UWP app that's a wrapper for Stremio web. Jellyfin for example made their Xbox app in this way.

As of PlayStation: it's probably only possibile to make it homebrew app as PlayStation doesn't have many non-game apps do it's probably not easy to make them.
