### ISSUE TITLE
repeated downloads/inefficient caching behaviour

### ISSUE THREAD

**Issue by zoenetic** [Stremio/stremio-features#711]
this might be more about torrentio than stemio, I am unsure, however:

Many series are available as a single source including all episodes.

However, I have noticed that in these situations, after playing episode one of a series (once the entire season is in the cache) playing the second episode in the series results in a new entry in the cache, and the entire torrent being downloaded again.

In other words the cache appears to be repopulated per episode even tho it already includes the entire season (or in some cases multiple seasons).

This leads to a lot of duplicate downloading and buffering.

Is this expected behaviour? If so can it be improved? If not, what am I doing wrong?

**Comment by TRtomasz** [comment]
Stremio does not download entire season never it will always download one file only
`fileIdx - number, the index of the video file within the torrent (from infoHash); if fileIdx is not specified, the largest file in the torrent will be selected`

**Comment by zoenetic** [comment]
Does it download one whole torrent, or only one media file from within a
torrent?

**Comment by TRtomasz** [comment]
just this one file

**Comment by zoenetic** [comment]
Okay, that's not the behaviour I observed but I may have misinterpreted
what I was seeing. I'll do some more tests and if there's an issue I will
revisit.

Please feel free to close this issue
