### ISSUE TITLE
Samsung 1.67

### ISSUE THREAD

**Issue by Itaih9** [Stremio/stremio-features#712]
Is it possible to update the app on Samsung Smart TV to 1.67? 

In addition, when opening the videos in an external app through the TV(streamer), on Nova player, the subtitles aren't copied and only the video is there. 

Again, if possible, please add subtitle positioning options to the app itself. Thanks!

**Comment by jaruba** [comment]
You are comparing android tv app version with samsung tv app version. It is not possible to "update to 1.6.7" because they are completely different apps built for different operating systems.

**Comment by Itaih9** [comment]
Hi, thanks for the comment. The version isn't very important, but the Samsung version does lack some great new features which you've added to the Android tv version, and I hope it will be possible to add them soon

**Comment by jaruba** [comment]
Stremio's external subtitles also cannot be sent to any external player regardless of the app platform, this is a design limitation

**Comment by Itaih9** [comment]
Got it, thanks for giving me that information. Do you think that vertical subtitle positioning is something feasible for stremio? Regardless of the TV system

**Comment by jaruba** [comment]
Subtitle positioning is a core Stremio feature, it should be implemented (progressively) across all platforms

**Comment by Itaih9** [comment]
Thanks for the quick response! Will it be universal or per episode? Thanks!
