### ISSUE TITLE
Discover button

### ISSUE THREAD

**Issue by Mastermark2015** [Stremio/stremio-features#713]
**Stremio Version**
4.4.165 Win 11

**Is your feature request related to a problem? Please describe.**
Each time i open Stremio the Discover keeps showing real debrid downloads

**Describe the solution you'd like**
I usally set this to Movies-Top Seeded would be great if it remembed the last time it was used

**Describe alternatives you've considered**
none

**Additional context**
![image](https://github.com/Stremio/stremio-features/assets/12714126/7910883a-4787-4c28-9113-d143392d9898)

**Comment by TRtomasz** [comment]
We will not add feature that will change behavior that majority of users are used to.
