### ISSUE TITLE
Can how many mins and hrs remain of a movie be shown while watching a movie. 

### ISSUE THREAD

**Issue by driftflow23** [Stremio/stremio-features#715]
**Stremio Version**
Stremio Version and OS

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Hopefully this could be added to all devices. Showing how many hrs and mins remains of a movie/show.

**Comment by TRtomasz** [comment]
Please use the acuall issue form to post your feature idea instead using only the tittle.
