### ISSUE TITLE
Trakt sync

### ISSUE THREAD

**Issue by JoyceKimberly** [Stremio/stremio-features#72]
First of all, my apologies if I’ve misunderstood something here, but I’ve gotten the stremio 4 beta, happy that we’re finally getting trakt syncing... But all it seems to do is add shows to the library, not sync the watched/unwatched status of episodes...
Is this something you’re still working on? If not I’d really like to request this feature, because to be frank, isn’t that the whole point of having trakt syncing to begin with? :P

**Comment by Ivshti** [comment]
It's supposed to scrobble, but I'm not sure if we updated it to some updates of the trakt API a while back.

This is an important feature for us, and it's supposed to be working. We'll check it soon.

**Comment by JoyceKimberly** [comment]
Scrobbling would be great, but I still think syncing of watched/unwatched status is more important, since I might watch an episode at a friend’s house or on dvd or a movie in the cinema, mark it watched on trakt, and then would like to see it marked automatically on stremio, the way popcorntime does it already, their trakt sync option actually syncs...
