### ISSUE TITLE
[Feature request] Multilanguage Support for Cinemeta

### ISSUE THREAD

**Issue by EroSDEV** [Stremio/stremio-features#720]
**Stremio Version**
Stremio 4.4.165 x64

**Is your feature request related to a problem? Please describe.**
Cinemeta is a non-optional add-on and some people noticed that it doesn't provide titles and descriptions in various languages like spanish. Introducing this feature would be highly valued by numerous individuals worldwide.

**Describe the solution you'd like**
A feature to set Cinemeta results in another languages.

**Describe alternatives you've considered**
The Movie Database Addon which retrieves content in Spanish, Italian, or French if specified but manual search still displays results in English by default.

**Additional context**
When using the search function, titles don't match if they're written in another language, and the results only appear in English. It would be a great gift for the community to include this enhancement.

**Comment by TRtomasz** [comment]
Closing as a duplicate
