### ISSUE TITLE
Picture in Picture

### ISSUE THREAD

**Issue by mateo2408** [Stremio/stremio-features#721]
Stremio Version 4.4.165,  MacOS

Can you add a picture in picture to the app, I would love to work or browse while watching a show or a movie

**Comment by lothar-cell** [comment]
I'd love to see this!

**Comment by Polarite** [comment]
1 upping this especially for pc version! would be great!

**Comment by TRtomasz** [comment]
We do not plan to make nay major changes to the current desktop app client, sorry. You can use always on top option from the tray icon menu

**Comment by stickyburn** [comment]
> We do not plan to make nay major changes to the current desktop app client

@TRtomasz is this because the web app is becoming the 'official' client?
