### ISSUE TITLE
Scrubbing doesnt work unless you press up from the subtitle icon

### ISSUE THREAD

**Issue by Itaih9** [Stremio/stremio-features#724]
**Stremio Version** Theater 1.21
Stremio Version and OS

**Is your feature request related to a problem? Please describe.**

Sometimes, pressing up from any of the toolbar buttons goes directly to the pause button, rather than going through the scrubbing line.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kKaskak** [comment]
What do you mean by that? If I understood you correctly, when you left the slider focused, it goes back to the play / pause button?

**Comment by Itaih9** [comment]
Hi. I mean that sometimes it skips the slider altogether and goes directly from the buttons below to the play/pause button. Which quite confused my mother

**Comment by kKaskak** [comment]
> Hi. I mean that sometimes it skips the slider altogether and goes directly from the buttons below to the play/pause button. Which quite confused my mother

Ok I understand, thanks for clarifying 👍🏼

**Comment by Itaih9** [comment]
Hi! Have you decided whether or not to add this feature? Thanks!
