### ISSUE TITLE
Allow retaining audio selection across all episodes of a series

### ISSUE THREAD

**Issue by Itaih9** [Stremio/stremio-features#725]
**Stremio Version** theater 1.21
Stremio Version and OS

**Is your feature request related to a problem? Please describe.**

Currently, the audio language resets every time and has to be set for each episode individually 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TRtomasz** [comment]
You can configure default audio language preference in the settings.
