### ISSUE TITLE
Desktop app should have availability of themes for full screen mode, making the full screen app look like the TV app

### ISSUE THREAD

**Issue by Sanctur2** [Stremio/stremio-features#726]
**Stremio Version**
Stremio APP Desktop

**Is your feature request related to a problem? Please describe.**
The problem is that the current version of full screen doesn't justify full screen mode, because it just removes the borders and continues the same look, the controls don't work very well with this mode.

**Describe the solution you'd like**
The solution is to bring the full screen mode based on the TV app, which has a more optimized interface for when activating the full screen mode, with similar navigation and the community is free to bring different themes to the full screen, having more elegance to who wants to put the PC on the TV and turn on this mode. The controls should also be reformed for full screen mode like a console app, like Netflix and such. Get inspired by customizing fullscreen themes like Kodi and even Playnite and transform the desktop Stremio fullscreen into a TV app with community availability bring new themes and different views to use this fullscreen on a TV

**Describe alternatives you've considered**

**Additional context**
I tried using the desktop app with the PC connected to a TV and it was simply horrible to navigate, everything is small even with several tips for enlarging the Windows icons, and using the controller to control the mouse is dated, I hope you consider bringing it the fullscreen mode more inspired by the TV app for the desktop, it doesn't need to be a copy and paste, but a more adaptive interface for TV and the community can work on themes for this mode

Stremio TV app
![screenshot_2-1024x576](https://github.com/Stremio/stremio-features/assets/103393670/eeb45a73-fadb-45f7-8095-41701633d49c)

Stremio App Desktop Fullscreen
![Captura de tela 2024-02-16 182842](https://github.com/Stremio/stremio-features/assets/103393670/aedf1596-cfea-4403-9b97-9e084b62aa70)

**Comment by TRtomasz** [comment]
These are two different designs for two different kind of devices. While TV design works the best for the tv we dont think it will be the best for the desktop app.
