### ISSUE TITLE
idle mode or screensaver for OLED screens

### ISSUE THREAD

**Issue by rat-dentist** [Stremio/stremio-features#728]
Stremio TV App
Running on Chromecast TV for Google. 

Problem
Running Stremio on a Chromecast to an OLED screen - there is risk of burn in when UI is left on or a video is paused for long periods.

Solution
An optional screensaver/idle mode - with configurable settings for when to turn it on. Ideally something as simple as a clock on a black background - that doesn't stay in the same place.

**Describe alternatives you've considered**
The chromecast built in screensaver kicks in after ten minutes (too long - and cant change it), and also displays really bright photos and imagery - which is really jarring at night. Ideally you want something that is low brightness - non static imagery (or black - to save those pixels) - and configurable time to activate.

**Comment by sutulustus** [comment]
+1

**Comment by TRtomasz** [comment]
IF you leave video paused it your device will still enter the ambient mode after like 10 minutes  we do not prevent this
