### ISSUE TITLE
Web Stremio iOS 

### ISSUE THREAD

**Issue by trcisen** [Stremio/stremio-features#729]
Hello,
I just figured out a way to watch series on iOS with subtitles without external player. If you can add playsinline attribute to video tag in html file we can easily watch. Otherwise iOS own player makes the video full screen without subtitles.
Is it possible for you to add that attribute in video tag?

Best Regards

**Comment by charliesheen14** [comment]
If you download vlc, and change the video player in settings to vlc you"ll have no problems with audio and subtitles !

**Comment by trcisen** [comment]
Yes I can use VLC to watch but VLC doesn’t add subtitles automatically. So it will be much better if Stremio player is adapted to safari.

**Comment by charliesheen14** [comment]
Well thats weird because in my case it does add subs automatically.

**Comment by TRtomasz** [comment]
We do not get what is the issue here, subtitles are working just fine on ipad.
