### ISSUE TITLE
Couple ideas

### ISSUE THREAD

**Issue by NoName033** [Stremio/stremio-features#730]
1.6.7, Android TV

Currently, I have to select the audio for each episode of the show I'm watching, it would be great if the audio was mantained once selected.

A button to skip openings and a randomize button would be great, sometimes a show has too many episodes (e.g: simpsons) and you just want to watch an episode, not select one of the hundreds of them. 

Having to skip the opening of a show is really annoying, a button to skip it would be great.

A version for WebOS (aka LG TVs) would be good too.

**Comment by TRtomasz** [comment]
Please use the form to request feautres, and keep in mind one issue = one feature requests or we will not be able to maintain this repository.
 If you want to have audio selected for each episode just select default audio language in the settings.

**Comment by jaruba** [comment]
Stremio is now available on 2020+ LG TVs: https://blog.stremio.com/stremio-is-now-available-on-lg-tvs-for-models-2020/
