### ISSUE TITLE
better external player firestick

### ISSUE THREAD

**Issue by kopred24** [Stremio/stremio-features#732]
on the firestick i use this app for my vod but i want to use it with a external player but on a different app i want to use i have another different external player and both apps use one external player is there any way of a better option to pick my external player.

please thanks very much.

**Comment by TRtomasz** [comment]
You pick what external player will be used, not the app so just select different one.

**Comment by kopred24** [comment]
if a different app has allready picked a player to use then streamio will
use that one and not the one i want.

**Comment by kopred24** [comment]
cud you add summit like this.

on the firestick if a different app has allready set a external player
streqmio will use the same player.

no worries thanks anyway
