### ISSUE TITLE
Vertical subtitle positioning 

### ISSUE THREAD

**Issue by Itaih9** [Stremio/stremio-features#739]
**Stremio Version**
Stremio Version and OS
Samsung smart tv latest version

**Is your feature request related to a problem? Please describe.**

Will vertical subtitle aligning be available? Thanks

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TRtomasz** [comment]
Your issue does not contain any details other than title please create new one with all the required details

**Comment by Itaih9** [comment]
Hi, it includes details of the request
