### ISSUE TITLE
Option to disable the pop-up when the frame rate is matched

### ISSUE THREAD

**Issue by isgapetti** [Stremio/stremio-features#740]
**Stremio Version**
Stremio 1.6.7 on Nvidia Shield Pro 2019

**Is your feature request related to a problem? Please describe.**
When the "Frame Rate Matching" setting is enabled, a pop-up appears on the screen every single time a video is played. We do not need to be reminded every single time that the frame rate is matched.

**Describe the solution you'd like**
The option to simply disable this pop-up.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by TRtomasz** [comment]
If it will not be possible to enable frame rate matching then popup will not be displayed.

**Comment by isgapetti** [comment]
I don't understand.

Other applications like Plex and Kodi have frame rate matching but no pop-ups are displayed.
