### ISSUE TITLE
Vertical subtitle positioning

### ISSUE THREAD

**Issue by Itaih9** [Stremio/stremio-features#741]
**Stremio Version**
Stremio Version and OS
Samsung smart tv latest version ANDROID TV

**Is your feature request related to a problem? Please describe.**
I am frustrated when the subtitles are at the bottom of the screen and i can't vertically align them higher to be able to watch whats going on on the screen while reading the subtitles, because of my tunnel vision

**Describe the solution you'd like**
Vertical position alignment options

**Describe alternatives you've considered**
Using nova player or the default samsung tv player which have this option

**Additional context**
Thanks for the effort

**Comment by kKaskak** [comment]
Is this the feature that you want to be added? Did I understand you correctly?
<img width="261" alt="Screenshot 2024-02-28 at 20 45 57" src="https://github.com/Stremio/stremio-features/assets/117831817/27c4ecda-1c50-4055-aeaa-96c2cc1ef7cd">

**Comment by Itaih9** [comment]
Hi! I believe so, yes. And ideally it would be accessible within each episode or film, and remember the position, across everything or across all episodes of the same series. Thanks!

**Comment by Itaih9** [comment]
Hi! Did you decide whether or not to add this feature? Thanks!

**Comment by TRtomasz** [comment]
This will be added in the next release, please stay tuned you should have it soon :)

**Comment by Itaih9** [comment]
Hi! I see you've added the feature! Thank you so much! But currently it's not working on my device, is it only for me?

In addition, I think it would be good to be able to access the subtitle menu through the episode and not only the main menu.

2 more things, would it ever be possible to view the video and subtitles as well in an external player? And would you add an option to select audio language for a title so it doesn't have to be changed every episode? Like for anime. Thanks so much and keep up the good work!

**Comment by kKaskak** [comment]
What do you mean by not accessible from episode?

**Comment by kKaskak** [comment]
> Hi! I see you've added the feature! Thank you so much! But currently it's not working on my device, is it only for me?
> 
> In addition, I think it would be good to be able to access the subtitle menu through the episode and not only the main menu.
> 
> 2 more things, would it ever be possible to view the video and subtitles as well in an external player? And would you add an option to select audio language for a title so it doesn't have to be changed every episode? Like for anime. Thanks so much and keep up the good work!

Can you tell me what movie / series you've tried watching and it wasn't working?

**Comment by Itaih9** [comment]
Currently only language selection is available from within the episode, not additional subtitle options,
I'm trying to watch attack on titan on 1.6.9 mibox
 Checking out a few other titles, it seems that sometimes the subtitles are adjusted properly, sometimes only the size changes but not the position, and often most of the selectable subtitles don't work at all. Thanks!

**Comment by kKaskak** [comment]
<img width="1666" alt="Screenshot 2024-04-16 at 13 06 45" src="https://github.com/Stremio/stremio-features/assets/117831817/6a674c7a-f690-43e5-95ce-5e049eb79db9">

Clearly, you can choose the vertical positioning from the episode?

**Comment by kKaskak** [comment]
Or am I missing something? Also I haven't seen any reports saying that the feature is broken yet.

**Comment by Itaih9** [comment]
https://drive.google.com/file/d/1CqrsooiwlQ_LlsNkBec6cPahom01vmAR/view?usp=drivesdk
Here is a video of how it is for me. I also haven't been able to access the menu you showed from within an episode

**Comment by kKaskak** [comment]
Oh because you are using the android TV app not the Samsung app. :)

> Stremio Version
Stremio Version and OS
Samsung smart tv latest version

You mentioned before that you use the Samsung tv app. Please if possible be more specific next time. This feature was implemented in the Samsung TV app, not the Android TV app. If your TV is smart, you can install the app from the official Samsung app store.

**Comment by Itaih9** [comment]
I live in two houses so it's different for each house haha

**Comment by Itaih9** [comment]
I tried on the Samsung tv as well, on the latest version. I can see that menu, but it appears that no subtitles are selectable. I've tried attack on titan for example

**Comment by kKaskak** [comment]
> I tried on the Samsung tv as well, on the latest version. I can see that menu, but it appears that no subtitles are selectable. I've tried attack on titan for example

You need to wait a moment for them to load, if they not show up exit the menu wait a second and enter again. Be sure your app has the latest update.

**Comment by Itaih9** [comment]
Hi! The subtitles are still not loading properly in, for example, the anime solo leveling. Could you try it and let me know? Thanks!

**Comment by kKaskak** [comment]
> Hi! The subtitles are still not loading properly in, for example, the anime solo leveling. Could you try it and let me know? Thanks!

Load normally for me
<img width="1675" alt="Screenshot 2024-04-30 at 16 58 08" src="https://github.com/Stremio/stremio-features/assets/117831817/75f0f9cf-3acc-4b91-80ca-cbcfad8c2203">

<img width="1674" alt="Screenshot 2024-04-30 at 16 59 36" src="https://github.com/Stremio/stremio-features/assets/117831817/a5cc3dad-c154-4faa-93fa-758a88b0198f">

**Comment by Itaih9** [comment]
Trying to watch the office now as well and same issue. Using the Samsung app version 1.3. What do you think could cause this? Thanks!

**Comment by kKaskak** [comment]
> Trying to watch the office now as well and same issue. Using the Samsung app version 1.3. What do you think could cause this? Thanks!

Can you please check if the server is online and running in the settings, just try to refresh it?  Are the subtitles not loading up and returning an error when you click on a specific subs option?

**Comment by Itaih9** [comment]
Yep the server is online, there's no errors it just says none for subtitles

**Comment by kKaskak** [comment]
> Yep the server is online, there's no errors it just says none for subtitles
So you see this?
<img width="1670" alt="Screenshot 2024-04-30 at 17 10 16" src="https://github.com/Stremio/stremio-features/assets/117831817/6b3f8297-d9b6-4deb-907b-ff1b3ba67e68">

**Comment by kKaskak** [comment]
Exit the menu and enter again. Wait a few seconds before doing so. When you instantly try to enter the menu, the sub options haven't loaded up yet for the movie / series you are watching.

**Comment by Itaih9** [comment]
Yeah it looks like that

**Comment by Itaih9** [comment]
I've tried it a few times for a few files, even after 2 minutes it didn't change

**Comment by kKaskak** [comment]
> I've tried it a few times for a few files, even after 2 minutes it didn't change

Really strange here is a demo how it works for me -->

https://github.com/Stremio/stremio-features/assets/117831817/2d726da3-50c8-4f50-a795-a1b5516bba43

**Comment by Itaih9** [comment]
Yeah I'm pretty much doing the same? Is that on the TV or a TV emulator?

**Comment by kKaskak** [comment]
> Yeah I'm pretty much doing the same? Is that on the TV or a TV emulator?

This is on emulator. But it works fine on TV I'm using for testing too

**Comment by Itaih9** [comment]
Interesting, is there any more information you need?

**Comment by kKaskak** [comment]
> Interesting, is there any more information you need?

If you can provide the exact model of your TV. That would help a lot

**Comment by Itaih9** [comment]
It is a samsung smart tv UE55CU700UXMI

**Comment by Itaih9** [comment]
hi! Is there any update upcoming for either system? Thanks!

**Comment by kKaskak** [comment]
As I mentioned before, subtitles appear to work normally for Samsung smart TV and for Android TV. The vertical positioning on android TV is not implemented yet so I can't give you any exact dates when it will be available.

**Comment by kKaskak** [comment]
> hi! Is there any update upcoming for either system? Thanks!

I will look into your model issue.

**Comment by Itaih9** [comment]
Hi, well unfortunately subtitles are not appearing for me in either system, am I the only one reporting this issue? Thanks

**Comment by kKaskak** [comment]
> Hi, well unfortunately subtitles are not appearing for me in either system, am I the only one reporting this issue? Thanks

Have you tried a different stream? What add-ons are you using?

**Comment by Itaih9** [comment]
![Uploading Screenshot_20240522_124838_Stremio.jpg…]()
Hi, I've tried multiple streams, I've attached the list of installed addons. Thanks!

**Comment by kKaskak** [comment]
Try uploading the photo again since it failed. Before posting the coment, wait for it to finish up

**Comment by Itaih9** [comment]
![Screenshot_20240522_124838_Stremio](https://github.com/Stremio/stremio-features/assets/157367721/20af5441-8ab2-4296-b059-9b4ca45a4c75)
How's this?

**Comment by Itaih9** [comment]
Hi, it seems that the Samsung tv version works now for the subtitles, but the mibox version still doesn't support it

**Comment by kKaskak** [comment]
If it's not implemented yet, please stay tuned for any new updates on our blog. Thank you.

**Comment by Itaih9** [comment]
Hello again :) any news on when this is supposed to be added to android tv? Thanks!

**Comment by TRtomasz** [comment]
it has been in the android Tv app for the very long time 
![image](https://github.com/Stremio/stremio-features/assets/40594253/52951e2b-9d3a-4141-a73f-36d16007ad2a)

**Comment by Itaih9** [comment]
Hi! Does it work? I've tried adjusting this setting but either subtitles appear in the default position or don't appear at all

**Comment by TRtomasz** [comment]
The higher value of the Vertical offset the higher will be subtitles presented on the screen

**Comment by Itaih9** [comment]
Yes of course :). No change was apparent for me. Let me check again

**Comment by Itaih9** [comment]
It appears to work for some titles and some not, not sure what the cause is. For example curb your enthusiasm season 1, "addic7ed" subtitles don't work at all. But some embedded subtitles do work

**Comment by Itaih9** [comment]
Hi, how are you? Still having issues with subtitles. Many titles display none for subtitles even though there should be subtitles in the file. For example, Tower of God season 1 episode 3, any file that explicitly contains subtitles. Version theater 1.3.0

**Comment by Avtera** [comment]
when this will available for pc?

**Comment by Itaih9** [comment]
Hi, for some TVs (I use android tv on xiaomi smart tv) the advanced subtitle options are only accesible through the main menu. Can they be added to the in video menu? Thanks!
