### ISSUE TITLE
[Feature request - Android] Availability to cast to DLNA TVs

### ISSUE THREAD

**Issue by Tienssy** [Stremio/stremio-features#743]
**Stremio Version**
v1.6.9, Android 11

**Is your feature request related to a problem? Please describe.**
I'm not able to cast to TVs via DLNA inside Stremio app directly.

**Describe the solution you'd like**
Easily cast to TVs DLNA via additional button (choose cast instead of play).

**Comment by TRtomasz** [comment]
DLNA cast will not be fixed only recommended way of casting is via chromecasting.
