### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by Dazsnaz** [Stremio/stremio-features#745]
**Stremio Version**
Stremio Version and OS

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [. Profiles would be a great addition..]

**Describe the solution you'd like**
A clear and concise description of what you want to happend

**Describe alternatives you've considered**

**Additional context**

**Comment by TRtomasz** [comment]
https://github.com/Stremio/stremio-features/issues/622
