### ISSUE TITLE
Native PiP support for Android

### ISSUE THREAD

**Issue by VantageXV** [Stremio/stremio-features#746]
**Stremio Version**
Stremio Version and OS

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I’d like to suggest native PiP support for Android. Stremio is a great application however personally I, and many others, like to type messages and or multi-task when watching our favourite shows. PiP is very useful and apps such as YouTube and Netflix have shown the luxury of this feature. 

**Describe alternatives you've considered**
I’ve used external player for PiP (via VLC) however the switch is by no means seamless and I’ve noticed with higher file sizes, VLC tends to buffer quite a lot and cause some visual bugs and other issues when used for PiP

**Additional context**

**Comment by TRtomasz** [comment]
please try using a search before creating a feature request https://github.com/Stremio/stremio-features/issues/471
