### ISSUE TITLE
Spoiler image Adding an option removes it

### ISSUE THREAD

**Issue by Smqp331** [Stremio/stremio-features#747]
.ll
 Last version stremio windows11
I wish an option would be added that would allow removing episode images because they spoil the enjoyment of the episodes
![IMG_7447](https://github.com/Stremio/stremio-features/assets/162115742/9975660d-2941-441b-aabb-7336146b5b75)

**Comment by TRtomasz** [comment]
Sorry, this kind of feature will not added anytime soon.
Ps i dont think this can spoil anything as a single image lacks context
