### ISSUE TITLE
Notifications for Library content availability 

### ISSUE THREAD

**Issue by wenchiee** [Stremio/stremio-features#749]
**Stremio Version**
Android TV

**Is your feature request related to a problem? Please describe.**
Although it's a nice feature to have, new episode aired notifications are basically useless unless someone uploads said content straight away for the addons to scrape. Sometimes this takes a long time or they never get uploaded so it's increasingly frustrating for users who watch on-air shows that get left with a cluttered Continue Watching filled with numbered titles they cannot watch mixed in with whetever other show or film they started watching.

**Describe the solution you'd like**
It would be more functional if Stremio could 'communicate' with the installed addons and return notification only when that show or film has viable link available. This could perhaps be added under Library for films and shows to enable 'Notify on Airing' or 'Notify on Availability'

**Comment by TRtomasz** [comment]
This is not possible, stremi do not upload content we dont know when or if it is available
