### ISSUE TITLE
Subtitle preview in sub list

### ISSUE THREAD

**Issue by DaRkViVi** [Stremio/stremio-features#751]
**Stremio Version**
Any

**Is your feature request related to a problem? Please describe.**
Sometimes the files doesn't contain properly named subtitles, so it's always a pain to test each one till you find the one in the language you are looking for.

**Describe the solution you'd like**
I would like to have a small preview of the highlighted subtitle in the sub list (like the first 2-3 sentences) so you can understand if this is the language you are looking for.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by TRtomasz** [comment]
Sorry, this will not be implemented  as it would require additional resources from our side which are not free.

**Comment by DaRkViVi** [comment]
> Sorry, this will not be implemented as it would require additional resources from our side which are not free.

Thanks for the fast reply, I can understand the problem on your side. :)
