### ISSUE TITLE
Split spanish audio tracks between latin (South America) and castillian (Spain-EU)

### ISSUE THREAD

**Issue by trolles** [Stremio/stremio-features#753]
So, in the PC version you can select which audio track plays but in web app through TV you can't. Audio gets selected according to the audio track you have selected in settings as default (if it is available). 

Problem is there is only one spanish option when selecting audio track in settings but many movies have two spanish audio tracks (latin and castillian). Would it be possible to differentiate those audio tracks in Stremio settings so if I mark castillian that is the one selected by web app through TV and not the latin one?. 

Cheers.

**Comment by TRtomasz** [comment]
While this might be possible for subitltes since the biggest subtitles provider uses separate codes for both languages, this is not possible for audio tracks as they come with video and their names are not standarized.
