### ISSUE TITLE
[UX] Long press Content to hide

### ISSUE THREAD

**Issue by atwalg2** [Stremio/stremio-features#755]
**Stremio Version**
All versions

**Is your feature request related to a problem? Please describe.**
I see too much content I've seen through the app, or else where, or that I would never be interested in watching myself. This is noise to my eyes and I would like to hide it so i don't need to see it presented to me ever again

**Describe the solution you'd like**
Not sure if all these are feasible with the current architecture 

Ideal solution:
Long Press show or movie -> hide from search -> saves to shared Stremio setting on backend

Second best solution:
hide list stored on client side, and sent to endpoints to use in their Catelog items fetching queries

Third best solution: (100% feasible)
Client side only hiding (db query not effected)

**All 3 of these solutions are better than none at all**

Hidden content could be added to it's own category with the option to unhide it, or in some other list view with a basic text search functionality built in

**Describe alternatives you've considered**
- Building my own catalog that allows me to hide stuff like this for myself from an external app 
     - but would only work for my own catalog and no one else's

**Additional context**

**Comment by TRtomasz** [comment]
Content hiding is not possible, this will not be implemented.
