### ISSUE TITLE
Add filters to catalogs

### ISSUE THREAD

**Issue by atwalg2** [Stremio/stremio-features#756]
**Stremio Version**
All versions (mobile android, windows, web)

**Is your feature request related to a problem? Please describe.**
Sorting sucks right now, allow this functionality please

**Describe the solution you'd like**
- SDK Sorting functionality, based on sort categories selectable from the UI (enabled via json config for plugin)
- Default client side sorting (if plugin doesn't support it, show your own default sorting)

**Describe alternatives you've considered**
Using an external site to find content

**Additional context**

**Comment by TRtomasz** [comment]
Addons can implement sotring by additional genres.
