### ISSUE TITLE
[Easy win] Allow subtitle Text shadow to match VLC android highly legible subtitles

### ISSUE THREAD

**Issue by atwalg2** [Stremio/stremio-features#758]
**Stremio Version**
Android TV (Nvidia Shield)
All other platforms (but probably less impactful)

**Is your feature request related to a problem? Please describe.**
- Subtitles can be hard to read for certain content (anime being one)
- Built in solutions don't go far enough (although very close)

**Describe the solution you'd like**
- Add the ability to set a text shadow (color, and size maybe) on android tv (and others if possible) via the same subtitle settings
- Ideally able to match what VLC player has

Bonus points:
user can edit subtitles in built in player view
subtle display profiles (probably only need 2 max) for different content - user selectable with a default

**Describe alternatives you've considered**
Open content in VLC player, but this is janky sometimes, and you lose all tracking on media watching progress in Stremio
I currently use the options provided, but it's considerably easier to read via VLCs subtitles

**Additional context**

**Comment by TRtomasz** [comment]
You can modifie subtitles background in the app settings, also subtitles size is a setting.
