### ISSUE TITLE
Subtitles Position

### ISSUE THREAD

**Issue by elgreko16** [Stremio/stremio-features#76]
A nice missing feature is the on screen change subtitle position, to move it to top, bottom, etc.

Think about it friends!!!

**Comment by mistergii** [comment]
It seems like that they don't really care what users want. Adding subtittles position isn't that big change in app, I am asking for it a few months now....

**Comment by ambarpathak11** [comment]
Yeah i want to adjust the position of subtitles but i cant.
It is too awkward that subtitles show up in the wrong position and cover the movie scene,it should be displayed like the youtube ones.

**Comment by Sunnysky** [comment]
My feet on the ottoman get in the way of the subtitles.  Common guys.
