### ISSUE TITLE
Posters

### ISSUE THREAD

**Issue by koliune** [Stremio/stremio-features#763]
**Stremio Version**
Stremio 4.4.165, Windows 10

**Is your feature request related to a problem? Please describe.**
Yes, the problem is that you put the latest poster for shows as a banner, which spoils many shows. For example, I started watching Modern Family, which has 11 seasons, obviously things will change in 11 years, but I don't wanna know who the new characters are or who is going to leave the show because the newest poster is always there. It's a spoiler.

**Describe the solution you'd like**
For TV shows, you should put the poster for the first season as the main poster / banner. This would not spoil shows for anyone. If possible, maybe have the poster change every time I enter a new season. For movies, there doesn't need to be a change obviously.

**Describe alternatives you've considered**
I have no alternatives.

**Additional context**
The previous example is enough proof. It got spoiled for me that a character is going to have a baby, how the characters will look when they get older, new characters and who they're next to shows me who they will date, etc.

**Comment by TRtomasz** [comment]
This will not be changed. Also i dont think looking at a poster with people you dont know will spoil anything since you dont know them. What if this was cast from 1st season on the poster? Would it spoil anything since wow it would be showing whole cast from the 1st season you are about to watch?
