### ISSUE TITLE
Exo Player deprecated

### ISSUE THREAD

**Issue by seddik88** [Stremio/stremio-features#764]
FYI if I am not mistaken Stremio uses Exo player...

Exo Player is deprecating as of end of March 2024.. They already stopped working on it it seems

https://github.com/google/ExoPlayer.

Latest update was 7 month ago and they don't intend updating it any more, so it's possible it will start getting worse...

**Comment by TRtomasz** [comment]
Stremio migrated to media3 long time ago.
