### ISSUE TITLE
Re-Sync Subtitles function in Stremio App on Samsung TV

### ISSUE THREAD

**Issue by lmodinis** [Stremio/stremio-features#766]
**Stremio Version**
Latest Stremio App on Samsung TV

**Is your feature request related to a problem? Please describe.**
If the subtitles are out of sync, there's no option to delay or antecipate the timming (as there is in the Stream windows version).

**Describe the solution you'd like**
Implement functionality to re-sync the timing of the subtitles (similar to Windows version)

**Describe alternatives you've considered**

**Additional context**

**Comment by TRtomasz** [comment]
will be added in the next release, please stay tuned :)

**Comment by lmodinis** [comment]
Thank you very much for your great work!!
