### ISSUE TITLE
Ability to disable add-on's

### ISSUE THREAD

**Issue by Andre20259** [Stremio/stremio-features#768]
**Stremio Version**
Version 1.6.10 on android

I use stremio with real debrid and torrentio but sometimes there aren't any streams available with rd, so to see the show I wanted I have to install a add-on without the Rd feature. 

For example next to the button to uninstall a add-on there was a check box with the ability to put the add-on to "sleep" and not show on the available streams list. 

Another solution would probably be a way to choose the order add-ons show on the screen.

**Comment by TRtomasz** [comment]
You can have same addon installed mutiple times additionally on the top in each app there is addon selector so you can limit results to a specific addon
