### ISSUE TITLE
Audio offset

### ISSUE THREAD

**Issue by stormer32** [Stremio/stremio-features#769]
**Stremio Version**
Stremio Version and OS
1.6.7 for Android TV 
**Is your feature request related to a problem? Please describe.**
Sometimes when watching a movie or TV show on Stremio, the audio is out of sync with the video. This seems to be more common when a surround sound audio track is being played. 

**Describe the solution you'd like**
I would like an audio offset setting to be added to the Stremio app, so that audio sync problems can easily be resolved. This could be implemented in a similar way to the subtitles delay adjustment that already exists in Stremio. The audio offset should allow adjustment in both directions (+ and -) 

**Describe alternatives you've considered**

**Additional context**

**Comment by charliesheen14** [comment]
Do you have this problem while you have a surround sound at home ? Otherwise just find another stream without surround sound i suppose.

**Comment by stormer32** [comment]
Thanks for your reply. My surround sound works ok. It's just that when I play a source with surround sound on Stremio the audio is out of sync. Unfortunately my surround sound system doesn't have a way of adjusting the sync.
If an audio offset was available in Stremio it would solve the problem. I know some apps have a similar adjustment (Tivimate for example).
I can watch without surround sound ok, but would much prefer to watch with surround sound if possible.
Thanks
________________________________

**Comment by charliesheen14** [comment]
I also have this problem, but recently added the annatarRD addon. And never experienced the problem again. I have a 7.1 onkyo and it works amazing. The problem happened mostly with big streams on torrentioRD. So maybe try annatarRD for a short term solution! And i hope they add a offset!

**Comment by stormer32** [comment]
Thanks for your suggestion. I've given this a try but unfortunately it doesn't make any noticeable difference. I'm using a Panasonic 5.1 surround sound system
________________________________

**Comment by TRtomasz** [comment]
closing as a duplicate
