### ISSUE TITLE
Lock genres (or subselections) when changing providers 

### ISSUE THREAD

**Issue by dblviking** [Stremio/stremio-features#771]
**Stremio Version**
Stremio android tv 1.6.7 on firestick 4K max

**Is your feature request related to a problem? Please describe.**
If you want to check comedies from different movie providers, you have to change it back to comedy every time

**Describe the solution you'd like**
Because of the linked layout, if you change a parent ie Movies, your “child” selections will reset every time. 

**Describe alternatives you've considered**
None

**Additional context**
It looks like a core UI design problem but why should checking for ie) documentaries or comedies on all platforms be so difficult?

**Comment by TRtomasz** [comment]
Changing core behavior of the app when everyone is used to it is not possible.
