### ISSUE TITLE
[Android TV] Remove clearart logo on Android homescreen channel posters

### ISSUE THREAD

**Issue by izao88** [Stremio/stremio-features#773]
Whenever you add Stremio lists to Android TV home channel a cropped version of the clearart logo of the TV Series appears on the bottom left of the poster. Would be nice if you could stop this from happening.

**Comment by jaruba** [comment]
i don't understand how this is a feature request, maybe u want to report a bug? then use https://github.com/Stremio/stremio-bugs

i also don't understand what you are trying to explain, if u do report it as a bug, include a screenshot or a video of the issue to make it clear / obvious
