### ISSUE TITLE
Ability to disable plugins without uninstalling

### ISSUE THREAD

**Issue by FreeWoRLD83** [Stremio/stremio-features#774]
I was wondering if it would be possible to be able to disable plugins, instead of completely uninstalling it.

In cases where some of the plugins experience downtime, users usually depend on alternative (with similar functionality) plugins.

Keeping multiple plugins installed and in active mode is an option, however doing this causes to have duplicate results on day to day usage. It also creates unnecessary traffic with duplicate results.

Having ability to disable some plugins (and keeping it installed and setup) and enabling them when needed, would I think be great. Perhaps it would also save bandwidth on the plugin provider, since some certain plugins are down and massive demand occurs on trying to install alternative plugins at that time. 

Thanks again for this wonderful project. I love it.

**Comment by TRtomasz** [comment]
you can filter results in each app, by filtering them from the top dropdown.
