### ISSUE TITLE
Android TV's stream list cache issue

### ISSUE THREAD

**Issue by teemokin** [Stremio/stremio-features#777]
**Stremio Version**
Stremio Android TV OS

**Is your feature request related to a problem? Please describe.**

It seems that the stream list caching in the Android TV app is causing No Stream Found issue.
For example, when there is an issue with the addon server, streams get cached(no stream found), and later when reopened, due to the cached stream list, it doesn't return a new list.

**Describe the solution you'd like**

I tell people to clear the app cache, but most of them don't know how to do it.
It's unreasonable to ask people who don't even know what cache is to clear it.
I think there needs to be an option to clear cache on the settings main page. plus restart as well. 

**Additional context**
this is exactly the same stuff that I wrote on Discord's #dev channel by the way.

**Comment by charliesheen14** [comment]
+1

**Comment by TRtomasz** [comment]
This will not be implemented. Addons decides how long their responses should be cached and their set corresponding headers.
Imagine we ignore this and we will overload the addons

**Comment by teemokin** [comment]
> This will not be implemented. Addons decides how long their responses should be cached and their set corresponding headers. Imagine we ignore this and we will overload the addons

I'm not suggesting turning off the cache feature.
To be precise, it's something that can be experienced in the Android TV app only I guess.
I probably didn't explain it accurately. To elaborate further, once the 'some-addon.com/streams/movie/tt00000.json' is saved, it doesn't refresh when it needs to, which is why I'm suggesting clearing the cache.

The reason is that some addons like created by myself don't have a 99% uptime, and when the server(scraper) goes wrong with an empty stream list or wrong stream links get cached, there needs to be a way to fix it.

Of course, just telling them to clear the cache should work, but since people struggle with how to and where to do it, I'm asking for a clear cache option in the Streamio app. I heard that Streamio was developed for regular users to use easily, so I think having this feature would be beneficial, which is why I'm suggesting it.

Thank you for your attention and consideration.
