### ISSUE TITLE
Suggestion: random episode selector for TV shows

### ISSUE THREAD

**Issue by PolarisFluff** [Stremio/stremio-features#778]
**Stremio Version**
Whatever the current version on windows 10 is

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a button on the episode selection screen of TV shows to open a random episode.

**Describe alternatives you've considered**
idk

**Additional context**
I like to watch random episodes of shows that I've watched a ton

**Comment by TRtomasz** [comment]
We will not add features that will clutter the UI without any big benefit to the majority of the users.

**Comment by PolarisFluff** [comment]
I don't think it would clutter up much. I'm thinking a small button right here? Or on the bottom left near the add to library button
![image](https://github.com/Stremio/stremio-features/assets/81457784/70e2aa2d-e4a6-4e74-b081-5120df04e1e8)
