### ISSUE TITLE
[Request] Touch Bar Media controls

### ISSUE THREAD

**Issue by ben3man** [Stremio/stremio-features#779]
**Stremio Version**: Stremio Version 4.4.168 on MacOS 

**Problem**: Currently, navigating through media playback controls on the Stremio app for Mac requires using the mouse or keyboard shortcuts. This can be inconvenient especially on devices like MacBooks equipped with Touch Bar functionality but with no use for It in the app.

**Solution**: Implement media playback controls directly onto the Macbook Touch Bar for seamless navigation during movie playback. This would include essential controls such as play/pause, skip forward/backward, and possibly a timeline scrubber for precise playback adjustment.

**Alternatives Considered**: One alternative solution could be expanding the functionality of existing keyboard shortcuts or allowing users to customize their preferred controls. However, these options may not offer the same level of convenience and immediacy as integrating controls directly onto the Touch Bar.

**Additional Context**: By incorporating media controls onto the Touch Bar,I think users can enjoy a better experience on Stremio for Mac. I'm a massive fan of the app but the Touch Bar being redundant has bugged me for some time and I believe this feature would be a good way to optimise the app's compatibility with Mac.

**Comment by TRtomasz** [comment]
Apple has removed touchbar from its products i dont think there is a point in implementing this now
