### ISSUE TITLE
Escape key should navigate back - doing the same as clicking "back"

### ISSUE THREAD

**Issue by lsoarestd** [Stremio/stremio-features#78]
I often open a movie metadata and regret and want to go back. By instinct, I click Esc but nothing happens. This should work also when playing a movie, etc.
Thanks!

**Comment by Rapso** [comment]
It works in that way, what device and stremio version you use?

**Comment by lsoarestd** [comment]
It seems it was a temporary bug. It started working later and it's still ok.
![image](https://user-images.githubusercontent.com/20595884/35129520-edf5a852-fcb3-11e7-85c6-1beae5c8029c.png)
in a Windows 10 PC
