### ISSUE TITLE
Forced English Subtitles

### ISSUE THREAD

**Issue by MikeCumbria** [Stremio/stremio-features#784]
My current Stremio Versions 1.6.8 Fire Stick and 1.6.12 Android mobile 

There's currently no option in Stremio's settings to set as Default subtitle language "Forced" or "Forced English" as listed on someother apps/players.

In the built in Stremio player you can sometimes find listed English Forced subs to select, but you can't set it in Stremio's settings to default to this which would be really useful.

Forced subtitles allow you to watch a show in English, that has occasional foreign language parts were the subs only pop up for those parts. For instance I'm watching Ozark right now, often the entire episode is in English, but some episodes when the Mexicans talk, you've got to pause and rewind then look for the subs. Sometimes there's Forced English to turn on manually or you just turn on English if not. But it would be better if in Stremio's list of subtitles languages to choose from, if you could include Forced please.

Thanks 👍

**Comment by isgapetti** [comment]
+1

**Comment by TRtomasz** [comment]
This is not possible as embedded subtitles are not standarized we do not know which ones are 'forced'

**Comment by MikeCumbria** [comment]
It's nothing to do with embedded subtitles. Forced subtitles are a file the same as any language. It's definitely possible to do this with other apps/players.

**Comment by isgapetti** [comment]
> This is not possible as embedded subtitles are not standarized we do not know which ones are 'forced'

+1. This has nothing to do with embedded subtitles. Forced subtitles have the words "Forced" in parenthesis like this:
**English (Forced)**

**Comment by mindgam3s** [comment]
yes. please!

**Comment by KeKyKo** [comment]
I know this is an old post but, YES PLEASE :)
