### ISSUE TITLE
Microsoft stremio app

### ISSUE THREAD

**Issue by KadenStav** [Stremio/stremio-features#785]
Is it possible for you guys to add a stremio app the Microsoft store? 
you should. It would probably increase user count. Aswell as allowing people to use it on Xbox, and showing up while people are browsing on the Microsoft store. making it more accessible.

if there is a reason why that’s not possible I’d be interested as to why that is.

**Comment by jaruba** [comment]
if an app is in the microsoft store, then it doesn't mean that it is available on xbox too
regardless, we tried years ago and microsoft refused it

**Comment by Julmik647** [comment]
There's a way to make it possibile: while Stremio doesn't have a UWP version, you can make an UWP app that's a wrapper for Stremio web. Jellyfin for example made their Xbox app in this way.

On Microsoft Store on Windows you can just publish already existing Windows version. Microsoft allows non-UWP apps to be publisher in Microsoft Store. But there's one problem:

> regardless, we tried years ago and microsoft refused it
