### ISSUE TITLE
Allow control of Stremio via HTTP

### ISSUE THREAD

**Issue by seddik88** [Stremio/stremio-features#792]
Would be nice to use a remote app like Yatse on Android or Kore to control the Stremio App. With Stremio installed on a Raspberry Pi or even connecting a PC to an external monitor to watch tv it would be useful to use our phone as a remote.

Control via HTTP will allow us to use remote controls on stremio creating a web interface.

**Comment by TRtomasz** [comment]
Stremio main intenion is to make it as simple as possible, such features would require a lot of work and would be used by very small percentage of our users.
