### ISSUE TITLE
samsung tv: adjust subtitles offset

### ISSUE THREAD

**Issue by igorcafe** [Stremio/stremio-features#793]
**Stremio Version**
Latest Stremio for Samsung TV

**Is your feature request related to a problem? Please describe.**

Yes. Many times the subtitle is 10 sec off and its unwatchable.

**Describe the solution you'd like**
The feature that most versions of stremio have.

**Describe alternatives you've considered**
No alternative.

**Comment by TRtomasz** [comment]
Hello, will close the issue for now, this will be included in the next release that is coming soon!

**Comment by igorcafe** [comment]
@TRtomasz thank you!
Will it be announced somewhere? Just so I can update it here :)

**Comment by kKaskak** [comment]
> @TRtomasz thank you! Will it be announced somewhere? Just so I can update it here :)

You should've received an update already 👍🏼
