### ISSUE TITLE
Skip To Feature

### ISSUE THREAD

**Issue by qbrotherton** [Stremio/stremio-features#795]
**Stremio Version**
Stremio for Firestick

I have used the VLC player and on that player, it has a "Skip To" certain time feature and when using Stremio without an external player, this isn't possible. This feature is very handy if the movie/tv show restarts from the beginning and the part you were at is towards the end.

**Describe the solution you'd like**
The solution is to add this feature under the settings during the movie/tv show. VLC Player is a great example to follow.

**Describe alternatives you've considered**
Alternatives to this would be faster way to fast forward through your show or to have timestamps.

**Comment by TRtomasz** [comment]
You can change seek time from 10 seconds up to 30 seconds in the settings.
