### ISSUE TITLE
Choose subtitle language

### ISSUE THREAD

**Issue by javiimp** [Stremio/stremio-features#796]
**Stremio Version**
Stremio Version and OS

**Describe the solution you'd like**
An option to just choose the subtitles languages u want to see? Because sometimes there are 100s of languages I dont use. And for iOS users would be nice a native app.

**Comment by charliesheen14** [comment]
This is an addon. You can try open subtitles v3.

**Comment by charliesheen14** [comment]
For ios, please go to web.stremio.com and place this on your homescreen. Then download vlc, and change the default player in the settings of your stremio to vlc. And voila you can use stremio on your iphone/ipad. Here a toturial: https://blog.stremio.com/using-stremio-web-on-iphone-ipad/
