### ISSUE TITLE
Need more indian addons.

### ISSUE THREAD

**Issue by Jittesh26** [Stremio/stremio-features#797]
I have 2 website suggestions to add to it as an addon .
1.https://tamilyogi.se/home/
2.https://tamilgun.group/home/

**Comment by charliesheen14** [comment]
Please read the stremio page on github before posting an issue. This is what it says:

"It's important to understand how Stremio works. Stremio is an easy to use media center driven by a simple add-ons system. Stremio does not include any content by itself, nor does it develop any content Add-ons other than YouTube and Filmon.tv."
