### ISSUE TITLE
Launch as maximized from windows taskbar 

### ISSUE THREAD

**Issue by Arthorox** [Stremio/stremio-features#802]
**Stremio Version**
Stremio Version - 4.4.168 
OS - Windows 10 pro

**Is your feature request related to a problem? Please describe.**
The problem is that whenever i open stremio from taskbar it launches as a small window.

**Describe the solution you'd like**
 I want it to launch as maximized when launched from taskbar.

**Describe alternatives you've considered**
I tried to change the launch settings in properties but it didn't help as it'd just move the normal window into a corner and not maximize it.

**Additional context**
when opened with the normal window setting it opens like this,
![image](https://github.com/Stremio/stremio-features/assets/113876111/50c7e707-94a3-4307-890e-d710b0a21e6d)

when opened with the maximized setting it opens like this,
![image](https://github.com/Stremio/stremio-features/assets/113876111/25219438-ca31-49f0-9d9f-0c1e23b8bd2b)

**Comment by charliesheen14** [comment]
Is this when you click on the cube next to your personal setting in the right above corner ?

**Comment by TRtomasz** [comment]
it will open in the exact size you left the window open, if you leave the window in full size and minize it will open in the full size
