### ISSUE TITLE
Stream Dailymotion content in Stremio

### ISSUE THREAD

**Issue by Fassaris2001** [Stremio/stremio-features#803]
**Stremio Version**
All versions and all OS

**Is your feature request related to a problem? Please describe.**
I would like an addon so that i can stream Dailymotion content in Stremio 

**Describe the solution you'd like**
Same as above

**Describe alternatives you've considered**
No alternatives

**Additional context**
I have a code that might help. It was generated using chatgpt:
const fetch = require('node-fetch');

// Function to fetch the catalog
async function fetchCatalog() {
    const response = await fetch('https://api.dailymotion.com/videos?fields=id,title,description,duration&tags=tvshow');
    const data = await response.json();
    const catalog = data.list.map(item => ({
        id: item.id,
        name: item.title,
        description: item.description,
        type: 'series',
        poster: `https://www.dailymotion.com/thumbnail/video/${item.id}`
    }));
    return catalog;
}

// Function to fetch metadata
async function fetchMeta(id) {
    const response = await fetch(`https://api.dailymotion.com/video/${id}?fields=id,title,description,duration`);
    const data = await response.json();
    const meta = {
        id: data.id,
        name: data.title,
        description: data.description,
        type: 'series',
        poster: `https://www.dailymotion.com/thumbnail/video/${data.id}`
    };
    return meta;
}

// Function to fetch streams
async function fetchStreams(id) {
    const response = await fetch(`https://api.dailymotion.com/video/${id}/stream_hls_url`);
    const data = await response.json();
    const streams = {
        hls: data.hls_url
    };
    return streams;
}

module.exports = {
    fetchCatalog,
    fetchMeta,
    fetchStreams
};

// Stremio addon JSON structure
const addonManifest = {
    "id": "com.example.dailymotiontv",
    "name": "Dailymotion TV Shows",
    "description": "Watch TV shows from Dailymotion.",
    "version": "1.0.0",
    "resources": ["catalog", "meta", "stream"],
    "types": ["series"],
    "catalogs": [
        {
            "type": "series",
            "id": "dailymotion_series",
            "name": "Dailymotion TV Shows",
            "extra": [
                {
                    "name": "search",
                    "isRequired": false
                }
            ]
        }
    ],
    "background": "https://example.com/background.jpg",
    "logo": "https://example.com/logo.png",
    "contactEmail": "",
    "manifestVersion": 1
};

module.exports.addonManifest = addonManifest;

**Comment by jaruba** [comment]
this is not a Stremio feature request, Stremio does not offer any content, you can try at https://reddit.com/r/StremioAddons , maybe a community developer will consider creating such an addon
