### ISSUE TITLE
tvshow time integration

### ISSUE THREAD

**Issue by gabrielbiel7** [Stremio/stremio-features#81]
when we finish episodes in stremio app, it could automatically mark as watched in tvshow time. this feature already exists in popcorn time. thanks

**Comment by Skywalkr08** [comment]
I was here thinking of posting it myself. There should be an option for TV Time scrobbling instead on Trakt

**Comment by MootMootz** [comment]
Hello there,

I expected this feature to be added so many times wondering it would have been done before I make a search on Google... :/
Sooooo... please guys, go for it.
It'd be very nice to be organized... ;)

(I assume you would be helpful for a LOT of people)

**Comment by TRtomasz** [comment]
closing as duplicate of https://github.com/Stremio/stremio-features/issues/21
