### ISSUE TITLE
Editor de Subtitulos en Smart Tv 

### ISSUE THREAD

**Issue by Hanzohazashi1** [Stremio/stremio-features#811]
Stremio Smartv
Editor de Subtitulos
Sugerencia 
Aumentar el tamaño del contorno del subtitulo de 0 a 100 
Editar el Fondo de subtitulo de 0 a 100 manejar transparencia 

Otras sugerencias
Compatibilidad de subtitulos con stremio en Smart TV, algunos subtitulos funcionan en stremio para PC pero para Smart tv no
Aumentar addons de subtitulos en español

**Comment by TRtomasz** [comment]
Please use english only in this repository.
