### ISSUE TITLE
Text improvement 

### ISSUE THREAD

**Issue by GKid94** [Stremio/stremio-features#819]
**Stremio Version**
1.6.12, Android 12 MIUI 13 

**Is your feature request related to a problem? Please describe.**
The seeders, video size and torrent text are hard to see

**Describe the solution you'd like**
Make the seeders, video size and torrent name text more noticable

**Describe alternatives you've considered**
None

**Additional context**
/
![IMG_20240421_053046](https://github.com/Stremio/stremio-features/assets/18757054/27237150-6fa2-4074-b200-c5112885d5ad)
![Screenshot_2024-04-21-05-32-53-152_com miui securitycenter](https://github.com/Stremio/stremio-features/assets/18757054/b80e7070-4422-4616-affd-ace16b278ada)
![Screenshot_2024-04-21-05-32-58-796_com android settings](https://github.com/Stremio/stremio-features/assets/18757054/43454b5b-8db1-412b-a2d2-4b0ead4dcc13)

**Comment by TRtomasz** [comment]
We do not know which part of description is video file size and amount of seeders so we cant make them more noticable.
Also you didnt mention what would be more noticable? On your screenshot everything is perfectly visible

**Comment by GKid94** [comment]
> We do not know which part of description is video file size and amount of seeders so we cant make them more noticable. Also you didnt mention what would be more noticable? On your screenshot everything is perfectly visible

I said what and marked it on the image
