### ISSUE TITLE
Option for addon developers to control a catalog visibility in home/discover

### ISSUE THREAD

**Issue by aaalsaleh** [Stremio/stremio-features#820]
**Stremio Version**
All versions and platforms

**Is your feature request related to a problem? Please describe.**
Addon developers cannot control whether a catalog should appear on the home screen or not. Not all catalogs need to be on home screen, and not all catalogs need to be in discover either. There are many people who requested the ability to hide certain catalogs from the home screens, and currently even addon developers cannot do it for their own addons.

**Describe the solution you'd like**
Just like there are `extra` options for `genre`, `search`, and `skip` in the addon manifest for catalogs, there should be an additional option `home` to control whether a catalog should appear in the home screen or not. For example:
- `{name: "home", isRequired: true}` means it is a home screen only catalog
- `{name: "genre", isRequired: true, options: [...]}` means it is a discover only catalog
- `{name: "search", isRequired: true}` means it is a search results only catalog.

**Describe alternatives you've considered**
Currently I set `{name: "genre", isRequired: true, options: [...]}` for any addon I wish to hide from the home screen (even when there are no genres). However, it is not possible to have a home screen only addon (without showing in discover).

**Comment by TRtomasz** [comment]
Feature for people to hide catalogs should not be implemented by giving addon developers possibility to hide them from the addon config, i dont see any point of this feature

**Comment by aaalsaleh** [comment]
I think there is misunderstanding. This feature is not for people to hide catalogs, but rather for addon developers to control the visibility of their own addon's catalogs. Currently addon developers can only hide their own catalogs from home screen by making either `genre` or `search` as required, and it is not even possible to hide from discover. With the suggestion, addon developers can specify whether the catalog is a home-only, discover-only, search-only or for all.
