### ISSUE TITLE
Landscape poster shape is not respected in discover (macOS)

### ISSUE THREAD

**Issue by aaalsaleh** [Stremio/stremio-features#822]
**Stremio Version**
Stremio 4.4 (macOS)

**Is your feature request related to a problem? Please describe.**
If an addon's catalog entry is set to `"posterShape": "landscape"`, it will appear as `landscape` in home and search screens, but it will be forced into a `poster` shape in discover screen. This is not an issue for `"posterShape": "square"` as it'll appear consistently as `square` in home, discover, and search. Same for `poster` shape.

**Describe the solution you'd like**
Respect `"posterShape": "landscape"` in all tabs/screens.

**Describe alternatives you've considered**
There are no alternatives, as it is currently beyond our control.

**Additional context**
This issue doesn't exist in the Android Mobile, Android TV, or Web.
Other platforms (Windows/Linux) weren't tested.

**Comment by TRtomasz** [comment]
I will close this issue, we have implemented fix for this recently and it will be included once we make next release.
