### ISSUE TITLE
Audio Passthrough option needed in Android TV version (same as mobile app)

### ISSUE THREAD

**Issue by TioBundy** [Stremio/stremio-features#825]
**Stremio Version and OS: 1.6.9 - Android TV or 1.6.12 in mobile version. OS: Fire OS 7.6.6.9**

The Stremio Mobile Version app has a Passthrough audio option that the Android TV app does not have available.
This absolutely makes no sense since the passthrough of audio is to be used with AVR equipment or compatible soundbars to get the True HD, DTS MA, DTS-X audio.

Tested with Kodi that the audio passthrough in streaming/trackers fonts or similar, it is not a problem of configuration and to endorse the doubts, uninstalled the app of Stremio version Android TV And installed the Stremio version of mobile or tablet, activated the Passthrough option for audio and magic, at first, I have DTS X (Jurassic Park, which is the movie I was testing with).

Please include this option in upcoming versions because I don't know a single case from someone who needs Passthrough on mobile devices, plus the phone version is unfriendly take TVs.

Thanks!

**Comment by TRtomasz** [comment]
There is no such setting in the ExoPlayer. You coudl try enabling Tunneled Playback in the settings.

**Comment by TioBundy** [comment]
No, tunneled playback doesn't work, activated it but doesn't work.

In addition, that the mobile version does work, with which it is a matter of updating the Smart TV app and including said option as in the phone version, which I do not understand that a phone needs This option, as I mentioned, does not make sense to find it on mobile phones and not on Smart TV. Plus I have installed and tested the mobile one and it works, but if the interface is a disaster for a TV.
