### ISSUE TITLE
Voice search within the app should use google assistant, existing voice search is really bad

### ISSUE THREAD

**Issue by Zizou3000** [Stremio/stremio-features#826]
I don't know what stremio uses now, but it's recognition is REALLY bad, nothing close to assistant.  Since app is assistant searchable already, i think pressing assistant button within the app should do a search within the app automatically. 

Google has started disabling movie search via assistant on the home screen, so good in app search would be even more valuable.

**Comment by TRtomasz** [comment]
Please use the new feature template when requestion new feature
