### ISSUE TITLE
Separate Continue Watching from Auto Play Next Episode

### ISSUE THREAD

**Issue by wenchiee** [Stremio/stremio-features#827]
**Stremio Version**
Android TV

**Is your feature request related to a problem? Please describe.**
When turning off Autoplay Next Episode, the Show (series) vanishes from Continue Watching when i finish an episode. To bring it up again I would have to search for it and start watching another episode, after which the cycle repeats. This is an issue as I wish to keep the series in Continue Watching even if I had finished one of its episodes and plan to return to it later.

**Describe the solution you'd like**
These two features would ideally be separate from eachother, Continue Watching should refer to a Series/Show not a single episode of one.

**Comment by TRtomasz** [comment]
what do you mean by 'homescreen'?
I'v just checked and nothing disappears after disabling 'auto play next episode' So please update your issue with more details.

**Comment by wenchiee** [comment]
@TRtomasz thanks, updated.
Homescreen was referring to the Stremio home screen. Rephrased it so it's no longer confusing hopefully.

**Comment by whatuserever** [comment]
@TRtomasz can we reopen this please? I would love to have Stremio update the "Continue Watching" section without auto-playing episodes.
