### ISSUE TITLE
Please provide this via F-Droid.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [Stremio/stremio-features#829]
#### **Stremio Version**

<table><tr>
    <th>Stremio</th>
    <td><a href="https://dl.strem.io/android/v1.6.12-com.stremio.one/com.stremio.one-1.6.12-4208802-arm64-v8a.apk">https://dl.strem.io/android/v1.6.12-com.stremio.one/com.stremio.one-1.6.12-4208802-arm64-v8a.apk</a></td>
</tr><tr>
    <th>OS</th>
    <td><a href="https://fairphone-android-builds.ams3.digitaloceanspaces.com/FP5/A13/FP5-TT4C-factory.zip">https://fairphone-android-builds.ams3.digitaloceanspaces.com/FP5/A13/FP5-TT4C-factory.zip</a></td>
</tr></table>

#### **Is your feature request related to a problem? Please describe.**

I don't have the Google Play Store on my device, as do myriad others, because unless it comes with your AOSP-based OS (or you can sideload it via TWRP) it's unavailable for many.

#### **Describe the solution you'd like**

https://gitlab.com/fdroid/fdroid-website/-/blob/983b18d077b5ab407d286410bb6c26a9cb548724/_docs/FAQ_-_App_Developers.md#how-do-i-get-my-app-included

#### **Describe alternatives you've considered**

1.	https://play.google.com/store/apps/details?id=com.stremio.one&hl=en&gl=US
1.	https://github.com/recloudstream/cloudstream/issues/336#issuecomment-2087501016

#### **Additional context**

1.	Additional rationale is available at https://github.com/Tadashi-Hikari/Sapphire/issues/2#issue-1228766021.
1.	https://github.com/search?q=org%3AStremio+f-droid&type=issues returns 0 relevant results.

**Comment by celenityy** [comment]
+1, I hope it'd at least be possible to publish the APK releases via GitHub so it can be installed and updated via an app like Obtainium.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Stremio/stremio-features/issues/829#issuecomment-2088507957

@Retold3202, I've consequently filed https://github.com/Stremio/stremio-features/issues/831#issue-2273610799 for you.

**Comment by TRtomasz** [comment]
Stremio mobile app isnt opensource so we cannot make releases public, sorry.

**Comment by celenityy** [comment]
> Stremio mobile app isnt opensource so we cannot make releases public, sorry.

Is there any consideration to make it open source? And regardless, is it still possible to post the APK files somewhere like GitHub? The APKs seem available on your website already, but having them somewhere like this on GitHub would make it much easier for users to download and install Stremio outside of the Play Store, and wouldn't require any real maintenance or effort on your end. 

@TRtomasz

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Stremio/stremio-features/issues/829#issuecomment-2107364977

@TRtomasz, I've aforexplained that it doesn't need to be OSS to be posted. All you need to do is provide an F-Droid repository. https://thedoc.eu.org/fdroid/ is an example of a closed-source application provided via an F-Droid repository.
