### ISSUE TITLE
Windows Backspace Behaviour

### ISSUE THREAD

**Issue by SecondBrekfast** [Stremio/stremio-features#832]
**Stremio Version**
Stremio 4.4.168 - Windows 11

**Is your feature request related to a problem? Please describe.**
When in full screen, pressing backspace (used to exit the stream), will first return Stremio to a windowed state. Only a second press will exit the stream and go back to the main menu.

**Describe the solution you'd like**
Backspace should not exit full screen mode. Only escape should be used to exit full screen. Backspace should return to the previous menu while the app remains in full screen.

**Comment by TRtomasz** [comment]
This is intended behavior and has been like this forever, we will not change it as users are used to it.

**Comment by SecondBrekfast** [comment]
> This is intended behavior and has been like this forever, we will not change it as users are used to it.

This is really poor UX. Why would Backspace and Escape perform the same action, only for Backspace to perform a different action on the second keypress? Makes no sense for a user experience perspective.

Unless there a key bind to exit a stream without exiting full screen that I'm unaware of?

**Comment by TRtomasz** [comment]
Actually i think you are right, we will check internally if we all agree this should be changed

**Comment by SecondBrekfast** [comment]
> Actually i think you are right, we will check internally if we all agree this should be changed

That's great to hear. Kindly keep us up to date with your decision.

**Comment by ajstrobus4** [comment]
This is the only reason i cannot bring myself to use this app, hitting back on a menu takes the whole app out of fullscreen being considered "intended" behavior, made me go completely crosseyed just reading that.... coupled with the locked shortcuts that cannot be changed, forces the app to be a extremely inferior product, when just a simple change makes it the best at least in a single category? wow...  

... and closing as complete with no change, that makes even less sense...

**Comment by SecondBrekfast** [comment]
> This is the only reason i cannot bring myself to use this app, hitting back on a menu takes the whole app out of fullscreen being considered "intended" behavior, made me go completely crosseyed just reading that.... coupled with the locked shortcuts that cannot be changed, forces the app to be a extremely inferior product, when just a simple change makes it the best at least in a single category? wow...
> 
> ... and closing as complete with no change, that makes even less sense...

This has been resolved; they added a toggle for "Escape key exit full screen" in the settings which effects both Esc and Backspace.

I still think that they should separate Backspace and Esc into two different keybinds, Backspace to return to the previous menu and Esc to exit full screen, but I don't seem them doing this which is why I marked it as resolved.

**Comment by Wemmy0** [comment]
This decision makes it more complex than it needs to be to get Stremio working along with HDMI-CEC on a media center PC.
Instead of creating a script to emulate keyboard presses, you have to create a virtual gamepad device, a needlessly complex python script to translate `cec-client` to a virtual xbox 360 controller

It would make much more sense to have ESC exit full screen, and backspace on a separate hotkey to go back without exiting full screen.

This could also possibly be done with running Stremio in a gamescope window so it's forced into a fullscreen resolution, but again, needlessly complicated
