### ISSUE TITLE
Watch Progress Convenience

### ISSUE THREAD

**Issue by zeetstar** [Stremio/stremio-features#833]
5.0.0-beta.8
Stremio Web/IOS

**Is your feature request related to a problem? Please describe.**

My only gripe of the app is that when i go to start/continue a series, it alwasy opens on the latest relased season of the series, which risks the exposure of potential spoilers and also is a quality of life issue as i always have to go back to the season im on.

**Describe the solution you'd like**
All I believe is needed is if a show has never been watched, the first season to come up should be season 1 rather than the latest season. Similarly, if the series has been watched the season to come up should be the one in which the last episode was watched.

**Describe alternatives you've considered**
n/a

**Additional context**
![image](https://github.com/Stremio/stremio-features/assets/119452211/c4657b7f-b20c-4275-9feb-6539ef7709bf)

this image shows an unwatched show, bringing up the latest season which could cause spoilers, may also an option to hide thumbnails would help

**Comment by TRtomasz** [comment]
Closing this as it is a bug, not a missing feature we are tracking this internal to be implemented/fixed.
