### ISSUE TITLE
add BoxART in video player UI Just like KODI 

### ISSUE THREAD

**Issue by eSkRo32** [Stremio/stremio-features#835]
**Stremio Version**
Stremio on Android TV

**Additional context**
Like when we play a movie or tv show, and let's say we hit pause ⏸, we would not only see the player UI with seek bar and stuff, but their would Also be a BoxArt of what's playing. Kinda like in Kodi! 

See Here, would look awesome 😁👍
![Screenshot_20240504-112923_Chrome](https://github.com/Stremio/stremio-features/assets/17524629/1cc9df9a-d7be-4203-8b14-20c83813e1c5)

Thanks guys, Stremio Rocks 🤘

**Comment by TRtomasz** [comment]
Sorry, this will not be implemented, there is no purpose for this other than wasting the space in the player
