### ISSUE TITLE
A way to copy magnet links before opening the video

### ISSUE THREAD

**Issue by Celio1080p** [Stremio/stremio-features#836]
**Stremio Version**
Stremio Version 4.4.168, and OS Windows 11 Pro

**Is your feature request related to a problem? Please describe.**
Just a request. A way to copy the magnet link without having to open the video first.

**Describe the solution you'd like**
When i right click on a video, before opening it, giving me some options, copying the magnet link as one of them.

And a way to grab whole seasons magnet link too, if possible ? some series have too many episodes, and having to click and open
one by one is.. not nice.

Sorry my english, noob brazilian here.

**Comment by TRtomasz** [comment]
https://github.com/Stremio/stremio-features/issues/310 https://github.com/Stremio/stremio-features/issues/249 https://github.com/Stremio/stremio-features/issues/280

**Comment by radenko98** [comment]
I would love this option as well!

**Comment by Molier** [comment]
> [#310](https://github.com/Stremio/stremio-features/issues/310) [#249](https://github.com/Stremio/stremio-features/issues/249) [#280](https://github.com/Stremio/stremio-features/issues/280)

Hi @TRtomasz  I see a lot of issues/feature requests for this functionality, you mentioned in 2022 that it was in the closed source codebase? and now all the issues are marked as completed , but I dont see any PR or explanation on how it is completed? and the functionality is not found in the latest version i tested? whats the progress on this issue and is it still not possible to contribute to it open source?

**Comment by Molier** [comment]
> > [#310](https://github.com/Stremio/stremio-features/issues/310) [#249](https://github.com/Stremio/stremio-features/issues/249) [#280](https://github.com/Stremio/stremio-features/issues/280)
> 
> Hi [@TRtomasz](https://github.com/TRtomasz) I see a lot of issues/feature requests for this functionality, you mentioned in 2022 that it was in the closed source codebase? and now all the issues are marked as completed , but I dont see any PR or explanation on how it is completed? and the functionality is not found in the latest version i tested? whats the progress on this issue and is it still not possible to contribute to it open source?

Just to follow up and confirm that the feature to copy magnet is in older stable version 4.4 (when you are actively opening a video) but it is completely missing in the latest beta 5.0 and in the web version as well. but just the option after opening the video. 
So the issue in latest beta has effectively downgraded in functionality. no copying magnet at all.
