### ISSUE TITLE
Auto select 

### ISSUE THREAD

**Issue by braam777** [Stremio/stremio-features#837]
Hi. Was wondering if you can add a function where stremio automatically select and play a source instead of you having to choose one? So instead of giving different magnet option, when you hit PLAY the movie automatically start, using 1 or maybe a couple different feeds. Reason why I ask, my partner struggle to understand why we need to select 1 and play, why cant the movie or series not just start automatically when hitting play.
Thanks

**Comment by Vance-ng-vn** [comment]
What would happen if Stremio automatically streams torrents and you get caught by the police?

What would happen if Stremio automatically streams 8k video files while your phone or laptop can't even handle 2k videos?

**Comment by TRtomasz** [comment]
No this is not possible, sorry.

**Comment by ghettocentral420** [comment]
> What would happen if Stremio automatically streams torrents and you get caught by the police?
> 
> What would happen if Stremio automatically streams 8k video files while your phone or laptop can't even handle 2k videos?

It would be up to the user to sort and configure their addons properly to limit the video size. It's the user's responsibility if they installed an addon that supplies torrents.
