### ISSUE TITLE
Subtitle opacity

### ISSUE THREAD

**Issue by taaktuuq** [Stremio/stremio-features#838]
**Stremio Version**
Latest build, WIN 11 + Android TV

OLED TVs are prone to burn in with very bright subtitles, especially in HDR. Could we please get a slider to adjust subtitle opacity? Slightly opaque subtitles are healthier for burn in prone screens, and also less distracting while consuming content.

**Comment by TRtomasz** [comment]
Each subtitles color setting allows you to set custom transparency 
![image](https://github.com/Stremio/stremio-features/assets/40594253/5d877a51-aee6-4732-bef5-36994f5dc186)
