### ISSUE TITLE
Change Cache Directory OR Installation Directory location

### ISSUE THREAD

**Issue by HorselessName** [Stremio/stremio-features#84]
I have a SSD with 120 GB, and another drive with 1 Tb.
I can't change the cache location and that's very annoying. Would be awesome if i could do that :)

**Comment by Ivshti** [comment]
Doesn't the option in settings work? Which operating system are you using?

**Comment by shubho2706** [comment]
Same situation. OS: Windows 10
The option in settings changes it temporarily. So evert time  I boot, I need to change the directory.

**Comment by MBaltz** [comment]
> i "fixed" making the ~/stremio-server/stremio-cache folder a symlink redirecting to ext-drive/.stremio-cache folder, apparently its now using the big storage, hope this isnt wasting my ssd transfer limit neutral_face

I fixed this making a symbolic link too.
```bash
$ mv ~/.stremio-server/stremio-cache /mnt/dados_2/
$ ln -s /mnt/dados_2/stremio-cache ~/stremio-server/stremio-cache
```

Now I can use a 10GB cache size to stremio :)

> My partition is mounted on boot, via _fstab_

**Comment by colovalenz** [comment]
> Doesn't the option in settings work? Which operating system are you using?

I'm on Win 10. The 5.0 version doesn't have that feature. I try with the 4.4 version that does have it and works perfectly. 

Could you add this feature in future updates? Please and Thank you :)

**Comment by cwrlys** [comment]
> > Doesn't the option in settings work? Which operating system are you using?
> 
> I'm on Win 10. The 5.0 version doesn't have that feature. I try with the 4.4 version that does have it and works perfectly.
> 
> Could you add this feature in future updates? Please and Thank you :)

You can do the configuration manually in your server configuration, in _server-settings.json_, located on %AppData%\stremio\stremio-server, changing the _cacheRoot_ variable to the new path.
