### ISSUE TITLE
Stremio for IOS 17.5 (no limited)

### ISSUE THREAD

**Issue by carlospccarvalho** [Stremio/stremio-features#840]
iOS 17.5 now allows apps to be installed outside the apps store. It would be very interesting to make the app available without limitations for this version of iOS.

**Comment by jaruba** [comment]
does Apple still want us to pay 0.5 eur for each install and each update after we pass 1 mil users for the EU region with a sideloadable app?

regardless:
- you did not use the issue template so this request is invalid
- asking for new platforms to be supported is not a feature request, expanding to new platforms does not need requests, it is one of our primary goals and we will try it anyway
