### ISSUE TITLE
Change Shown Tab on Stremio Startup

### ISSUE THREAD

**Issue by MohammadAbualhasanAnati** [Stremio/stremio-features#844]
**Stremio Version**
Stremio Version 4.4.165 and All OSes

**Is your feature request related to a problem? Please describe.**
Actually, no. It is not a problem related. I would consider it a complement missing feature.

**Describe the solution you'd like**
The ability to save last used tab. If I want this feature to be enabled a setting would be added so that I would choose what tab to show on stremio startup. Or if I want the last used tab to be saved, to continue where I've left off.

**Describe alternatives you've considered**
If the saving last tab is difficult or needs lots of work, then you would just add a simple setting to choose from, what specific tab to visit directly on startup of your app. .e.g. Library tab instead of recommecndations home tab.

**Additional context**
Reason behind this feature request, is that I know what I want to watch & I'm saving it in library. It is so disturbing to see all random movies when first run the app. I prefer to directly go to library and watch what I have saved already!

Thanks for your time & consideration

**Comment by TRtomasz** [comment]
Intention is keep stremio as simple as possible, we are not able to add option for everything so this will not be added sorry.
