### ISSUE TITLE
[Request] Option for default audio track quality

### ISSUE THREAD

**Issue by shanestonk** [Stremio/stremio-features#845]
**Stremio Version**
Stremio Version and OS 
latest stremio Google Tv

**Is your feature request related to a problem? Please describe.**

Stremio keep choosing audio track ac3 or lower quality but not higher quality eg dolby atmos, truehd or dts hd ma. i have dolby atmos soundbar and need to manually choose atmos audio track whenever video play. A bit hassle.

**Describe the solution you'd like**

Wish stremio dev can make option in the playback setting for default audio track quality eg first option atmos second option dts ma hd for eg so whenever movie play stremio will pick dolby atmos audio track first if available.

**Describe alternatives you've considered**

**Additional context**

**Comment by TRtomasz** [comment]
Stremio does not have information what is quality of the audio track this is not possible.
