### ISSUE TITLE
Add see all button to Android TV app

### ISSUE THREAD

**Issue by Denverdave11** [Stremio/stremio-features#846]
Android TV version

On both the desktop version and mobile Android versions you can view many rows of thumbnails at once which makes browsing very easy. But on the Android TV version you just have to scroll right in a single row forever to browse. 

Please add the see all button to each row like on PC to open into the many thumbnails view so all I have to do is hit down to show a new row and can see many options at once. Exactly like it behaves on the desktop version. There is much more screen real estate on a TV so it should be easy to do.

**Comment by soliverc** [comment]
I would also love this feature, and I requested it  back in November 2023 and it has been ignored.  So... good luck. 

My request: 

https://github.com/Stremio/stremio-features/issues/589

**Comment by TRtomasz** [comment]
Closing as a duplicate. @soliverc we are small team managing apps for Android TV, Android, Linux, Windows, MacOs, Samsung Tvs and WebOs Tvs not to mention web standalone app and stremio service. Not crucial features will be treated with low priority, sorry.
