### ISSUE TITLE
Upload personal subtitles into internal player

### ISSUE THREAD

**Issue by Proteus1963** [Stremio/stremio-features#847]
**Stremio Version**
Stremio Version and OS
Stremio 1.6.9.  Android TV 9

**Is your feature request related to a problem? Please describe.**
I would like to upload subtitles that I cannot find and that I translate myself

**Describe the solution you'd like**
Feature like VLC, MX for loading local subtitles into internal player

**Describe alternatives you've considered**

**Additional context**

**Comment by TRtomasz** [comment]
Stremio does not host subtitles, you can upload subtitles to stremio, you should check opensubtitles webpage
