### ISSUE TITLE
Add libMPV to Android TV app as alternative for libVLC

### ISSUE THREAD

**Issue by e1ker** [Stremio/stremio-features#848]
**Stremio Version**
1.6.9 Android TV

**Is your feature request related to a problem? Please describe.**
Many people use Stremio for anime, which heavily uses .ass subtitles with advanced typesetting. Most players available with Android TV struggle with this by using the wrong font, being unable to display more than one simultaneous subtitle, etc. Even when they're supposedly able to read .ass subtitles most do it poorly. The only two examples I've found that work properly are VLC and MPV but for years VLC on Android TV has had problems with pretty bad stuttering every time a subtitle line changes, making it unusable for anime. MPV's not perfect since it has problem with performance in bigger files and lacks DV support (also no frame matching on the external app) but it does display the subtitles perfectly with no stutter related to them, and most anime files are not big enough for performance concern. Using the external app though makes it not possible to use frame matching and you can't make a series remember the player like you can between Exoplayer and libVLC at the moment.

**Describe the solution you'd like**
Just as VLC has libVLC, MPV has libMPV (which I believe is already implemented on desktop). Since libVLC has that problem with subtitles I believe it would be great to add libMPV as another option (or replace libVLC since I'm not sure it provides any benefits compared to libMPV) for native  player on the Android TV app.

**Describe alternatives you've considered**
Other good solutions could be the ability the external players as default for specific series or, even better, for the entire anime genre if you have a catalog plugin that correctly identifies anime as such (this last solution would work much better if applied to genre instead of category, since some people like me like to use Cinemeta instead of plugin like Kitsu, the former of which categorizes anime as series or movies but can still have anime as genre or tags, and the latter of which just creates a differenr category called Anime)

**Aditional Info**
Also would be awesome to see the subtitles format in the subtitles menu, to see if it's worth it to change players on specific anime or files.

**Comment by TRtomasz** [comment]
Mpv team does not release `libMPV` as a separate android library so this is not possible without a lot of work from our side.
You can install mpv app on your android device though and use it as an external player.

**Comment by e1ker** [comment]
What about some of the alternatives discussed? Being able to use the external player automatically for a specific series/genre/subtitle format would basically fix the same problem.

**Comment by bt4ibwem8** [comment]
> Mpv team does not release `libMPV` as a separate android library

why not? you already do it with libVLC, right?

**Comment by victorgveloso** [comment]
@bt4ibwem8 libVLC has [official android support](https://code.videolan.org/videolan/vlc-android)
On the other hand, I found [this repo](https://github.com/mpv-android/mpv-android) that does all the heavy lifting (although it's not "official" as in made by mpv core devs)
