### ISSUE TITLE
DTS-HD passthrough issue.

### ISSUE THREAD

**Issue by YungZanji** [Stremio/stremio-features#851]
**Stremio Version**
Stremio Version and OS
Stremio: 1.6.9 and OS: Android TV 11

**Is your feature request related to a problem? Please describe.**

I’m always trying to get DTS-HD audio files to work on the native exo player when playing blu ray remuxes. I am on the latest 9.1.1 firmware for NVIDIA Shield Pro 2019 running Android TV 11. However, it only sends through DTS core to my AVR (X3800H) This is important because exo player supports DV and vlc doesn’t. On VLC and JustPlayer, which is based on exoplayer also, the DTS-HD pass through works flawlessly, but JustPlayer has poor refresh rate matching and VLC doesn’t have DV. 

**Describe the solution you'd like**

Is there a way we can incorporate DTS-HD compatibility? I know the recent tech update states it’s now it should work but for my device it does not. I would just like to be able to watch my remuxes and have DV and DTS-HD support. 

**Describe alternatives you've considered**

Possibly incorporating a third native player choice like JustPlayer. But with Stremio’s frame matching. Since it works flawlessly with that player. 

**Additional context**
None.

**Comment by TRtomasz** [comment]
Have you tried enabling tunneled playback in the settings?
