### ISSUE TITLE
Being able to set different default players between genres/series. Alternatively, being able to choose a player other than the default.

### ISSUE THREAD

**Issue by e1ker** [Stremio/stremio-features#853]
**Stremio Version**
1.6.9 Android TV

**Is your feature request related to a problem? Please describe.**
Exoplayer lacks .ass subtitles styling used in anime. libVLC lags with subtitles and lacks DV support. External players fail either at DV or subtitles. There's no one fit all solution and you cannot directly load into preferred player seamlessly.

**Describe the solution you'd like**
I feel there's different alternatives. You could set a different player for a specific genre (for example anime) or series. If possible would be great to select between external players too for this. You could also be able to set Exoplayer or external as a general default like you do now and then when long pressing a media file a context menu that lets you choose a different player could come up.

**Describe alternatives you've considered**
At the moment the closest two solutions available are selecting an internal player as default, waiting for the content to load, the selecting pressing the external player button and having to.wait for it to load again. You could also set external player as default and always keep pressing Once when choosing a player, with no way to choose Exoplayer or libVLC. Both are impractical and finicky though.

**Additional context**
Again, I'm not sure if this is possible on Android, but if this end up being implemented being able to choose between external players instead of using the native Android association to file would be great, as no one player has all the features you might want and using the Android "Open With" menu is finicky and cumbersome on Android TV with the possibility of hitting "Always" there making you have to go and reset the association settings.

**Comment by TRtomasz** [comment]
Such feature will not be added. We want to keep the app as simple as possible this is just a monster that is almost impossible to implement properly without multiple edge cases. Not to mention it would require a lot of time and would be used only by very few users ending with this is simply not possible because Stremio do not controll which player will be used it is user choice and it is remebered by system not the app.
