### ISSUE TITLE
Request for LG MENA region

### ISSUE THREAD

**Issue by CodedHexagon** [Stremio/stremio-features#856]
I've been trying to figure out how to get the Stremio app to operate on my LG TV, but it's not available in the MENA area.

I know how to add external apps to the TV app store using the developer app.

Unfortunately, no link is provided to download the file and so I can't upload it to the TV.

I'm asking the LGTV Stremio app's download files so I may try to sideload it.

![image](https://github.com/Stremio/stremio-features/assets/69865865/f2d24623-12d6-44a9-8fca-4b5dba1eebf0)

**Comment by TRtomasz** [comment]
Sorry this is outside of our control.

**Comment by nadir121** [comment]
> Sorry this is outside of our control.

Can you elaborate on why you can't provide the installation package?
