### ISSUE TITLE
[Feature Request] Subtitle improvements across platforms

### ISSUE THREAD

**Issue by quincyp** [Stremio/stremio-features#857]
**Stremio Version**
Stremio Version 1.6.9 and Android TV OS && Stremio Samsung TV OS

**Is your feature request related to a problem? Please describe.**
Android TV:
subtitle items (vertical offset, size, background color, etc) are only accessible via home > settings > playback. This is frustrating as you will often need to adjust these settings per the video/subtitles. 

Samsung TV:
vertical offset is accessible via video playback subtitle menu, but only increments by 5%. The increment is just too large and pushed some things much too far or too little. 

Stremio Subtitle Options Overall:
Lastly for both I encounter issues with fonts that are formatted oddly and difficult to read with the thin outline. 

**Describe the solution you'd like**
Android TV:
Subtitle settings should be added to video playback subtitle menu (like Samsung TV stremio)

Samsung TV:
Change increments instead to 1% (like Android TV stremio)

Stemio Subtitle Options Overall:
I would suggest an option to select from a few default font options and potentially increase outline size/thickness. 

**Describe alternatives you've considered**
No alternatives considered, the first 2 fixes seem possible as they are on other versions of Stremio already

**Additional context**
N/A. However, apologies for posting this feature request originally on the stremio-bugs repo! Hope I got the formatting correct this time around

**Comment by TRtomasz** [comment]
These all are subjective, and will not be changed based on one user request.
