### ISSUE TITLE
Audio offset 

### ISSUE THREAD

**Issue by stormer32** [Stremio/stremio-features#859]
**Stremio Version**
Stremio Version and OS
1.6.9 for Android TV

**Is your feature request related to a problem? Please describe.**
Sometimes when watching a movie or TV show on Stremio, the audio is out of sync with the video. This seems to be more common when a surround sound audio track is being played.

**Describe the solution you'd like**
I would like an audio offset setting to be added for the internal Exoplayer, the same as has already been implemented for the internal libvlc player.  I find that Exoplayer is more stable and works better with subtitles compared to libvlc. 

**Describe alternatives you've considered**

**Additional context**

**Comment by TRtomasz** [comment]
Exo does not support audio delay
