### ISSUE TITLE
Stremio for Tizen

### ISSUE THREAD

**Issue by mabusdogma** [Stremio/stremio-features#86]
Is there a way to create a *.wgt app for Tizen (the OS on Samsung's Smart TV)? I would love to run it directly from the TV without a PC
I know the apps are based in HTML and they have Cross-platform Applications with android and IOS... I have Tizen studio but I don't know where to start... 
Anyone who can help on this?

**Comment by Ivshti** [comment]
I am not familiar with tizen (nor is anyone on our team)

But a good start would be to see if https://app.strem.io would load

**Comment by mabusdogma** [comment]
It opens the page, you can sign in with the facebook account, see everything perfect, like in the PC... but when you try to see a movie you get a message: "failed to fetch", it looks like in the default web browser the transmission for bittorrent, youtube and streaming are not allowed.

Any workarounds for this? There are bittorrent apps on Tizen, so out of the browser it could be possible to make an app (or use a third app) to see if https://app.strem.io would load...

**Comment by mabusdogma** [comment]
Now I see the trailers work, but not the movies

**Comment by mabusdogma** [comment]
I can see it happens everywhere, in my laptop also (with both Chrome and Firefox), when I try to see a movie I got "Failed to fetch", so i guess everything is going normally on app.strem.io... what can I do next? is there a way to solve this "failed to fetch" and make an app on Tizen, or make this webpage work from the TV browser?

**Comment by beamkiller** [comment]
Tested https://app.strem.io too. Chrome gives Failed to fetch. Tizen OS and PS4 gives Network request failed.

**Comment by nurielt75** [comment]
Tizen can run node , so it shouldn’t be a problem , another way is having stremio team add an option to set stremio server Ip on their app.strem.io site then you could use any other device as server and your tv as client

**Comment by Vioner** [comment]
@mabusdogma @beamkiller
app.strem.io is just a client, not a standalone, serverapp. 

@nurielt75 the idea of setting server IP is great. Would be much better to have the server on TV though.

**Comment by naezith** [comment]
app.strem.io does not work on Windows Chrome or Firefox. ERR_CASTING_UPDATE_TITLE

Same with Samsung NU7400's web browser.

**Comment by FelipeBarrosCruz** [comment]
The same here.
Test in Sansung TV 65RU7100.
Also test in Xbox One with Internet Explorer browser and Chrome browser.
I'll start test's on Tizen trying to encapsulate the `app.strem.io` on the application.

**Comment by Dorisutu** [comment]
Tested on my Samsung 43RU7400 and I get the same error, Failed to fetch.

Does anyone find a solution for this?

**Comment by vinyoliver** [comment]
Any news on this?

**Comment by TRtomasz** [comment]
At the moment it is not possible to port existing Android app to tizen platform. But, recently we have announced new Stremio version called Stremio Web it is in alpha version but it is open source so you can feel free to check it out https://blog.stremio.com/stremio-web-alpha-is-now-open-source/ Stremio web will be web based stremio version so it will be possible to use it on Tizen tvs

**Comment by jaruba** [comment]
Stremio is now available in the Samsung TV App Store - https://blog.stremio.com/stremio-is-now-available-in-the-samsung-tv-app-store/

**Comment by taty0012** [comment]
slt  pls esk stremio est disponible pour tizen 2019 est +.... rediriger moi les frers car je ne l ai pas trouver dans mon store app samsung  est comment puise j savoire si mon tizen est de 2019 est + ou pas ...merci

**Comment by jaruba** [comment]
@taty0012 i'm afraid that if you can't find it in the app store, then it already means that your Samsung TV is not 2019+

**Comment by nurielt75** [comment]
Amazing !!! Good jobOn 30 Nov 2023, at 0:51, Alexandru Branza ***@***.***> wrote:﻿
Stremio is now available in the Samsung TV App Store - https://blog.stremio.com/stremio-is-now-available-in-the-samsung-tv-app-store/

**Comment by taty0012** [comment]
thanks so is samsung tv smart UE43N7025 tizen serie 7 is in 2019 tv vserie release pls help if now is there any news about stremio  for tv samsung 2018 or 2017 ...thak u very much frend

**Comment by jaruba** [comment]
@taty0012 we do not have any intention or plan of supporting 2017 and 2018 TVs at the moment

**Comment by leandrocoding** [comment]
> @taty0012 we do not have any intention or plan of supporting 2017 and 2018 TVs at the moment

Is there a specific reason why you don't provide the tpk for the stremio App. This way people (like me) could try to get it to work on the unsupported platforms.

I understand that it is not worth the effort to officially support these old TVs, but I would love to try and get it to work.

Would that not work, because the app depends on 2019+ Features?

I love the work you guys are doing!
Thank you!
