### ISSUE TITLE
Scroll like Netflix 

### ISSUE THREAD

**Issue by Dbjiyneusb** [Stremio/stremio-features#860]
**Stremio Version**
1.6.12 Android and Google TV

**Is your feature request related to a problem? Please describe.**
When scrolling a movie/series using ExoPlayer it skips forward or back a period of time. However it doesn't show what bit I am skipping to 

**Describe the solution you'd like**
I would like to scroll like on Netflix where it gives you a reel of still frame images at around 10 second intervals and I can scroll to the part I want to watch and select it for the video to load at that timeframe 

**Describe alternatives you've considered**
A way of viewing the content in still frames at scrollable intervals 

**Additional context**
For reference - look and Netflix and copy how they scroll

**Comment by TRtomasz** [comment]
this is not possible.
