### ISSUE TITLE
Improve Anime Tracking: Allow Stremio to Output Stream Titles

### ISSUE THREAD

**Issue by kuusuru** [Stremio/stremio-features#866]
**Stremio Version:** 4.4.168 on Windows 11 Pro

**Is your feature request related to a problem? Please describe.**

Yes, my feature request is related to a limitation in Stremio's current functionality. Currently, Stremio doesn't provide a way for external applications to access the title of the currently playing stream and just outputs "Stremio - Freedom to Stream" in the application window or whatever the top titlebar is called.

This creates a problem for users who want to integrate Stremio with Taiga, a popular anime and manga tracking application. Taiga relies on the title of the application window or a filename of the video being watched to automatically synchronize watch progress for anime.

**Describe the solution you'd like**

I propose adding an option within Stremio's settings to enable the output of the currently playing stream title. This title could be displayed or made accessible through various methods:

* A dedicated text field within the Stremio interface displaying the current stream title.
* An option to output the title to a folder as a filename where I can get Taiga to scan.

**Describe alternatives you've considered**

The current workaround involves playing Stremio streams through a separate media player like VLC. While this allows Taiga to recognize the process and potentially the title, it's a clunky and inconvenient solution for people like me who prefer the Stremio player instead.

**Additional context**

This feature would benefit users who prioritize seamless integration between Stremio and anime tracking applications like Taiga. Additionally, the ability to output stream titles could open doors for future integrations with other tracking or monitoring tools.

By implementing this feature, Stremio can enhance the user experience for those who utilize the platform for anime streaming and tracking.

**Comment by kuusuru** [comment]
Any luck with this guys?

**Comment by TRtomasz** [comment]
Closing this issue, as duplicate, we are working on a feature that will allow 3rd party trackers to create addons to track progress.
