### ISSUE TITLE
Extend 'Continue Watching' List to Show More Than Last Eight Items

### ISSUE THREAD

**Issue by tariqs0** [Stremio/stremio-features#867]
**Stremio Version** 
4.4.168 on macOS Catalina

**Is your feature request related to a problem? Please describe.**
Yes, my feature request is related to a limitation in Stremio's current functionality. Currently, Stremio doesn't provide a way to see the full list of 'Continue Watching' list.

The 'Continue Watching' list is currently limited to only the last eight items. This limitation is problematic because it restricts access to a broader history of what I've been watching, making it difficult to resume shows or movies that I haven't finished watching but started some time ago.

**Describe the solution you'd like**

I propose adding an option within Stremio's settings to enable the output of the 'Continue Watching' list in the home page to show more than the last eight items. Additionally, I would like the 'Continue Watching' list to function similarly to the 'Watched' list in the Library section, which handles a much more extensive history. Ideally, this list should allow users to see at least the last 20 items they have started watching.

- **Expand 'Continue Watching' List Display Options:** Add an option within Stremio's settings that allows users to customize the number of items displayed in the 'Continue Watching' list on the home page.
- **Functionality Similar to 'Watched' List:** Enable the 'Continue Watching' list to function similarly to the 'Watched' list found in the Library section, which accommodates a more extensive history of watched content.
- **Increase List Capacity:** Ideally, adjust the 'Continue Watching' list to show at least the last 20 items that a user has started watching, enhancing the ability to resume viewing more easily.

**Describe alternatives you've considered**

An alternative could be to provide users with a setting to customize the number of items displayed in the 'Continue Watching' list, allowing for greater flexibility based on individual needs.

**Additional context**

This change would enhance the user experience by making it easier to pick up where they left off, especially for users who frequently switch between different series or movies. This feature is standard in many other streaming platforms and would be a valuable addition to Stremio.

**Comment by TRtomasz** [comment]
This will not be added to the existing desktop app, sorry. Stremio 5 does not have this limitation

**Comment by tariqs0** [comment]
dear @TRtomasz, 
> This will not be added to the existing desktop app, sorry. Stremio 5 does not have this limitation

how can i get Stremio 5 ?

**Comment by tariqs0** [comment]
> > This will not be added to the existing desktop app, sorry. Stremio 5 does not have this limitation
> 
> how can i get Stremio 5 ?

**Comment by TRtomasz** [comment]
@tariqs0  Stremio 5 is a web app https://web.stremio.com/
requires Stremio Service or regular stremio app to be turned on in the background in order to have access to the all features

**Comment by tariqs0** [comment]
@TRtomasz thank you for your support 
i will take it as solution at least there's a workaround for the issue

**Comment by tariqs0** [comment]
@TRtomasz also it would b great if possible to add "continue watching" same as "watched" in Library in desktop app
