### ISSUE TITLE
[UI Visibility] Enhance and streamline tags & being able to read full filename

### ISSUE THREAD

**Issue by itsrenoria** [Stremio/stremio-features#868]
**Stremio Version**
web.strem.io
app.strem.io

**Is your feature request related to a problem? Please describe.**
Tags (e.g DV, HDR, Multi Audio, 4K etc.) are not streamlined. Some of them are next to the source name, some of them under the filename or as part of it, some tags are missing entirely for some titles and some tags are not used at all (e.g Hybrid). 

On mobile (not sure about other clients) it's impossible to see the full filename for most of the content. Mainly due to the filename size however most of the screen is used for artwork and this information is truncated. 

**Describe the solution you'd like**
Revamp and streamline tagging by adding the missing ones and keeping a simplified UX under the same place in the UI for these tags.

Dedicate a bit more space towards the available sources or implement an auto scroll on the filenames or manual scroll. Currently you're not able to do anything about it. 

**Additional context**
Below some examples from web.strem.io and app.strem.io on how these are displayed. Also, whilst I very much prefer stremio and its UI and UX another example from Kodi on how this is handled (both tags and filenames).

![IMG_9046](https://github.com/Stremio/stremio-features/assets/1799282/bbd5a29c-a4e1-4278-b313-3659886e8fa1)
![IMG_9047](https://github.com/Stremio/stremio-features/assets/1799282/cb732574-2605-4935-a1d8-b00cc9524d24)
![IMG_9048](https://github.com/Stremio/stremio-features/assets/1799282/3c234924-bea5-4cd1-bc8b-095d336a4998)
![IMG_9049](https://github.com/Stremio/stremio-features/assets/1799282/138ba276-5825-49d3-8c78-871c728211c7)
![IMG_9050](https://github.com/Stremio/stremio-features/assets/1799282/b065e574-ff37-438d-96a8-0fc7ae8ee2d9)
![IMG_9051](https://github.com/Stremio/stremio-features/assets/1799282/af2229f3-da1c-460d-8422-04eee9dd603c)

**Comment by jaruba** [comment]
this feature request is invalid, all the text that is shown for streams comes from addons, Stremio does not parse any filename or stream name or anything, it just displays what the community built addons are returning

**Comment by itsrenoria** [comment]
> this feature request is invalid, all the text that is shown for streams comes from addons, Stremio does not parse any filename or stream name or anything, it just displays what the community built addons are returning

sure enough, but being able to display (on mobile) the filename that the community built addons are returning fully, is surely valid?

**Comment by itsrenoria** [comment]
> this feature request is invalid, all the text that is shown for streams comes from addons, Stremio does not parse any filename or stream name or anything, it just displays what the community built addons are returning

![IMG_9242](https://github.com/Stremio/stremio-features/assets/1799282/b52cbdd5-c26b-4aed-a5f8-54c390ea6744)

another example, full filename is shown
