### ISSUE TITLE
Problem with barcode in OSX app

### ISSUE THREAD

**Issue by uberchilly** [Stremio/stremio-features#87]
![image](https://user-images.githubusercontent.com/5727941/39672942-b2535d10-5133-11e8-8412-abec83d31e62.png)

**Comment by jaruba** [comment]
![top-men-working-on-it-top-men-indiana-jones-lost-ark-ending-1370708259x](https://user-images.githubusercontent.com/1777923/39710808-838e4050-5226-11e8-84d3-198bb688d0ae.gif)
