### ISSUE TITLE
Faster Cinemata Movies and Series poster loading

### ISSUE THREAD

**Issue by shanestonk** [Stremio/stremio-features#870]
**Stremio Version**
Stremio Version and OS
Latest version and Google Tv

**Is your feature request related to a problem? Please describe.**

Lately it seems the Stremio Cinemata load slower to show the Movies and Series poster. 

**Describe the solution you'd like**

Probably let user have option to download list of movie series, manually update list, or stremio cinemata use multi thread downloading of poster.![image](https://github.com/Stremio/stremio-features/assets/87970107/33c5f035-9ba7-4641-b23c-f8a8485c6a68)

**Describe alternatives you've considered**

**Additional context**

**Comment by TRtomasz** [comment]
Stremio is a free app and our infrastructure is state of the art considering our limited resources. I dont think that thre is any issue with speed of loading posters, otherwise we would have tons of users reports, so i dont see here any feature that could be implemented
