### ISSUE TITLE
Is it impossible to add opening skipping recap option

### ISSUE THREAD

**Issue by pookiewx** [Stremio/stremio-features#871]
Please take note of the following text:

**Stremio Version**
Stremio Version and OS

**Is your feature request related to a problem? Please describe.**
Yes, because it can change a lot of things, like added options. More people use this app, especially anime watch
<img width="268" alt="Ecl5GR2XgAAKG30" src="https://github.com/Stremio/stremio-features/assets/142195419/ef315bbf-5e46-4233-88b6-ac5faec204d8">
ers

**Describe the solution you'd like**
Add an option for skipping opening and recaps for a smoother viewing experience.

**Describe alternatives you've considered**
From the user's perspective, an enhanced viewing experience for the app.

**Additional context**
Please add any other relevant context or screenshots about the feature request here.

**Comment by TRtomasz** [comment]
No this is not possible, we do not controll available streams like netfix to be able to do it.

**Comment by pookiewx** [comment]
I do not expect you to have the same level of control over Netflix as they do.just.do openng  Or stremio addons for this or create a skip time button on the player that can happed
