### ISSUE TITLE
Added skip time button option 

### ISSUE THREAD

**Issue by pookiewx** [Stremio/stremio-features#873]
To all devices and Stremio website 

**Is your feature request related to a problem? Please describe.**
Adding a skip time button can help viewers skip TV show openings and endings, especially when watching anime. or movies tv  characters 

**Describe the solution you'd like**
Add a skip time button on the player  also an option for changing the skipping time if some don't like the skip button option for disabling the button 

**Describe alternatives you've considered**
this is the only solution I can come up with after thinking for a lot of days 

**Additional context**
![Screenshot_20240604_222251_Dantotsu](https://github.com/Stremio/stremio-features/assets/142195419/389cd30f-78fb-4437-ac02-fb6995c1d669)
![Screenshot_20240604_222245_Dantotsu](https://github.com/Stremio/stremio-features/assets/142195419/c3084723-f506-42cd-a6ad-6264f6fbd758)

**Comment by TRtomasz** [comment]
Ending skipping, exists in the app, we show a button to start next episode, you can controll when it shows up by configuring "Next video popup duration" setting, for skipping opening you should use regular forwarding options, no reason to clutter ui and menu with options

**Comment by pookiewx** [comment]
Bro what

**Comment by pookiewx** [comment]
> This exists in the app under "Next video popup duration" to skip ending, for skipping opening you should use regular forwarding options, no reason to clutter ui and menu with options

Bro what
