### ISSUE TITLE
Add animetosho to stremio as an addon or to torrentio

### ISSUE THREAD

**Issue by The2ndYamchaEnjoyer** [Stremio/stremio-features#874]
**Stremio Version**
Stremio Version and OS

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jaruba** [comment]
i already closed one of ur issues today for the same reason, we do not create addons, the community addon developers do, how u'd be able to reach them is a mystery to us
