### ISSUE TITLE
Support Dolby Atmos passthrough in Samsung TV App

### ISSUE THREAD

**Issue by subru** [Stremio/stremio-features#876]
**Stremio Version**
Stremio Version 1.3.0 on Tizen OS 8.0 firmware 1411

**Is your feature request related to a problem? Please describe.**
The Samsung TV App in general works very nicely but unfortunately it doesn't playback Dolby Atmos.

**Describe the solution you'd like**
I would like Dolby Atmos soundtrack to play with full Atmos and not DD+.

**Describe alternatives you've considered**
My soundbar is connected to my eARC port and other apps do pass Atmos and both my TV & soundbar have the latest firmware. Moreover, if I play the same file on my firestick, it does pass through Atmos.

**Comment by TRtomasz** [comment]
Looks like your TV itself cant passthrough dolby atmos, there is no such setting for us to use there.
