### ISSUE TITLE
Offline access

### ISSUE THREAD

**Issue by orlandovallejos** [Stremio/stremio-features#88]
It would be really nice if we could have a offline access to the previously downloaded library. It's very useful because we could download the movies and watch them whenever we want, even though we don't have internet access.

If you guys could make a section for this it would be amazing, something like Netflix has.

Amazing work!

**Comment by Ivshti** [comment]
we tried rolling out this feature many times, but it's complex for a few reasons, including determining how to manage and prioritize parallel downloads, how to make a convenient UI and how to manage space. However, we do plan on still rolling this out at some point, probably with some iteration of 4.x 

thanks for the tip!

@jaruba what do you think

**Comment by jaruba** [comment]
funnily enough, i just saw this request now and have already started work on something very similar to this not more then a couple of days ago as a separate hobby project.

i agree that it's a complex task, especially with Stremio's current architecture, there are many things to consider here, some notable ones would be: disk space, would the downloaded items continue to be seeded, (if so, setting a maximum of parallel active torrents), checking files periodically to make sure users didn't delete them manually, some sort of an option or manager to stop seeding, as u might want ur full bandwidth at times, partially downloaded files (if the app closes during a download, those previous files need to be verified on start to resume download)

But the thing that i consider to be bad UX from all of this, would be the lack of a comprehensive manager. Stremio would use more resources, more bandwidth, without a manager with which u can keep it at bay, it may do more harm then good to users in the long run. I may be overcomplicating this for now though, it needs a well thought of plan that takes all or most edge cases into account while also giving users some control over it.

**Comment by inluxc** [comment]
+1

**Comment by TRtomasz** [comment]
Achived with 3rd party software - https://github.com/BurningSands70/stremio-downloader

**Comment by Chaiavi** [comment]
Please reopen this feature request, as it is very important for lots of people and should be incorporated in the core of StreamIO
