### ISSUE TITLE
[LG WebOS] Go back to details page when closing a stream

### ISSUE THREAD

**Issue by whatuserever** [Stremio/stremio-features#880]
**Stremio Version**
Stremio Theater v1.3.0
LG WebOS 8.3.1-30

**Is your feature request related to a problem? Please describe.**
The reasoning is similar to #879. I often find myself having to change video source. However, when I close the stream, Stremio takes me back to the home page. Choosing "Continue Watching" from the home screen defaults to the same source, so I have to manually go to the series page, find my episode, and then choose another source.

**Describe the solution you'd like**
Display the episode details page when closing a stream, instead of going to the home screen.

**Describe alternatives you've considered**
Manually going to the episode details page.

**Additional context**
* The problem described above seems to only be relevant when playing content directly from the "Continue Watching" section.
* My request is the same as the behavior in Android TV version of Stremio.

**Comment by TRtomasz** [comment]
This behavior will not be changed as it would affect to many users that are used to to it.

**Comment by whatuserever** [comment]
I opened this issue *because* I'm used to the behavior from Android TV. The LG WebOS version is rather new and doesn't match that behavior.
