### ISSUE TITLE
Requesting Audio related feature to improve audio quality even in 2.1 channel supported devices like soundbar or tv. 

### ISSUE THREAD

**Issue by Chandu9346** [Stremio/stremio-features#883]
**Stremio Version**
LATEST using both Android and tv with soundbar

**Is your feature request related to a problem? Please describe.**
Is there any way that we can play 5.1 audio to downstream to 2.1 audio channel, I can't find audios except 5.1 or 7.1 in streams that makes dialogues not clear even at full volume. I am using 2.1 supported soundbar while playing movies in that even I am playing at 100% I can't able to hear dialogues clearly but if I use external player to tracking of what we watched is not updating. So requesting if there is any update or answer to my issue.

**Describe the solution you'd like**
Not sure with any solution tried with Nova and Kodi they make audio bit high but downgrading bass and sometimes noises

**Describe alternatives you've considered**
NA

**Additional context**
Nope explained all in top sessions

**Comment by TRtomasz** [comment]
You should switch in the settings to use libvlc instead exoplayer then it should help with downmixing.
It is possible to configure everything so it will work properly with Exoplayer but cant give you exact configuration as it depends on your hardware, but i was able to configure my Samsung smart tv in a way that exoplayer volume level is the same as with libvlc.
There is no feature here we can implement, only your setup configuration, we do not create video players we use existing components: exoplayer(media3) and vlc player.
