### ISSUE TITLE
Infuse support (Mac)

### ISSUE THREAD

**Issue by zeronullempty** [Stremio/stremio-features#885]
MacOS

Can streams be launched directly in Infuse Player FOR MAC? I can copy/paste the stremio url manually but it would be cool if it was supported as an external player ON MAC.

VLC. It doesn't have the HDR support and colors of Infuse.

I know you have said not to support on Infuse on iOS. But this is for Mac. It would really help the user experience. Thanks.

**Comment by TRtomasz** [comment]
Please use the template when requesting new feature.
