### ISSUE TITLE
Kodi RPC settings 

### ISSUE THREAD

**Issue by Dappakid13** [Stremio/stremio-features#887]
**Is your feature request related to a problem? Not a problem, more like a missing feature.

I love stremio and I have been looking for a really good external player and the best and most versatile one for me is kodi.  With rpc u should be able to have track the progress like the other players.

I want to be able to set kodi as the external player and adjust the port manually  which should allow me to resume my progress similar to sycler and weyd.

Screenshot:  shows kodi weyd setting below.

![Screenshot_20240615_003509_weyd](https://github.com/Stremio/stremio-features/assets/54221932/1c37f4fd-ff31-454d-b7ae-defe575487a8)
![Screenshot_20240615_003459_weyd](https://github.com/Stremio/stremio-features/assets/54221932/3647f6d3-b125-419c-b694-3c9c33703619)

**Comment by TRtomasz** [comment]
We do not plan to add anything like this, as this would be used by very small % of our user base and would require a lot of effort
