### ISSUE TITLE
dual subtitles support

### ISSUE THREAD

**Issue by nacho00112** [Stremio/stremio-features#888]
**Stremio Version**
Stremio 1.6.12 Android 11

**Is your feature request related to a problem? Please describe.**
I think this may be useful for many people, this will not only lead to better comprehesion of foreign content, but will also help language learners, because at the end I believe that language learning is indirectly related with watching content, the proof of this is that in the language learning community, netflix and youtube are some of most widely used tools to learn through audiovisual content.

**Describe the solution you'd like**
some sort of functionality to select two languages for dual subtitles.

**Describe alternatives you've considered**
the closest tools I've found for something like this is LingoTube app, which is a wrapper for youtube that does dual subtitles using youtube subtitles function + google translate, and has many more useful options for example to be able to select subtitles text and then you can also quickly look up for a specific word or phrase by selecting it and then you get a pop-up of one of the many online dictionaries LingoTube support. There are also netflix extensions that I've read about and have never been able to use.

**Additional context**
I will describe my personal needs for this function, but you may of course implement it as you wish, the ideal for me would be to have audio in say, english, a subtitle in english, and another in spanish (I'm spanish speaker so sorry for any english mistake).

**Comment by nacho00112** [comment]
It seems that this request has already been rejected several times in the past, so if there is no plan of adding this, before closing the issue, could you please at least give me some advice to find alternatives?

**Comment by nacho00112** [comment]
or, what about the subtitle select function and dictionary pop-up? may it be added?

**Comment by jaruba** [comment]
@nacho00112 Stremio is not a language learning app, and we are not planning on making it a language learning app. If some community dev decides to make an addon that merges multiple subtitles into one then u will get this feature, otherwise Stremio's goals do not align with this request.
