### ISSUE TITLE
Android mobile and Android TV apps feature requests

### ISSUE THREAD

**Issue by ZainAjam** [Stremio/stremio-features#889]
**Stremio Version**
Stremio Version 1.6.12 Android 14
Stremio Version 1.6.9 Android TV 11

**Is your feature request related to a problem? Please describe.**
It is not

**Describe the solution you'd like**

Feature requests: 
1. Make the android TV app tile right angle corners. It has white corners on the tile because of the tile image seems to not have rectangular corners

2. Split the library section on Android TV in to movies and TV shows

3. Insert movies and TV shows tabs in the library section of the mobile app

4. Improve the discover section of Android TV app so that there is no need for filters at the top but rather the different combination of filters are displayed as rows. This means the user doesn't need to deal with specific filters when trying to discover content. Selecting the correct combination of filters may result in a lost opportunity to discover content. Also managing filters is slightly inconvenient. 

5. Allow reordering of rows on the home screen or at the very least allow reordering of the add-ons that cause the order of the rows

6. Please allow sorting TV shows in library by last air date

7. Now the risky one ... Please allow app user profiles

**Describe alternatives you've considered**
Not applicable

**Additional context**
These feature requests are so to help make the user experience better

**Comment by TRtomasz** [comment]
Please use one issue for one new feature request

**Comment by TRtomasz** [comment]
https://github.com/Stremio/stremio-features/issues/622#issuecomment-4673832722
