### ISSUE TITLE
launch in fullscreen mode

### ISSUE THREAD

**Issue by joshjames** [Stremio/stremio-features#89]
hi i cant seem to see the core code base here on github.. so havent been able to find out of the compiled electron exetuable supports any command parameters...
nevertheless i tried the obvious stremio.exe -fullscreen, stremio.exe /fullscreen, stremio.exe --fullscreen...
and tried stremio.exe /? and other help possabilities with no results...
so im assuming the exectuable has no parameter options??

SO.
is it possible to add the ability to launch the application (desktop, windows, electron) in fullscreen mode with some command parameters?
or if someone could point me to the core code base.. im sure I can make a fork, find the current fullscreen toggle, add a parameter argument function and recompile myself..
my code would be too sloppy to be considered to be merged back to main but it would be fine for my own purposes.

thanks :)
Josh

**Comment by Ivshti** [comment]
This is our shell: https://github.com/stremio/stremio-shell

and an example of argument parsing: https://github.com/Stremio/stremio-shell/blob/master/main.qml#L286

and window mode: https://github.com/Stremio/stremio-shell/blob/master/main.qml#L362

basically you have to put it in this function: https://github.com/Stremio/stremio-shell/blob/master/main.qml#L489
