### ISSUE TITLE
Fix the shape of the Android TV tile icon for Stremio

### ISSUE THREAD

**Issue by ZainAjam** [Stremio/stremio-features#890]
**Stremio Version**
Stremio Version 1.6.9 Android TV 11

**Is your feature request related to a problem? Please describe.**
It is not

**Describe the solution you'd like**
Make the android TV app tile corner radius match that of the Android TV OS launcher's tile shape. At the moment, it has white corners on the tile because of the tile image seems to not have rectangular corners

**Describe alternatives you've considered**
Not applicable

**Additional context**
None

**Comment by TRtomasz** [comment]
What is the device you are using?

**Comment by ZainAjam** [comment]
Shield TV running Android TV os ... The corners of the app tile have some white to it

![Screenshot_20240617-134607](https://github.com/Stremio/stremio-features/assets/32865278/d70e0f5b-ac4b-43b7-a28a-32e597d1d041)

**Comment by charliesheen14** [comment]
I have the same issue on a nokia 8010

**Comment by TRtomasz** [comment]
This is Android TV issue not stremio issue where they do not present responsive banners correctly.
