### ISSUE TITLE
On Android TV, have a "Movies" and "TV Shows" menu item in the side bar instead of having a single "Library"menu item

### ISSUE THREAD

**Issue by ZainAjam** [Stremio/stremio-features#891]
**Stremio Version**
Stremio Version 1.6.9 Android TV 11

**Is your feature request related to a problem? Please describe.**
It is not

**Describe the solution you'd like**
Split the library menu item on the left side bar on Android TV into separate "movies" and "TV shows" sections.

**Describe alternatives you've considered**
Not applicable

**Additional context**
None

**Comment by TRtomasz** [comment]
Whats the point of this? When you open library you see both Movies and Series on the same screen there is no point to have two separate options in the menu

**Comment by ZainAjam** [comment]
Would have been nice to use the separate sections to be a wall of posters instead a slidable list and if movies have its own section, you get lots of movies in a single page
