### ISSUE TITLE
On Android Mobile, have the library section have "Movies"and "TV Shows" as swipeable tabs instead of drop down lists

### ISSUE THREAD

**Issue by ZainAjam** [Stremio/stremio-features#892]
**Stremio Version**
Stremio Version 1.6.12 Android 14

**Is your feature request related to a problem? Please describe.**
It is not

**Describe the solution you'd like**
Because the library only has two filters, it would be a little more convenient for user to have the two options as swipeable tabs instead of dropdowns.

**Describe alternatives you've considered**
Not applicable

**Additional context**
None

**Comment by TRtomasz** [comment]
Library does not have only two types, it has only two types for you because you added two types of content to your library
