### ISSUE TITLE
Improve the discover tab on Android TV

### ISSUE THREAD

**Issue by ZainAjam** [Stremio/stremio-features#893]
**Stremio Version**
Stremio Version 1.6.9 Android TV 11

**Is your feature request related to a problem? Please describe.**
It is not

**Describe the solution you'd like**
Improve the discover section of Android TV app so that there is no need for filters at the top but rather the different combination of filters are displayed as rows instead. This makes better use of the TV canvas and means the user doesn't need to deal with specific filters when trying to discover content. Selecting the correct combination of filters may result in a lost opportunity to discover content. Also managing filters is slightly inconvenient.

There may also be some merit in moving the items that are currently in the home screen to the discover screen but keep the filters at the top. Then the home screen can rather be used for things like "Continue Watching" and "Favourites".

**Describe alternatives you've considered**
Not applicable

**Additional context**
None

**Comment by TRtomasz** [comment]
You have dashboard section exactly for this, it displays more items without filters.
We dont want to overload addons with requests whensomeone opens Discover section.
