### ISSUE TITLE
In the library, please allow a sort option to sort by air date (for tv shows) and Release Date (for movies)

### ISSUE THREAD

**Issue by ZainAjam** [Stremio/stremio-features#895]
**Stremio Version**
Stremio Version 1.6.9 Android TV 11

**Is your feature request related to a problem? Please describe.**
It is not

**Describe the solution you'd like**
Please allow sorting TV shows in library by last air date and movies by release date

**Describe alternatives you've considered**
Not applicable

**Additional context**
None

**Comment by TRtomasz** [comment]
closing as duplicate https://github.com/Stremio/stremio-features/issues/562

**Comment by ZainAjam** [comment]
Issue 562 is not the same issue as this one. THis one is about sorting the tv episodes inside the LIBRARY by air date
