### ISSUE TITLE
Please allow for user profiles on the app OR at least allow for a quick way to switch accounts

### ISSUE THREAD

**Issue by ZainAjam** [Stremio/stremio-features#896]
**Stremio Version**
Stremio Version 1.6.9 Android TV 11

**Is your feature request related to a problem? Please describe.**
It is not

**Describe the solution you'd like**
Please allow a way to store a stremio account in the app, so that logout and login can easily be done by selecting the accounts

**Describe alternatives you've considered**
Not applicable

**Additional context**
None

**Comment by TRtomasz** [comment]
Please use search feature before creating new feature request
https://github.com/search?q=repo%3AStremio%2Fstremio-features+profile&type=issues

**Comment by TRtomasz** [comment]
https://github.com/Stremio/stremio-features/issues/622#issuecomment-4673832722
