### ISSUE TITLE
Hide porn from results 

### ISSUE THREAD

**Issue by mnewiraq** [Stremio/stremio-features#899]
As a user of Stremio, I would like to request an option to hide adult content from search results. This feature would enhance the user experience by allowing individuals to filter out inappropriate or sensitive material. Please consider implementing this feature for a safer and more family-friendly browsing experience.

Thank you for your attention to this matter!

**Comment by gduchateau1982** [comment]
Something like parentcontrol add pincode on porn results and also set pincode before installing. Maybe with kids profile and pincode on de parent profile.
That will be verry helpfull. ❤️

**Comment by TRtomasz** [comment]
If you dont want porn content in search result you should remove porn addons. Stremio does not control provided content. We have no idea what is porn and what is not.

**Comment by carterlion13sAltAcc** [comment]
> As a user of Stremio, I would like to request an option to hide adult content from search results. This feature would enhance the user experience by allowing individuals to filter out inappropriate or sensitive material. Please consider implementing this feature for a safer and more family-friendly browsing experience.
> 
> Thank you for your attention to this matter!
1, installing [The Movie Database] (https://94c8cb9f702d-tmdb-addon.baby-beamup.club/configure) in your language
2, go to Stremio addons and access the browser console and paste this CODE: 
https://pastebin.com/raw/sBgszEW6)

Wait until the message Success: {"result":{"success":true}}

You will now be able to remove Cinemeta. (If the protection message still appears, just press F5 on the page and try removing the addon). If you followed my advice and installed the TMDB addon before running the script, it will now be your new catalog manager. If you haven't installed TMDB and have already removed Cinemeta, you now have a broken system. No problem! You can install TMDB and run the script again, or re-install [Cinemeta](https://v3-cinemeta.strem.io/) and everything will work as before. 
Credit: https://www.reddit.com/r/StremioAddons/comments/1d8wbul/how_to_remove_cinemeta/

**Comment by cliffordpascal** [comment]
Even simplier than that is to simply code stremio to be able to disable  addons without uninstalling them, if an add-on is providing adult material simply turn it off without uninstalling it, when you want to retrieve adult material, go into the addon page find addon and enter pin to re-enable it, devs could do this in 10 mins
