### ISSUE TITLE
Make magnet links available in resolution selection screen.

### ISSUE THREAD

**Issue by leukhe** [Stremio/stremio-features#9]
If the source is a torrent, make a magnet link available, either in the inbween screen, or as a sharing option next to twitter, plus and facebook. 

Useful to find the exact torrent to download for adding in the local library. 

(well.. save to file if 100% cached is nice too.)

**Comment by Ivshti** [comment]
How about adding an item to the player's context menu "Copy magnet link" or "Copy HTTP link" depending on the stream's source?

**Comment by rodrigograca31** [comment]
This feature would be awesome!
If we could have the magnet link we could download the torrent and have it offline and be seeding....

**Comment by rodrigograca31** [comment]
Hi @TRtomasz 

Why was this issue closed? Was this be implemented?

Thanks

**Comment by TRtomasz** [comment]
@rodrigograca31 Yes, this is implemented in Stremio 4 magnet links are available through player context menu

**Comment by rodrigograca31** [comment]
OMG! :open_mouth: 
This is awesome! There's also a "Download this Video" option! :tada: 

Now hopefully there will be more seeders (if people convert the magnet link to torrent and seed it, instead of just downloading the video)

**Comment by alexandrebarbaruiva** [comment]
@TRtomasz whenever I try to use the magnet link, it returns a static URL with nothing in it to download. Wasn't it supposed to return the file's torrent URL?

My URL: magnet:?xt=urn:btih:bd5a8bf61bf70e940bfa99e414dff3b0fd4d8b68

**Comment by TRtomasz** [comment]
@alexandrebarbaruiva  Thats how magnet links looks.
