### ISSUE TITLE
Request for an easier and more intuitive user interface on Android TV

### ISSUE THREAD

**Issue by ZainAjam** [Stremio/stremio-features#906]
**Stremio Version**
Stremio Version 1.6.9 Android TV 11

**Is your feature request related to a problem? Please describe.**
It is not

**Describe the solution you'd like**
Looking at the Netflix app, it has the following sections:

- Search
- Home
- New & Popular
- Shows
- Movies
- Categories
- My List

I would love to see Stremio implement the above layout, by doing the following:

- Nothing to change on search, so that would stay the same
- Nothing to change on home, so that would stay the same
- No need for "News and Popular" section at this stage, although it would be a nice bonus
- **Introduce a Shows section, which would effectively be the home section but for TV shows only**
- **Introduce a Movies section, which would effectively be the home screen but for Movies only**
- No need for "Categories" section at this stage, although it would be a nice bonus
- **Rename "Library" to "My Watchlist" or "Favourites"**

**Describe alternatives you've considered**
Not applicable

**Additional context**
None

**Comment by TRtomasz** [comment]
This is highly subjective i dont see any benefit for majority of users that would come with implementing this.

**Comment by ZainAjam** [comment]
I think having a TV show and movies section will help considerably.

I sit down and want to look for a movie but then I just dig through the
home screen full of both movies and TV shows. It would be great to have a
home screen just for TV shows and great to have a home screen just for
Movies.

Strange that you don't see the value in that for many users.
