### ISSUE TITLE
Support for VidHub as an external player

### ISSUE THREAD

**Issue by vijayvcm** [Stremio/stremio-features#907]
VidHub is an cheaper alternative media player for infuse. It’s powerful and has a lot of playback feature. 

Recently they are supporting 3rd Party App Integration also. 

It would be awesome if we get VidHub as additional optional under external player section of Stremio.

Here is the documentation url for opening videos via x-callback url.

https://vidhub.okaapps.com/3rd-party-app-integration/

**Comment by mrsidnaik** [comment]
Hello, 

I am using Stremio lite on ios and I do not see VidHub as an external player option. It is just Outplayer and Infuse. 

Am I missing something?
