### ISSUE TITLE
Add brightness and volume slider in default player

### ISSUE THREAD

**Issue by ashishb122** [Stremio/stremio-features#908]
**Stremio Version**
Stremio Version 1.6.12 Android

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In the default player it would be better if brightness and volume slider is present. That would be a great feature.

**Describe alternatives you've considered**

**Additional context**

**Comment by TRtomasz** [comment]
https://github.com/search?q=repo%3AStremio%2Fstremio-features+brightness&type=issues
