### ISSUE TITLE
Enable subtitles when rewinding for 10 seconds and then disable it (wadeysay)

### ISSUE THREAD

**Issue by isgapetti** [Stremio/stremio-features#912]
**Stremio Version**
1.6.9 on Nvidia Shield 2019

**Is your feature request related to a problem? Please describe.**
You are watching a movie (with _disabled subtitles_ or _forced subtitles_) and then suddenly, you can't understand the dialogue of a character because they are whispering it or have a thick accent. To figure out what was just said is a multi-step process: pause the movie, switch subtitles to english, rewind the movie, watch and READ it, and then switch back to forced or disabled subtitles.

**Describe the solution you'd like**
Have the option to enable this wadeysay feature with one button press in order to
- pause the movie
- switch subtitles to english
- rewind the movie
- watch and READ it
- and then switch back to forced or disabled subtitles

**Describe alternatives you've considered**
N/A

**Additional context**
This request is pretty much the same as Kodi's [wadeysay](https://forum.kodi.tv/showthread.php?tid=372702) addon which is a nice quality of life feature.

Possible configuration options:
Rewind time: range 0 to 60 seconds - how much to rewind in seconds

Keep subtitle on longer than rewind time : range 0 to 60 seconds - subtitles will stay on for all of rewind time plus this amount in seconds
SDH: on/off - prefer subtitle for deaf and hard of hearing

Subtitle forced: options - if forced subtitle is encountered then find subtitle with selected language preference

Subtitle disabled: options - if subtitle is off then turn on either selected subtitle as long as it is not forced or find subtitle with selected language preference

**Comment by jaruba** [comment]
i understand that some addon of a different app is solving a (very) minor issue for (very) few users, but Stremio addons cannot do this and we will not fill the app with features and settings that the majority of users will never use or even understand..

just always have subtitles on to ensure that u understand what the actors say?
