### ISSUE TITLE
Reorder home screen widgets 

### ISSUE THREAD

**Issue by jamos316** [Stremio/stremio-features#915]
I would love it if I could get the my trakt widgets on the home screen (tv show progress & movies watch list) to appear at the top.
This will allow me to keep track of when TV shows come back.

Thanks

**Comment by TRtomasz** [comment]
Please use the search option before opening new issue, willo close that one as a duplicate https://github.com/search?q=repo%3AStremio%2Fstremio-features+reorder&type=issues
