### ISSUE TITLE
automatically buffer the next episode

### ISSUE THREAD

**Issue by DavidSingh3** [Stremio/stremio-features#918]
**Stremio Version**
Stremio Version 4.4.160 and OS Ubuntu 22.04

**Is your feature request related to a problem? Please describe.**
It's a minor inconvenience that I have to wait a couple of seconds for the next episode to start buffering.

**Describe the solution you'd like**
There should be an optional config setting that when enabled, will automatically start buffering the next episode when buffering for the current episode is completed. 

**Describe alternatives you've considered**
N/A

**Additional context**
A duplicate of this issue was requested in 2018: https://github.com/Stremio/stremio-features/issues/80.
This was marked as "completed" and closed without any further elaboration. From what I can tell this feature does not exist yet.

**Comment by TRtomasz** [comment]
closing that one as duplicate - https://github.com/search?q=repo%3AStremio%2Fstremio-features+buffer&type=issues 
Completed does not mean it has been 'completed' it is how github shows it and it cant be changed. We simply will not implement such feature for now.
