### ISSUE TITLE
Option to Enable or Disable Subtitles on a Per Show Basis

### ISSUE THREAD

**Issue by isgapetti** [Stremio/stremio-features#921]
**Stremio Version**
Stremio 1.6.9 on Shield TV 2019

**Is your feature request related to a problem? Please describe.**
I like subtitles being disabled, but I have to enable them for foreign shows or other shows that have thick accents. Right now, I would have to enable subitles everytime I start a new episode of a foreign show. This happens when I'm trying to watch from the Trakt History Catalog from the Trakt Integration addon.

**Describe the solution you'd like**
An option or toggle in the show's episodes page that will enable or disable subtitles for all the episodes of that show.

Rough sketch:

![IMG_5624](https://github.com/Stremio/stremio-features/assets/70197545/578cdc14-1460-4f01-9d5c-eec69498702f)

**Describe alternatives you've considered**
N/A

**Additional context**
An additional option for the audio language can be a nice quality of life addition.

**Comment by TRtomasz** [comment]
You can disable the by setting default subtitles language to "none" in the settings.

**Comment by isgapetti** [comment]
You seem to have misunderstood. Yes I know I can disable subtitles in the settings.

The feature I'm requesting is the option to **enable subtitles** for specific shows.
