### ISSUE TITLE
Stremio app bring native on PlayStation 4 and PlayStation 5 consoles

### ISSUE THREAD

**Issue by xman92** [Stremio/stremio-features#922]
STREMIO applications are on PlayStation 4 and 5 consoles! Can this app Stremio be on both PS4 and PS5 systems, respectively? Every fan of PlayStation would love that. I own a PlayStation 5 console that 1st came out in 2020 4 years ago. The app selection on PS5 is minimal. Will Stremio be native on PS4 and PS5 consoles?

**Comment by TRtomasz** [comment]
No, stremio will not be released for playstation or xbox any time soon
