### ISSUE TITLE
Option to Enable Subtitles on a Per Show Basis

### ISSUE THREAD

**Issue by isgapetti** [Stremio/stremio-features#924]
**Stremio Version**
Stremio 1.6.9 on Shield TV 2019

**Is your feature request related to a problem? Please describe.**
I like subtitles being **disabled** most of the time, but I have to _enable_ them for foreign shows or other shows that have thick accents. 

Right now, I would have to manually enable subitles everytime I start an episode of a foreign show. This happens when I'm trying to watch from the Trakt History Catalog of the Trakt Integration addon.

**Describe the solution you'd like**
An option or toggle in the show's episodes page that will enable subtitles for all the episodes of that **specific show**.

Rough sketch:

![345312324-578cdc14-1460-4f01-9d5c-eec69498702f](https://github.com/Stremio/stremio-features/assets/70197545/e50d647b-5b64-48b9-8f65-8d0549476685)

**Additional context**
This is a rephrased version of this closed [request](https://github.com/Stremio/stremio-features/issues/921#issuecomment-2205454279) since it seems to be misunderstood.

**Comment by TRtomasz** [comment]
We will not add feature that would be used by only very small % of Stremio users. Main idea of the app is to be as simple as possible. And basically we dont want to add option/configuration for every possible feature.
