### ISSUE TITLE
Subtitles, Audio Track Cycle and other controls  mappable to a controller 

### ISSUE THREAD

**Issue by L1NSEED** [Stremio/stremio-features#926]
Overall I just feel a disconnect when watching movies and TV shows that you have to control via an app interface . Gives the android TV experience a smart phone vibe.

I think it is important overall for better control with remotes like DVDs and TVs have had for years.  Ideally not through a third party mapper id even buy a Stremio remote for my shield or fire stick  . I’d also like to extend this request to Mac and PC via keyboard shortcuts .

I also would like to see an improvement to the D-pad  interface with a bit of flavour and increased discoverability and selecting of options like subtitles.

Thank you

**Comment by TRtomasz** [comment]
We do not plan to release our own remote.
