### ISSUE TITLE
Stremio for UWP (Xbox Dev mode)

### ISSUE THREAD

**Issue by BTr-RJ** [Stremio/stremio-features#927]
Is it possible to port Stremio to UWP for use on Xbox Series consoles in Dev Mode? I currently have Stremio installed on an Android TV box and LG TV WebOS, but I believe having it on Xbox would be beneficial for portability (since I own a Series S, which is almost a powerful Mini PCs with its size) and for its resources (such as native Dolby Vision and Atmos support). There are lots of of emulators and apps (including Kodi) already for Xbox Dev Mode, no Xbox Store involved....

Can it be done?

**Comment by TRtomasz** [comment]
No it is not possible

**Comment by DamageCase13** [comment]
> Is it possible to port Stremio to UWP for use on Xbox Series consoles in Dev Mode? I currently have Stremio installed on an Android TV box and LG TV WebOS, but I believe having it on Xbox would be beneficial for portability (since I own a Series S, which is almost a powerful Mini PCs with its size) and for its resources (such as native Dolby Vision and Atmos support). There are lots of of emulators and apps (including Kodi) already for Xbox Dev Mode, no Xbox Store involved....
> 
> Can it be done?

> No it is not possible


Well, arent you wrong?

**Comment by IanWONeill** [comment]
https://github.com/Misunderstood-Wookiee/Stremio-UWP/releases

**Comment by Cxsmo-ai** [comment]
There is stremio uwp for dev mode but 2 years old

**Comment by Julmik647** [comment]
> No it is not possible

There's a way to make it possibile: while Stremio doesn't have a UWP version, you can make an UWP app that's a wrapper for Stremio web. Jellyfin for example made their Xbox app in this way.
