### ISSUE TITLE
Reorder and disable addons

### ISSUE THREAD

**Issue by magste123** [Stremio/stremio-features#933]
**Stremio Version**
Google TV Andrpid 1.6.11
**Is your feature request related to a problem? Please describe.**
Add-ons are fixed in the order they are installed, for example different movie catalogues and services. This affects how they appear in the home section. The only way to change the order is to uninstall and reinstall in the order you want them.

There is also no way to disable an addon, only uninstall it.

**Describe the solution you'd like**
1. Ability to move add-ons up or down in the list.

2. Ability to disable and reenable add-ons rather than uninstalling them. This includes the one that come with stremio that cannot be uninstalled.

**Describe alternatives you've considered**
Uninstalling add-ons and reinstalling them in the correct sequence. This is time consuming, especially for addons requiring configuration.

**Comment by TRtomasz** [comment]
closing as duplicated of many same requests you can find in this repo
