### ISSUE TITLE
Rating pop up for trakt after viewing a show/movie

### ISSUE THREAD

**Issue by hypercryptoman** [Stremio/stremio-features#934]
A rating pop up after viewing a show or movie for trakt as soon it done viewing kind of like what is possible on kodi. Toggle option in settings. Be useful feature that I after to do manually after viewing and would completely bring me over from Kodi, which I want to do as stremio is simpler and easier to use. Thanks.

**Comment by TRtomasz** [comment]
This goes against rule to keep stremio to be as simple as possible.

**Comment by naviln** [comment]
I would love this feature. Some way to mark as watched and then rate it via the stremio UI.

**Comment by prestonsmartuk** [comment]
Same here, would love this feature. Will help with my trakt / couch money lists

**Comment by oozan22** [comment]
I have an ios shortcut to rate a title in trakt given imdb link:
take the logic here and implement a ui element- in streams maybe?(play 1 star, play 2 star....)
or preferably a ui element with stars (emty rating, 2/10 ,4/10... 10/10)
--- also needs to pull rating from trakt api with each title.

share an imdb link to rate a title(100% successful logic):

https://www.icloud.com/shortcuts/2e2dd331c523492881d6e3df7e299147

refresh token:

https://www.icloud.com/shortcuts/b696714dd466488db771573f0794ea9f
