### ISSUE TITLE
Sort by size regardless of addon

### ISSUE THREAD

**Issue by nagelsax** [Stremio/stremio-features#935]
**Stremio Version**
Stremio Version and OS

All Operating systems

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

I wish that the app could have av option to sort by size regardless of in which addon the fine is found in. 

**Describe the solution you'd like**

If I search for a video and I have 3 addons installed, and addon 1 has the video at say 20 gb but addon number 3 has  the video at 50 gb and addon 2 has it at 55 gb, it would be great to have the videos sorted ny size regardless of which addon. 

See the attached screenshots to see the problem. 

**Additional context**

![Screenshot_20240714-110643](https://github.com/user-attachments/assets/61cd2323-93b1-40c9-870c-15bdda7cef50)
![Screenshot_20240714-110758](https://github.com/user-attachments/assets/8885e0df-5c12-4ac2-864e-102e1db222f4)
![Screenshot_20240714-110744](https://github.com/user-attachments/assets/a2788945-672a-4b9f-a0bb-a91e099a7ab8)

**Comment by TRtomasz** [comment]
stremio does not have any data about video file size, this is coming from addons in the text form, so this feature is impossible to be implemented in a way that will work in 100% cases
