### ISSUE TITLE
[Feature Request] Stremio Audio Passthrough option

### ISSUE THREAD

**Issue by shanestonk** [Stremio/stremio-features#937]
**Stremio Version**
Stremio Version and OS
latest stremio and Android Tv

**Is your feature request related to a problem? Please describe.**

In Kodi, Nova and other movie app have the option to set audio as Passthrough but in Stremio there none of it. People using soundbar eg earc or arc they need the app to passthrough to the soundbar. 

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Make option so audio can be passthrough to soundbar or external

**Describe alternatives you've considered**

**Additional context**

![image](https://github.com/user-attachments/assets/6603216c-25eb-4b5e-8710-1b9db61ad858)

**Comment by TRtomasz** [comment]
There is no passthrough option in the Exo player - turn on tunneled playback. In general if exo detects that your device is capable to decode something it will automatically passthrough.
