### ISSUE TITLE
[Feature Request]Add Google chrome cast like feature for Fire tv os also.

### ISSUE THREAD

**Issue by Blue-Bliss** [Stremio/stremio-features#938]
**Stremio Version**
Stremio Version 1.6.12 on Android 14 OS
                              &
Stremio version-1.6.9 on Fire TV stick 4k max gen 1 OS.

**Is your feature request related to a problem?: 
Yes. I am unable to cast stremio from my phone to my fire tv  ( There is cast option available for fire tv on youtube,primevideo, netflix etc.)
Although stremio can be casted on android/google tv with chromecast seamlessly (but its doesn't happen for fire tv)**

**Describe the solution you'd like**:
Please Enable cast screen to fire tv also. (Like youtube, prime video, netflix etc. have done)

**Describe alternatives you've considered**:
Only whole phone screen mirroring works. But its frustrating , since you can't do anything on phone while watching.

**Comment by TRtomasz** [comment]
firetv devices do not come with built in chromecast.

**Comment by Blue-Bliss** [comment]
But its possible to cast directly through netflix, prime video, youtube apps from android phone to fire tv. How do they do that?

**Comment by Blue-Bliss** [comment]
![Screenshot_20240716_210154~2](https://github.com/user-attachments/assets/531955ef-edc6-48a6-bc1d-f1bd7dd5c45b)

Attaching the supporting screenshot from youtube.

**Comment by Blue-Bliss** [comment]
> firetv devices do not come with built in chromecast.

I have attached the supporting screenshot from youtube. Please go through that.
Can't this be done for stremio also?
