### ISSUE TITLE
[New Feature Request] Enabling cast feature from android phone to firetv

### ISSUE THREAD

**Issue by Blue-Bliss** [Stremio/stremio-features#939]
firetv devices do not come with built in chromecast.

_Originally posted by @TRtomasz in 
https://github.com/Stremio/stremio-features/issues/938#issuecomment-2230746733_

**QUERY**- I have attached the relevant screenshot from YOUTUBE showing that they allow to cast directly through app from PHONE to FIRETV.
Same feature is present in Prime video and Netflix also.
Can't we get the same feature in Stremio also?
            
![Screenshot_20240716_210154~2](https://github.com/user-attachments/assets/cdf6e130-d81c-4515-8395-4419b55d30de)

**Comment by TRtomasz** [comment]
This will not be added as they do not have built in chromecast. WE will not support DLNA casting as this technology is not worth it. You can just install stremio on your firestick
