### ISSUE TITLE
Speed Up and Slow Down video

### ISSUE THREAD

**Issue by Archetipo95** [Stremio/stremio-features#94]
Add the possibility to increse and reduce the speed for the video

**Comment by Xpcker** [comment]
Pleaseeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
