### ISSUE TITLE
[New Feature Request] -Subtitle/Audio cycle support

### ISSUE THREAD

**Issue by L1NSEED** [Stremio/stremio-features#940]
**Stremio Version**
Stremio Version and OS - Google TV/ Fire Stick + PC/Mac

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] When I have to go through a mobile phone like menu to turn on/off subtitles for when I watch with my wife  and when changing the Audio Track for Foreign films / TV shows 

**Describe the solution you'd like**

A Way to map  Subtitle Cycle / Audio Track Cycle buttons to remotes. for example the Fire Stick Pro remote (with custom buttons) or the Nvidia Shield remote + Button Mapper app - Custom Remotes for these devices that can be found on Amazon and Online Retailers that have dedicated Subtitle and Audio Buttons 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.  Hold  down on Dpad for Subtitle switching  and up for Audio Track 

**Additional context**

I don't mean to offend any of the creators or to create a hard job but I would like a reason as to why this can't or shouldn't be implemented . it has been a standard function since the very first DVD player I Owned. especially for subtitles this should be a must have - please consider the context of non english speakers to which Audio /Subtitles are a necessary function

**Comment by TRtomasz** [comment]
We do not plan to add such features that would be used by very small group of people and would require significant effort to be added.

**Comment by L1NSEED** [comment]
I would assume that non native English speakers is in fact a large part of the user base. And of course there is the reverse for Foreign films / shows and anime
