### ISSUE TITLE
Subtitles on samsung TV

### ISSUE THREAD

**Issue by bartolo112** [Stremio/stremio-features#942]
Written are displayed in the options to choose from, but when I select them, a message like this is displayed and the subtitles are not shown. It happens on Samsung tv on newest version of stremio.
![20240718_190916](https://github.com/user-attachments/assets/d11ce9c6-81e5-4481-a88c-6a6f78b76a2f)
![20240718_190906](https://github.com/user-attachments/assets/c372bd9a-2d99-4f4e-a961-b2cbf29b5b21)

**Comment by TRtomasz** [comment]
These are subtitles from not official addon but - Opensubtitles Plus addon so i guess addon is not working.
Ps this is stremio-features repository please use stremio-bugs for reporting bugs

**Comment by bartolo112** [comment]
Yeah, but on PC it works fine

pt., 19 lip 2024, 10:35 użytkownik Tomasz ***@***.***>
napisał:
