### ISSUE TITLE
Stremio Atv audio passthrough in settings

### ISSUE THREAD

**Issue by shanestonk** [Stremio/stremio-features#943]
**Stremio Version**
Stremio Version and OS
1.6.10 Android Tv 11

**Is your feature request related to a problem? Please describe.**

In Kodi, nova video player and other app have the option to enable audio passthrough but in stremio it have nothing for it. 

**Describe the solution you'd like**

Make option for audio passthrough in Stremio

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/user-attachments/assets/9f472982-a6d7-4243-9dc9-7db25bc2b935)

**Comment by TRtomasz** [comment]
Please, there is no need to open same issue again, as i said before Exoplayer does not have passthrough option. So it is not possible to add. If exoplayer detects that your device is capable to decode sound it will passthrough it automatically. Also you can try turning on tunneled playback in the settings.
