### ISSUE TITLE
network status stremio unlimited time on

### ISSUE THREAD

**Issue by qaron84** [Stremio/stremio-features#944]
**Stremio Version**
any version

**Is your feature request related to a problem? Please describe.**
it's not a problem, a suggestion.

**Describe the solution you'd like**
plz i would like a single option [on/off] in settings that disables the fading time on hover event. i always preferred to watch the percent going up... plz add this feature. thx

**Describe alternatives you've considered**
add an option in settings that disables the fading time on network status

**Additional context**
it's comforting for me watching the percent going up. thank you

![Pasted image](https://github.com/user-attachments/assets/0490465a-0211-4b2c-97eb-b2cf42b4845b)

**Comment by TRtomasz** [comment]
keep letter d pressed it will be displayed all the time then

**Comment by qaron84** [comment]
how long can you keep pressing the button d? my suggestion is simple:
1. option in settings that disables/enables the hover/fade time
2. mouse over the button that brings up the Network Status window

**Comment by Jaebraeka** [comment]
Even if the stats appeared under the timeline or in the corner of the movie so it doesn't obscure the middle of the screen would be nice.. 

As for percentage.. would love to see both so either way it's covered.. so maybe an option under settings.. 

Also, would love to see this as an option across all versions of STREMIO as I do see it as a useful feature to display the connection stats, etc.
