### ISSUE TITLE
Community-Based Auto Skip Feature for Intros and Outros

### ISSUE THREAD

**Issue by 7ROBE** [Stremio/stremio-features#951]
**Stremio Version:**
         **1.6.11**

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to manually skip the intro and outro of every episode I watch. This interrupts the flow of my viewing experience and takes away from the convenience that Stremio offers.

**Describe the solution you'd like**
I would like to suggest a community-based auto skip feature for intros and outros, similar to SponsorBlock. This feature would allow users to mark the start and end points of intros and outros in episodes or videos. These segments would then be automatically skipped for other users who opt into the feature.

**Describe alternatives you've considered**
I've considered manually skipping these segments or using third-party applications, but both solutions are inconvenient and disrupt the seamless viewing experience that I enjoy with Stremio.

**Additional context**
Implementing this feature could involve creating a community-driven database where users can submit and vote on the accuracy of intro and outro timings. This would ensure the reliability and accuracy of the skipped segments. Additionally, providing an option in the settings menu to enable or disable this feature would give users the flexibility to choose their preferred viewing experience.

**Comment by TRtomasz** [comment]
closing as duplicate https://github.com/search?q=repo%3AStremio%2Fstremio-features+skip+intro&type=issues
