### ISSUE TITLE
HDR to SDR tone mapping

### ISSUE THREAD

**Issue by jan-kleks** [Stremio/stremio-features#952]
**Stremio Version**
All

**Is your feature request related to a problem? Please describe.**
Many movies (especially 4K) feature HDR and do not look good on SDR screens/devices with poor HDR-support.

**Describe the solution you'd like**
An option in the menu (like with framerate matching) to convert HDR to SDR. There could be additional parameters to configure such as the target display's nits.

**Describe alternatives you've considered**
One can try to watch an SDR version

**Additional context**
See also:
- https://github.com/natural-harmonia-gropius/hdr-toys
- mpv and madVR tonemapping settings
- https://github.com/androidx/media/issues/826

**Comment by jaruba** [comment]
i feel like this is outside the scope of our project, there are usually many sources to choose from and the user should choose the source that matches the device's capabilities

tone-mapping is not a correction that leads to realistic colors, it is an approximate correction, this means that the colors from tone-mapping are not the intended colors of the video creator, it is a "close enough" workaround so the colors do not look washed out (as the hdr or dolby vision layer is not processed at all), for the correct colors the user should choose a source that is not hdr / dovi..

**Comment by TRtomasz** [comment]
Closing as out of scope
