### ISSUE TITLE
Add-on movies launched from Other/Downloads category do not utilize subtitle plug-ins

### ISSUE THREAD

**Issue by jan-kleks** [Stremio/stremio-features#953]
**Stremio Version**
All

**Is your feature request related to a problem? Please describe.**
For instance, you want to add a movie manually to the Other/Downloads section, but after launching it you see that subtitle plugin-ins do not work.

**Describe the solution you'd like**
Let plug-ins to load subtitles  

**Describe alternatives you've considered**
You can look for a movie with built-in subtitles.

**Comment by TRtomasz** [comment]
Thats not possible, as they are categorized as others. Addon that add them to others should create catalogs in movies/series categories
