### ISSUE TITLE
Feature Request: Add Two-factor authentication 

### ISSUE THREAD

**Issue by srejithn** [Stremio/stremio-features#963]
To keep users safe and secure, it would be a good idea for Stremio to add Two-factor authentication feature.

The implementation of this feature will help to protect users data and enhance the overall security.

**Comment by TRtomasz** [comment]
what exactly is at risk in this case?
I dont see sense in implementing this since nothing that is stored on stremio side or can be done with unautorized stremio account access is in anyway critical.
