### ISSUE TITLE
Add a donation button and a user wallet

### ISSUE THREAD

**Issue by neaumusic** [Stremio/stremio-features#964]
**Stremio Version**
All platforms

**Is your feature request related to a problem? Please describe.**
The current digital media landscape is fragmented, creating a "provider hell" for consumers in 2024. This fragmentation leads to multiple issues:

1. High cumulative costs from multiple subscriptions
2. Poor user experience navigating multiple apps and interfaces
3. Limited content accessibility due to platform exclusives
4. Ad saturation deteriorating user experience
5. Perceived decline in content quality despite rising costs

These factors have driven some users to unofficial content sources, solving immediate access issues but raising ethical concerns and depriving creators of compensation. Stremio, as a content aggregator, is uniquely positioned to address this problem.

**Describe the solution you'd like**
Implement a direct creator support feature within Stremio:

1. Add a "Support Creator" / "Donation" button alongside content listings
2. When clicked, display verified payment channels linked to official content creators (studios, directors, rights holders)
3. (Implement a system to verify and authenticate legitimate rights holders)

This solution allows users to ethically support creators directly, even when accessing content through unofficial channels, while maintaining Stremio's neutral aggregator position.

**Describe alternatives you've considered**
Post-viewing purchases through platforms like Apple TV or Amazon
   - Limitation: Doesn't work for exclusive streaming content or shows that can't be purchased individually

**Additional context**
n/a

**Comment by TRtomasz** [comment]
this is simply not possible, stremio isn't financial app to keep funds.
