### ISSUE TITLE
Can't go back using escape, backspace, or mouse buttons on stremio app windows 10

### ISSUE THREAD

**Issue by Jerbungleton** [Stremio/stremio-features#965]
**Stremio Version**
Stremio 4.4.168
WebUI 4.4172
Server 4.20.8

**Is your feature request related to a problem? Please describe.**
I have it set up so that I have a lists show on my homepage. I can only view a few of these before needing to click view more. When I'm done viewing, I want to go back, but nothing lets me go back to the home menu where I was at before. Not backspace, escape, or mouse buttons. The backspace and escape keys don't do anything. I notice that if I fullscreen, all they'll do is take me out of fullscreen. I can go back with back with backspace and escape whenever I click on a movie to view, but want to instead go back to the catalogue of that list. 

**Describe the solution you'd like**
I would like to click escape and not exit full screen. I would also like to go back to the home page with escape and be at the same place it was at (same list you were previously at) because when this problem happens I have to go back home then scroll all the way back down if I want to continue my search. I would also like a backspace button that you can click to go back

**Describe alter

https://github.com/user-attachments/assets/766a078d-7ce2-4c57-ab1f-57ac84335403

natives you've considered**
I tried pretty much all I could. I wouldn't have been writing this if I didn't

**Additional context**

https://github.com/user-attachments/assets/cc403001-a4a5-4846-b64b-9536af0a4f10

https://github.com/user-attachments/assets/d5c4facd-4ec7-4b68-a28b-25424c787c39

**Comment by Jerbungleton** [comment]
please ignore the duplicate video i put between the question about alternatives I considered

**Comment by TRtomasz** [comment]
you switch main tabs with F1/F2/F3 shortcuts.
