### ISSUE TITLE
Feature: Genre filtering for 'Library'

### ISSUE THREAD

**Issue by womow** [Stremio/stremio-features#966]
Apply the genre filtering and sorting capabilities available in 'Discover' to 'Library'. Having the ability to filter based on genre and sort by Added, Released, Last Watched, etc.  would allow the user to better navigate large and diverse collections of Series and Movies that have been added to Library.

**Comment by womow** [comment]
Since this feature would be more geared toward categorizing than discovering, I think it would be better if e.g., when a series is added to the library, the user assigns a single genre of their choice from all available genres to apply to that series for the purpose of library categorizing. Default genre selection is often not intuitive or in any case not necessarily how the user would want or expect that series to be categorized. Also, for ease of use, the Library filter drop-down menu should only display the user-assigned genres for which the filter actually yields results. Most users will probably only use a handful of common genres for categorizing like drama, talk, reality, documentary... Having to rifle through the long list of available genres every time when there are only a handful that yield results would be cumbersome. All this would apply equally to movies. Sorting selection for movies and series should probably stick to each separately since users often want them sorted differently, every time.

**Comment by womow** [comment]
My preference, rather than this, would be that the user be able to add their own top-level custom Libraries, defined by them from the start as Series or Movies from the start, and when opened contain all the series (or movies) assigned to that custom Library, a la Plex. That would mean when the user hits 'Add to Library' they would be presented with a drop-down list of available user-defined libraries, defaulting to 'Library' if none are defined. I suspect this feature would involve significant UI and code re-arrangement, and therefore not taken on, but maybe I'm wrong, it would be ideal imo.

**Comment by TRtomasz** [comment]
closing as duplicate
