### ISSUE TITLE
[LG WebOs] Add emojis flags

### ISSUE THREAD

**Issue by onfire-d** [Stremio/stremio-features#967]
**Stremio Version**
Latest WebOS for LG

**Is your feature request related to a problem? Please describe.**
Not a problem. But countries flags are black and white and it’s hard to difference which flags is for each country, making difficult to choose the correct link choice.

**Describe the solution you'd like**
Using Android-kind of flags emojis

**Comment by TRtomasz** [comment]
emojis are controlled by the system android has different ones ios has different ones etc
