### ISSUE TITLE
Auto select source stream

### ISSUE THREAD

**Issue by Sgrbhtngr** [Stremio/stremio-features#968]
**Stremio Version**
Fire OS

**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Please add the option of auto selecting the first streaming option on the list. This will facilitate 1-click play. 

**Describe alternatives you've considered**
Alternative is to manually choose the stream. 

**Additional context**
While watching a TV series, if we click on next episode, Stremio chooses a stream on its own. This shows that the feature is possible.

**Comment by TRtomasz** [comment]
We will not add such features, as it could affect users safety and privacy.

**Comment by Sgrbhtngr** [comment]
Thanks for the response. However, this feature already exists when we are watching a series. It auto-plays the next episode without us having to choose the stream. We are only twisting to have the same thing available while watching movies or the first episode of the series. Also, I just wanted to let you all know that I absolutely enjoy Stremio. The interface is truly professional, unlike Kodi. Stremio has transformed my streaming life for the better, and I am grateful!

**Comment by GuilhermeBSilva2002** [comment]
> We will not add such features, as it could affect users safety and privacy.

wtf?? how does this affect user safety and privacy??? even Nuvio has that, you guys are unbelievable
