### ISSUE TITLE
Fix Invalid Links for Netflix’s Unsolved Mysteries — Train Whoever is Uploading Links

### ISSUE THREAD

**Issue by majaboo** [Stremio/stremio-features#969]
**Stremio Version**
Stremio 4.4.168
Web UI 4.4.172
Server 4.20.8

**Is your feature request related to a problem? Please describe.**
Whoever uploaded the server links for this show, Unsolved Mysteries, did not do it correctly. The newest season is season 4, but the titles and number of episodes are from season 3. (which ironically season 3 is missing off of Stremio entirely) The thumbnails are missing for the episodes, and the links for the seemingly season 4 are incorrectly placed and are in fact from season 3. 

**Describe the solution you'd like**
I want someone, anyone, with the ability to find the server links for the correct seasons volunteer themselves to do a good samaritan service and fix the mess that someone else made. PLEASE. 

**Describe alternatives you've considered**
I have tried uninstalling and reinstalling Stremio as well as Torenttio, to no avail. I’m not renewing my Netflix subscription for 5 episodes—please help me. I’m sure other people are wanting this to be fixed too. 

**Additional context**
I was brought here by the r/stremioaddons subreddit rules, so I apologize if this is not the place to do this.. I am just very eager to resume watching one of my favorite shows. Please help, anyone.

**Comment by TRtomasz** [comment]
This is repository for stremio features not stremio bugs(check stremio-bugs) 2. Stremio does not upload anything so not sure what you mean here. 3. Stremio does not provide thumbnails if they are not available from the 3rd party provider we will not show them.
