### ISSUE TITLE
Search function for add-ons

### ISSUE THREAD

**Issue by TRtomasz** [Stremio/stremio-features#97]
Even with only current amount of add-ons it is kind of hard to look through them. There should be option to search through add-ons added.

**Comment by Ivshti** [comment]
there's a search bar in the top left at the addons page; is that what you mean?

**Comment by TRtomasz** [comment]
![obraz](https://user-images.githubusercontent.com/40594253/47578228-2b792600-d949-11e8-943a-2edf1e9d769e.png)
I see there only field to type add-on url
