### ISSUE TITLE
Play HDR10+ like normal HDR10.

### ISSUE THREAD

**Issue by Chris3461** [Stremio/stremio-features#970]
**Stremio Version**
1.6.11 Android TV

**Is your feature request related to a problem? Please describe.**
When i try to play videos that only have HDR10+ and dv, i can't play them in normal HDR10.

**Describe the solution you'd like**
In Kodi there is an option called "Allow HDR dynamic metadata formats", with that option when unchecking HDR10+ and DV, I can play HDR10+ like normal HDR10, I hope something like that can be added.

**Comment by TRtomasz** [comment]
Afaik this is default behavior in exoplayer if there is no hdr10+ support it will not pass hdr10+ supplemental data to the decoder.
