### ISSUE TITLE
Categories 

### ISSUE THREAD

**Issue by everton9357** [Stremio/stremio-features#971]
**Stremio Version**
Stremio Version and OS

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Hi stremio is a brilliant app well better than Kodi in the future do you think you could put more categories instead of just movies and series it could be kids war western etc this would make it a lot better.
Many thanks 
David Moss

**Comment by TRtomasz** [comment]
You can filter videos by genres once you open 'movies' or 'series'
