### ISSUE TITLE
Library: “Watch Later”, “Watched”, “Watching”

### ISSUE THREAD

**Issue by permedd** [Stremio/stremio-features#972]
**Stremio Version**
Stremio Version, OS, FireStick

**Is your feature request related to a problem? Please describe.**
Right now we have library, but it will be a good idea to have a category in the library which includes:
- Watch Later
- Watched
- Watching
Having just library we don’t know if we have watched, if we are supposed to start the movie/series.

**Describe the solution you'd like**
- Watch Later
- Watched
- Watching
Having this in the library category, and we should tag the movie/series ourself.

**Comment by kKaskak** [comment]
Library chips filters were implemented thus closing this.
