### ISSUE TITLE
Select Dubbed Main

### ISSUE THREAD

**Issue by permedd** [Stremio/stremio-features#975]
**Stremio Version**
Stremio Version, OS, firestick

**Is your feature request related to a problem? Please describe.**
If there is a dub version of movies/series/anime, can it be the main act, instead of being sub versions that comes up first.
Maybe have a option for dub/sub, something similar to

**Additional context**
![IMG_9014](https://github.com/user-attachments/assets/8e1016aa-921c-4056-b9f7-644ad3d50b61)

**Comment by TRtomasz** [comment]
Stremio does not have information which ones have dubbing or embedded subs it is not possible
