### ISSUE TITLE
Request to not show update available in Play store when Stremio is up to date

### ISSUE THREAD

**Issue by realAllonZ** [Stremio/stremio-features#979]
**Stremio Version**
Stremio 1.6.12 for Android Mobile

**Is your feature request related to a problem? Please describe.**
When installing Stremio outside of the Play store, Obtainium in my case, Play shows update available even when Stremio is up to date.

**Describe the solution you'd like**
Other sideloaded apps have had this issue as well but have recently been resolved. Not sure how they did it.

**Describe alternatives you've considered**
No known alternatives.

**Comment by TRtomasz** [comment]
This is not related to stremio, we do not control what play store is showing
