### ISSUE TITLE
Surround sound passthrough 

### ISSUE THREAD

**Issue by kalzorzortek** [Stremio/stremio-features#981]
Stremio Android Tv
We need passthrough option for surround sound because the exoplayer and libvlc is not enough for new codecs. Please add this feature otherwise Stremio loosing it's advanced position in streaming world. Biggest two key points of streaming is video and sound. Video is ok but for sound this is so bad to be stuck in stereo.

**Comment by TRtomasz** [comment]
This is not possible, we do not controll what exoplayer and libvc provides.
