### ISSUE TITLE
Subtitle position in Stremio  .

### ISSUE THREAD

**Issue by Smith-Williams** [Stremio/stremio-features#982]
Enhancement Request: Subtitle Placement and Customization for PC Desktop Version

Dear Developers, I would like to suggest an enhancement to our current subtitle settings, specifically for the PC desktop version. It would be highly beneficial to provide an option for users to set subtitles at the top of the screen. This feature could greatly improve the viewing experience for many users, especially in cases where bottom-placed subtitles obstruct crucial visual content.

Moreover, offering a broader range of subtitle customization options would further enhance accessibility and user satisfaction. Features such as adjustable subtitle size, font choice, color options, and background shading can cater to diverse user preferences and needs.

I believe that implementing these enhancements will not only improve the overall user experience but also demonstrate our commitment to accessibility and user-centric design. I hope you will consider these suggestions for future updates.

Thank you for your attention to this matter.

**Comment by TRtomasz** [comment]
there is no need to open same issue multiple times
