### ISSUE TITLE
Update MPV to latest version

### ISSUE THREAD

**Issue by Loukious** [Stremio/stremio-features#984]
**Stremio Version**
Stremio Version: 4.4.168
OS: Win11

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like you to update MPV that's being used by Stremio desktop app to the latest version which currently has video upscaling (which is a nice feature to have).
https://github.com/mpv-player/mpv/pull/14698

**Describe alternatives you've considered**
Nothing

**Additional context**
Video upscaling uses the GPU to enhance video quality.

**Comment by TRtomasz** [comment]
you can try just replace libmpv dll file inside stremio installation folder with the latest one

**Comment by Loukious** [comment]
> you can try just replace libmpv dll file inside stremio installation folder with the latest one

I tried and it didn't work. Seems like Stremio uses a really old version of libmpv-1.dll meanwhile the current version is libmpv-2.dll (names could be inaccurate as I don't remember exactly). The API may have changed.

**Comment by TRtomasz** [comment]
You have to use 32 bit libmpv version
