### ISSUE TITLE
AutoPlay Trailer (Similar to Netflix)

### ISSUE THREAD

**Issue by permedd** [Stremio/stremio-features#985]
**Stremio Version**
Stremio Version, OS, Firestick

**Is your feature request related to a problem? Please describe.**
When you hoover on top of a movie/series, the list goes down, and on the right top corner the trailer begins of the movie/series, that you have hoovered on to, is it possible to add this on stremio, rather than clicking on the movie/series and clicking on trailer.

**Comment by TRtomasz** [comment]
This is not possible to be done at the level that would be satisfying, stremio does not host any trailers, and playing videos from youtube outside youtube is not the most smooth experience
