### ISSUE TITLE
Dedicated customizable timeskip button

### ISSUE THREAD

**Issue by MO-oncake** [Stremio/stremio-features#989]
Android TV user,

I'm aware there's the option to adjust the timeskip duration already but I'm looking at an addition to this feature.

Having the ability ro retain the forward and back time skips to default but have a dedicated custiomizable button/icon. say something like +85 seconds (most anime intros). This way I dont have to constantly keep editing the time between long skips and short skips. Thanks.

**Comment by TRtomasz** [comment]
We will not add this feature it would only clutter UI and would be used by small % of users
