### ISSUE TITLE
Feature: Library indication that the series ended/canceled

### ISSUE THREAD

**Issue by maxsnts** [Stremio/stremio-features#990]
4.4.168 on MacOS Sonoma
Stremio Version and OS

Hello

In this day and age where TV series seasons get released years apart, and most of the time get canceled in between, it would be interested to have and indication library card to show if the series is still on the air or ended.
I supposed this would be easy enough, since the series either has the end year or not.

This way we could see in the library if a series had ended (without open them one by one) and remove it from the library.

Thank you for the amazing piece of software.

**Comment by TRtomasz** [comment]
We do not have info if series is ended/cancelled it is not possible

**Comment by maxsnts** [comment]
I understand that there is no definitive indication, could the lack of end year be used to create a hint that it might have ended?
![image](https://github.com/user-attachments/assets/4079b376-92ed-4f31-9e4a-4eb32a259f8a)
![image](https://github.com/user-attachments/assets/f913a7f9-9ec9-4636-b70f-1a02ea48cf6d)

I think it would be useful even if not infallible.

**Comment by TRtomasz** [comment]
After detailed check, we actually have such data, but once series gets marked as ended we stop updating it automatically. So if such series gets restarted i could imagine a lot of people being disappointed by stremio not showing this properly.

**Comment by maxsnts** [comment]
I would think that people remove from the library series that ended, preventing them from receiving updates anyway, but i see your point. 
On the other hand i think restarting series e a rare event, i remember only Heroes and Prison Break, but i don't watch everything obviously.
Anyway, this was a "nice to have" thing that maybe only me would like.

Thank you anyway.
Best regards

**Comment by maxsnts** [comment]
Not to be a paint in the ass, but I will just leave here an example.
TV series "Kaos" it was canceled.
In Stremio it shows:
![image](https://github.com/user-attachments/assets/ae9947d4-b3d3-4751-95c4-341459fef05e)

In Imdb it shows:
![image](https://github.com/user-attachments/assets/a61cdeb0-1d1d-43ee-9d90-88c4fd95b623)

I understand how hard you maintenance must be, or i can take a guess at least.
My ideia is just that if there is an indication that "might have ended/canceled" to let people know on the library.
No need to think of it as a definitive info, just a "ei, this may never come back, go investigate".

Again, thank you.
Hope you reconsider.
Best regards (sorry about the insistence)
