### ISSUE TITLE
Bug? Volume level is not kept between uses

### ISSUE THREAD

**Issue by maxsnts** [Stremio/stremio-features#991]
4.4.168 on MacOS Sonoma
Stremio Version and OS

In previous versions, volume level was kept when we closed Stremio
In recent versions, when we open Stremio, the volume is always reseted to the middle.

Is it possible to revert this change and have the volume keep its value between uses?

Thank you

**Comment by TRtomasz** [comment]
Not sure what you mean by previous version. i have checked and this piece of software has not been changes in 9 years

**Comment by maxsnts** [comment]
What do you mean no changes in 9y?
All repos seam to be active and i was told to report stuff here.
![image](https://github.com/user-attachments/assets/034a8939-dac2-48c5-b231-0eb4dd7d75a1)

**Comment by TRtomasz** [comment]
There was no change in regards how player behaves in terms of audio volume. Any change at this moment would affect millions of users who are used to the current behavior so it will not be implemented.
Additionally i have checked and audio volume level is being remebered when you exit the app and open it again on mac os sonoma

**Comment by maxsnts** [comment]
Is the volume level saved somewhere, file, where i have no write permissions?
Its weird that i does not save it only for me, while everything else works fine.

**Comment by maxsnts** [comment]
I took another look and the problem is actually different.
The problem is that when using the scroll to move the volume, it never goes up from the middle.
Every little touch on a Apple Mouse will reset the volume to the middle.
I will open a new issue with the correct title.

**Comment by TRtomasz** [comment]
@maxsnts  this is intended averything above middle(old 100%) is artifical boost.

**Comment by maxsnts** [comment]
OK, got it. 
Somehow this is does not work right on my system since the volume that i use for everything else (youtube, music, etc) is too low on Stremio, but ok, such is life.
