### ISSUE TITLE
Remove thumbnails on TV series episodes

### ISSUE THREAD

**Issue by mickopato** [Stremio/stremio-features#992]
**Stremio Version**
Stremio Version and OS
All versions & devices

**Is your feature request related to a problem? Please describe.**
Thumbnails for individual episodes of TV shows on Stremio often include major spoilers for what happens in that episode. I've had it happen on multiple occasions while watching Game of Thrones. 

**Describe the solution you'd like**
It would be great to have the option to just remove thumbnails for episodes altogether, or to at least blur them, or black out the image, or even just make every episode thumbnail the default poster for the show - whatever is easiest from a programming perspective. 

**Describe alternatives you've considered**
See above

**Additional context**

**Comment by TRtomasz** [comment]
this will not happens as thumbnail are crucial part of the UI and removing them will mean reworking whole UI.
