### ISSUE TITLE
Feature Request - Ability to update Stremio within app

### ISSUE THREAD

**Issue by Patevan9** [Stremio/stremio-features#995]
It would be nice to know there is an update and  be able to update to the newest version within the app. That would come in handy on a streaming box without having to rely on Google Play or having to go to website to download. Simply a button that you click that says "Update" would be nice. Also might help people to get the correct type of Stremio? Many times people will have the wrong version or platform (Stremio Android TV or Android Mobile).
Just a thought.

**Comment by TRtomasz** [comment]
This will not be implemented as it would require significant cost to handle such updates
