### ISSUE TITLE
Allow to quickly turn off/on add-ons (without unistalling them) to conserve, for instance, their API limits

### ISSUE THREAD

**Issue by jan-kleks** [Stremio/stremio-features#998]
**Is your feature request related to a problem? Please describe.**
Let's say you have got an add-on which practically always gives you good content results. However, sometimes you need (**and only sometimes**) more results from another add-on which has API limits. And because this second limited add-on loads **every time** you are searching for content you might run out of its limit when you actually need it...

**Describe the solution you'd like**
An option to quickly turn on/off add-ons / activate them manually on content search screens.

**Comment by TRtomasz** [comment]
We will not add features that would be used by a very small number of users. You can just copy current manifest url and remove addon and add it again using copied url, and it would be almost not different than going to Addons disabling, doing something, going to addons enabling.
