### ISSUE TITLE
Pre-Roll

### ISSUE THREAD

**Issue by kingjii** [Stremio/stremio-features#999]
**Stremio Version**
Samsung OS

**Is your feature request related to a problem? Please describe.**
Not a problem but better end experience. 

**Describe the solution you'd like**
Would love pre-roll feature, similar to plex, where I can add local files as intro (e.g. imax countdown) and be able to select it, so it pops up every time a movie is selected. Or Tv show, depending on whatever the user would like. Would love to add trailers to queue up before movies as well. 

**Describe alternatives you've considered**
Plex

**Additional context**
I have a home theater system and would love to add extra trinkets to make the cinematic experience that much more involved.

**Comment by TRtomasz** [comment]
https://stremio.zendesk.com/hc/en-us/articles/115003378231-How-does-Stremio-compare-to-Kodi-and-Plex
